import type { GreenTechModule, GreenTechTier } from "@/lib/greentech";

export type GreenTechLearningSection = {
  title: string;
  objective: string;
  teaching: string[];
  keyPoints: string[];
  learnerPrompt: string;
};

type ModuleSpecifics = {
  fundamentals: string;
  relationships: string;
  application: string;
  dataAi: string;
  enterprise: string;
};

const specifics: Record<string, ModuleSpecifics> = {
  "GF-01": {fundamentals:"A food-energy-water (FEW) system is a connected system in which food production depends on water delivery and energy, while water and energy decisions affect productivity, cost and resilience. Learners should recognize sources, loads, storage, controls and productive-use components as one system rather than isolated equipment.",relationships:"Map how photovoltaic generation, pumping, storage, irrigation and food production exchange energy, water and information. A change in one block can create consequences elsewhere; for example, poor storage sizing can force pumping at the wrong time or reduce irrigation reliability.",application:"Build a block diagram from source to end use. Label energy flow, water flow, control signals, measurement points and safety boundaries, then explain what happens if one component becomes unavailable.",dataAi:"Use digital tools or AI to organize a FEW system map, compare alternative architectures and identify missing interfaces. Every suggested connection must be checked against the actual equipment, drawings, trainer guidance and field observations.",enterprise:"A basic FEW mapping service can help a farm, school or community understand its current system before investing in upgrades. The technician must define the client's problem, map assets accurately and avoid recommending changes beyond verified competence."},
  "GF-02": {fundamentals:"Technical safety begins with recognizing hazards before touching equipment. Core categories include electrical energy, pressure, moving parts, heat, sharp edges, chemicals, slips, falls, manual handling and environmental exposure.",relationships:"PPE is the last layer of defense, not the first. Safe work also depends on elimination, isolation, guarding, lockout or safe-state procedures, controlled access, correct tools and clear communication.",application:"Perform a simple job hazard analysis: identify the task, list hazards, rate consequences, select controls and define stop-work conditions. The learner should be able to explain why each control is appropriate.",dataAi:"AI may help generate a preliminary hazard checklist, but the learner must compare it with the real worksite and trainer-approved procedure. Missing hazards, wrong equipment assumptions or unsafe generic advice must be identified and rejected.",enterprise:"Safety readiness is part of professional value. A technician who documents hazards, uses PPE correctly and communicates stop-work decisions protects clients, coworkers, equipment and the reputation of the service business."},
  "GF-03": {fundamentals:"Technical measurements are useful only when the correct tool, range, units and method are used. Learners should distinguish dimensional, electrical, hydraulic and environmental measurements and understand basic accuracy and repeatability.",relationships:"Tool selection affects the quality of evidence. A measurement without units, location, time, method or instrument context may be impossible to interpret later.",application:"Complete a measurement sheet that records what was measured, tool used, unit, reading, expected range and any unusual observation. Repeat selected readings to check consistency.",dataAi:"Digital tools can format records, calculate differences and flag unusual values. AI must never invent missing measurements; any estimated value must be clearly labeled as an estimate and separated from field data.",enterprise:"Measurement support can be offered as part of site surveys, maintenance and troubleshooting. Professional practice requires calibrated or fit-for-purpose tools, traceable records and clear limitations."},
  "GF-04": {fundamentals:"Basic direct-current electrical work requires understanding voltage, current, resistance, polarity, continuity, power and protective devices. Learners should know why conductors, connectors and protection must match the intended load.",relationships:"Voltage drives current through a circuit, while resistance and load characteristics affect current draw. Reversed polarity, short circuits, loose connections and undersized conductors can create faults or unsafe conditions.",application:"Construct a protected low-voltage DC circuit under supervision, verify polarity before energizing, measure voltage and current, and compare the result with a simple expected calculation.",dataAi:"Use AI or a calculator to check Ohm's-law or power calculations, but verify component ratings and polarity from labels, datasheets and direct measurement. Generated wiring instructions cannot override trainer or manufacturer requirements.",enterprise:"Basic DC inspection and protected low-voltage support can become an entry service when performed within authorized scope. Documentation should state what was checked, what was measured and what requires escalation."},
  "GF-05": {fundamentals:"Photovoltaic modules convert sunlight into direct-current electrical energy. Learners should understand module rating terms, open-circuit voltage, operating voltage, current, orientation, shading and the difference between nameplate and field output.",relationships:"Photovoltaic output changes with irradiance, temperature, shading, wiring and load conditions. Even a healthy module may produce less than its nameplate rating under real conditions.",application:"Measure module voltage and current on a supervised training setup, record environmental conditions and compare observed output with expected behavior without assuming that nameplate power will always be reached.",dataAi:"AI can help interpret why measured output differs from expectation, but conclusions must be checked against actual irradiance, shading, module condition, wiring and manufacturer data.",enterprise:"Basic photovoltaic cleaning, inspection and performance checks can be a service opportunity. The learner must distinguish routine observation from work that requires a qualified installer or electrician."},
  "GF-06": {fundamentals:"Water pumps convert mechanical or electrical energy into water movement. Key ideas are flow rate, head, suction conditions, discharge conditions, efficiency and the difference between pump types.",relationships:"A pump must operate against the actual hydraulic system. Pipe friction, elevation, restrictions and valves affect the duty point, so a pump cannot be selected from flow rate alone.",application:"Measure flow on a training rig, estimate static head, observe changes when resistance changes and record the relationship between pump operation and delivered water.",dataAi:"AI can explain pump curves or organize calculations, but the learner must use real duty requirements and manufacturer curves rather than generic recommendations.",enterprise:"Pump-flow observation and basic maintenance support can help farms and communities identify underperformance early. Service notes should separate observed symptoms from confirmed causes."},
  "GF-07": {fundamentals:"Drip irrigation delivers water through pipes, filters, valves, laterals and emitters. Learners should understand pressure, flow, filtration, flushing, emitter spacing and common causes of non-uniform delivery.",relationships:"Clogging, pressure loss, leaks and poor layout affect how evenly plants receive water. Filtration and flushing therefore support both hydraulic performance and crop management.",application:"Assemble a small drip-irrigation zone, flush it, inspect for leaks and compare emitter discharge at several points to identify obvious non-uniformity.",dataAi:"Use AI to organize a troubleshooting checklist or calculate simple flow totals, then verify each suspected problem through observation and measurement.",enterprise:"Small drip-system assembly and inspection can be an entry-level service. The technician should define the installation scope, materials, testing procedure and maintenance instructions."},
  "GF-08": {fundamentals:"Food-production systems depend on timely water, suitable growing conditions and reliable energy for tasks such as pumping, sensing, lighting or processing. Integration means matching technical infrastructure to biological needs.",relationships:"Too little water, excessive irrigation, poor timing or unreliable energy can all reduce productivity. The best technical solution therefore considers crop or production requirements rather than optimizing equipment in isolation.",application:"Map the energy and water inputs of a small productive system, identify when each input is needed and note where storage, efficiency or scheduling could improve reliability.",dataAi:"AI can help organize production inputs and generate questions, but crop requirements, field conditions and observed performance must be confirmed with trusted agronomic information and local evidence.",enterprise:"Input mapping can support advisory services for small producers. A useful service identifies constraints and opportunities without promising yield outcomes that have not been demonstrated."},
  "GF-09": {fundamentals:"Sensors convert physical conditions into data. Learners should understand what a sensor measures, where it should be placed, its units, sampling interval, plausible range and the difference between a sensor reading and ground truth.",relationships:"Bad placement, poor calibration, damaged wiring, timing errors or environmental interference can create misleading data. A digital value is not automatically a correct value.",application:"Collect a short series of sensor or manual observations, record metadata and compare readings with an independent observation or reference instrument when possible.",dataAi:"AI can flag anomalies or summarize trends, but the learner must investigate placement, calibration, timestamps and independent evidence before rejecting or correcting data.",enterprise:"Basic field monitoring and logging can be provided to farms, schools and community projects. Value comes from consistent records and reliable interpretation, not from collecting data without a decision purpose."},
  "GF-10": {fundamentals:"Preventive maintenance aims to detect deterioration before it becomes failure. Common actions include inspection, cleaning, tightening where authorized, checking leaks, observing unusual noise or heat and maintaining records.",relationships:"Maintenance frequency should reflect equipment condition, environment, duty cycle and manufacturer guidance. Over-maintenance can also create risk if unnecessary disassembly introduces faults.",application:"Use a checklist to inspect a training system, identify normal and abnormal conditions, complete approved maintenance actions and record items that require escalation.",dataAi:"AI can help organize recurring maintenance records or compare observations over time, but it must not invent inspection findings or authorize work outside the learner's scope.",enterprise:"Routine inspection packages can become recurring service contracts. Clear checklists, dates, findings and recommended follow-up create trust and help customers plan maintenance costs."},
  "GF-11": {fundamentals:"Technical documentation makes systems understandable to other people. Useful records include equipment lists, labels, sketches, schematics, measurements, revision dates and as-built information.",relationships:"Poor documentation causes maintenance errors, weak handover and repeated diagnostic work. A drawing must match the actual installation, not merely the original intention.",application:"Create an as-built sketch and equipment record for a training system, including labels, major connections, measurements and any difference from the original diagram.",dataAi:"AI can improve wording, formatting and document structure, but it must not fabricate equipment, ratings, measurements or site conditions.",enterprise:"Documentation support adds value to installation and maintenance services. Professional records reduce future service time and improve customer handover."},
  "GF-12": {fundamentals:"The foundation practical integrates safety, measurement, assembly, operation, monitoring, maintenance and documentation. Competence is demonstrated through observable work rather than attendance.",relationships:"A complete task requires planning before action, safe execution, measurement during work, acceptance checks after work and clear handover. Weakness in any stage can compromise the final result.",application:"Complete a supervised integrated task from preparation through handover. The assessor should be able to see safe practice, correct tool use, valid measurements, troubleshooting and accurate documentation.",dataAi:"AI may support planning, explanation or record organization, but the learner must independently demonstrate the core practical skills and verify any AI-assisted conclusion.",enterprise:"Package the practical as a small customer-style service with scope, materials, evidence, cost logic and handover. The final result should show technical competence and professional behavior."},
  "GT2-01": {fundamentals:"A technical site assessment converts a real location into usable design information. It considers existing infrastructure, demand, access, hazards, space, water source, energy source, users, environmental constraints and future expansion.",relationships:"Site conditions determine which technical options are feasible. A good design can still fail if the survey misses shading, elevation, access, pipe routes, structural constraints or user requirements.",application:"Conduct a structured FEW survey, document measurements and observations, photograph or sketch key features and produce a constraint/opportunity summary that can support later design decisions.",dataAi:"AI can organize survey notes and suggest follow-up questions, but all site-specific facts must come from direct observation, verified records or responsible stakeholder interviews.",enterprise:"A documented site assessment is a standalone technical service and the foundation of credible quotations. State assumptions, exclusions and information that still needs verification."},
  "GT2-02": {fundamentals:"Load and demand assessment quantifies how much energy and water users require, when they require it and which loads are critical. Daily totals alone are insufficient when timing affects storage or generation decisions.",relationships:"Peak demand, operating duration, simultaneity, seasonal variation and service priority influence system sizing. Water demand may also drive pumping energy demand.",application:"Create daily energy and water profiles using equipment ratings, measured flow, operating hours and realistic usage assumptions. Show units and separate measured from assumed inputs.",dataAi:"Use AI or spreadsheets to check arithmetic, create scenarios and visualize profiles, but preserve an auditable chain from source data to final totals.",enterprise:"Energy and water demand audits can identify waste, right-size equipment and reduce customer overspending. A professional audit explains uncertainty rather than presenting false precision."},
  "GT2-03": {fundamentals:"Photovoltaic array configuration combines modules in series and parallel while respecting voltage, current, power, temperature and equipment limits. Protection, conductor sizing and isolation are part of safe configuration.",relationships:"Series increases voltage while parallel paths increase current. Temperature can raise open-circuit voltage in cold conditions, so configuration must be checked against controller or inverter limits.",application:"Design and wire a protected training array, calculate string voltage/current, verify polarity and compare calculated values with measurements before connection to downstream equipment.",dataAi:"AI can compare possible configurations, but every limit must be verified against manufacturer datasheets and applicable electrical requirements.",enterprise:"Array configuration and inspection support requires precise records and strict scope control. Quotations should include modules, protection, conductors, connectors, labor and testing."},
  "GT2-04": {fundamentals:"Battery and control systems store energy and manage charging, discharging and load supply. Learners should understand battery type, nominal voltage, capacity, state of charge, charge controllers, protective devices and operating limits.",relationships:"Battery life and safety depend on temperature, depth of discharge, charge settings, current limits and wiring quality. Control settings must match the specific battery and system architecture.",application:"Configure a protected training storage/control setup, confirm settings from manufacturer information, measure key values and observe normal charging or load behavior.",dataAi:"AI can help interpret logs or explain settings, but it must not override battery-management protection, manufacturer limits or competent electrical judgment.",enterprise:"Battery inspection and control-system maintenance can be valuable recurring services. Record settings, symptoms, measurements and any intervention requiring specialist escalation."},
  "GT2-05": {fundamentals:"Pump selection matches a pump to a required duty point. The technician must quantify required flow and total dynamic head, then use a manufacturer pump curve and installation constraints.",relationships:"An oversized or undersized pump can waste energy, reduce reliability or fail to deliver required water. Pipe diameter, elevation, friction, storage and operating schedule all influence selection.",application:"Calculate a defined duty point, compare candidate pumps, install a training pump under approved procedures and test actual flow and pressure/head against expectations.",dataAi:"AI can compare options and perform scenario calculations, but the final choice must use verified duty requirements and authentic pump curves.",enterprise:"Pump duty assessment and selection is a high-value technical service when paired with transparent calculations, installation scope, testing and customer handover."},
  "GT2-06": {fundamentals:"Water storage and distribution systems use tanks, pipes, valves, fittings and controls to buffer supply and deliver water where needed. Storage volume, elevation, pressure and demand shape performance.",relationships:"Storage can decouple pumping time from water-use time, while pipe sizing and valve placement affect losses, control and maintenance. Poor overflow, drainage or support can create safety and water-loss problems.",application:"Assemble a training storage/distribution system, test filling and delivery, inspect for leaks and document valve positions, pipe routes and observed performance.",dataAi:"Digital tools can support volume calculations and layout comparisons, but hydraulic behavior must be confirmed through real measurements and inspection.",enterprise:"Tank and distribution installation, inspection and maintenance can be packaged as a service with materials, labor, testing, cleaning and after-service requirements."},
  "GT2-07": {fundamentals:"A drip-irrigation installation must deliver water uniformly enough for the intended crop zone. Design includes flow demand, pressure, filtration, pipe sizing, valves, laterals, emitters and flushing points.",relationships:"Pressure variation, clogged emitters, leaks and excessive lateral length reduce uniformity. Installation quality and maintenance therefore directly affect agronomic performance.",application:"Install and pressure-test a training zone, measure emitter discharge at representative points, calculate a simple uniformity indicator and correct an identified fault.",dataAi:"AI or spreadsheets can help calculate uniformity and compare readings, but the learner must verify field measurements and physically investigate poor-performing emitters.",enterprise:"Drip installation and maintenance is a clear technical service. Scope should include layout, materials, testing, user training and a maintenance schedule."},
  "GT2-08": {fundamentals:"Agrivoltaic systems combine photovoltaic infrastructure with agricultural production on the same land. Technical decisions must consider energy generation, crop environment, irrigation, machinery and worker access, structural safety and operations.",relationships:"Panel spacing, height and orientation influence shading, access and microclimate. Irrigation routes and maintenance activities must coexist with electrical infrastructure without creating new hazards.",application:"Prepare a site-layout exercise that shows photovoltaic zones, crop zones, access paths, irrigation routes, equipment clearances and operational constraints.",dataAi:"AI can compare layout alternatives or organize trade-offs, but agronomic suitability, structural design, electrical safety and local site conditions require qualified human review.",enterprise:"Agrivoltaic site support can include surveys, operations assistance and monitoring. Avoid representing advanced structural or electrical design work beyond authorized competence."},
  "GT2-09": {fundamentals:"Field monitoring requires correct sensor selection, installation, metadata and quality assurance. A sensor record should identify variable, unit, location, depth or height, sampling interval and maintenance status.",relationships:"Telemetry can move data from field sensors to dashboards, but communications do not improve poor-quality measurements. Data quality begins at the sensor and installation.",application:"Install a supervised monitoring point, record metadata, collect observations and perform at least one plausibility or cross-check test.",dataAi:"AI may flag anomalies, missing values or trends. The technician must check timestamps, placement, calibration and site events before deciding that a value is wrong.",enterprise:"Sensor installation and monitoring services create recurring value when reports connect data to customer decisions such as irrigation, maintenance or resource use."},
  "GT2-10": {fundamentals:"CHIPU control fundamentals connect sensors, rules or models, decisions, control outputs and actuators. Safe automation requires thresholds, hysteresis, interlocks, alarms, manual override and defined fallback states.",relationships:"A control action should occur only when input conditions are valid and safety constraints are satisfied. Without hysteresis or timing logic, equipment may cycle excessively.",application:"Create and test a simple Sensor → Data → Rule/Model → Decision → Control → Actuator → Result → Feedback chain using a training scenario and documented safe states.",dataAi:"AI can help propose control logic or analyze logs, but AI/model outputs remain bounded by hard safety interlocks and operator authority.",enterprise:"Basic control mapping and monitoring support can improve reliability for farms and small infrastructure. Document logic, thresholds, manual controls and failure behavior for the customer."},
  "GT2-11": {fundamentals:"Commissioning proves that an installed system is safe, complete and performing as intended before handover. Troubleshooting uses a disciplined sequence rather than random part replacement.",relationships:"Baselines created during commissioning become future diagnostic references. A fault may originate in power, hydraulics, sensors, settings, wiring, mechanical components or user operation.",application:"Commission a training system, record baseline readings, identify a planted fault, form hypotheses, test them one at a time and document the corrective action and retest result.",dataAi:"AI can broaden troubleshooting hypotheses, but evidence from measurements and controlled tests determines the diagnosis.",enterprise:"Commissioning and fault-diagnosis services are valuable because they reduce callbacks and downtime. Reports should state baseline values, faults found, corrective actions and remaining limitations."},
  "GT2-12": {fundamentals:"The FEW Systems Technician assessment integrates site assessment, demand analysis, configuration, installation, instrumentation, control, commissioning, troubleshooting and handover.",relationships:"A technician must connect design intent to field execution and evidence. Safe completion is not enough if the system cannot be measured, explained and handed over responsibly.",application:"Complete an integrated technician task with defined customer requirements, measurements, installation or configuration work, commissioning, one diagnostic challenge and final documentation.",dataAi:"Use AI transparently where permitted, documenting input, output, verification and final human decision. Core technical competence must remain independently demonstrable.",enterprise:"Present the work as a professional service package with scope, cost, exclusions, testing evidence, customer instructions and after-service plan."},
  "GA-01": {fundamentals:"Advanced FEW architecture begins with requirements, interfaces, operating states, constraints and performance objectives. Architecture defines how energy, water, storage, production, sensing, control and users interact before detailed component selection.",relationships:"Architectural decisions create downstream consequences for reliability, maintainability, cost, data needs and expansion. Interfaces are often where integrated systems fail.",application:"Develop and defend an architecture diagram, interface register and operating-state description for a realistic FEW use case, including normal, degraded and safe states.",dataAi:"Use AI to explore alternative architectures and failure scenarios, then trace every accepted design choice to explicit requirements, evidence or engineering judgment.",enterprise:"Architecture and advisory services require clear deliverables, assumptions and decision records. The professional value is in reducing integration risk before procurement and construction."},
  "GA-02": {fundamentals:"Advanced photovoltaic design combines resource assessment, load profile, array sizing, electrical configuration, protection, conductor selection, temperature effects, losses and energy balance.",relationships:"A design must satisfy both electrical limits and operational objectives. More installed capacity may not solve poor timing, storage limits, curtailment or load-management problems.",application:"Develop a photovoltaic design with array sizing, string configuration, key protective elements, expected energy balance and at least one sensitivity analysis.",dataAi:"AI can accelerate scenario generation and comparison, but all consequential calculations, ratings and assumptions require independent engineering verification.",enterprise:"Photovoltaic design and audit services should present a traceable basis of design, options, constraints, cost implications and boundaries of professional responsibility."},
  "GA-03": {fundamentals:"Advanced water-energy design links water demand, pumping duty, photovoltaic or grid supply, batteries, tanks and operating schedules. Water storage can function as an operational flexibility asset.",relationships:"Pumping at different times changes energy requirements, storage levels and service reliability. Battery storage and water storage are not interchangeable, but both can shift when energy is used.",application:"Design and defend an operating strategy that schedules pumping and storage under defined energy availability, water demand, reserve and equipment constraints.",dataAi:"Use AI or optimization tools to compare scenarios and forecast-informed strategies, while validating feasibility against pump limits, tank capacity, energy balance and safety constraints.",enterprise:"Water-energy optimization services can reduce operating cost or improve reliability. Proposals should quantify assumptions and distinguish modeled benefits from measured performance."},
  "GA-04": {fundamentals:"Advanced agrivoltaic design coordinates photovoltaic geometry, crop requirements, water systems, access, structure, operations, monitoring and economics. It is a multi-objective design problem rather than a photovoltaic project with crops added afterward.",relationships:"Changes in panel height, spacing and orientation affect energy production, shading patterns, machinery access, irrigation layout, maintenance and capital cost.",application:"Prepare an agrivoltaic design and operations plan that identifies performance objectives, layout trade-offs, crop/operations constraints, monitoring needs and maintenance access.",dataAi:"AI can support alternative-layout exploration and trade-off documentation, but agronomic, structural and electrical decisions must remain within qualified professional review.",enterprise:"Agrivoltaic advisory can include feasibility, operations planning and monitoring. Clearly separate preliminary advisory from stamped engineering, permitting or specialist agronomy where those are required."},
  "GA-05": {fundamentals:"Advanced monitoring architecture defines sensors, telemetry, timestamps, metadata, calibration, validation, storage, quality flags and access. Data quality must be designed, not inspected only after problems appear.",relationships:"A decision system is only as trustworthy as its data lineage. Communications gaps, clock drift, sensor drift and undocumented maintenance can invalidate otherwise sophisticated analysis.",application:"Build a sensor and telemetry plan with data dictionary, validation checks, quality flags, maintenance expectations and a response procedure for missing or implausible data.",dataAi:"AI can assist anomaly detection and data triage, but every automated flag should preserve provenance and allow human review of why data were accepted, corrected or rejected.",enterprise:"Monitoring-architecture and data-quality services can support performance contracts and digital twins. Define data ownership, reporting frequency, quality thresholds and support responsibilities."},
  "GA-06": {fundamentals:"Advanced CHIPU control architecture manages multiple states, priorities, constraints and failure responses across FEW assets. The system should define who or what has authority to act and under which conditions.",relationships:"Forecasts and AI models may influence decisions, but interlocks, equipment limits, minimum reserves and manual override establish non-negotiable boundaries.",application:"Develop state logic for a multi-asset FEW scenario, including inputs, decisions, actuators, alarms, interlocks, degraded modes, manual override and safe shutdown behavior.",dataAi:"Treat AI/model outputs as advisory or bounded control inputs. Log recommendations, accepted actions, rejected actions and the rule or human decision that determined the final outcome.",enterprise:"Smart-control integration services require commissioning, cybersecurity awareness, operator training and change control. Customers must understand what the automation can and cannot do."},
  "GA-07": {fundamentals:"System performance analysis converts operational data into defensible indicators such as energy yield, water delivery, pumping efficiency, uptime, irrigation performance, resource productivity and cost.",relationships:"KPIs require correct denominators, time windows and normalization. Apparent improvement can be caused by weather, demand changes, missing data or altered operating conditions rather than the intervention being evaluated.",application:"Analyze a FEW dataset, define appropriate KPIs, normalize where needed, visualize trends and distinguish observation from causal interpretation.",dataAi:"Use AI to support coding, anomaly review or interpretation, but verify calculations and avoid unsupported causal claims. Preserve source data and analytical steps.",enterprise:"Performance analytics can support optimization, service agreements and investment decisions. Reports should focus on decisions the customer can take and the uncertainty around each conclusion."},
  "GA-08": {fundamentals:"Reliability engineering examines how and why systems fail. Fault trees, FMEA, criticality ranking and root-cause analysis help prioritize preventive actions instead of treating every fault equally.",relationships:"A visible symptom may have several underlying causes, and one root cause may create multiple symptoms. Reliability analysis links failure modes to consequences, detection methods and controls.",application:"Complete an FMEA or fault-tree exercise, rank critical failure modes, investigate a selected fault using evidence and propose corrective and preventive actions.",dataAi:"AI can expand the hypothesis set, but ranking must use physical plausibility, failure history, measurements and system knowledge rather than language-model confidence.",enterprise:"Reliability diagnostic services create value by reducing downtime and repeat failures. Recommendations should identify priority, evidence, expected benefit and residual risk."},
  "GA-09": {fundamentals:"Operations and maintenance planning transforms assets into a managed lifecycle. It includes asset registers, criticality, inspection intervals, preventive tasks, condition-based triggers, spares, documentation and responsibilities.",relationships:"Not every asset deserves the same maintenance intensity. Criticality, failure consequence, environment, redundancy and replacement lead time determine priorities.",application:"Prepare an O&M plan with asset criticality, task schedule, trigger conditions, spares strategy, documentation requirements and escalation procedures.",dataAi:"AI can organize maintenance knowledge and summarize history, but service intervals and actions must be grounded in manufacturer guidance, actual condition and risk assessment.",enterprise:"O&M planning supports recurring service contracts and lifecycle budgeting. Define response times, included tasks, exclusions, reporting and customer responsibilities."},
  "GA-10": {fundamentals:"Technical economics connects engineering choices to lifecycle cost and value. Core concepts include CAPEX, OPEX, replacement, maintenance, energy or water savings, revenue, time horizon, sensitivity and uncertainty.",relationships:"The lowest upfront cost may not be the lowest lifecycle cost. Technical performance, utilization, downtime, financing and replacement assumptions strongly influence economic outcomes.",application:"Complete a preliminary technical-economic assessment with transparent assumptions, cost categories, benefits, sensitivity cases and a recommendation that reflects uncertainty.",dataAi:"AI can help generate scenarios or organize cost categories, but it must not fabricate market prices. Every cost input should have a source, date or explicit assumption.",enterprise:"Technical-economic advisory helps customers compare investments. Ethical practice requires distinguishing estimates from quotations and avoiding guaranteed savings without supporting evidence."},
  "GA-11": {fundamentals:"Technical leadership aligns people, documents and decisions so complex work remains controlled. Key practices include design review, QA/QC, revision control, change management, meeting records, operator training and handover.",relationships:"Uncontrolled changes can invalidate drawings, calculations, procurement and safety assumptions. Leadership therefore requires both communication and configuration control.",application:"Prepare and present a controlled handover package with revision status, outstanding items, operating guidance, training record and acceptance evidence.",dataAi:"AI may support drafting, synthesis and meeting summaries, but accountable humans approve technical content and maintain revision history.",enterprise:"Technical supervision and QA/QC are professional services in their own right. Define review authority, deliverables, acceptance criteria and how changes are authorized."},
  "GA-12": {fundamentals:"The advanced capstone integrates architecture, photovoltaic design, water-energy strategy, agrivoltaics, sensing, controls, performance, reliability, O&M, economics and leadership into one defensible solution.",relationships:"A capstone must reconcile competing objectives rather than optimize one subsystem. Technical performance, safety, reliability, maintainability, cost and user needs should be evaluated together.",application:"Develop, document and defend an integrated FEW solution including requirements, architecture, calculations, control logic, monitoring, reliability, O&M, economics and implementation plan.",dataAi:"Use AI transparently across research, scenario development, coding or analysis. Maintain an AI Work Log and independently verify every consequential technical decision.",enterprise:"Present the capstone as an investment-ready or service-ready proposal with customer problem, technical solution, cost, risk, implementation phases, evidence plan and after-service strategy."},
};

function tierDepth(tier: GreenTechTier) {
  if (tier.code === "GF") return "At foundation level, the learner should be able to explain the concept clearly, work safely under supervision and produce basic traceable evidence.";
  if (tier.code === "GT2") return "At technician level, the learner should be able to perform defined technical work with increasing independence, quantify decisions and complete commissioning-quality records.";
  return "At advanced level, the learner should be able to justify design choices, evaluate trade-offs, manage uncertainty and defend decisions to technical and non-technical stakeholders.";
}

export function getGreenTechLearningSections(tier: GreenTechTier, module: GreenTechModule): GreenTechLearningSection[] {
  const s = specifics[module.code];
  if (!s) throw new Error(`Missing developed GreenTech learning content for ${module.code}`);
  return [
    {
      title: "Learning Section 1 — Understand the Core System",
      objective: `Explain the essential concepts behind ${module.title} and connect them to the stated competency: ${module.competency}`,
      teaching: [s.fundamentals, tierDepth(tier)],
      keyPoints: ["Define the system or task before selecting tools or solutions.", "Separate verified facts from assumptions.", "Connect the module concept to food, energy and water outcomes."],
      learnerPrompt: `Explain ${module.title} in your own words. Identify the main components or variables, the technical purpose, and one reason this competence matters in a real FEW system.`,
    },
    {
      title: "Learning Section 2 — Explore Relationships, Safety & Failure",
      objective: "Explain how components or variables interact, identify safety boundaries and predict what can go wrong.",
      teaching: [s.relationships, "Think in cause-and-effect chains: input → process → output → feedback. A competent technician should be able to explain not only what a component does, but how its behavior influences the rest of the system."],
      keyPoints: ["Identify interfaces between components and people.", "State at least one credible failure mode and consequence.", "Apply LIFEWS stop-work principles whenever a safety boundary is uncertain."],
      learnerPrompt: `Describe two important relationships within this module. For each, explain what could fail, what evidence would reveal the problem, and what safety action or escalation would be appropriate.`,
    },
    {
      title: "Learning Section 3 — Apply, Measure & Calculate",
      objective: "Translate the concept into a measurable technical task using units, procedures, calculations and acceptance checks.",
      teaching: [s.application, `The required practical for this module is: ${module.diy} Measurements and calculations must include units, source or method, and enough context for another technician to reproduce or review the work.`],
      keyPoints: ["Record measured values before interpretation.", "Show calculation steps and units.", "Define what acceptable performance would look like before declaring success."],
      learnerPrompt: `Prepare the measurement and calculation plan for ${module.diy} List the values to record, the units, the tools or data sources, the calculation steps and the acceptance criteria you would use.`,
    },
    {
      title: "Learning Section 4 — Data, Digital Tools & AI",
      objective: `Use digital tools and AI at the ${tier.aiStage} level while preserving verification, traceability and human responsibility.`,
      teaching: [s.dataAi, `Module AI focus: ${module.aiFocus} No AI-generated instruction overrides LIFEWS safety procedures, trainer instructions, equipment manufacturer requirements, applicable standards or competent professional judgment.`],
      keyPoints: ["Record what data or prompt was provided to AI.", "Verify outputs against measurements, trusted documentation or calculation.", "Document corrections and the final human decision."],
      learnerPrompt: "Describe one appropriate AI-assisted task for this module. State the input, expected output, verification method, one possible AI error and the final decision that must remain with the learner or responsible professional.",
    },
    {
      title: "Learning Section 5 — Enterprise, Field Application & Reflection",
      objective: `Connect the competence to a real service opportunity at the ${tier.enterpriseStage} level and define professional evidence of value.`,
      teaching: [s.enterprise, `Field focus: ${module.fieldFocus}. Enterprise focus: ${module.enterpriseFocus}. A responsible service clearly states customer problem, scope, exclusions, cost basis, evidence, handover and after-service.`],
      keyPoints: ["Solve a real customer or community problem, not an invented need.", "Price only work that can be delivered safely and competently.", "Use evidence, documentation and after-service to build trust."],
      learnerPrompt: `Identify a realistic customer or community need related to ${module.title}. Define the service scope, what you would measure or deliver, one exclusion, the main cost categories and what evidence would prove the work was completed properly.`,
    },
  ];
}
