import type { AppLanguage } from "@/lib/i18n6";
import type { CurriculumProgram } from "@/lib/curriculum";
import type { GreenSkillsProgram } from "@/lib/greenskills";

export type ProgramArm = "pathways" | "kadara" | "greentech";

const common = {
  en: { language: "Language", greenSkillsHome: "GreenSkills Home", pathways: "Pathways", kadara: "Kadara", greenTech: "GreenTech", skillsPassport: "Skills Passport", fieldWorks: "FieldWorks", learnerSpace: "Learner space", staffWorkspace: "Staff workspace", curriculum: "Curriculum", staffSignIn: "Staff sign in", backToGreenSkills: "Back to GreenSkills", competency: "Competency", diy: "DIY / practical", commonFramework: "COMMON COMPETENCY FRAMEWORK", domainsFollow: "Six domains follow the learner.", domainsPassport: "Six domains recorded in the Skills Passport.", assessmentEvidence: "ASSESSMENT & EVIDENCE", competenceNotAttendance: "COMPETENCE, NOT ATTENDANCE", assessmentTitle: "Every lesson includes a practical proof point.", certificationTitle: "Certification requires verified evidence.", metrics: ["8 MCQs","5 theory questions","Mandatory DIY","Practical checklist","Evidence upload","Skills Passport update"], domains: ["Knowledge","Practical Skills","Data & Digital","Safety","Enterprise & Employability","Leadership & Life Skills"] },
  ha: { language: "Harshe", greenSkillsHome: "Gidan GreenSkills", pathways: "Pathways", kadara: "Kadara", greenTech: "GreenTech", skillsPassport: "Fasfon Ƙwarewa", fieldWorks: "FieldWorks", learnerSpace: "Wurin ɗalibi", staffWorkspace: "Wurin ma’aikata", curriculum: "Manhaja", staffSignIn: "Shigar ma’aikata", backToGreenSkills: "Koma GreenSkills", competency: "Ƙwarewa", diy: "DIY / aiki", commonFramework: "TSARIN ƘWAREWA NA GAMA-GARI", domainsFollow: "Fannoni shida suna bin ci gaban ɗalibi.", domainsPassport: "Ana rubuta fannoni shida a Fasfon Ƙwarewa.", assessmentEvidence: "KIMANTAWA DA SHAIDA", competenceNotAttendance: "ƘWAREWA, BA HALARTA KAWAI BA", assessmentTitle: "Kowane darasi yana da shaidar aiki.", certificationTitle: "Takardar shaida tana buƙatar tabbatacciyar hujja.", metrics: ["Tambayoyi 8 na zaɓi","Tambayoyin bayani 5","DIY dole","Jerin duba aiki","Loda shaida","Sabunta Fasfon Ƙwarewa"], domains: ["Ilimi","Ƙwarewar Aiki","Bayanai da Dijital","Tsaro","Sana’a da Samun Aiki","Jagoranci da Ƙwarewar Rayuwa"] },
  ar: { language: "اللغة", greenSkillsHome: "الرئيسية لـ GreenSkills", pathways: "Pathways", kadara: "Kadara", greenTech: "GreenTech", skillsPassport: "جواز المهارات", fieldWorks: "FieldWorks", learnerSpace: "مساحة المتعلم", staffWorkspace: "مساحة الموظفين", curriculum: "المنهج", staffSignIn: "دخول الموظفين", backToGreenSkills: "العودة إلى GreenSkills", competency: "الكفاءة", diy: "عمل تطبيقي / DIY", commonFramework: "إطار الكفاءات المشترك", domainsFollow: "ستة مجالات تتابع تقدم المتعلم.", domainsPassport: "تُسجَّل ستة مجالات في جواز المهارات.", assessmentEvidence: "التقييم والأدلة", competenceNotAttendance: "الكفاءة لا الحضور فقط", assessmentTitle: "يتضمن كل درس دليلاً عملياً.", certificationTitle: "تتطلب الشهادة أدلة موثقة.", metrics: ["8 أسئلة اختيار من متعدد","5 أسئلة نظرية","DIY إلزامي","قائمة تحقق عملية","رفع الأدلة","تحديث جواز المهارات"], domains: ["المعرفة","المهارات العملية","البيانات والرقمنة","السلامة","ريادة الأعمال وقابلية التوظيف","القيادة ومهارات الحياة"] },
  yo: { language: "Èdè", greenSkillsHome: "Ilé GreenSkills", pathways: "Pathways", kadara: "Kadara", greenTech: "GreenTech", skillsPassport: "Pásípò Ọgbọ́n", fieldWorks: "FieldWorks", learnerSpace: "Àyè akẹ́kọ̀ọ́", staffWorkspace: "Àyè òṣìṣẹ́", curriculum: "Ètò ẹ̀kọ́", staffSignIn: "Wọlé gẹ́gẹ́ bí òṣìṣẹ́", backToGreenSkills: "Padà sí GreenSkills", competency: "Agbára iṣẹ́", diy: "DIY / iṣẹ́ ọwọ́", commonFramework: "ÈTÒ AGBÁRA IṢẸ́ APAPỌ̀", domainsFollow: "Àwọn ẹ̀ka mẹ́fà ń tẹ̀lé ìlọsíwájú akẹ́kọ̀ọ́.", domainsPassport: "A ń kọ àwọn ẹ̀ka mẹ́fà sínú Pásípò Ọgbọ́n.", assessmentEvidence: "ÌDÁNWÒ ÀTI Ẹ̀RÍ", competenceNotAttendance: "AGBÁRA IṢẸ́, KÌ Í ṢE WÍWÀ NÍ KÍLÁÀSÌ NIKAN", assessmentTitle: "Gbogbo ẹ̀kọ́ ní ẹ̀rí iṣẹ́ ọwọ́ kan.", certificationTitle: "Ìjẹ́rìí nilo ẹ̀rí tí a fìdí múlẹ̀.", metrics: ["MCQ 8","Ìbéèrè àlàyé 5","DIY dandan","Àtòjọ ìdánwò iṣẹ́","Gbé ẹ̀rí sókè","Ṣe àfikún Pásípò Ọgbọ́n"], domains: ["Ìmọ̀","Ọgbọ́n Iṣẹ́","Data àti Dijítà","Ààbò","Iṣòwò àti Ṣíṣeé-Gbà-Síṣẹ́","Olórí àti Ọgbọ́n Ìgbésí-ayé"] },
  ig: { language: "Asụsụ", greenSkillsHome: "Ụlọ GreenSkills", pathways: "Pathways", kadara: "Kadara", greenTech: "GreenTech", skillsPassport: "Paspọtụ Nkà", fieldWorks: "FieldWorks", learnerSpace: "Ebe onye mmụta", staffWorkspace: "Ebe ndị ọrụ", curriculum: "Usoro ọmụmụ", staffSignIn: "Nbanye ndị ọrụ", backToGreenSkills: "Laghachi na GreenSkills", competency: "Ikike", diy: "DIY / ọrụ aka", commonFramework: "USORO IKIKE NDỊ A NA-EJIKỌ ỌNỤ", domainsFollow: "Ngalaba isii na-eso ọganihu onye mmụta.", domainsPassport: "A na-edekọ ngalaba isii na Paspọtụ Nkà.", assessmentEvidence: "NLELE NA IHE AKAEBE", competenceNotAttendance: "IKIKE, Ọ BỤGHỊ NANỊ ỊBỊA KLASỊ", assessmentTitle: "Ihe ọmụmụ ọ bụla nwere ihe akaebe ọrụ.", certificationTitle: "Asambodo chọrọ ihe akaebe e nyochara.", metrics: ["MCQ 8","Ajụjụ nkọwa 5","DIY a chọrọ","Ndepụta nyocha ọrụ","Bulite ihe akaebe","Melite Paspọtụ Nkà"], domains: ["Ọmụma","Nkà Ọrụ","Data na Dijitalụ","Nchekwa","Azụmahịa na Nrụọrụ","Nduzi na Nkà Ndụ"] },
  fr: { language: "Langue", greenSkillsHome: "Accueil GreenSkills", pathways: "Pathways", kadara: "Kadara", greenTech: "GreenTech", skillsPassport: "Passeport de compétences", fieldWorks: "FieldWorks", learnerSpace: "Espace apprenant", staffWorkspace: "Espace du personnel", curriculum: "Programme", staffSignIn: "Connexion du personnel", backToGreenSkills: "Retour à GreenSkills", competency: "Compétence", diy: "DIY / pratique", commonFramework: "CADRE COMMUN DE COMPÉTENCES", domainsFollow: "Six domaines suivent la progression de l’apprenant.", domainsPassport: "Six domaines sont consignés dans le Passeport de compétences.", assessmentEvidence: "ÉVALUATION ET PREUVES", competenceNotAttendance: "LA COMPÉTENCE, PAS SEULEMENT LA PRÉSENCE", assessmentTitle: "Chaque leçon comprend une preuve pratique.", certificationTitle: "La certification exige des preuves vérifiées.", metrics: ["8 QCM","5 questions théoriques","DIY obligatoire","Liste de contrôle pratique","Téléversement de preuves","Mise à jour du Passeport de compétences"], domains: ["Connaissances","Compétences pratiques","Données et numérique","Sécurité","Entreprise et employabilité","Leadership et compétences de vie"] },
} as const;

export const greenSkillsHomeCopy = {
  en: {
    tagline: "Skills for Food • Energy • Water • Livelihoods", nav: common.en, eyebrow: "A LIFEWS CAPABILITY PLATFORM", hero1: "Skills that move people", hero2: "from learning to livelihood.", intro: "LIFEWS GreenSkills connects inclusive learning, practical livelihood skills and advanced technical training through three distinct programs and one shared skills identity.", explore: "Explore programs", journey: ["LEARN","PRACTICE","CERTIFY","WORK","BUILD","THRIVE"], programsEyebrow: "THREE PROGRAMS. ONE SYSTEM.", programsTitle: "Choose the pathway that matches the learner.", programsBody: "Participants do not have to pass through all three programs. They enter at the level appropriate to age, prior learning, goals and demonstrated competence.", flexible: "FLEXIBLE ENTRY. VERIFIED PROGRESSION.", routesTitle: "One ecosystem, multiple routes.", routes: [["YOUNGER LEARNER","Pathways → Education","Foundational learning followed by formal-school re-entry, approved alternative education or continuing learning."],["OLDER ADOLESCENT","Pathways → Kadara","Inclusive learning followed by vocational competence, employability and livelihood development."],["TECHNICAL ROUTE","Kadara → GreenTech","Occupational foundations followed by advanced FEW-system technical training, practical assessment and certification."],["DIRECT ENTRY","Kadara or GreenTech","Eligible youth, artisans, technicians and graduates can enter at an appropriate competency level without completing Pathways first."]], sharedEyebrow: "SHARED INFRASTRUCTURE", sharedTitle: "What connects the three programs.", sharedBody: "GreenSkills develops capability. AgriHubs provide places to practise. LIFEWS systems provide equipment. CHIPU supports monitoring and intelligence.", passportEyebrow: "ONE GREEN SKILLS IDENTITY", passportTitle: "LIFEWS Skills Passport", passportBody: "Courses, competencies, badges, certificates, projects, field hours, supervisor verification and transitions remain connected to one participant record.", passportFields: ["Courses","Competencies","Projects","Badges","Certificates","Field hours","Portfolio evidence","Transitions"], sidebarFooter: ["LEARN","PRACTICE","BUILD","THRIVE"] },
  ha: {
    tagline: "Ƙwarewa don Abinci • Makamashi • Ruwa • Rayuwa", nav: common.ha, eyebrow: "DANDALIN ƘWAREWA NA LIFEWS", hero1: "Ƙwarewar da ke motsa mutane", hero2: "daga koyo zuwa hanyar samun rayuwa.", intro: "LIFEWS GreenSkills tana haɗa koyo mai ɗaukar kowa, ƙwarewar sana’a da horon fasaha mai zurfi ta shirye-shirye uku da fasfon ƙwarewa guda ɗaya.", explore: "Duba shirye-shirye", journey: ["KOYO","AIKI","SAMUN SHAIDA","AIKI","GINA","CI GABA"], programsEyebrow: "SHIRYE-SHIRYE UKU. TSARI ƊAYA.", programsTitle: "Zaɓi hanyar da ta dace da ɗalibi.", programsBody: "Ba dole ba ne mahalarta su bi dukkan shirye-shiryen uku. Suna shiga matakin da ya dace da shekaru, ilimin baya, buri da ƙwarewar da aka nuna.", flexible: "SHIGA CIKIN SAUƘI. CI GABA MAI TABBATARWA.", routesTitle: "Tsari ɗaya, hanyoyi da yawa.", routes: [["ƊALIBI ƘARAMI","Pathways → Ilimi","Koyo na tushe sannan komawa makaranta, madadin ilimi da aka amince da shi ko ci gaba da koyo."],["MATASHI BABBAN SHEKARA","Pathways → Kadara","Koyo mai haɗawa sannan ƙwarewar sana’a, samun aiki da gina hanyar rayuwa."],["HANYAR FASAHA","Kadara → GreenTech","Tushe na sana’a sannan horon fasaha na tsarin abinci-makamashi-ruwa, gwajin aiki da takardar shaida."],["SHIGA KAI TSAYE","Kadara ko GreenTech","Matasan da suka cancanta, masu sana’a, teknishiyoyi da masu digiri za su iya shiga matakin da ya dace ba tare da kammala Pathways ba."]], sharedEyebrow: "ABUBUWAN DA AKE AMFANI DA SU TARE", sharedTitle: "Abin da ke haɗa shirye-shiryen uku.", sharedBody: "GreenSkills tana gina ƙwarewa. AgriHubs suna samar da wuraren aiki. Tsarin LIFEWS yana samar da kayan aiki. CHIPU yana tallafa wa sa ido da basirar tsarin.", passportEyebrow: "SHAIDAR GREEN SKILLS GUDA ƊAYA", passportTitle: "Fasfon Ƙwarewa na LIFEWS", passportBody: "Darussa, ƙwarewa, bajuna, takardun shaida, ayyuka, sa’o’in fili, tabbatarwar mai kula da sauye-sauye suna kasancewa a haɗe da rikodin mahalarta guda ɗaya.", passportFields: ["Darussa","Ƙwarewa","Ayyuka","Bajuna","Takardun shaida","Sa’o’in fili","Shaidar kundin aiki","Sauye-sauye"], sidebarFooter: ["KOYO","AIKI","GINA","CI GABA"] },
  ar: {
    tagline: "مهارات للغذاء • الطاقة • المياه • سبل العيش", nav: common.ar, eyebrow: "منصة LIFEWS لبناء القدرات", hero1: "مهارات تنقل الناس", hero2: "من التعلّم إلى سبل العيش.", intro: "تربط LIFEWS GreenSkills بين التعلّم الشامل والمهارات العملية لكسب العيش والتدريب التقني المتقدم عبر ثلاثة برامج وهوية مهارية مشتركة.", explore: "استكشاف البرامج", journey: ["تعلّم","تدرّب","احصل على شهادة","اعمل","ابنِ","ازدهر"], programsEyebrow: "ثلاثة برامج. نظام واحد.", programsTitle: "اختر المسار المناسب للمتعلم.", programsBody: "لا يلزم أن يمر المشاركون بالبرامج الثلاثة كلها. يدخلون المستوى المناسب للعمر والتعلّم السابق والأهداف والكفاءة المثبتة.", flexible: "دخول مرن. تقدم موثّق.", routesTitle: "منظومة واحدة، مسارات متعددة.", routes: [["متعلم أصغر","Pathways → التعليم","تعلّم تأسيسي يتبعه العودة إلى المدرسة أو تعليم بديل معتمد أو تعلّم مستمر."],["مراهق أكبر","Pathways → Kadara","تعلّم شامل يتبعه تأهيل مهني وقابلية للتوظيف وتنمية سبل العيش."],["المسار التقني","Kadara → GreenTech","أسس مهنية يتبعها تدريب تقني متقدم لأنظمة الغذاء والطاقة والمياه وتقييم عملي وشهادة."],["دخول مباشر","Kadara أو GreenTech","يمكن للشباب والحرفيين والفنيين والخريجين المؤهلين الدخول في مستوى الكفاءة المناسب دون إكمال Pathways أولاً."]], sharedEyebrow: "البنية التحتية المشتركة", sharedTitle: "ما الذي يربط البرامج الثلاثة؟", sharedBody: "تطوّر GreenSkills القدرات، وتوفر AgriHubs أماكن للتدريب، وتوفر أنظمة LIFEWS المعدات، ويدعم CHIPU المراقبة والذكاء التشغيلي.", passportEyebrow: "هوية مهارية واحدة", passportTitle: "جواز مهارات LIFEWS", passportBody: "تبقى الدورات والكفاءات والشارات والشهادات والمشروعات وساعات الميدان وتحقق المشرف والانتقالات مرتبطة بسجل مشارك واحد.", passportFields: ["الدورات","الكفاءات","المشروعات","الشارات","الشهادات","ساعات الميدان","أدلة الملف","الانتقالات"], sidebarFooter: ["تعلّم","تدرّب","ابنِ","ازدهر"] },
  yo: {
    tagline: "Ọgbọ́n fún Oúnjẹ • Agbára • Omi • Ìgbésí-ayé", nav: common.yo, eyebrow: "PẸ́LẸ́TÍFỌ́Ọ̀MÙ AGBÁRA LIFEWS", hero1: "Ọgbọ́n tó ń gbé ènìyàn lọ", hero2: "láti ẹ̀kọ́ sí ìgbésí-ayé.", intro: "LIFEWS GreenSkills so ẹ̀kọ́ tó ṣí sí gbogbo ènìyàn, ọgbọ́n iṣẹ́ ìgbésí-ayé àti ìdánilẹ́kọ̀ọ́ imọ̀-ẹ̀rọ tó jinlẹ̀ pọ̀ nípasẹ̀ ètò mẹ́ta àti ìdánimọ̀ ọgbọ́n kan.", explore: "Ṣàwárí àwọn ètò", journey: ["KỌ́","ṢE ADAṢE","GBA ÌJẸ́RÌÍ","ṢIṢẸ́","KỌ́","DÀGBÀ"], programsEyebrow: "ÈTÒ MẸ́TA. ÈTÒ-Ọ̀NÀ KAN.", programsTitle: "Yan ọ̀nà tó bá akẹ́kọ̀ọ́ mu.", programsBody: "Kò pọn dandan kí olukopa kọjá gbogbo ètò mẹ́ta. Wọ́n wọ ìpele tó bá ọjọ́-ori, ẹ̀kọ́ tẹ́lẹ̀, àfojúsùn àti agbára tí wọ́n ti fi hàn mu.", flexible: "ÌWỌLÉ RỌRÙN. ÌLỌSÍWÁJÚ TÍ A FÌDÍ MÚLẸ̀.", routesTitle: "Ecosystem kan, ọ̀nà púpọ̀.", routes: [["AKẸ́KỌ̀Ọ́ KÉKERÉ","Pathways → Ẹ̀kọ́","Ẹ̀kọ́ ìpilẹ̀, lẹ́yìn náà ìpadà sí ilé-ẹ̀kọ́, ẹ̀kọ́ àfidípò tàbí ẹ̀kọ́ tó ń bá a lọ."],["ỌDỌ́ TÓ TI DÀGBÀ","Pathways → Kadara","Ẹ̀kọ́ tó kó gbogbo ènìyàn wọlé, lẹ́yìn náà ọgbọ́n iṣẹ́, ìmúrasílẹ̀ iṣẹ́ àti ìdàgbàsókè ìgbésí-ayé."],["Ọ̀NÀ IMỌ̀-Ẹ̀RỌ","Kadara → GreenTech","Ìpilẹ̀ iṣẹ́, lẹ́yìn náà ìdánilẹ́kọ̀ọ́ FEW tó jinlẹ̀, ìdánwò iṣẹ́ àti ìjẹ́rìí."],["ÌWỌLÉ TÀÀRÀ","Kadara tàbí GreenTech","Àwọn ọdọ, oníṣẹ́ ọwọ́, teknishan àti akẹ́kọ̀ọ́ gírámádùẹ́ẹ̀tì tó yẹ lè wọ ìpele tó bá agbára wọn mu láì kọ́kọ́ parí Pathways."]], sharedEyebrow: "AMÁYÉDẸRÙN APAPỌ̀", sharedTitle: "Kí ni ń so àwọn ètò mẹ́ta pọ̀?", sharedBody: "GreenSkills ń kọ́ agbára. AgriHubs ń pèsè ibi adaṣe. Eto LIFEWS ń pèsè ohun èlò. CHIPU ń ṣe atilẹyin ìmójútó àti ọgbọ́n eto.", passportEyebrow: "ÌDÁNIMỌ̀ GREEN SKILLS KAN", passportTitle: "Pásípò Ọgbọ́n LIFEWS", passportBody: "Ẹ̀kọ́, agbára, baaji, ìjẹ́rìí, iṣẹ́ àkànṣe, wákàtí pápá, ìfọwọ́sí olùbojútó àti ìyípadà ń dúró pọ̀ mọ́ igbasilẹ olukopa kan.", passportFields: ["Ẹ̀kọ́","Agbára","Iṣẹ́ àkànṣe","Baaji","Ìjẹ́rìí","Wákàtí pápá","Ẹ̀rí portfolio","Ìyípadà"], sidebarFooter: ["KỌ́","ṢE ADAṢE","KỌ́","DÀGBÀ"] },
  ig: {
    tagline: "Nkà maka Nri • Ike • Mmiri • Ihe E Ji Ebi", nav: common.ig, eyebrow: "IKPO OKWUTE IKE LIFEWS", hero1: "Nkà na-akwalite mmadụ", hero2: "site n’ịmụ ihe ruo n’ọrụ ndụ.", intro: "LIFEWS GreenSkills jikọtara mmụta gụnyere mmadụ niile, nkà bara uru maka ọrụ ndụ na ọzụzụ teknụzụ dị elu site na mmemme atọ na otu njirimara nkà.", explore: "Lelee mmemme", journey: ["MỤTA","MEE OMUME","NATA ASAMBODO","RỤỌ ỌRỤ","WULITE","TOO"], programsEyebrow: "MMEMME ATỌ. OTU USORO.", programsTitle: "Họrọ ụzọ dabara onye mmụta.", programsBody: "Ndị sonyere agaghị agafe mmemme atọ niile. Ha na-abanye n’ọkwa dabara afọ, mmụta gara aga, ebumnuche na ikike ha gosipụtara.", flexible: "NBANYE NA-AGBANWE AGbanwe. ỌGANIHU E KWESỊRỊ IKWA AKA.", routesTitle: "Otu ecosystem, ọtụtụ ụzọ.", routes: [["ONYE MMỤTA DỊ NTỌ","Pathways → Agụmakwụkwọ","Mmụta ntọala, mgbe ahụ ịlaghachi ụlọ akwụkwọ, agụmakwụkwọ ọzọ a kwadoro ma ọ bụ mmụta na-aga n’ihu."],["NWATA TOZURU ETO","Pathways → Kadara","Mmụta gụnyere mmadụ niile, mgbe ahụ nkà ọrụ, nkwadebe ọrụ na mmepe ihe e ji ebi ndụ."],["ỤZỌ TEKNỤZỤ","Kadara → GreenTech","Ntọala ọrụ, mgbe ahụ ọzụzụ teknụzụ FEW dị elu, nyocha ọrụ na asambodo."],["NBANYE OZUGBO","Kadara ma ọ bụ GreenTech","Ndị ntorobịa, ndị ọrụ aka, teknishian na ndị gụsịrị akwụkwọ nwere ike ịbanye n’ọkwa ikike dabara ha na-enweghị imecha Pathways mbụ."]], sharedEyebrow: "AKỤRỤNGWA A NA-EJIKỌ ỌNỤ", sharedTitle: "Ihe na-ejikọta mmemme atọ.", sharedBody: "GreenSkills na-ewulite ikike. AgriHubs na-enye ebe a na-eme omume. Sistemụ LIFEWS na-enye akụrụngwa. CHIPU na-akwado nlekota na ọgụgụ isi sistemụ.", passportEyebrow: "OTU NJIRIMARA GREEN SKILLS", passportTitle: "Paspọtụ Nkà LIFEWS", passportBody: "Usoro ọmụmụ, ikike, baajị, asambodo, ọrụ, awa ubi, nkwenye onye nlekọta na mgbanwe na-anọgide jikọtara na otu ndekọ onye sonyere.", passportFields: ["Usoro ọmụmụ","Ikike","Ọrụ","Baajị","Asambodo","Awa ubi","Ihe akaebe portfolio","Mgbanwe"], sidebarFooter: ["MỤTA","MEE OMUME","WULITE","TOO"] },
  fr: {
    tagline: "Compétences pour l’alimentation • l’énergie • l’eau • les moyens de subsistance", nav: common.fr, eyebrow: "PLATEFORME DE CAPACITÉS LIFEWS", hero1: "Des compétences qui font avancer les personnes", hero2: "de l’apprentissage aux moyens de subsistance.", intro: "LIFEWS GreenSkills relie l’apprentissage inclusif, les compétences pratiques de subsistance et la formation technique avancée au moyen de trois programmes distincts et d’une identité de compétences commune.", explore: "Explorer les programmes", journey: ["APPRENDRE","PRATIQUER","CERTIFIER","TRAVAILLER","CONSTRUIRE","PROSPÉRER"], programsEyebrow: "TROIS PROGRAMMES. UN SYSTÈME.", programsTitle: "Choisissez le parcours adapté à l’apprenant.", programsBody: "Les participants ne sont pas obligés de suivre les trois programmes. Ils entrent au niveau adapté à leur âge, leurs acquis, leurs objectifs et leurs compétences démontrées.", flexible: "ENTRÉE FLEXIBLE. PROGRESSION VÉRIFIÉE.", routesTitle: "Un écosystème, plusieurs parcours.", routes: [["APPRENANT PLUS JEUNE","Pathways → Éducation","Apprentissage fondamental suivi d’un retour à l’école, d’une éducation alternative approuvée ou d’un apprentissage continu."],["ADOLESCENT PLUS ÂGÉ","Pathways → Kadara","Apprentissage inclusif suivi de compétences professionnelles, d’employabilité et de développement des moyens de subsistance."],["PARCOURS TECHNIQUE","Kadara → GreenTech","Bases professionnelles suivies d’une formation technique avancée aux systèmes FEW, d’une évaluation pratique et d’une certification."],["ENTRÉE DIRECTE","Kadara ou GreenTech","Les jeunes, artisans, techniciens et diplômés admissibles peuvent entrer au niveau de compétence approprié sans avoir d’abord terminé Pathways."]], sharedEyebrow: "INFRASTRUCTURE PARTAGÉE", sharedTitle: "Ce qui relie les trois programmes.", sharedBody: "GreenSkills développe les capacités. Les AgriHubs offrent des lieux de pratique. Les systèmes LIFEWS fournissent l’équipement. CHIPU soutient le suivi et l’intelligence des systèmes.", passportEyebrow: "UNE IDENTITÉ GREEN SKILLS", passportTitle: "Passeport de compétences LIFEWS", passportBody: "Cours, compétences, badges, certificats, projets, heures de terrain, vérification du superviseur et transitions restent liés à un seul dossier participant.", passportFields: ["Cours","Compétences","Projets","Badges","Certificats","Heures de terrain","Preuves de portfolio","Transitions"], sidebarFooter: ["APPRENDRE","PRATIQUER","CONSTRUIRE","PROSPÉRER"] },
} as const;

const programCards = {
  en: {
    pathways: { eyebrow:"LEARNING & TRANSITION", tagline:"From Learning to Opportunity", purpose:"An inclusive learning and transition program creating flexible routes back into education, skills and future opportunity.", themes:["Foundational learning","Literacy & numeracy","Life skills","GrowMeal practical learning","Food literacy","Digital foundations"], action:"Explore Pathways" },
    kadara: { eyebrow:"SKILLS, WORK & ENTERPRISE", tagline:"Learn. Build. Earn.", purpose:"A vocational, employability and enterprise pathway helping older adolescents and young adults build practical skills and sustainable livelihoods.", themes:["Agriculture","Food production","Food processing","Packaging","Energy","Water"], action:"Explore Kadara" },
    greentech: { eyebrow:"TECHNICAL TRAINING & CERTIFICATION", tagline:"Train. Certify. Deploy.", purpose:"Competency-based technical training for the installation, operation and maintenance of integrated food-energy-water systems.", themes:["Photovoltaic fundamentals","PV installation & safety","Water pumping","Drip irrigation","Agrivoltaic systems","FEW systems installation"], action:"Explore GreenTech" },
  },
  ha: {
    pathways: { eyebrow:"KOYO DA SAUYI", tagline:"Daga Koyo Zuwa Dama", purpose:"Shirin koyo da sauyi mai haɗawa wanda ke samar da hanyoyin komawa ilimi, ƙwarewa da damar gaba.", themes:["Koyo na tushe","Karatu da lissafi","Ƙwarewar rayuwa","Koyon GrowMeal na aiki","Ilimin abinci","Tushen dijital"], action:"Duba Pathways" },
    kadara: { eyebrow:"ƘWAREWA, AIKI DA SANA’A", tagline:"Koya. Gina. Samu.", purpose:"Hanyar sana’a, samun aiki da kasuwanci da ke taimaka wa matasa su gina ƙwarewar aiki da hanyar rayuwa mai ɗorewa.", themes:["Noma","Samar da abinci","Sarrafa abinci","Marufi","Makamashi","Ruwa"], action:"Duba Kadara" },
    greentech: { eyebrow:"HORON FASAHA DA TAKARDAR SHAIDA", tagline:"Horo. Tabbatar. Aika Aiki.", purpose:"Horon fasaha bisa ƙwarewa don girkawa, sarrafawa da kula da haɗaɗɗun tsarin abinci-makamashi-ruwa.", themes:["Tushen photovoltaic","Girkawar PV da tsaro","Famfon ruwa","Ban-ruwa na drip","Tsarin agrivoltaic","Girkawar tsarin FEW"], action:"Duba GreenTech" },
  },
  ar: {
    pathways: { eyebrow:"التعلّم والانتقال", tagline:"من التعلّم إلى الفرص", purpose:"برنامج شامل للتعلّم والانتقال يوفر مسارات مرنة للعودة إلى التعليم والمهارات والفرص المستقبلية.", themes:["التعلّم التأسيسي","القراءة والحساب","مهارات الحياة","التعلّم العملي GrowMeal","الثقافة الغذائية","الأساسيات الرقمية"], action:"استكشاف Pathways" },
    kadara: { eyebrow:"المهارات والعمل وريادة الأعمال", tagline:"تعلّم. ابنِ. اكسب.", purpose:"مسار مهني للتوظيف وريادة الأعمال يساعد المراهقين الأكبر سناً والشباب على بناء مهارات عملية وسبل عيش مستدامة.", themes:["الزراعة","إنتاج الغذاء","تصنيع الغذاء","التعبئة","الطاقة","المياه"], action:"استكشاف Kadara" },
    greentech: { eyebrow:"التدريب التقني والشهادة", tagline:"تدرّب. احصل على شهادة. انطلق.", purpose:"تدريب تقني قائم على الكفاءة لتركيب وتشغيل وصيانة أنظمة الغذاء والطاقة والمياه المتكاملة.", themes:["أساسيات الخلايا الكهروضوئية","تركيب PV والسلامة","ضخ المياه","الري بالتنقيط","أنظمة الزراعة الكهروضوئية","تركيب أنظمة FEW"], action:"استكشاف GreenTech" },
  },
  yo: {
    pathways: { eyebrow:"Ẹ̀KỌ́ ÀTI ÌYÍPADÀ", tagline:"Láti Ẹ̀kọ́ Sí Àǹfààní", purpose:"Ètò ẹ̀kọ́ àti ìyípadà tó ṣí sí gbogbo ènìyàn, tó ń dá ọ̀nà rọrùn padà sí ẹ̀kọ́, ọgbọ́n àti àǹfààní ọjọ́ iwájú.", themes:["Ẹ̀kọ́ ìpilẹ̀","Kíkà àti ìṣirò","Ọgbọ́n ìgbésí-ayé","Ẹ̀kọ́ GrowMeal lórí iṣẹ́","Ìmọ̀ oúnjẹ","Ìpilẹ̀ dijítà"], action:"Ṣàwárí Pathways" },
    kadara: { eyebrow:"ỌGBỌ́N, IṢẸ́ ÀTI IṢÒWÒ", tagline:"Kọ́. Kọ́lé. Rí Owó.", purpose:"Ọ̀nà iṣẹ́, ìmúrasílẹ̀ iṣẹ́ àti iṣowo fún ọdọ tó ń kọ́ ọgbọ́n ọwọ́ àti ìgbésí-ayé tó lè dúró pẹ́.", themes:["Ogbin","Ṣíṣe oúnjẹ","Ìṣètò oúnjẹ","Àpò/ìdìpọ̀","Agbára","Omi"], action:"Ṣàwárí Kadara" },
    greentech: { eyebrow:"ÌDÁNILẸ́KỌ̀Ọ́ IMỌ̀-Ẹ̀RỌ ÀTI ÌJẸ́RÌÍ", tagline:"Kọ́. Gba Ìjẹ́rìí. Lọ Ṣiṣẹ́.", purpose:"Ìdánilẹ́kọ̀ọ́ imọ̀-ẹ̀rọ tó dá lórí agbára fún fifi, ṣiṣakoso àti títọ́jú eto oúnjẹ-agbára-omi tó darapọ̀.", themes:["Ìpilẹ̀ photovoltaic","Fifi PV àti ààbò","Fífa omi","Irigeson drip","Eto agrivoltaic","Fifi eto FEW"], action:"Ṣàwárí GreenTech" },
  },
  ig: {
    pathways: { eyebrow:"MMỤTA NA MGbanwe", tagline:"Site n’Ịmụ Ihe Ruo n’Ohere", purpose:"Mmemme mmụta na mgbanwe gụnyere mmadụ niile nke na-emepụta ụzọ dị mfe ịlaghachi n’agụmakwụkwọ, nkà na ohere n’ọdịnihu.", themes:["Mmụta ntọala","Ịgụ na mgbakọ","Nkà ndụ","Mmụta GrowMeal n’omume","Ọmụma nri","Ntọala dijitalụ"], action:"Lelee Pathways" },
    kadara: { eyebrow:"NKÀ, ỌRỤ NA AZỤMAHỊA", tagline:"Mụta. Wulite. Ritee Uru.", purpose:"Ụzọ ọrụ, nkwadebe ọrụ na azụmahịa na-enyere ndị ntorobịa aka iwulite nkà bara uru na ihe e ji ebi ndụ na-adịgide adịgide.", themes:["Ọrụ ugbo","Mmepụta nri","Nhazi nri","Nkwakọ ngwaahịa","Ike","Mmiri"], action:"Lelee Kadara" },
    greentech: { eyebrow:"ỌZỤZỤ TEKNỤZỤ NA ASAMBODO", tagline:"Zụlite. Nata Asambodo. Gaa Ọrụ.", purpose:"Ọzụzụ teknụzụ dabere n’ikike maka ịwụnye, ịrụ ọrụ na idobe sistemụ nri-ike-mmiri jikọtara ọnụ.", themes:["Ntọala photovoltaic","Ntinye PV na nchekwa","Pumping mmiri","Drip irrigation","Sistemụ agrivoltaic","Ntinye sistemụ FEW"], action:"Lelee GreenTech" },
  },
  fr: {
    pathways: { eyebrow:"APPRENTISSAGE ET TRANSITION", tagline:"De l’apprentissage aux opportunités", purpose:"Un programme inclusif d’apprentissage et de transition créant des voies flexibles vers l’éducation, les compétences et les possibilités futures.", themes:["Apprentissage fondamental","Littératie et numératie","Compétences de vie","Apprentissage pratique GrowMeal","Littératie alimentaire","Bases numériques"], action:"Explorer Pathways" },
    kadara: { eyebrow:"COMPÉTENCES, TRAVAIL ET ENTREPRISE", tagline:"Apprendre. Construire. Gagner.", purpose:"Un parcours professionnel, d’employabilité et d’entreprise aidant les adolescents plus âgés et les jeunes adultes à développer des compétences pratiques et des moyens de subsistance durables.", themes:["Agriculture","Production alimentaire","Transformation alimentaire","Emballage","Énergie","Eau"], action:"Explorer Kadara" },
    greentech: { eyebrow:"FORMATION TECHNIQUE ET CERTIFICATION", tagline:"Former. Certifier. Déployer.", purpose:"Une formation technique basée sur les compétences pour l’installation, l’exploitation et la maintenance de systèmes intégrés alimentation-énergie-eau.", themes:["Fondamentaux photovoltaïques","Installation PV et sécurité","Pompage de l’eau","Irrigation goutte-à-goutte","Systèmes agrivoltaïques","Installation de systèmes FEW"], action:"Explorer GreenTech" },
  },
} as const;

export const programPageCopy = {
  en: {
    pathways: { eyebrow:"A LIFEWS GREENSKILLS PROGRAM", tagline:"Learning • Skills • Opportunity • Transition", intro:"An inclusive learning and transition program for Almajiri learners, out-of-school children and girls, never-enrolled learners, school dropouts, over-age learners, underserved adolescents and transitioning youth.", primary:"Enter learner space", journey:["REACH","ASSESS","LEARN","GROW","BUILD","TRANSITION","THRIVE"], serves:"WHO PATHWAYS SERVES", servesTitle:"Flexible routes back into learning and opportunity", audiences:["Almajiri learners","Never-enrolled children","Out-of-school children","Out-of-school girls","School dropouts","Over-age learners","Underserved adolescents","Transitioning youth"], programsEyebrow:"THREE PATHWAYS PROGRAMS", programsTitle:"Age-responsive progression with practical learning.", programsBody:"Pathways Foundation, Explorer and Transition provide a staged route from foundational learning into education re-entry, Kadara, GreenTech, apprenticeship or other appropriate next destinations." },
    kadara: { eyebrow:"SKILLS, WORK & ENTERPRISE", tagline:"Learn. Build. Earn.", intro:"Kadara develops practical competence, employability, enterprise capability and sustainable livelihoods through three progressive programs. Agriculture and AgriEnterprise content are housed here rather than treated as a separate top-level GreenSkills arm.", primary:"Explore Kadara programs", journey:["DISCOVER","LEARN","PRACTICE","BUILD","EARN","LEAD"], programsEyebrow:"THREE KADARA PROGRAMS", programsTitle:"Progressive skills from starter level to enterprise.", programsBody:"Placement is based on age, diagnostic assessment, prior experience, safety requirements and demonstrated competence. Participants may enter at the appropriate level rather than repeating mastered content." },
    greentech: { eyebrow:"TECHNICAL TRAINING & CERTIFICATION", tagline:"Train. Certify. Deploy.", intro:"GreenTech develops competency-based technical capability for people who install, operate, maintain and monitor integrated food-energy-water systems through three progressive technician levels.", primary:"Explore GreenTech programs", journey:["ORIENT","TRAIN","PRACTICE","ASSESS","CERTIFY","DEPLOY"], programsEyebrow:"THREE GREENTECH PROGRAMS", programsTitle:"Progressive technical competence from foundations to advanced systems.", programsBody:"Placement considers age, education, diagnostic assessment, prerequisite competence and safety requirements. Technical certification requires demonstrated competence rather than attendance alone." },
  },
  ha: {
    pathways: { eyebrow:"SHIRIN LIFEWS GREENSKILLS", tagline:"Koyo • Ƙwarewa • Dama • Sauyi", intro:"Shirin koyo da sauyi mai haɗawa ga almajirai, yaran da ba sa makaranta da ’yan mata, waɗanda ba su taɓa shiga makaranta ba, waɗanda suka daina makaranta, waɗanda shekarunsu suka wuce aji, matasa marasa isassun dama da matasan da ke sauya mataki.", primary:"Shiga wurin ɗalibi", journey:["ISA","KIMANTA","KOYO","GIRMA","GINA","SAUYI","CI GABA"], serves:"WA PATHWAYS YAKE YI WA HIDIMA", servesTitle:"Hanyoyi masu sassauci zuwa koyo da dama", audiences:["Almajirai","Yaran da ba su taɓa shiga makaranta ba","Yaran da ba sa makaranta","’Yan matan da ba sa makaranta","Waɗanda suka daina makaranta","Masu shekaru fiye da aji","Matasan da ba su da isassun dama","Matasan da ke sauya mataki"], programsEyebrow:"SHIRYE-SHIRYEN PATHWAYS UKU", programsTitle:"Ci gaba bisa shekaru tare da koyo na aiki.", programsBody:"Pathways Foundation, Explorer da Transition suna samar da matakai daga koyo na tushe zuwa komawa ilimi, Kadara, GreenTech, koyon sana’a ko wata hanyar gaba da ta dace." },
    kadara: { eyebrow:"ƘWAREWA, AIKI DA SANA’A", tagline:"Koya. Gina. Samu.", intro:"Kadara tana gina ƙwarewar aiki, shirin samun aiki, ƙwarewar kasuwanci da rayuwa mai ɗorewa ta shirye-shirye uku masu ci gaba.", primary:"Duba shirye-shiryen Kadara", journey:["GANO","KOYO","AIKI","GINA","SAMU","JAGORANCI"], programsEyebrow:"SHIRYE-SHIRYEN KADARA UKU", programsTitle:"Ƙwarewa mai ci gaba daga matakin farawa zuwa sana’a.", programsBody:"Ana sanya mahalarta bisa shekaru, kimantawa, gogewar baya, bukatun tsaro da ƙwarewar da aka nuna. Za a iya shiga matakin da ya dace ba tare da maimaita abin da aka riga aka iya ba." },
    greentech: { eyebrow:"HORON FASAHA DA TAKARDAR SHAIDA", tagline:"Horo. Tabbatar. Aika Aiki.", intro:"GreenTech tana gina ƙwarewar fasaha ga masu girkawa, sarrafawa, kula da sa ido kan haɗaɗɗun tsarin abinci-makamashi-ruwa ta matakai uku na teknishan.", primary:"Duba shirye-shiryen GreenTech", journey:["SHIRI","HORO","AIKI","KIMANTA","TAKARDAR SHAIDA","AIKA AIKI"], programsEyebrow:"SHIRYE-SHIRYEN GREENTECH UKU", programsTitle:"Ƙwarewar fasaha mai ci gaba daga tushe zuwa tsarin ci gaba.", programsBody:"Sanya mahalarta yana la’akari da shekaru, ilimi, kimantawa, ƙwarewar da ake buƙata da tsaro. Takardar shaida tana buƙatar a nuna ƙwarewa, ba halarta kawai ba." },
  },
  ar: {
    pathways: { eyebrow:"برنامج LIFEWS GREENSKILLS", tagline:"التعلّم • المهارات • الفرص • الانتقال", intro:"برنامج شامل للتعلّم والانتقال لمتعلمي الألماجيري والأطفال والفتيات غير الملتحقين بالمدرسة ومن لم يسبق لهم الالتحاق والمتسربين والمتعلمين الأكبر سناً والمراهقين المحرومين والشباب في مراحل الانتقال.", primary:"دخول مساحة المتعلم", journey:["الوصول","التقييم","التعلّم","النمو","البناء","الانتقال","الازدهار"], serves:"من يخدمهم PATHWAYS", servesTitle:"مسارات مرنة للعودة إلى التعلّم والفرص", audiences:["متعلمو الألماجيري","أطفال لم يسبق لهم الالتحاق بالمدرسة","أطفال خارج المدرسة","فتيات خارج المدرسة","متسربون من المدرسة","متعلمون أكبر من السن المعتاد","مراهقون محرومون","شباب في مرحلة انتقال"], programsEyebrow:"ثلاثة برامج PATHWAYS", programsTitle:"تدرج مناسب للعمر مع تعلّم عملي.", programsBody:"تقدم Pathways Foundation وExplorer وTransition مساراً متدرجاً من التعلّم الأساسي إلى العودة للتعليم أو Kadara أو GreenTech أو التدريب المهني أو وجهات مناسبة أخرى." },
    kadara: { eyebrow:"المهارات والعمل وريادة الأعمال", tagline:"تعلّم. ابنِ. اكسب.", intro:"تطوّر Kadara الكفاءة العملية وقابلية التوظيف والقدرة على ريادة الأعمال وسبل العيش المستدامة عبر ثلاثة برامج متدرجة.", primary:"استكشاف برامج Kadara", journey:["اكتشف","تعلّم","تدرّب","ابنِ","اكسب","قُد"], programsEyebrow:"ثلاثة برامج KADARA", programsTitle:"مهارات متدرجة من مستوى البداية إلى ريادة الأعمال.", programsBody:"يعتمد تحديد المستوى على العمر والتقييم التشخيصي والخبرة السابقة ومتطلبات السلامة والكفاءة المثبتة. يمكن للمشارك الدخول في المستوى المناسب دون تكرار ما أتقنه." },
    greentech: { eyebrow:"التدريب التقني والشهادة", tagline:"تدرّب. احصل على شهادة. انطلق.", intro:"تطوّر GreenTech قدرات تقنية قائمة على الكفاءة للأشخاص الذين يركبون ويشغلون ويصونون ويراقبون أنظمة الغذاء والطاقة والمياه المتكاملة عبر ثلاثة مستويات فنية متدرجة.", primary:"استكشاف برامج GreenTech", journey:["توجيه","تدريب","ممارسة","تقييم","شهادة","نشر"], programsEyebrow:"ثلاثة برامج GREENTECH", programsTitle:"كفاءة تقنية متدرجة من الأساسيات إلى الأنظمة المتقدمة.", programsBody:"يراعي تحديد المستوى العمر والتعليم والتقييم التشخيصي والكفاءات السابقة ومتطلبات السلامة. تتطلب الشهادة التقنية كفاءة مثبتة لا الحضور فقط." },
  },
  yo: {
    pathways: { eyebrow:"ÈTÒ LIFEWS GREENSKILLS", tagline:"Ẹ̀kọ́ • Ọgbọ́n • Àǹfààní • Ìyípadà", intro:"Ètò ẹ̀kọ́ àti ìyípadà tó ṣí sí àwọn akẹ́kọ̀ọ́ Almajiri, ọmọ tí kò sí ní ilé-ẹ̀kọ́, ọmọbìnrin tí kò sí ní ilé-ẹ̀kọ́, ẹni tí kò tíì forúkọsílẹ̀ rí, ẹni tó jáwọ́ ní ilé-ẹ̀kọ́, ẹni tó ti pé jù fún kíláàsì rẹ̀, ọdọ aláìní àǹfààní àti ọdọ tó ń wọ ìpele tuntun.", primary:"Wọ àyè akẹ́kọ̀ọ́", journey:["DÉ Ọ̀DỌ̀","ṢE ÌDÁNWÒ","KỌ́","DÀGBÀ","KỌ́","YÍPADÀ","DÀGBÀ SÍI"], serves:"ÀWỌN TÍ PATHWAYS Ń ṢE FÚN", servesTitle:"Ọ̀nà rọrùn padà sí ẹ̀kọ́ àti àǹfààní", audiences:["Akẹ́kọ̀ọ́ Almajiri","Ọmọ tí kò tíì forúkọsílẹ̀","Ọmọ tí kò sí ní ilé-ẹ̀kọ́","Ọmọbìnrin tí kò sí ní ilé-ẹ̀kọ́","Ẹni tó jáwọ́ ní ilé-ẹ̀kọ́","Akẹ́kọ̀ọ́ tó ti pé jù fún kíláàsì","Ọdọ aláìní àǹfààní","Ọdọ tó ń wọ ìpele tuntun"], programsEyebrow:"ÈTÒ PATHWAYS MẸ́TA", programsTitle:"Ìlọsíwájú tó bá ọjọ́-ori mu pẹ̀lú ẹ̀kọ́ iṣẹ́ ọwọ́.", programsBody:"Pathways Foundation, Explorer àti Transition ń pèsè ọ̀nà ìpele láti ẹ̀kọ́ ìpilẹ̀ sí ìpadà ẹ̀kọ́, Kadara, GreenTech, apprenticeship tàbí ibi tó yẹ míì." },
    kadara: { eyebrow:"ỌGBỌ́N, IṢẸ́ ÀTI IṢÒWÒ", tagline:"Kọ́. Kọ́lé. Rí Owó.", intro:"Kadara ń kọ́ agbára iṣẹ́, ìmúrasílẹ̀ iṣẹ́, agbára iṣowo àti ìgbésí-ayé tó lè dúró pẹ́ nípasẹ̀ ètò mẹ́ta tó ń ga sí i.", primary:"Ṣàwárí àwọn ètò Kadara", journey:["ṢÀWÁRÍ","KỌ́","ṢE ADAṢE","KỌ́","RÍ OWÓ","DARÍ"], programsEyebrow:"ÈTÒ KADARA MẸ́TA", programsTitle:"Ọgbọ́n tó ń ga láti ìpele ìbẹ̀rẹ̀ sí iṣowo.", programsBody:"A ń yan ìpele gẹ́gẹ́ bí ọjọ́-ori, ìdánwò, ìrírí tẹ́lẹ̀, ààbò àti agbára tí a ti fi hàn. Olukopa lè wọ ìpele tó yẹ láì tún ohun tó ti mọ̀ ṣe." },
    greentech: { eyebrow:"ÌDÁNILẸ́KỌ̀Ọ́ IMỌ̀-Ẹ̀RỌ ÀTI ÌJẸ́RÌÍ", tagline:"Kọ́. Gba Ìjẹ́rìí. Lọ Ṣiṣẹ́.", intro:"GreenTech ń kọ́ agbára imọ̀-ẹ̀rọ fún àwọn tó ń fi, ṣiṣakoso, tọju àti ṣọ eto oúnjẹ-agbára-omi tó darapọ̀ nípasẹ̀ ìpele teknishan mẹ́ta.", primary:"Ṣàwárí àwọn ètò GreenTech", journey:["MÚRA","KỌ́","ṢE ADAṢE","ṢE ÌDÁNWÒ","GBA ÌJẸ́RÌÍ","LỌ ṢIṢẸ́"], programsEyebrow:"ÈTÒ GREENTECH MẸ́TA", programsTitle:"Agbára imọ̀-ẹ̀rọ tó ń ga láti ìpilẹ̀ sí eto tó jinlẹ̀.", programsBody:"Ìpele ń wo ọjọ́-ori, ẹ̀kọ́, ìdánwò, agbára àkọ́kọ́ àti ààbò. Ìjẹ́rìí imọ̀-ẹ̀rọ nilo agbára tí a fìdí múlẹ̀, kì í ṣe wíwà ní kíláàsì nikan." },
  },
  ig: {
    pathways: { eyebrow:"MMEMME LIFEWS GREENSKILLS", tagline:"Mmụta • Nkà • Ohere • Mgbanwe", intro:"Mmemme mmụta na mgbanwe gụnyere ndị Almajiri, ụmụaka na ụmụ agbọghọ na-anọghị n'ụlọ akwụkwọ, ndị na-amụbeghị akwụkwọ, ndị kwụsịrị akwụkwọ, ndị gafere afọ klaasị, ndị ntorobịa na-enweghị ohere zuru oke na ndị na-abanye n’ọkwa ọhụrụ.", primary:"Banye ebe onye mmụta", journey:["RUTE","NWALEE","MỤTA","TOO","WULITE","Gbanwee","TOO ỌMA"], serves:"NDỊ PATHWAYS NA-EJERE OZI", servesTitle:"Ụzọ dị mfe ịlaghachi na mmụta na ohere", audiences:["Ndị Almajiri","Ụmụaka na-amụbeghị akwụkwọ","Ụmụaka na-anọghị n'ụlọ akwụkwọ","Ụmụ agbọghọ na-anọghị n'ụlọ akwụkwọ","Ndị kwụsịrị akwụkwọ","Ndị gafere afọ klaasị","Ndị ntorobịa na-enweghị ohere zuru oke","Ndị ntorobịa na-agbanwe ọkwa"], programsEyebrow:"MMEMME PATHWAYS ATỌ", programsTitle:"Ọganihu dabara afọ na mmụta ọrụ aka.", programsBody:"Pathways Foundation, Explorer na Transition na-enye ụzọ n’usoro site na mmụta ntọala ruo n’ịlaghachi n’agụmakwụkwọ, Kadara, GreenTech, apprenticeship ma ọ bụ ụzọ ọzọ dabara adaba." },
    kadara: { eyebrow:"NKÀ, ỌRỤ NA AZỤMAHỊA", tagline:"Mụta. Wulite. Ritee Uru.", intro:"Kadara na-ewulite ikike ọrụ, nkwadebe ọrụ, ikike azụmahịa na ihe e ji ebi ndụ na-adịgide adịgide site na mmemme atọ na-arị elu.", primary:"Lelee mmemme Kadara", journey:["CHỌPỤTA","MỤTA","MEE OMUME","WULITE","RITEE URU","DUO"], programsEyebrow:"MMEMME KADARA ATỌ", programsTitle:"Nkà na-arị elu site na mbido ruo n’azụmahịa.", programsBody:"A na-ahọpụta ọkwa dabere na afọ, nyocha, ahụmịhe gara aga, nchekwa na ikike e gosipụtara. Onye sonyere nwere ike ịbanye n’ọkwa dabara ya na-enweghị imeghachi ihe ọ maala." },
    greentech: { eyebrow:"ỌZỤZỤ TEKNỤZỤ NA ASAMBODO", tagline:"Zụlite. Nata Asambodo. Gaa Ọrụ.", intro:"GreenTech na-ewulite ikike teknụzụ dabere n’ikike maka ndị na-etinye, na-arụ ọrụ, na-edobe ma na-enyocha sistemụ nri-ike-mmiri jikọtara ọnụ site na ọkwa teknishian atọ.", primary:"Lelee mmemme GreenTech", journey:["KWADO","ZỤLITE","MEE OMUME","NWALEE","NATA ASAMBODO","GAA ỌRỤ"], programsEyebrow:"MMEMME GREENTECH ATỌ", programsTitle:"Ikike teknụzụ na-arị elu site na ntọala ruo na sistemụ dị elu.", programsBody:"Nhọpụta ọkwa na-ele afọ, agụmakwụkwọ, nyocha, ikike mbido na nchekwa. Asambodo teknụzụ chọrọ ikike e gosipụtara, ọ bụghị nanị ịbịa klaasị." },
  },
  fr: {
    pathways: { eyebrow:"UN PROGRAMME LIFEWS GREENSKILLS", tagline:"Apprentissage • Compétences • Opportunités • Transition", intro:"Un programme inclusif d’apprentissage et de transition pour les apprenants Almajiri, les enfants et filles non scolarisés, les personnes jamais inscrites, les décrocheurs, les apprenants en retard d’âge, les adolescents défavorisés et les jeunes en transition.", primary:"Entrer dans l’espace apprenant", journey:["ATTEINDRE","ÉVALUER","APPRENDRE","GRANDIR","CONSTRUIRE","TRANSITION","PROSPÉRER"], serves:"PUBLICS SERVIS PAR PATHWAYS", servesTitle:"Des voies flexibles vers l’apprentissage et les opportunités", audiences:["Apprenants Almajiri","Enfants jamais scolarisés","Enfants non scolarisés","Filles non scolarisées","Décrocheurs scolaires","Apprenants en retard d’âge","Adolescents défavorisés","Jeunes en transition"], programsEyebrow:"TROIS PROGRAMMES PATHWAYS", programsTitle:"Une progression adaptée à l’âge avec apprentissage pratique.", programsBody:"Pathways Foundation, Explorer et Transition offrent un parcours progressif depuis les apprentissages fondamentaux vers le retour à l’éducation, Kadara, GreenTech, l’apprentissage professionnel ou d’autres destinations appropriées." },
    kadara: { eyebrow:"COMPÉTENCES, TRAVAIL ET ENTREPRISE", tagline:"Apprendre. Construire. Gagner.", intro:"Kadara développe les compétences pratiques, l’employabilité, la capacité entrepreneuriale et des moyens de subsistance durables grâce à trois programmes progressifs.", primary:"Explorer les programmes Kadara", journey:["DÉCOUVRIR","APPRENDRE","PRATIQUER","CONSTRUIRE","GAGNER","DIRIGER"], programsEyebrow:"TROIS PROGRAMMES KADARA", programsTitle:"Des compétences progressives du niveau débutant à l’entreprise.", programsBody:"Le placement tient compte de l’âge, du diagnostic, de l’expérience antérieure, des exigences de sécurité et des compétences démontrées. Les participants peuvent entrer au niveau approprié sans répéter les acquis maîtrisés." },
    greentech: { eyebrow:"FORMATION TECHNIQUE ET CERTIFICATION", tagline:"Former. Certifier. Déployer.", intro:"GreenTech développe des capacités techniques fondées sur les compétences pour les personnes qui installent, exploitent, entretiennent et surveillent des systèmes intégrés alimentation-énergie-eau, à travers trois niveaux progressifs de technicien.", primary:"Explorer les programmes GreenTech", journey:["ORIENTER","FORMER","PRATIQUER","ÉVALUER","CERTIFIER","DÉPLOYER"], programsEyebrow:"TROIS PROGRAMMES GREENTECH", programsTitle:"Une compétence technique progressive, des bases aux systèmes avancés.", programsBody:"Le placement tient compte de l’âge, de la formation, de l’évaluation diagnostique, des compétences préalables et des exigences de sécurité. La certification technique exige des compétences démontrées, et pas seulement la présence." },
  },
} as const;

const programMeta = {
  en: {},
  ha: { PF:["Pathways Foundation","kimanin shekaru 8–11"], PE:["Pathways Explorer","kimanin shekaru 12–14"], PT:["Pathways Transition","kimanin shekaru 15–17+"], KS:["Kadara Skills Starter","kimanin shekaru 15–17"], KW:["Kadara Workforce","galibi shekaru 18+"], KE:["Kadara Enterprise","18+ / rayuwa da sana’a"], GF:["GreenTech Foundation Technician","16+ horon fasaha mai kulawa"], GT2:["GreenTech FEW Systems Technician","horon teknishan na ci gaba"], GA:["GreenTech Advanced Systems","babban horon fasaha"] },
  ar: { PF:["Pathways Foundation","تقريباً 8–11 سنة"], PE:["Pathways Explorer","تقريباً 12–14 سنة"], PT:["Pathways Transition","تقريباً 15–17+ سنة"], KS:["Kadara Skills Starter","تقريباً 15–17 سنة"], KW:["Kadara Workforce","أساساً 18+"], KE:["Kadara Enterprise","18+ / سبل العيش وريادة الأعمال"], GF:["GreenTech Foundation Technician","16+ تدريب تقني تحت الإشراف"], GT2:["GreenTech FEW Systems Technician","تدريب فني متقدم"], GA:["GreenTech Advanced Systems","تدريب تقني متقدم"] },
  yo: { PF:["Pathways Foundation","ní àfihàn ọjọ́-ori 8–11"], PE:["Pathways Explorer","ní àfihàn ọjọ́-ori 12–14"], PT:["Pathways Transition","ní àfihàn ọjọ́-ori 15–17+"], KS:["Kadara Skills Starter","ní àfihàn ọjọ́-ori 15–17"], KW:["Kadara Workforce","púpọ̀ jù lọ 18+"], KE:["Kadara Enterprise","18+ / ìgbésí-ayé àti iṣowo"], GF:["GreenTech Foundation Technician","16+ ìdánilẹ́kọ̀ọ́ imọ̀-ẹ̀rọ lábẹ́ abojuto"], GT2:["GreenTech FEW Systems Technician","ìdánilẹ́kọ̀ọ́ teknishan tó ga"], GA:["GreenTech Advanced Systems","ìdánilẹ́kọ̀ọ́ imọ̀-ẹ̀rọ tó ga"] },
  ig: { PF:["Pathways Foundation","ihe dịka afọ 8–11"], PE:["Pathways Explorer","ihe dịka afọ 12–14"], PT:["Pathways Transition","ihe dịka afọ 15–17+"], KS:["Kadara Skills Starter","ihe dịka afọ 15–17"], KW:["Kadara Workforce","karịsịa 18+"], KE:["Kadara Enterprise","18+ / ihe e ji ebi ndụ na azụmahịa"], GF:["GreenTech Foundation Technician","16+ ọzụzụ teknụzụ n'okpuru nlekọta"], GT2:["GreenTech FEW Systems Technician","ọzụzụ teknishian dị elu"], GA:["GreenTech Advanced Systems","ọzụzụ teknụzụ dị elu"] },
  fr: { PF:["Pathways Foundation","environ 8–11 ans"], PE:["Pathways Explorer","environ 12–14 ans"], PT:["Pathways Transition","environ 15–17+ ans"], KS:["Kadara Skills Starter","environ 15–17 ans"], KW:["Kadara Workforce","principalement 18+"], KE:["Kadara Enterprise","18+ / moyens de subsistance et entreprise"], GF:["GreenTech Foundation Technician","16+ formation technique supervisée"], GT2:["GreenTech FEW Systems Technician","formation technique intermédiaire"], GA:["GreenTech Advanced Systems","formation technique avancée"] },
} as const;

const translatedPurpose = {
  en: "This program is part of LIFEWS GreenSkills and must remain aligned with LIFEWS work in food production, water systems, renewable energy, agrivoltaics, practical field learning, enterprise, monitoring, and community livelihoods.",
  ha: "Wannan shiri ɓangare ne na LIFEWS GreenSkills kuma yana haɗuwa da aikin LIFEWS a samar da abinci, tsarin ruwa, makamashi mai sabuntawa, agrivoltaics, koyon aiki a fili, sana’a, sa ido da rayuwar al’umma.",
  ar: "هذا البرنامج جزء من LIFEWS GreenSkills ويظل متوافقاً مع عمل LIFEWS في إنتاج الغذاء وأنظمة المياه والطاقة المتجددة والزراعة الكهروضوئية والتعلّم الميداني العملي وريادة الأعمال والمراقبة وسبل عيش المجتمعات.",
  yo: "Ètò yìí jẹ́ apá LIFEWS GreenSkills, ó sì ń bá iṣẹ́ LIFEWS mu nínú ṣíṣe oúnjẹ, eto omi, agbára tuntun, agrivoltaics, ẹ̀kọ́ pápá lórí iṣẹ́, iṣowo, ìmójútó àti ìgbésí-ayé àwùjọ.",
  ig: "Mmemme a bụ akụkụ LIFEWS GreenSkills ma na-agbaso ọrụ LIFEWS n’ime mmepụta nri, sistemụ mmiri, ike ọhụrụ, agrivoltaics, mmụta ubi n’omume, azụmahịa, nlekota na ihe e ji ebi ndụ n’obodo.",
  fr: "Ce programme fait partie de LIFEWS GreenSkills et reste aligné sur les activités LIFEWS en production alimentaire, systèmes d’eau, énergies renouvelables, agrivoltaïsme, apprentissage pratique sur le terrain, entreprise, suivi et moyens de subsistance communautaires.",
} as const;

export function getCommonCopy(language: AppLanguage) { return common[language]; }
export function getGreenSkillsHomeCopy(language: AppLanguage) { return greenSkillsHomeCopy[language]; }
export function getProgramPageCopy(language: AppLanguage, arm: ProgramArm) { return programPageCopy[language][arm]; }

export function localizeGreenSkillsPrograms(programs: GreenSkillsProgram[], language: AppLanguage): GreenSkillsProgram[] {
  const cards = programCards[language];
  return programs.map((program) => ({ ...program, ...cards[program.id], themes: [...cards[program.id].themes] }));
}

export function localizeCurriculumPrograms(programs: CurriculumProgram[], language: AppLanguage): CurriculumProgram[] {
  if (language === "en") return programs;
  const meta = programMeta[language] as Record<string, readonly [string,string]>;
  return programs.map((program) => {
    const item = meta[program.code];
    return { ...program, title: item?.[0] ?? program.title, age: item?.[1] ?? program.age, purpose: translatedPurpose[language] };
  });
}

export function localizedCompetencyDomains(language: AppLanguage) {
  return ["K","P","D","S","E","L"].map((code,index) => [code, common[language].domains[index]] as const);
}
