import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "../pathways-foundation/pf-01";

type PT04Module = Omit<PF01Module,"code"> & { code:"PT-04" };

const en: PT04Module = {
  code:"PT-04", title:"Applied Digital Skills", level:"Pathways Transition",
  age:"Approximately ages 15–17+; activities should follow baseline digital access, literacy and safeguarding requirements.",
  duration:"6 guided lessons plus digital portfolio practical and assessment", fieldworkHours:5,
  bigQuestion:"How can I use digital tools safely and professionally to record work, communicate, organize evidence and prepare for my next opportunity?",
  whyItMatters:"Digital competence is now part of learning, technical work, agriculture, enterprise and employment. Learners need more than device familiarity: they must create reliable records, communicate professionally, protect information, organize evidence and critically check AI-supported outputs.",
  outcomes:["Create and organize files using clear names and folders.","Enter and format simple work records in documents or spreadsheets.","Communicate professionally through supervised digital channels.","Capture useful photo, measurement and task evidence.","Apply privacy, password, consent and misinformation safeguards.","Use AI tools for bounded support while checking accuracy and authorship.","Build a simple digital profile or project evidence folder."],
  vocabulary:["file","folder","format","spreadsheet","record","evidence","metadata","privacy","password","consent","backup","cloud","offline","attachment","subject line","AI","verification","digital footprint"],
  materials:["supervised phone, tablet or computer","sample files and photographs","offline document/spreadsheet app where available","practice email/message templates","USB or local storage where appropriate","project evidence checklist"],
  safety:["Never publish a learner's personal information, exact location or identifiable images without appropriate consent.","Use training accounts or supervised communication channels.","Passwords must not be shared in class demonstrations.","Do not upload confidential documents to public AI services.","Learners must verify AI-generated claims and retain responsibility for submitted work."],
  lessons:[
    {id:"PT-04-L1",title:"Organize Digital Work",objective:"Create a reliable folder and file-naming system for learning and work evidence.",teaching:["Digital work becomes usable when files can be found quickly.","Good filenames identify project, date or version without exposing unnecessary personal data.","A simple folder hierarchy prevents evidence from becoming scattered."],activity:"Sort a mixed set of sample files into a logical project structure.",diy:"Create a GreenSkills digital folder with subfolders for PROFILE, PROJECTS, FIELDWORKS, ASSESSMENTS and CERTIFICATES and apply a consistent naming rule.",aiLayer:"AI Layer 1 — Classification: compare your folder structure with an AI suggestion and explain which organization better fits the actual evidence.",enterprise:"Reliable file organization reduces lost records and improves professional handover.",quiz:[{question:"What makes a useful filename?",options:["Clear identity and version/date context","Random characters only","A password","No extension ever"],answer:0},{question:"Why use folders?",options:["To organize related evidence","To make files larger","To replace backups","To hide mistakes"],answer:0},{question:"Should filenames expose unnecessary personal data?",options:["No","Always","Only online","Only for photos"],answer:0}]},
    {id:"PT-04-L2",title:"Documents and Digital Records",objective:"Create accurate, readable records using basic document and spreadsheet tools.",teaching:["A work record should state what happened, when, where appropriate, and what evidence supports it.","Tables and spreadsheets help structure repeated observations.","Formatting should improve readability rather than decorate the record."],activity:"Turn handwritten field observations into a clean digital table.",diy:"Create a one-page digital work log with date, task, quantity or measurement, result, issue and next action.",aiLayer:"AI Layer 2 — Formatting support: use AI or a template to suggest organization, then verify every fact against the original notes.",enterprise:"Accurate records support inventory, quality, costing and accountability.",quiz:[{question:"What should a digital work record prioritize?",options:["Accuracy and readability","Decoration","Long paragraphs only","Unverified estimates"],answer:0},{question:"What is a spreadsheet useful for?",options:["Structured repeated data","Replacing safety rules","Storing passwords publicly","Avoiding measurements"],answer:0},{question:"What should happen after AI reformats notes?",options:["Verify facts against source notes","Submit without reading","Delete originals immediately","Assume all values are correct"],answer:0}]},
    {id:"PT-04-L3",title:"Professional Digital Communication",objective:"Write concise, respectful digital messages with appropriate context and attachments.",teaching:["Professional messages identify purpose, necessary context and requested action.","Subject lines and filenames help recipients understand attachments.","Tone, timing and channel should fit the relationship and task."],activity:"Improve several unclear or inappropriate workplace messages.",diy:"Prepare a supervised message submitting a project record with a clear subject, greeting, two-sentence summary, attachment reference and professional closing.",aiLayer:"AI Layer 3 — Drafting assistance: compare an AI-assisted draft with your own and remove inaccurate, excessive or inappropriate wording.",enterprise:"Clear communication improves customer, supplier and supervisor relationships.",quiz:[{question:"What belongs in a professional message?",options:["Clear purpose and requested action","Unrelated personal details","Passwords","Unverified accusations"],answer:0},{question:"Why name attachments clearly?",options:["So recipients can identify them","To increase file size","To avoid opening them","To hide versions"],answer:0},{question:"Who is responsible for an AI-assisted message you send?",options:["You","The AI only","Nobody","The device"],answer:0}]},
    {id:"PT-04-L4",title:"Capture Evidence That Proves Work",objective:"Collect photographs, measurements and notes that demonstrate a completed task without compromising privacy.",teaching:["Evidence should prove a competency rather than simply show attendance.","Useful evidence can include before/after views, measurements, checklists and supervisor verification.","Images should avoid unnecessary faces, private information and unsafe staging."],activity:"Judge sample evidence as strong, weak or unsafe and explain why.",diy:"Create a three-item evidence set for one practical task: labelled photo or diagram, measurement/record, and short reflection.",aiLayer:"AI Layer 4 — Evidence review: ask an AI tool to identify missing context, then decide which suggestions are valid using the assessment criteria.",enterprise:"Evidence supports quality assurance, portfolios and credible service records.",quiz:[{question:"What should competency evidence demonstrate?",options:["What the learner can do","Attendance only","Popularity","Device ownership"],answer:0},{question:"Which strengthens a practical photo?",options:["A related measurement or checklist","A filter","Unrelated text","Hidden context"],answer:0},{question:"Should private information appear unnecessarily in evidence?",options:["No","Yes","Always for proof","Only in filenames"],answer:0}]},
    {id:"PT-04-L5",title:"Privacy, Security and Digital Judgment",objective:"Apply basic privacy, account-security, consent and misinformation checks.",teaching:["Strong account practices include unique passwords and appropriate recovery controls.","Consent matters before sharing identifiable information or images.","Online information and AI outputs can be incomplete, outdated or false; source checking remains necessary."],activity:"Complete a digital-risk scenario sort covering passwords, suspicious links, image consent and questionable claims.",diy:"Build a Digital Safety Checklist: ACCESS → PRIVACY → CONSENT → SOURCE → VERIFY → SHARE.",aiLayer:"AI Layer 5 — Critical evaluation: test one factual AI response against a trusted source or supplied reference and document any difference.",enterprise:"Digital security protects records, reputation and customer information.",quiz:[{question:"Should the same weak password be reused everywhere?",options:["No","Yes","Only for work","Only for school"],answer:0},{question:"What is required before sharing identifiable images where policy requires it?",options:["Appropriate consent","A filter","A caption only","Nothing"],answer:0},{question:"What should you do with an important AI-generated claim?",options:["Verify it","Assume it is true","Forward it immediately","Delete all sources"],answer:0}]},
    {id:"PT-04-L6",title:"Build Your Digital Transition Profile",objective:"Assemble organized, truthful digital evidence for education, training or work transition.",teaching:["A transition profile can summarize strengths, competencies, projects and verified evidence.","Claims should be specific and supported by evidence.","Different opportunities require different emphasis, but facts must remain truthful."],activity:"Review a sample profile and distinguish evidence-backed claims from vague claims.",diy:"Build a Digital Transition Folder containing a one-page profile/CV, two project evidence items, one assessment record and a next-step statement.",aiLayer:"Integration — profile review: use AI for spelling, structure or gap checking, but independently verify every claim and remove invented experience.",enterprise:"A credible digital profile helps communicate capability to training providers, employers and collaborators.",quiz:[{question:"What makes a strong profile claim?",options:["Specific evidence","Exaggeration","Unverifiable titles","Copied experience"],answer:0},{question:"Can AI invent experience for your CV?",options:["No","Yes if it sounds good","Only for technical work","Only without dates"],answer:0},{question:"What should a transition folder contain?",options:["Organized evidence supporting capability","Passwords","Unrelated downloads","Private data from others"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Which file structure best supports a Skills Passport?",options:["Clearly named folders by evidence type","One unnamed folder","Random downloads","Files stored only in chat"],answer:0},{question:"What is the main purpose of a digital work log?",options:["Record tasks and evidence accurately","Decorate a profile","Replace practical work","Store passwords"],answer:0},{question:"What makes a professional digital message effective?",options:["Clear purpose, context and action","Maximum length","Informal slang in every case","No subject"],answer:0},{question:"What is stronger evidence of a practical task?",options:["Photo/diagram plus measurement and verification","A selfie only","Attendance only","An AI-generated picture"],answer:0},{question:"What should you do before sharing identifiable information?",options:["Check consent and privacy requirements","Share first","Remove the filename only","Ask an AI"],answer:0},{question:"How should AI support assessed work?",options:["As checked assistance, not fabricated authorship","By inventing experience","By replacing evidence","Without disclosure where required"],answer:0},{question:"Why keep backups?",options:["To reduce risk of losing important records","To create duplicate mistakes intentionally","To avoid organization","To share passwords"],answer:0},{question:"Which profile statement is best?",options:["A specific competency supported by evidence","I can do everything","An invented certificate","An unsupported job title"],answer:0}],theory:["Explain a practical folder and file-naming system for GreenSkills evidence.","Describe the fields you would include in a digital work log and why.","Write the structure of a professional message used to submit a project record.","Explain four privacy or security checks you should make before sharing digital evidence.","Describe how AI can support a digital profile without replacing your responsibility for accuracy."],practical:"Create and present a Digital Transition Folder containing a one-page profile/CV, structured work log, two pieces of practical evidence, one assessment record, a professional submission message and a digital-safety checklist. Demonstrate file organization and explain how each claim is verified."},
  evidence:["GreenSkills folder structure","Digital work log","Professional submission message","Three-item practical evidence set","Digital Safety Checklist","Digital Transition Folder/profile","Facilitator digital-competency assessment"],
  passport:["K: understands digital records, communication, privacy and verification","P: creates organized digital evidence and professional records","D: uses documents, spreadsheets and AI-supported tools critically","S: protects privacy, consent and account security","E: uses digital records and communication in work/enterprise contexts","L: takes responsibility for accuracy and professional digital conduct"],
  trainerNotes:["Provide offline equivalents where connectivity is limited.","Do not penalize learners for lack of personal device ownership.","Use training accounts and fictional data for demonstrations involving privacy.","Assess information quality and organization, not software brand familiarity.","Ensure girls and boys rotate equally through device and documentation roles."],
  remediation:"Use one supervised device and a prepared folder template. Practice one task at a time: rename, save, find, enter a record, attach a file, then verify it.",
  extension:"Create a simple spreadsheet evidence index with filters for competency code, date, evidence type and verification status, then use it to audit the learner's transition portfolio.", imagePrompts:[]
};
export const pt04ByLanguage: Partial<Record<AppLanguage,PT04Module>> = { en };
export function getPT04(language:AppLanguage):PT04Module { return pt04ByLanguage[language] ?? en; }
