import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "../pathways-foundation/pf-01";

type PT01Module = Omit<PF01Module,"code"> & { code:"PT-01" };

const en: PT01Module = {
  code:"PT-01",
  title:"Know Your Strengths",
  level:"Pathways Transition",
  age:"Approximately ages 15–17+; placement should reflect demonstrated readiness rather than age alone.",
  duration:"6 guided lessons plus personal inventory, evidence review and transition-planning assessment",
  fieldworkHours:4,
  bigQuestion:"What am I already able to do, where do I need to grow, and how can I use evidence to choose my next learning or work pathway?",
  whyItMatters:"Transition decisions are stronger when learners can describe their abilities with evidence rather than guesses. This module helps learners identify strengths, interests, habits, practical competencies and gaps, then connect them to realistic education, Kadara, GreenTech, apprenticeship and community opportunities.",
  outcomes:[
    "Distinguish interests, strengths, values, habits and demonstrated competencies.",
    "Use examples and evidence to describe current abilities accurately.",
    "Identify at least three competency gaps relevant to a preferred pathway.",
    "Compare personal preferences with the requirements of different learning and work routes.",
    "Create a realistic short-term development goal with actions and evidence measures.",
    "Use digital or AI-supported reflection tools critically without allowing them to define the learner's identity or future.",
    "Present a personal strengths-and-next-step profile respectfully and confidently."
  ],
  vocabulary:["strength","interest","value","competency","evidence","habit","skill gap","goal","pathway","feedback","reflection","portfolio","readiness","transferable skill","improvement"],
  materials:["personal inventory worksheet","skills cards","competency-domain cards","notebook","portfolio evidence or prior work samples","goal-planning sheet","optional supervised digital device","career/pathway information sheets"],
  safety:[
    "Personal reflection must not require disclosure of trauma, family hardship or private information.",
    "Do not rank learners publicly or compare them in ways that shame previous schooling or skill levels.",
    "Feedback must focus on observable behaviour and evidence rather than personality labels.",
    "Digital tools must not collect unnecessary sensitive personal data.",
    "AI-generated personality, career or aptitude claims must be treated as suggestions only and checked against real evidence and trusted guidance."
  ],
  lessons:[
    {id:"PT-01-L1",title:"Strength Is More Than Talent",objective:"Distinguish strengths, interests, values, habits and competencies.",teaching:["An interest is something a person enjoys or wants to explore.","A strength is an area in which a learner performs relatively well or learns effectively.","A competency is demonstrated knowledge or skill that can be observed and evidenced.","Reliable habits such as punctuality, preparation and follow-through can strengthen performance."],activity:"Sort example statements into interest, strength, value, habit or competency and explain the reasoning.",diy:"Complete a five-column Self-Profile Wheel with one evidenced example in each category.",aiLayer:"AI Layer 1 — Classification: compare learner classifications with an AI-generated grouping and discuss where context changes the answer.",enterprise:"Employers, teams and enterprise partners need people who can describe what they can reliably contribute, not only what they like.",quiz:[{question:"Which is a competency?",options:["Installing a drip line correctly under supervision","Liking technology","Valuing honesty","Wanting to travel"],answer:0},{question:"Which is a habit?",options:["Arriving prepared and on time","Enjoying gardening","Knowing a formula","Choosing a career"],answer:0},{question:"Why separate interests from competencies?",options:["Because enjoying something does not automatically prove skill","Because interests never matter","Because competencies cannot improve","Because skills are fixed"],answer:0}]},
    {id:"PT-01-L2",title:"Evidence of What I Can Do",objective:"Identify credible evidence that supports claims about skills and strengths.",teaching:["Evidence can include completed tasks, observations, photos, records, assessment results, supervisor feedback or verified portfolio items.","A strong claim names what was done, under what conditions and to what standard.","Self-confidence is useful, but evidence makes a profile more credible."],activity:"Review sample claims such as 'I am good at teamwork' and rewrite them using observable evidence.",diy:"Create a Strength-Evidence Table with at least six claims and one evidence source for each.",aiLayer:"AI Layer 2 — Evidence quality: ask AI to suggest evidence for a skill claim, then rank the suggestions as strong, weak or unverifiable.",enterprise:"Evidence-based profiles support employability, contracting, apprenticeship selection and responsible customer trust.",quiz:[{question:"Which is strongest evidence?",options:["A verified completed task and supervisor feedback","A guess","A slogan","A promise"],answer:0},{question:"What should a skill claim include?",options:["Observable evidence","Only confidence","Only a title","Only age"],answer:0},{question:"Why keep portfolio evidence?",options:["To demonstrate competence over time","To replace learning","To guarantee employment","To hide gaps"],answer:0}]},
    {id:"PT-01-L3",title:"Feedback Without Losing Confidence",objective:"Use constructive feedback to identify patterns, strengths and growth areas.",teaching:["Useful feedback is specific, timely and connected to a task or behaviour.","A growth area is not a permanent weakness; it identifies what to practise next.","Learners can compare self-assessment with feedback and investigate differences."],activity:"Practice a feedback protocol: OBSERVATION → IMPACT → NEXT STEP using neutral scenarios.",diy:"Collect two pieces of structured feedback from approved peers, trainers or supervisors and summarize one repeated strength and one growth area.",aiLayer:"AI Layer 3 — Feedback synthesis: compare a learner's own summary with an AI-generated summary of anonymized sample feedback and check for exaggeration or missing context.",enterprise:"People who respond professionally to feedback can improve quality, service and teamwork faster.",quiz:[{question:"Useful feedback should be…",options:["specific and connected to behaviour","insulting","vague only","publicly embarrassing"],answer:0},{question:"A growth area means…",options:["something to improve through practice","permanent failure","no future opportunity","a reason to stop"],answer:0},{question:"What should you do when feedback differs from self-assessment?",options:["Examine the evidence and context","Ignore all feedback","Assume you are wrong","Delete your records"],answer:0}]},
    {id:"PT-01-L4",title:"My Competency Gaps",objective:"Compare current evidence with the requirements of a preferred next pathway.",teaching:["A competency gap is the difference between current demonstrated ability and the standard required for a target role or course.","Gaps can be in knowledge, practical skill, digital ability, safety, enterprise or leadership.","Prioritizing gaps helps learners focus limited time and resources."],activity:"Use a sample pathway requirement sheet and mark READY, DEVELOPING or NOT YET EVIDENCED for each competency.",diy:"Complete a Gap Analysis for one preferred pathway and identify the top three development priorities.",aiLayer:"AI Layer 4 — Requirement comparison: use AI to summarize a pathway description, then verify every requirement against the official or facilitator-provided source.",enterprise:"Training plans and workforce development are more effective when they target specific competency gaps.",quiz:[{question:"What is a competency gap?",options:["Difference between current ability and required standard","A personal insult","A fixed trait","A salary"],answer:0},{question:"Why prioritize gaps?",options:["To focus development effort","To hide strengths","To avoid practice","To guarantee success"],answer:0},{question:"Which domain can contain a gap?",options:["Safety","Only age","Only hobbies","Only income"],answer:0}]},
    {id:"PT-01-L5",title:"Choose a Direction, Not a Destiny",objective:"Compare several realistic pathways using interests, evidence, constraints and opportunities.",teaching:["A next step is a decision for the current stage, not an irreversible life sentence.","Pathways can include further education, Kadara, GreenTech, apprenticeship, supervised work experience or other verified routes.","Good decisions consider fit, prerequisites, time, cost, safety, accessibility and future progression."],activity:"Compare three pathway scenarios using a decision matrix with the same criteria.",diy:"Create a Personal Pathway Decision Matrix for at least three realistic next-step options.",aiLayer:"AI Layer 5 — Decision support: ask AI for pros and cons of options, then identify assumptions, missing local information and any unsupported claims.",enterprise:"Choosing training that matches real opportunities can reduce wasted time and improve readiness for future livelihoods.",quiz:[{question:"Is a next-step choice permanent?",options:["No","Always","Only for technical training","Only if written down"],answer:0},{question:"Which is a useful comparison criterion?",options:["Prerequisites and progression","Logo colour","Rumours","Popularity alone"],answer:0},{question:"What should AI advice be checked against?",options:["Verified local information and personal evidence","Nothing","Social media only","A random guess"],answer:0}]},
    {id:"PT-01-L6",title:"My Strengths and Next-Step Profile",objective:"Integrate strengths, evidence, gaps and pathway choice into a concise transition profile.",teaching:["A transition profile should state what the learner can do, what evidence supports it, what needs development and what comes next.","Goals should be specific enough to guide action and evidence collection.","The profile should be updated as new evidence is earned."],activity:"Learners present a two-minute strengths-and-next-step profile and receive one evidence-based question from peers.",diy:"Complete a Transition Profile: STRENGTHS → EVIDENCE → GAPS → TARGET PATHWAY → 30-DAY ACTIONS → SUPPORT → EVIDENCE TO COLLECT.",aiLayer:"Integration — reflective verification: compare an AI-drafted profile with the learner's own evidence and remove claims that cannot be supported.",enterprise:"A concise evidence-based profile supports interviews, apprenticeship discussions, mentorship and future enterprise-team selection.",quiz:[{question:"What should a transition profile include?",options:["strengths, evidence, gaps and next actions","only strengths","only weaknesses","guaranteed outcomes"],answer:0},{question:"Should the profile change over time?",options:["Yes, as new evidence is earned","Never","Only after employment","Only if AI changes it"],answer:0},{question:"What makes a goal useful?",options:["Clear actions and evidence","Vague hopes only","No time frame","No next step"],answer:0}]}
  ],
  finalAssessment:{
    mcq:[
      {question:"What best defines a competency?",options:["Demonstrated knowledge or skill supported by evidence","Something you enjoy","A personality label","A future wish"],answer:0},
      {question:"Which is strongest evidence of teamwork?",options:["Verified contribution to a completed team task","Saying 'I work well with people'","A social media bio","A guess"],answer:0},
      {question:"What is a competency gap?",options:["A difference between current evidence and required standard","A permanent weakness","A personal failure","A job title"],answer:0},
      {question:"Which feedback is most useful?",options:["Specific feedback linked to behaviour and next steps","An insult","A vague compliment only","Public comparison"],answer:0},
      {question:"Why compare several pathways?",options:["To make a more informed next-step decision","To guarantee income","To avoid learning","To choose the most popular option"],answer:0},
      {question:"What should happen if AI labels a learner's personality or ideal career?",options:["Treat it cautiously and verify against real evidence and guidance","Accept it as final","Publish it publicly","Use it as a diagnosis"],answer:0},
      {question:"Which statement is strongest?",options:["I completed three supervised irrigation checks and my trainer verified the records","I am excellent at everything","I never need feedback","I will definitely succeed"],answer:0},
      {question:"What should a transition goal include?",options:["Specific actions and evidence to collect","Only a dream","No time frame","No support plan"],answer:0}
    ],
    theory:[
      "Explain the difference between an interest, a strength and a demonstrated competency, using one example of each.",
      "Describe three forms of credible evidence you could use to support a practical-skill claim.",
      "Explain how constructive feedback can help identify a development priority without reducing confidence.",
      "Choose one target pathway and describe three competency gaps you would need to close before entry or progression.",
      "Explain one useful and one risky way AI could be used during career or pathway reflection."
    ],
    practical:"Present a completed Strengths-and-Next-Step Profile containing at least five evidenced strengths or competencies, three priority gaps, comparison of three pathway options, one selected next step, a 30-day action plan and the evidence that will show progress. Respond to assessor questions using portfolio evidence."
  },
  evidence:["Self-Profile Wheel","Strength-Evidence Table","Structured feedback summary","Competency Gap Analysis","Personal Pathway Decision Matrix","30-day development goal","Final Strengths-and-Next-Step Profile","Facilitator presentation checklist"],
  passport:["K: distinguishes strengths, interests, values, habits and competencies","P: completes evidence-based self-assessment and pathway comparison tools","D: uses digital and AI support critically while protecting personal information","S: follows respectful feedback and privacy practices","E: connects competencies to employability and future enterprise-team contribution","L: reflects, receives feedback, sets goals and communicates a realistic next step"],
  trainerNotes:["Use strengths-based facilitation without inflating unsupported claims.","Offer oral, visual and written methods for self-assessment.","Do not use personality tests as gatekeeping instruments.","Pathway information should be current and verified where possible.","Ensure girls and boys receive equal exposure to technical, leadership and enterprise options.","Where learners have limited prior schooling, recognize practical and community-based evidence as valid when it can be demonstrated."],
  remediation:"Reduce the inventory to three prompts: What can I do? What evidence shows it? What do I want to improve next? Use facilitator questioning and one real work sample to rebuild confidence and evidence language.",
  extension:"Learner conducts one informational interview with an approved worker, technician, trainer or entrepreneur, compares the pathway requirements with the original gap analysis, and revises the 30-day plan.",
  imagePrompts:[]
};

export const pt01ByLanguage: Partial<Record<AppLanguage,PT01Module>> = { en };
export function getPT01(language:AppLanguage):PT01Module { return pt01ByLanguage[language] ?? en; }
