import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "../pathways-foundation/pf-01";
type PT05Module = Omit<PF01Module,"code"> & { code:"PT-05" };
const en: PT05Module = {
 code:"PT-05",title:"Food and Agriculture Skills",level:"Pathways Transition",age:"Approximately ages 15–17+; practical work must remain supervised and appropriate to learner readiness.",duration:"6 guided lessons plus supervised production project and assessment",fieldworkHours:8,
 bigQuestion:"How can we plan, carry out, monitor and improve a small food-production task using safe and evidence-based practices?",
 whyItMatters:"Transition learners need to move from knowing that crops grow to managing a defined production task. This module develops planning, soil and planting practice, crop care, observation, harvest quality and production records while connecting agriculture to food systems, resource use and livelihood pathways.",
 outcomes:["Prepare a simple crop-production plan from objective to output.","Assess a production site and prepare soil or growing media appropriately.","Apply spacing, planting and crop-care practices accurately.","Monitor plant condition, water, weeds and basic production risks.","Harvest and handle produce using hygiene and quality principles.","Maintain production records and calculate simple output indicators.","Use digital or AI support to interpret records without replacing field observation."],
 vocabulary:["production plan","site","soil","growing medium","spacing","planting depth","transplant","mulch","weed","pest","symptom","crop care","harvest maturity","quality","yield","loss","record","input","output"],
 materials:["safe hand tools","measuring tape","stakes/string","seeds or seedlings","prepared bed or containers","watering equipment","mulch","labels","gloves where appropriate","production record sheet","harvest container","scale where available"],
 safety:["Trainer must inspect tools and work area before practical sessions.","No unsupervised pesticide application or hazardous agrochemical handling.","Use safe lifting, hydration, sun protection and handwashing practices.","Food intended for consumption must be handled in accordance with local hygiene requirements.","Field observations must not encourage learners to touch unknown pests, animals or contaminated materials."],
 lessons:[
 {id:"PT-05-L1",title:"Plan the Production Task",objective:"Translate a crop goal into a practical sequence of inputs, tasks, timing and evidence.",teaching:["A production plan identifies crop, purpose, site, quantity, inputs, task sequence and expected output.","Timing should reflect crop needs and local conditions.","Plans should identify assumptions and constraints before work begins."],activity:"Compare two crop plans and identify missing inputs, unrealistic timing and unclear outputs.",diy:"Prepare a one-page production plan for one locally appropriate crop or container crop.",aiLayer:"AI Layer 1 — Planning comparison: compare an AI-generated task sequence with local trainer knowledge and identify assumptions that require verification.",enterprise:"Planning supports reliable output, input control and scheduling.",quiz:[{question:"What should a production plan identify?",options:["Crop, inputs, tasks, timing and output","Only crop name","Only price","Only weather"],answer:0},{question:"Why state assumptions?",options:["So they can be checked","To hide uncertainty","To guarantee yield","To avoid records"],answer:0},{question:"Should local crop timing be verified?",options:["Yes","No","Only by AI","Only after harvest"],answer:0}]},
 {id:"PT-05-L2",title:"Prepare the Site and Growing Medium",objective:"Assess and prepare a safe growing area for the planned crop.",teaching:["Site conditions include light, drainage, access, water and physical constraints.","Soil or growing media should support roots, air and water movement.","Compost and mulch can support soil management when used appropriately."],activity:"Conduct a supervised site walk and complete a suitability checklist.",diy:"Measure and prepare a small bed or container system, documenting dimensions and preparation steps.",aiLayer:"AI Layer 2 — Site checklist support: compare observed conditions with a digital checklist; field evidence overrides generic assumptions.",enterprise:"Good site preparation reduces avoidable rework and crop loss.",quiz:[{question:"Which is a site factor?",options:["Drainage","Font size","Password","Invoice number"],answer:0},{question:"Why measure a bed?",options:["To plan spacing and inputs","To replace planting","To guarantee rainfall","To avoid records"],answer:0},{question:"What should guide site decisions?",options:["Observed local conditions","Generic AI text alone","Guesswork","Advertising"],answer:0}]},
 {id:"PT-05-L3",title:"Plant With Accuracy",objective:"Apply appropriate spacing, depth and establishment practices.",teaching:["Spacing affects access to light, water, nutrients and airflow.","Planting depth and transplant handling vary by crop.","Labels and counts help track establishment."],activity:"Mark planting positions using measured spacing and check alignment before planting.",diy:"Plant or transplant a supervised production unit and record crop, date, spacing, count and establishment condition.",aiLayer:"AI Layer 3 — Measurement check: use a calculator or AI to verify plant-count estimates from spacing, then compare with the actual layout.",enterprise:"Accurate establishment improves input planning and expected output.",quiz:[{question:"Why does spacing matter?",options:["It affects crop access to resources","It is decorative","It replaces watering","It determines price directly"],answer:0},{question:"What should be recorded at planting?",options:["Date, crop, spacing and count","Passwords","Only learner name","Nothing"],answer:0},{question:"Should planting depth be identical for every crop?",options:["No","Yes","Always 10 cm","Only for seedlings"],answer:0}]},
 {id:"PT-05-L4",title:"Care, Observe and Respond",objective:"Monitor crop condition and carry out safe routine care based on observations.",teaching:["Routine care may include watering, weeding, mulching, support and sanitation.","Symptoms should be observed and recorded before deciding on a response.","Integrated management begins with prevention, observation and appropriate low-risk controls."],activity:"Use a crop-walk checklist to distinguish healthy growth, water stress, weed pressure and signs requiring trainer review.",diy:"Maintain a seven-day Crop Care Log recording condition, action, reason and result.",aiLayer:"AI Layer 4 — Symptom support: AI may suggest possibilities from described symptoms, but diagnosis and any treatment require evidence and qualified supervision.",enterprise:"Early detection reduces losses and unnecessary input use.",quiz:[{question:"What should happen before responding to a crop symptom?",options:["Observe and record evidence","Apply any chemical","Ignore it","Harvest everything"],answer:0},{question:"Which is routine crop care?",options:["Weeding","Sharing passwords","Electrical rewiring","Painting labels only"],answer:0},{question:"Can AI alone authorize pesticide use?",options:["No","Yes","Always","Only for vegetables"],answer:0}]},
 {id:"PT-05-L5",title:"Harvest, Handle and Judge Quality",objective:"Harvest at an appropriate stage and handle produce to reduce damage and contamination.",teaching:["Harvest maturity depends on crop and intended use.","Clean containers and gentle handling reduce physical and hygiene losses.","Quality checks can include size, damage, cleanliness, maturity and other crop-specific criteria."],activity:"Sort sample produce or images using a supplied quality checklist and explain decisions.",diy:"Complete a supervised harvest or simulated harvest, recording gross output, acceptable output and visible losses.",aiLayer:"AI Layer 5 — Quality classification: compare learner sorting with an AI or digital classification example and discuss where human/local standards differ.",enterprise:"Quality and loss control affect usable output and customer value.",quiz:[{question:"Why use clean harvest containers?",options:["To reduce contamination","To increase plant spacing","To replace records","To change maturity"],answer:0},{question:"What is harvest loss?",options:["Output that becomes unusable or downgraded","All harvested produce","Only water","Only seed"],answer:0},{question:"Does harvest maturity depend on crop and use?",options:["Yes","No","Never","Only on price"],answer:0}]},
 {id:"PT-05-L6",title:"Read the Production Record",objective:"Summarize production evidence and identify one justified improvement.",teaching:["Production records connect inputs, actions, observations and outputs.","Simple indicators include establishment rate, harvested quantity and loss proportion.","A useful improvement should be linked to evidence rather than assumption."],activity:"Review the module production record and identify one successful practice, one problem and one next-cycle improvement.",diy:"Prepare a Production Review Sheet with plan vs actual, output, losses, key observations and one evidence-based recommendation.",aiLayer:"Integration — record interpretation: ask AI to summarize the record, then correct any claim that is not supported by the actual field evidence.",enterprise:"Production records support planning, costing, quality and continuous improvement.",quiz:[{question:"What links inputs, actions and outputs?",options:["Production records","A logo","A password","A slogan"],answer:0},{question:"What should justify an improvement?",options:["Evidence","Guesswork","AI confidence","Rumour"],answer:0},{question:"Why compare plan with actual?",options:["To learn from performance","To hide deviations","To avoid measurement","To guarantee profit"],answer:0}]}
 ],
 finalAssessment:{mcq:[{question:"Which belongs in a production plan?",options:["Inputs and task timing","Passwords","Only crop color","Only price"],answer:0},{question:"Which factor matters when selecting a growing site?",options:["Drainage","Email subject","Logo size","File extension"],answer:0},{question:"Why measure spacing?",options:["To establish plants consistently","To replace soil","To prevent all pests","To determine rainfall"],answer:0},{question:"What is the safest first response to an unfamiliar crop symptom?",options:["Observe, record and seek appropriate guidance","Apply an unknown chemical","Ignore safety","Ask AI to prescribe"],answer:0},{question:"Why is gentle harvest handling important?",options:["It reduces damage","It increases weeds","It changes planting depth","It replaces hygiene"],answer:0},{question:"What should a Crop Care Log contain?",options:["Condition, action, reason and result","Only names","Only prices","Only photos without context"],answer:0},{question:"What makes a production recommendation credible?",options:["It is supported by records and observation","It sounds confident","It is longest","It comes from AI"],answer:0},{question:"What should happen with AI crop advice?",options:["Verify it against field evidence and qualified guidance","Apply automatically","Treat it as a pesticide label","Ignore local conditions"],answer:0}],theory:["Describe the main components of a simple crop-production plan.","Explain four factors you would inspect before preparing a growing site.","Explain how spacing, planting depth and establishment records affect production.","Describe a safe process for responding to an unfamiliar crop-health symptom.","Explain how harvest and production records can identify one improvement for the next production cycle."],practical:"Plan and manage a supervised small production unit from site preparation through establishment, routine care and harvest or defined output stage. Submit measurements, production plan, crop-care records, output/loss record and a short evidence-based production review."},
 evidence:["One-page production plan","Site suitability checklist","Bed/container measurement record","Planting and establishment record","Seven-day Crop Care Log","Harvest/output quality record","Production Review Sheet","Facilitator production-skills assessment"],
 passport:["K: understands production stages, crop care, harvest and records","P: prepares, establishes, maintains and evaluates a small production task","D: records observations and checks digital/AI interpretations against field evidence","S: uses tools, hygiene and crop-management practices within supervised safety limits","E: connects planning, quality and loss control to productive value","L: communicates observations and recommends evidence-based improvements"],
 trainerNotes:["Choose locally appropriate crops and adapt timing to actual conditions.","Do not require hazardous agrochemical handling.","Ensure equal access to tools, measurement, recordkeeping and leadership roles.","Assess production process and evidence, not yield alone because weather and other conditions vary.","Use containers or small plots where land is limited."],
 remediation:"Use a single fast-growing crop or container unit. Provide a pictorial task sequence and repeat measurement, planting and observation with trainer modeling before independent work.",
 extension:"Compare two small management treatments such as mulch/no mulch or two safe watering schedules, collect standardized observations and present a cautious evidence-based comparison without overclaiming causation.",imagePrompts:[]
};
export const pt05ByLanguage: Partial<Record<AppLanguage,PT05Module>>={en};
export function getPT05(language:AppLanguage):PT05Module{return pt05ByLanguage[language]??en;}
