import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "../pathways-foundation/pf-01";

type PT03Module = Omit<PF01Module,"code"> & { code:"PT-03" };

const en: PT03Module = {
  code:"PT-03",
  title:"Applied Numeracy",
  level:"Pathways Transition",
  age:"Approximately ages 15–17+; numerical complexity should follow baseline assessment and practical readiness.",
  duration:"6 guided lessons plus measurement-and-costing project and assessment",
  fieldworkHours:5,
  bigQuestion:"How can practical mathematics help us measure, plan, cost and check real food, water, energy and community tasks?",
  whyItMatters:"Workplaces and enterprises depend on accurate quantities, dimensions, rates, percentages and costs. This module turns numeracy into a practical tool for measuring materials, estimating resource use, reading simple data, checking calculations and preparing basic bills of quantities.",
  outcomes:[
    "Use whole numbers, decimals, fractions and percentages in practical contexts.",
    "Measure length, area, volume and mass using appropriate units.",
    "Convert common units accurately within familiar work situations.",
    "Calculate simple rates such as litres per minute, cost per unit and quantity per area.",
    "Estimate material quantities and prepare a basic bill of quantities.",
    "Use calculators, spreadsheets or AI tools to verify calculations while retaining independent reasoning.",
    "Identify implausible numerical results through estimation and unit checks."
  ],
  vocabulary:["estimate","unit","conversion","length","area","volume","mass","rate","ratio","percentage","quantity","unit cost","total cost","bill of quantities","tolerance","rounding","verification"],
  materials:["measuring tape","ruler","measuring containers","scale where available","calculator","graph paper","sample price list","simple bill-of-quantities template","garden/irrigation training objects","optional spreadsheet or supervised digital device"],
  safety:[
    "Measurement exercises must avoid roads, rooftops, live electrical systems and other hazardous locations.",
    "Learners must not lift heavy materials solely for weighing activities.",
    "Use supervised low-risk demonstrations for water-flow measurements.",
    "Do not use AI or calculator outputs without checking units and reasonableness.",
    "Costing examples should be educational and must not require minors to enter commercial contracts."
  ],
  lessons:[
    {id:"PT-03-L1",title:"Numbers, Fractions and Percentages at Work",objective:"Use basic arithmetic, fractions and percentages in realistic task scenarios.",teaching:["Work quantities are often expressed as whole numbers, decimals, fractions or percentages.","Percentages compare a part with a whole out of 100.","Estimation before calculation helps detect impossible results."],activity:"Solve short scenarios involving seed quantities, packaging counts, water containers and percentage completion.",diy:"Create a Practical Numeracy Sheet with two whole-number, two decimal, two fraction and two percentage examples from everyday work.",aiLayer:"AI Layer 1 — Answer checking: compare manual results with calculator or AI outputs and identify any mismatch caused by input or interpretation.",enterprise:"Accurate quantities support stock control, pricing and fair customer transactions.",quiz:[{question:"What is 25% of 200?",options:["50","25","75","100"],answer:0},{question:"Why estimate before calculating?",options:["To check whether the final answer is reasonable","To avoid calculation","To guarantee accuracy without working","To replace units"],answer:0},{question:"Which is equal to one half?",options:["0.5","0.2","2.0","5.0"],answer:0}]},
    {id:"PT-03-L2",title:"Measure Length, Area, Volume and Mass",objective:"Select appropriate tools and units for common practical measurements.",teaching:["Length measures distance, area measures surface, volume measures space occupied and mass measures amount of matter.","Units must match the quantity being measured.","Area of a rectangle is length × width; volume of a rectangular container is length × width × height when dimensions use compatible units."],activity:"Rotate through supervised stations measuring a garden bed, container, pipe length and safe packaged item.",diy:"Complete a Measurement Record containing at least two length, two area, two volume and two mass measurements or calculations.",aiLayer:"AI Layer 2 — Unit check: ask a digital tool to verify calculations, then explain why a correct number with the wrong unit is still incorrect.",enterprise:"Accurate dimensions reduce material waste and rework.",quiz:[{question:"Which unit fits area?",options:["square metres","litres","kilograms","minutes"],answer:0},{question:"How do you find rectangular area?",options:["length × width","length + mass","volume ÷ time","width − price"],answer:0},{question:"Why do units matter?",options:["They tell what the number represents","They are decorative","They replace measurement","They never affect decisions"],answer:0}]},
    {id:"PT-03-L3",title:"Convert Units Without Losing Meaning",objective:"Convert common units used in food, water, garden and technical work.",teaching:["Common conversions include 1000 millilitres = 1 litre, 100 centimetres = 1 metre and 1000 grams = 1 kilogram.","Write the starting unit and target unit before converting.","A conversion should preserve the same physical quantity even though the number changes."],activity:"Complete a conversion relay using length, volume and mass examples.",diy:"Build a one-page Unit Conversion Reference Card and solve ten conversion examples.",aiLayer:"AI Layer 3 — Conversion verification: test several correct and intentionally incorrect conversions with AI or calculator tools and explain which are plausible.",enterprise:"Unit errors can lead to incorrect orders, recipes, irrigation quantities and quotations.",quiz:[{question:"1000 mL equals…",options:["1 L","10 L","100 L","0.01 L"],answer:0},{question:"200 cm equals…",options:["2 m","20 m","0.2 m","2000 m"],answer:0},{question:"What should stay the same during conversion?",options:["The physical quantity","The numerical digits always","The written unit","The price"],answer:0}]},
    {id:"PT-03-L4",title:"Rates, Ratios and Resource Use",objective:"Calculate and interpret simple rates and ratios in practical systems.",teaching:["A rate compares quantities with different units, such as litres per minute or cost per kilogram.","A ratio compares quantities and can support mixing, spacing or resource planning.","Rates should be calculated from measured or clearly stated inputs."],activity:"Use a supervised water collection to calculate litres per minute and compare two sample flow rates.",diy:"Complete a Rate-and-Ratio Log with water flow, unit cost, quantity-per-area and one mixing or spacing example.",aiLayer:"AI Layer 4 — Rate interpretation: compare AI-generated conclusions about two rates with the actual units and context.",enterprise:"Rates help estimate time, operating requirements and resource costs.",quiz:[{question:"A flow rate might be expressed as…",options:["litres per minute","metres only","kilograms only","percent only"],answer:0},{question:"What does cost per kilogram represent?",options:["A rate","An area","A volume","A deadline"],answer:0},{question:"Why include units in a rate?",options:["To show what quantities are being compared","To make it look technical","To avoid measurement","To guarantee profit"],answer:0}]},
    {id:"PT-03-L5",title:"Estimate Materials and Costs",objective:"Estimate quantities and calculate simple material totals using a bill-of-quantities format.",teaching:["A bill of quantities lists items, units, quantities, unit costs and totals.","Total item cost = quantity × unit cost.","A project estimate should distinguish measured quantities from assumptions.","Small allowances may be justified for cutting loss or uncertainty, but they should be explicit."],activity:"Review a small garden or irrigation project and identify all items needed before calculating totals.",diy:"Prepare a basic Bill of Quantities for a small supervised project with at least six line items and a grand total.",aiLayer:"AI Layer 5 — Costing audit: compare the learner's BOQ with an AI-generated calculation and verify arithmetic, units and missing items manually.",enterprise:"Accurate costing supports quotations, budgeting and responsible use of capital.",quiz:[{question:"How is item total cost calculated?",options:["quantity × unit cost","quantity + unit cost always","area ÷ time","price − unit"],answer:0},{question:"What belongs in a BOQ?",options:["item, unit, quantity, unit cost and total","only product names","only a grand total","only labour"],answer:0},{question:"Why state assumptions?",options:["So others can understand how the estimate was made","To hide uncertainty","To guarantee the price","To avoid measurement"],answer:0}]},
    {id:"PT-03-L6",title:"Check the Number Before You Trust It",objective:"Use estimation, unit checks and independent recalculation to verify numerical results.",teaching:["A calculation can be mathematically correct but inappropriate if the input data or units are wrong.","Reasonableness checks compare the result with expected size, range or physical constraints.","Digital tools speed calculation but do not remove responsibility for checking inputs and outputs."],activity:"Audit a set of intentionally flawed measurements, rates and cost calculations and explain each error.",diy:"Complete a Numeracy Verification Checklist for the module project: INPUTS → UNITS → METHOD → ESTIMATE → CALCULATION → RECHECK → DECISION.",aiLayer:"Integration — numerical verification: use calculator, spreadsheet and AI outputs as secondary checks, documenting any disagreement and the final evidence-based decision.",enterprise:"Calculation errors can damage margins, safety, quality and customer confidence; verification is a professional control.",quiz:[{question:"Can a calculator answer still be wrong in practice?",options:["Yes, if inputs or units are wrong","No","Only with percentages","Only online"],answer:0},{question:"What is a reasonableness check?",options:["Comparing a result with an expected range or estimate","Deleting unexpected data","Rounding everything to zero","Trusting the first answer"],answer:0},{question:"Who remains responsible for checking digital calculations?",options:["The person using them","Nobody","The calculator","The customer only"],answer:0}]}
  ],
  finalAssessment:{
    mcq:[
      {question:"What is 10% of 350?",options:["35","3.5","3500","315"],answer:0},
      {question:"Which unit is appropriate for a garden-bed area?",options:["m²","L","kg","min"],answer:0},
      {question:"2500 mL equals…",options:["2.5 L","25 L","0.25 L","250 L"],answer:0},
      {question:"A pump delivers 20 L in 4 minutes. What is the average flow rate?",options:["5 L/min","80 L/min","16 L/min","24 L/min"],answer:0},
      {question:"If 6 fittings cost ₦500 each, what is the line total?",options:["₦3,000","₦500","₦6,500","₦30,000"],answer:0},
      {question:"What is the best first check when an answer looks unrealistic?",options:["Review inputs, units and method","Accept it","Delete it","Round it"],answer:0},
      {question:"What does a BOQ help organize?",options:["Items, quantities and costs","Only attendance","Only hazards","Only customer names"],answer:0},
      {question:"Why should AI-generated calculations be verified?",options:["They may use wrong assumptions, inputs or units","AI cannot calculate","Verification is never needed","Only because calculators are slow"],answer:0}
    ],
    theory:[
      "Explain the difference between length, area, volume and mass and give one work example of each.",
      "Convert 3.5 litres to millilitres and explain the conversion.",
      "A container fills 18 litres in 3 minutes. Calculate the average flow rate and state the unit.",
      "Describe the information required in a simple bill of quantities and explain why assumptions should be shown.",
      "Explain three ways to verify a numerical result before using it for a practical decision."
    ],
    practical:"Measure a small supervised project area or system, prepare a dimension sheet, calculate at least one area or volume, compute one practical rate, and prepare a six-item bill of quantities using a supplied price list. Present your calculations and demonstrate estimation, unit checks and independent verification."
  },
  evidence:["Practical Numeracy Sheet","Measurement Record","Unit Conversion Reference Card","Rate-and-Ratio Log","Six-item Bill of Quantities","Numeracy Verification Checklist","Project calculation sheet","Facilitator applied-numeracy assessment"],
  passport:["K: understands units, percentages, rates and basic costing relationships","P: measures practical quantities and prepares a simple BOQ","D: uses calculators/spreadsheets/AI as checked verification tools","S: conducts measurement activities within safe supervised boundaries","E: applies numeracy to materials, costs and resource planning","L: explains calculations clearly and challenges implausible results"],
  trainerNotes:["Use locally realistic measurements and price examples while making clear that training prices may change.","Allow learners to show working orally, visually or in tables where appropriate.","Require units on every final measurement and rate.","Assess method and checking, not only final answers.","Use calculators after learners understand the operation being performed.","Keep commercial examples educational for minors."],
  remediation:"Return to concrete measurement and number lines. Use one familiar project with whole-number values first, then introduce decimals, conversions and rates one layer at a time with repeated unit labeling.",
  extension:"Learner builds a spreadsheet version of the BOQ with formulas, adds a 5% explicit material allowance, compares manual and spreadsheet totals, and documents the reason for every formula.",
  imagePrompts:[]
};

export const pt03ByLanguage: Partial<Record<AppLanguage,PT03Module>> = { en };
export function getPT03(language:AppLanguage):PT03Module { return pt03ByLanguage[language] ?? en; }
