import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "../pathways-foundation/pf-01";
type PT06Module=Omit<PF01Module,"code">&{code:"PT-06"};
const en:PT06Module={
 code:"PT-06",title:"Water and Irrigation Skills",level:"Pathways Transition",age:"Approximately ages 15–17+; installation and testing must be supervised and limited to safe low-pressure training systems.",duration:"6 guided lessons plus irrigation installation practical and assessment",fieldworkHours:7,
 bigQuestion:"How can we move, store, distribute and check water so that a small production system receives the right amount safely and efficiently?",
 whyItMatters:"Food production depends on reliable water delivery. Learners need to understand the pathway from source to storage to distribution, recognize basic irrigation components, measure simple flow, install a small layout, identify common faults and document performance without entering hazardous pump or electrical work.",
 outcomes:["Trace water through source, storage, conveyance and application stages.","Identify common low-pressure irrigation components and their functions.","Measure simple volume, time and flow rate safely.","Plan a small irrigation layout using dimensions and crop needs.","Assemble and test a supervised drip or equivalent low-risk training layout.","Identify common leaks, blockages and uneven delivery using evidence.","Record system checks and propose water-efficiency improvements."],
 vocabulary:["source","storage","tank","conveyance","pressure","flow","flow rate","valve","filter","mainline","lateral","connector","emitter","dripline","leak","blockage","flush","distribution","uniformity","irrigation schedule"],
 materials:["low-pressure water source or elevated training container","food-grade or training water container","measuring jug/bucket","timer","safe tubing/dripline","valves/connectors","filter demonstration","emitters","end caps","measuring tape","layout sheet","inspection checklist"],
 safety:["Use only supervised low-pressure training systems suitable for learners.","No work on live electrical pumps, mains electricity, pressurized industrial lines, wells or confined tanks.","Keep walking areas dry enough to prevent slips and route hoses safely.","Use clean water for demonstrations involving hand contact where practicable.","Trainer must isolate water supply before disassembly or repair."],
 lessons:[
 {id:"PT-06-L1",title:"Follow the Water Path",objective:"Explain how water moves from source through storage and distribution to the crop or point of use.",teaching:["A water system can be understood as connected blocks: SOURCE → STORAGE → CONTROL → CONVEYANCE → APPLICATION → DRAINAGE/RETURN where applicable.","Each block has a function and possible failure points.","Gravity and pumps can create movement, but pump work requires appropriate technical supervision."],activity:"Trace and label the water path on a real or model training system.",diy:"Draw a Water Path Diagram for the training site and label at least six components or stages.",aiLayer:"AI Layer 1 — System recognition: compare your diagram with an AI-described water pathway and identify site-specific elements the generic answer misses.",enterprise:"Understanding system flow supports installation, maintenance and efficient resource use.",quiz:[{question:"What commonly comes after a water source?",options:["Storage or conveyance","A password","Packaging","Harvest"],answer:0},{question:"Why map system blocks?",options:["To understand functions and failure points","To decorate the site","To eliminate measurement","To replace inspection"],answer:0},{question:"Should learners work on live pump wiring in this module?",options:["No","Yes","Always","Only alone"],answer:0}]},
 {id:"PT-06-L2",title:"Know the Irrigation Components",objective:"Identify common components and explain their roles in a low-pressure irrigation layout.",teaching:["Filters reduce particles that can contribute to blockage.","Valves control flow; pipes and laterals convey water; emitters apply water near the target area.","Connectors, end caps and fittings must match the tubing and system design."],activity:"Complete a component identification station and match each item to its function.",diy:"Create an Irrigation Component Board or photo sheet with at least eight labelled components and functions.",aiLayer:"AI Layer 2 — Component identification: use image/text AI only as a secondary check; confirm names against actual manufacturer/trainer information.",enterprise:"Correct component identification reduces wrong purchases and installation errors.",quiz:[{question:"What does a valve do?",options:["Controls flow","Measures sunlight","Stores passwords","Harvests crops"],answer:0},{question:"Why use a filter?",options:["To reduce particles entering the system","To increase crop spacing","To generate electricity","To replace storage"],answer:0},{question:"What carries water along a row?",options:["A lateral or dripline","A CV","A scale","A harvest crate"],answer:0}]},
 {id:"PT-06-L3",title:"Measure Volume and Flow",objective:"Measure water volume and calculate a simple average flow rate.",teaching:["Flow rate compares volume with time, such as litres per minute.","A simple collection test uses a known time interval and measured volume.","Repeated measurements help reveal variation and measurement error."],activity:"Collect water safely for a timed interval and calculate litres per minute.",diy:"Complete three timed flow measurements, calculate each rate and report the average.",aiLayer:"AI Layer 3 — Calculation check: compare manual flow-rate calculations with a calculator or AI result and verify units.",enterprise:"Flow measurement helps estimate irrigation time, detect faults and plan water use.",quiz:[{question:"Flow rate compares…",options:["Volume and time","Price and color","Area and password","Mass and age"],answer:0},{question:"If 10 L is collected in 2 minutes, average flow is…",options:["5 L/min","20 L/min","12 L/min","8 L/min"],answer:0},{question:"Why repeat a measurement?",options:["To check variation and reliability","To guarantee pressure","To avoid units","To replace observation"],answer:0}]},
 {id:"PT-06-L4",title:"Plan the Layout",objective:"Use site dimensions and application points to draw a simple irrigation layout and material list.",teaching:["A layout should show water entry, control point, mainline, laterals and end points.","Dimensions help estimate pipe lengths and fitting quantities.","Routes should avoid unnecessary trip hazards and allow inspection and flushing."],activity:"Measure a small training plot and sketch two possible layouts before selecting one.",diy:"Prepare a scaled or dimensioned irrigation sketch with component quantities and a simple material list.",aiLayer:"AI Layer 4 — Layout critique: ask AI to identify possible omissions, then accept only suggestions consistent with measured site conditions and safe design.",enterprise:"Accurate layouts support material estimation and reduce waste.",quiz:[{question:"Why measure before planning pipe length?",options:["To estimate materials accurately","To increase pressure automatically","To replace valves","To avoid drawings"],answer:0},{question:"What should a layout show?",options:["Water path and components","Only learner names","Only crop prices","Passwords"],answer:0},{question:"Why keep routes inspectable?",options:["For maintenance and fault finding","For decoration","To hide leaks","To prevent records"],answer:0}]},
 {id:"PT-06-L5",title:"Assemble and Test a Training Irrigation Zone",objective:"Install and test a supervised low-pressure irrigation layout using correct sequence and checks.",teaching:["Installation follows the approved layout and compatible components.","Lines should be connected securely, end points managed correctly and system flushed where appropriate before final operation.","Testing checks leaks, flow and delivery at representative points."],activity:"In teams with role rotation, assemble a small irrigation zone and perform a controlled first test.",diy:"Install the approved layout, complete a commissioning checklist and record at least three delivery observations.",aiLayer:"AI Layer 5 — Commissioning support: compare the checklist with a digital/AI-generated checklist, but follow trainer/manufacturer requirements where they differ.",enterprise:"Commissioning before handover reduces callbacks and water loss.",quiz:[{question:"What should guide installation?",options:["The approved layout and compatible components","Guesswork","An unrelated video","Price only"],answer:0},{question:"Why test before handover?",options:["To identify leaks and delivery problems","To avoid inspection","To guarantee crop yield","To replace flushing"],answer:0},{question:"What is commissioning?",options:["Checking that the installed system operates as intended","Buying seeds","Writing a CV","Harvest sorting"],answer:0}]},
 {id:"PT-06-L6",title:"Find Faults and Improve Water Use",objective:"Use inspection and measurements to identify common low-risk faults and recommend corrective action.",teaching:["Visible leaks waste water and may reduce downstream delivery.","Blockages can cause weak or absent emitter flow.","Uneven delivery can arise from blockage, layout, pressure or other causes that require systematic checking.","Maintenance records should state symptom, evidence, action and result."],activity:"Diagnose trainer-created safe faults such as a loose fitting, kinked line or blocked training emitter.",diy:"Complete an Irrigation Inspection Log covering leak check, end-point delivery, one flow measurement, fault/action/result and one water-efficiency recommendation.",aiLayer:"Integration — troubleshooting: use AI to generate possible causes only after documenting symptoms; rank causes using actual measurements and inspection evidence.",enterprise:"Systematic troubleshooting saves time, water and replacement costs.",quiz:[{question:"What can a leak cause?",options:["Water loss and reduced downstream delivery","Higher literacy","Automatic filtration","Better file naming"],answer:0},{question:"What may cause an emitter not to flow?",options:["Blockage","A CV","Harvest maturity","A subject line"],answer:0},{question:"What should troubleshooting begin with?",options:["Observed symptoms and evidence","Random replacement","AI alone","Buying every component"],answer:0}]}
 ],
 finalAssessment:{mcq:[{question:"Which sequence best describes a simple water pathway?",options:["Source → storage/control → conveyance → application","Application → password → harvest","Filter → CV → source","Crop → email → tank"],answer:0},{question:"What is the function of a filter?",options:["Reduce particles entering irrigation lines","Store water indefinitely","Generate power","Measure crop height"],answer:0},{question:"What is a common unit for small irrigation flow rate?",options:["L/min","kg/m² only","°C","naira/m"],answer:0},{question:"12 litres collected in 3 minutes equals…",options:["4 L/min","36 L/min","15 L/min","9 L/min"],answer:0},{question:"Why prepare a dimensioned layout?",options:["To plan routes and materials","To guarantee pressure","To replace testing","To avoid inspection"],answer:0},{question:"What should be done before disassembling a training water line?",options:["Isolate the supply","Increase pressure","Touch live pump wiring","Remove PPE requirements"],answer:0},{question:"What belongs in a maintenance record?",options:["Symptom, evidence, action and result","Only a photo","Only price","Only learner name"],answer:0},{question:"How should AI be used during troubleshooting?",options:["To suggest possibilities that are checked against evidence","As automatic diagnosis","To authorize electrical repairs","To replace measurements"],answer:0}],theory:["Draw and explain the major stages in a simple irrigation water pathway.","Explain the functions of a filter, valve, mainline/lateral and emitter.","Describe how to conduct a timed collection test and calculate flow rate.","Explain the information required in a simple irrigation layout and material list.","Describe a systematic process for finding and documenting a leak, blockage or uneven-delivery problem."],practical:"Measure a supervised training area, prepare a simple irrigation layout and material list, assemble the approved low-pressure system, conduct commissioning checks, measure flow at selected points, identify at least one trainer-created fault, correct it safely and submit an inspection record with one water-efficiency recommendation."},
 evidence:["Water Path Diagram","Irrigation Component Board/photo sheet","Three flow-rate measurements","Dimensioned irrigation layout","Material list","Commissioning checklist","Irrigation Inspection Log","Facilitator irrigation-skills assessment"],
 passport:["K: understands water pathways, irrigation components, flow and common faults","P: measures, lays out, assembles and checks a safe training irrigation zone","D: calculates flow and uses digital/AI support as evidence-checked assistance","S: isolates supply and stays within low-pressure/non-electrical training boundaries","E: connects accurate installation and maintenance with water/material efficiency","L: works in rotating team roles and communicates faults clearly"],
 trainerNotes:["Keep this module separate from advanced pump/electrical technician training.","Use low-pressure gravity systems where possible for safe demonstration.","Rotate measurement, layout, assembly, inspection and documentation roles equitably.","Require actual measurements rather than generic design assumptions.","Adapt irrigation technology to locally relevant systems while retaining the same competency outcomes."],
 remediation:"Use a tabletop or short gravity-fed demonstration with color-coded components. Practice SOURCE → VALVE → LINE → EMITTER first, then add measurement and fault finding one step at a time.",
 extension:"Measure delivery from several emitters, calculate a simple max/min comparison, map the variation along the line and propose one cautious improvement based on inspection evidence.",imagePrompts:[]
};
export const pt06ByLanguage:Partial<Record<AppLanguage,PT06Module>>={en};
export function getPT06(language:AppLanguage):PT06Module{return pt06ByLanguage[language]??en;}
