import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "../pathways-foundation/pf-01";

type PT02Module = Omit<PF01Module,"code"> & { code:"PT-02" };

const en: PT02Module = {
  code:"PT-02",
  title:"Foundational Work Skills",
  level:"Pathways Transition",
  age:"Approximately ages 15–17+; supervised practice should match learner readiness and safeguarding requirements.",
  duration:"6 guided lessons plus team-work simulation and assessment",
  fieldworkHours:5,
  bigQuestion:"What behaviours and habits help a person become reliable, safe and useful in a real work or training environment?",
  whyItMatters:"Technical knowledge alone does not create work readiness. Learners need reliability, communication, teamwork, planning, safe behaviour and the ability to complete tasks to standard. This module develops those transferable skills through supervised simulations and evidence-based reflection.",
  outcomes:[
    "Explain why reliability, punctuality and preparation matter in work and training.",
    "Use clear verbal and written communication for simple task instructions and updates.",
    "Work in rotating team roles while sharing responsibility fairly.",
    "Plan and complete a small task within an agreed time and quality standard.",
    "Recognize when to ask for clarification, support or escalation.",
    "Give and receive professional feedback using observable evidence.",
    "Use digital tools responsibly for simple work communication and task records."
  ],
  vocabulary:["reliability","punctuality","instruction","standard","deadline","role","responsibility","handover","clarification","feedback","quality","escalation","attendance","task log","professionalism"],
  materials:["task cards","role cards","simple work-order sheet","timer","checklist","notebook","sample message templates","quality-check sheet","optional supervised digital device"],
  safety:[
    "Simulated work tasks must remain low-risk and age-appropriate.",
    "Learners must stop and ask for help when instructions are unsafe, unclear or beyond their authorization.",
    "No learner should be pressured to perform hazardous, heavy or adult-only work.",
    "Digital communication must use approved accounts or training simulations rather than personal contact details.",
    "Feedback must remain respectful and task-focused."
  ],
  lessons:[
    {id:"PT-02-L1",title:"Reliability Starts Before the Task",objective:"Demonstrate preparation, punctuality and readiness behaviours.",teaching:["Reliability means others can reasonably expect agreed tasks to be completed safely and on time.","Preparation includes checking instructions, materials, tools, PPE and timing before starting.","If delay is unavoidable, responsible workers communicate early rather than disappearing."],activity:"Compare several arrival-and-preparation scenarios and identify reliable and unreliable behaviours.",diy:"Create and use a personal Work-Readiness Checklist for one supervised task day.",aiLayer:"AI Layer 1 — Scenario classification: compare learner judgments with AI classifications and discuss where context matters.",enterprise:"Reliable service builds trust with supervisors, teammates and customers.",quiz:[{question:"What is a sign of reliability?",options:["Preparing before the task","Ignoring instructions","Arriving without needed materials","Hiding delays"],answer:0},{question:"If delay is unavoidable, what should you do?",options:["Communicate early","Say nothing","Blame others","Change the record"],answer:0},{question:"What should preparation include?",options:["Instructions, materials and safety checks","Only motivation","Only a phone","Nothing until work starts"],answer:0}]},
    {id:"PT-02-L2",title:"Listen, Clarify, Confirm",objective:"Receive instructions accurately and ask useful clarification questions.",teaching:["Good listening includes attention, note-taking and checking understanding.","Repeating the key task in your own words can confirm meaning.","Clarification is a professional skill, especially when safety, quality or deadlines are unclear."],activity:"Practice receiving a short work instruction, then use READ/REPEAT/ASK/CONFIRM before beginning.",diy:"Complete three instruction-confirmation records using task, deadline, standard and question fields.",aiLayer:"AI Layer 2 — Instruction simplification: compare an AI summary of a task instruction with the original and identify missing details.",enterprise:"Misunderstood instructions can waste materials, labour and customer trust.",quiz:[{question:"When should you ask for clarification?",options:["When key details are unclear","Never","Only after failure","Only if a supervisor is absent"],answer:0},{question:"What can confirm understanding?",options:["Repeating the task in your own words","Guessing","Starting immediately without checking","Ignoring the deadline"],answer:0},{question:"Why take notes?",options:["To reduce forgotten details","To replace communication","To avoid responsibility","To make tasks longer"],answer:0}]},
    {id:"PT-02-L3",title:"Team Roles and Shared Responsibility",objective:"Work effectively in rotating team roles and support fair participation.",teaching:["Teams work better when roles and responsibilities are clear.","Leadership is not the same as controlling every task.","Role rotation helps all learners practise technical, communication and coordination skills.","A strong team supports members without doing all their work for them."],activity:"Complete a short team challenge with rotating roles: coordinator, materials lead, recorder and quality checker.",diy:"Create a Team Role Rotation Sheet showing who did what, what worked and what should change next time.",aiLayer:"AI Layer 3 — Team reflection: compare an AI-generated team-improvement suggestion with evidence from the actual task.",enterprise:"Small enterprises depend on clear roles, handovers and accountability.",quiz:[{question:"Why rotate roles?",options:["So everyone develops broader skills","So one person avoids work","To remove accountability","To guarantee speed"],answer:0},{question:"What does a coordinator do?",options:["Helps organize the team and task","Controls everyone personally","Does every task alone","Ignores quality"],answer:0},{question:"What is shared responsibility?",options:["Each member contributes to agreed team outcomes","No one owns the task","Only the leader works","Everyone does the same thing"],answer:0}]},
    {id:"PT-02-L4",title:"Time, Quality and Task Completion",objective:"Plan a simple task against time, sequence and quality requirements.",teaching:["A task can be divided into steps, dependencies and checkpoints.","Finishing fast is not success if the result is unsafe or below standard.","Simple checklists help teams monitor progress before the deadline."],activity:"Sequence a practical work order into START → DO → CHECK → FINISH → HANDOVER.",diy:"Use a Task Completion Plan for one 30–60 minute supervised assignment, including expected finish time and two quality checks.",aiLayer:"AI Layer 4 — Planning critique: ask AI for a task sequence, then identify unrealistic timing or missing safety/quality steps.",enterprise:"Time and quality control affect cost, customer satisfaction and repeat work.",quiz:[{question:"Is fastest always best?",options:["No, quality and safety also matter","Yes","Only for teamwork","Only for paid work"],answer:0},{question:"What is a checkpoint?",options:["A place to verify progress or quality","A punishment","A final salary","A social message"],answer:0},{question:"Why sequence tasks?",options:["To organize work logically","To avoid planning","To remove deadlines","To make records unnecessary"],answer:0}]},
    {id:"PT-02-L5",title:"When Things Go Wrong",objective:"Respond appropriately to mistakes, delays, hazards and unexpected changes.",teaching:["Problems should be reported early when they affect safety, quality or completion.","Covering up mistakes can make consequences worse.","A useful problem report states what happened, what has been affected and what support is needed.","Escalation means taking an issue to someone with the authority or expertise to act."],activity:"Use four scenarios to decide: FIX WITHIN ROLE, ASK, STOP, or ESCALATE.",diy:"Complete a Problem and Escalation Log for three simulated workplace situations.",aiLayer:"AI Layer 5 — Risk screening: compare AI recommendations with the learner's authority level and safety rules; reject advice that exceeds authorization.",enterprise:"Responsible reporting protects people, equipment, products and business reputation.",quiz:[{question:"What should you do with a serious safety issue?",options:["Stop and escalate appropriately","Hide it","Continue without change","Post it publicly"],answer:0},{question:"Why report mistakes early?",options:["They may be easier to correct before harm grows","To avoid responsibility","To blame others","Because records do not matter"],answer:0},{question:"What is escalation?",options:["Taking an issue to someone with authority or expertise","Ignoring a problem","Making a private guess","Changing the evidence"],answer:0}]},
    {id:"PT-02-L6",title:"Simulated Workday",objective:"Integrate reliability, communication, teamwork, time management and quality in a supervised work simulation.",teaching:["Work readiness is demonstrated by consistent behaviour across a complete task cycle.","Professional handover includes what was completed, what remains, any problems and where records are stored.","Reflection should identify evidence of performance and one improvement target."],activity:"Teams complete a timed low-risk work assignment with role rotation, instruction confirmation, quality checks, problem response and handover.",diy:"Submit a Simulated Workday Pack containing readiness checklist, task plan, role record, quality checks, problem log and final handover note.",aiLayer:"Integration — work review: compare an AI-generated performance summary with the actual evidence and remove unsupported judgments.",enterprise:"Documented work habits support employability, apprenticeship readiness and reliable enterprise operations.",quiz:[{question:"What belongs in a handover?",options:["Completed work, remaining issues and records","Only a greeting","Only mistakes","No details"],answer:0},{question:"What proves work readiness best?",options:["Consistent demonstrated behaviour and evidence","A slogan","One good intention","Age alone"],answer:0},{question:"What should reflection produce?",options:["One evidence-based strength and one improvement target","Only praise","Only criticism","No next step"],answer:0}]}
  ],
  finalAssessment:{
    mcq:[
      {question:"What does reliability mean in a work context?",options:["Being prepared and completing agreed tasks responsibly","Always working alone","Never asking questions","Doing only interesting tasks"],answer:0},
      {question:"What is the best response to unclear instructions?",options:["Ask for clarification before proceeding","Guess","Ignore the unclear part","Wait until the deadline passes"],answer:0},
      {question:"Why use role rotation?",options:["To build wider competence and fair participation","To avoid accountability","To make one person lead forever","To slow the team"],answer:0},
      {question:"What should happen before final handover?",options:["Quality and completion checks","Delete records","Hide unfinished work","Skip communication"],answer:0},
      {question:"When should a learner escalate?",options:["When a problem exceeds their authority, skill or safety limits","Never","Only after damage occurs","Only for minor issues"],answer:0},
      {question:"Which is professional feedback?",options:["Specific, respectful and linked to observable behaviour","A personal insult","A rumour","A public comparison"],answer:0},
      {question:"What is useful in a task log?",options:["Time, task, status and issues","Only a title","No dates","Private passwords"],answer:0},
      {question:"What is the strongest evidence of work readiness?",options:["A completed supervised task with records and review","A promise","A profile slogan","A guess"],answer:0}
    ],
    theory:[
      "Explain three behaviours that make a learner reliable in a work or training environment.",
      "Describe how you would receive and confirm a work instruction before beginning a task.",
      "Explain why team role rotation can improve both fairness and competence.",
      "Describe a situation in which you should stop work and escalate rather than continue.",
      "Explain how time management and quality control affect enterprise or workplace performance."
    ],
    practical:"Complete a supervised simulated workday using an assigned task. Demonstrate preparation, instruction confirmation, team role participation, time planning, quality checks, safe problem response and professional handover. Submit the associated evidence pack and explain one improvement target."
  },
  evidence:["Work-Readiness Checklist","Instruction-confirmation records","Team Role Rotation Sheet","Task Completion Plan","Problem and Escalation Log","Quality-check record","Handover note","Facilitator simulated-workday assessment"],
  passport:["K: explains core work-readiness behaviours and communication practices","P: completes assigned low-risk tasks to agreed time and quality standards","D: uses simple digital or written task records responsibly","S: recognizes limits and escalates unsafe or unauthorized work","E: connects reliability and quality to customer and enterprise trust","L: communicates, collaborates, rotates roles and responds constructively to feedback"],
  trainerNotes:["Keep simulations realistic but low-risk.","Assess behaviour over the whole task cycle rather than one isolated moment.","Rotate leadership and technical roles equitably across gender and confidence levels.","Allow reasonable accommodations without lowering competency standards.","Distinguish genuine reliability issues from barriers outside a learner's control.","Use evidence and observation rather than personality judgments."],
  remediation:"Use one short task with a four-step checklist: PREPARE → CONFIRM → DO → HANDOVER. Repeat the task with coaching until the learner can perform the sequence with reduced prompting.",
  extension:"Learner acts as shift coordinator for a second simulation, prepares the work order, assigns rotating roles, monitors progress and conducts a brief evidence-based handover review.",
  imagePrompts:[]
};

export const pt02ByLanguage: Partial<Record<AppLanguage,PT02Module>> = { en };
export function getPT02(language:AppLanguage):PT02Module { return pt02ByLanguage[language] ?? en; }
