import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "../pathways-foundation/pf-01";

type PE04Module = Omit<PF01Module,"code"> & { code:"PE-04" };

const en: PE04Module = {
  code:"PE-04", title:"Water-Smart Growing", level:"Pathways Explorer", age:"Approximately 11–14 years; all irrigation observations and installations must be supervised and age-appropriate.", duration:"6 guided lessons plus a supervised irrigation-efficiency investigation and assessment", fieldworkHours:4,
  bigQuestion:"How can we give plants the water they need while reducing avoidable losses and managing water safely?",
  whyItMatters:"Water-smart growing is about matching crop water needs with timing, delivery and observation. Learners investigate soil moisture, evaporation, runoff, irrigation methods, simple scheduling and recordkeeping. They learn that saving water does not mean under-watering crops, and that irrigation decisions should be based on evidence, local conditions and system constraints.",
  outcomes:["Explain why plants need water and why both shortage and excess can reduce performance.","Identify major pathways of water input, storage, uptake and loss in a growing system.","Compare simple irrigation methods using criteria such as delivery control, labour, cost and loss potential.","Use safe observations and simple measurements to estimate water applied.","Create a basic irrigation schedule using crop stage, weather observations and soil-moisture evidence.","Identify runoff, leakage, overwatering and evaporation as potential avoidable losses.","Propose one practical water-saving improvement and define how to monitor it.","Critique AI or digital irrigation advice for missing local evidence, assumptions and safety constraints."],
  vocabulary:["irrigation","soil moisture","infiltration","evaporation","transpiration","runoff","leakage","root zone","schedule","volume","flow","efficiency","drip","watering can","mulch","rainfall","observation","indicator","constraint","trade-off"],
  materials:["measuring containers","watering can","safe drip-line demonstration where available","buckets","graduated bottles","soil-moisture observation sheet","mulch sample","stopwatch or phone timer under facilitator control","simple weather observation chart","garden plot or demonstration containers","calculator optional"],
  safety:["Do not allow learners to operate pumps, mains electrical equipment or pressurized systems without qualified supervision.","Prevent slips, standing water and trip hazards around hoses, buckets and irrigation lines.","Use only clean, approved water sources for school garden activities.","Learners must not enter tanks, wells, drains or other confined or hazardous water structures.","Avoid lifting heavy water containers; divide loads and use age-appropriate quantities.","AI irrigation advice involving pump settings, electrical systems, chemical injection or unsafe water sources must not be implemented by learners."],
  lessons:[
    {id:"PE-04-L1",title:"Where Water Goes",objective:"Map water inputs, storage, plant uptake and losses in a crop-growing system.",teaching:["Water can enter through rainfall or irrigation and move into soil or growing media.","Plants take up water through roots and release much of it through transpiration.","Water can also be lost through evaporation, runoff, deep drainage or leaks; some losses are unavoidable while others can be reduced."],activity:"Build a water-pathway diagram for a garden bed showing rainfall/irrigation, infiltration, root uptake, evaporation, runoff and drainage.",diy:"Create a Water Pathway Map for one school-garden bed or container system.",aiLayer:"AI Layer 1 — System map check: compare an AI-generated garden water cycle with the learner map and identify missing or oversimplified pathways.",enterprise:"Understanding water pathways helps growers identify where labour, pumping and water resources may be wasted.",quiz:[{question:"Where do plants mainly take up water?",options:["Through roots","Through labels","Through tools","Through pathways"],answer:0},{question:"Which can be a water loss?",options:["Runoff","Root uptake only","Harvest record","Crop name"],answer:0},{question:"Does saving water mean giving plants too little?",options:["No","Yes","Always","Only with drip"],answer:0}]},
    {id:"PE-04-L2",title:"Measure Water Applied",objective:"Use simple volume and time measurements to record irrigation inputs consistently.",teaching:["Water volume should be measured with clear units such as litres or millilitres.","Applying the same measured amount helps compare treatments fairly.","For flowing water, volume collected over a known time can be used as a simple indicator of flow rate."],activity:"Measure several small water volumes and conduct a supervised bucket-and-timer flow demonstration using a low-risk water source.",diy:"Complete a Water Use Record with date, location, method, volume, duration and observation.",aiLayer:"AI Layer 2 — Calculation verification: compare learner flow-rate calculations with calculator or AI results and resolve unit mistakes.",enterprise:"Measured water use supports better planning, cost estimation and detection of unusual consumption.",quiz:[{question:"Which is a water-volume unit?",options:["Litre","Metre","Kilogram","Degree"],answer:0},{question:"Why record irrigation volume?",options:["To understand water use","To guarantee yield","To remove observation","To replace crop care"],answer:0},{question:"What is needed for a simple flow estimate?",options:["Volume and time","Colour only","Crop name only","Area only"],answer:0}]},
    {id:"PE-04-L3",title:"Compare Irrigation Methods",objective:"Compare common irrigation methods using technical and practical criteria.",teaching:["Watering cans, furrows, hoses and drip systems differ in control, labour, cost, maintenance and loss potential.","A method that is efficient in one setting may be unsuitable in another because of cost, pressure, clogging or management requirements.","Fair comparison requires the same decision criteria."],activity:"Compare two or three irrigation methods using criteria for control, labour, cost, maintenance, evaporation/runoff risk and suitability.",diy:"Create an Irrigation Method Decision Matrix and justify a preferred option for a stated school-garden scenario.",aiLayer:"AI Layer 3 — Assumption checking: critique an AI recommendation that names one irrigation method as universally best.",enterprise:"Irrigation choice affects capital cost, operating effort, maintenance and reliability.",quiz:[{question:"Is drip always the best option?",options:["No","Yes","Only because it is modern","Only if AI says so"],answer:0},{question:"Which is a valid comparison criterion?",options:["Maintenance need","Logo colour","Popularity only","Price without context"],answer:0},{question:"Why compare methods with the same criteria?",options:["For a fairer decision","To guarantee one winner","To ignore trade-offs","To avoid evidence"],answer:0}]},
    {id:"PE-04-L4",title:"When Should We Irrigate?",objective:"Use plant stage, soil condition and weather observations to create a simple irrigation schedule.",teaching:["Irrigation timing should respond to crop needs and root-zone conditions, not a fixed habit alone.","Hot, dry and windy conditions can increase water demand, while rainfall may reduce irrigation need.","Overwatering can reduce aeration, waste water and contribute to nutrient loss or disease risk."],activity:"Review several crop-and-weather scenarios and decide whether to irrigate now, check again later or avoid irrigation, explaining the evidence used.",diy:"Build a one-week Irrigation Decision Log using soil observations, recent rainfall/weather and crop condition.",aiLayer:"AI Layer 4 — Scheduling critique: compare an AI-generated irrigation schedule with actual local observations and identify missing information.",enterprise:"Better scheduling can reduce unnecessary pumping or labour while protecting crop performance.",quiz:[{question:"Should irrigation always happen at the same time regardless of conditions?",options:["No","Yes","Only in dry regions","Only with automation"],answer:0},{question:"What can reduce irrigation need?",options:["Recent rainfall","A longer hose","A new notebook","Crop labels"],answer:0},{question:"What can overwatering cause?",options:["Poor aeration and waste","Guaranteed growth","No maintenance","Higher efficiency always"],answer:0}]},
    {id:"PE-04-L5",title:"Reduce Avoidable Water Losses",objective:"Identify practical actions that reduce runoff, evaporation, leakage and unnecessary application.",teaching:["Leaks and broken fittings can waste water before it reaches crops.","Mulch and appropriate timing can reduce exposed-surface evaporation.","Slow, well-targeted application can reduce runoff where infiltration is limited.","Water-saving changes should be monitored to ensure crops still receive adequate water."],activity:"Conduct a supervised water-loss audit around a demonstration system, marking visible leaks, overspray, runoff pathways and exposed wet soil.",diy:"Create a Water-Saving Action Plan with one loss, one proposed change, one expected benefit and one indicator to monitor.",aiLayer:"AI Layer 5 — Intervention screening: evaluate AI-suggested water-saving measures for local feasibility, cost, crop risk and safety.",enterprise:"Reducing avoidable water loss can lower operating effort and resource costs, but poorly designed savings can reduce crop quality or yield.",quiz:[{question:"Which is an avoidable loss?",options:["A leaking fitting","Plant uptake","Necessary transpiration","Recorded rainfall"],answer:0},{question:"How can mulch help?",options:["Reduce soil-surface evaporation","Replace all water","Fix leaks","Measure flow"],answer:0},{question:"What should happen after a water-saving change?",options:["Monitor crop and water indicators","Assume success","Stop recordkeeping","Delete baseline data"],answer:0}]},
    {id:"PE-04-L6",title:"Design a Water-Smart Growing Plan",objective:"Integrate measurement, scheduling, method selection and loss reduction into a practical irrigation plan.",teaching:["A good plan states the crop/system, water source, delivery method, decision rules, expected water use, risks and monitoring indicators.","Plans should include contingencies for rainfall, leaks, blocked emitters or water shortage.","Evidence should be reviewed over time and the schedule adjusted rather than treated as permanent."],activity:"Teams create and present a water-smart plan for a school-garden case, then revise it after peer questions about assumptions and trade-offs.",diy:"Complete a Water-Smart Growing Plan: SYSTEM → WATER SOURCE → METHOD → SCHEDULE RULE → VOLUME RECORD → LOSS CONTROLS → SAFETY → MONITORING → REVISION.",aiLayer:"Integration — decision support: ask AI to challenge the plan with alternative methods or schedules, then accept only changes supported by site evidence and facilitator guidance.",enterprise:"Operational water plans help growers manage reliability, cost, maintenance and production risk.",quiz:[{question:"What should a water-smart plan include?",options:["Method, schedule, monitoring and loss controls","Only a preferred technology","No records","Guaranteed results"],answer:0},{question:"Why include contingencies?",options:["Conditions and system faults can change","To eliminate maintenance","To avoid decisions","To make data unnecessary"],answer:0},{question:"Should irrigation plans be revised?",options:["Yes, when evidence supports change","Never","Only when AI says so","Only after crop failure"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Which is a pathway of water loss?",options:["Runoff","Root uptake only","Planting date","Crop label"],answer:0},{question:"What unit can measure irrigation volume?",options:["Litre","Metre","Second only","Degree"],answer:0},{question:"What is needed for a simple flow estimate?",options:["Volume and time","Colour and height","Crop variety only","Price only"],answer:0},{question:"Why compare irrigation methods?",options:["Their suitability, cost and loss potential differ","One method is always best","To avoid maintenance","To remove trade-offs"],answer:0},{question:"What should influence irrigation timing?",options:["Crop stage, soil condition and weather","Habit only","Brand of hose","AI alone"],answer:0},{question:"Which action can reduce evaporation?",options:["Appropriate mulch","Increasing leaks","Overwatering","Removing all surface cover"],answer:0},{question:"How should AI irrigation advice be treated?",options:["Checked against local evidence and safety","Used automatically","Treated as sensor data","Used instead of observation"],answer:0},{question:"What makes a water-saving intervention credible?",options:["Baseline evidence and monitoring","A slogan","No measurements","Guaranteed claims"],answer:0}],theory:["Draw a water-pathway diagram for a garden and explain three possible water losses.","Explain how you would measure water applied during one irrigation event.","Compare two irrigation methods using at least four criteria and explain one trade-off.","Describe how soil condition, weather and crop stage can affect irrigation timing.","Design one water-saving improvement and explain how you would check that it saves water without harming crop performance."],practical:"Complete a supervised Water-Smart Growing Investigation. Record one irrigation input, compare at least two delivery or management options, identify one avoidable loss, develop a simple schedule rule, propose one improvement, and present monitoring indicators, safety controls and limitations."},
  evidence:["Water Pathway Map","Water Use Record","Irrigation Method Decision Matrix","Irrigation Decision Log","Water-Loss Audit","Water-Saving Action Plan","Water-Smart Growing Plan","Facilitator practical assessment record"],
  passport:["K: explains crop water needs, water pathways, irrigation methods and scheduling principles","P: measures simple irrigation inputs and conducts supervised water-loss observations","D: records volume/time data, compares options and critiques AI irrigation recommendations","S: follows safe water handling, slip/trip prevention and electrical/pump boundaries","E: links water efficiency, maintenance and reliability to production decisions","L: explains trade-offs, collaborates on irrigation plans and revises decisions using evidence"],
  trainerNotes:["Keep water conservation tied to crop adequacy; do not reward under-watering as 'efficiency'.","Use safe low-pressure demonstrations where possible.","Do not require learners to operate pumps, repair electrical equipment or enter hazardous water structures.","Where weather data are unavailable, use facilitator-provided scenarios rather than inventing precision.","Distinguish measured water use from estimated use in all records.","Enterprise discussion should focus on resource efficiency and operating decisions, not commercial selling by minors."],
  remediation:"Use two containers with the same crop and measured water volumes. Compare a direct targeted application with a deliberately less controlled method, record visible runoff or wetting differences, and explain one safe improvement.",
  extension:"Design a two-week irrigation comparison using two safe management strategies. Specify equal crop conditions, measured water inputs, one plant-response indicator, one water-loss indicator, assumptions and a decision rule for choosing the better approach.",
  imagePrompts:["Photorealistic African learners ages 11–14 in a supervised school garden measuring irrigation water with graduated containers beside vegetable beds and a simple low-pressure drip demonstration, safe environment, natural daylight, no readable text.","Educational systems illustration showing rainfall and irrigation entering a garden bed, with arrows for infiltration, root uptake, transpiration, evaporation, runoff and drainage, clean scientific visual, no readable text.","Photorealistic side-by-side school demonstration comparing watering can application and simple drip irrigation on equal vegetable beds, measuring containers and observation clipboard visible, no hazardous equipment, no readable text."]
};

export const pe04ByLanguage: Partial<Record<AppLanguage,PE04Module>> = { en };
export function getPE04(language:AppLanguage):PE04Module { return pe04ByLanguage[language] ?? en; }
