import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "../pathways-foundation/pf-01";

type PE06Module = Omit<PF01Module,"code"> & { code:"PE-06" };

const en: PE06Module = {
  code:"PE-06",
  title:"Food Hygiene and Processing",
  level:"Pathways Explorer",
  age:"Approximately 11–14 years; all food handling must be supervised and limited to low-risk school activities.",
  duration:"6 guided lessons plus a supervised food-hygiene and processing investigation and assessment",
  fieldworkHours:4,
  bigQuestion:"How can we handle and process food safely while protecting quality and reducing avoidable waste?",
  whyItMatters:"Food can become unsafe or lose quality when hands, water, surfaces, tools, storage conditions or handling practices are poor. Learners explore contamination pathways, personal hygiene, cleaning and sanitation, simple processing steps, time–temperature awareness, packaging and traceability. The module develops practical food-literacy and enterprise thinking without asking minors to undertake commercial production or high-risk processing.",
  outcomes:[
    "Explain common contamination pathways in simple food-handling systems.",
    "Demonstrate correct handwashing and safe preparation-area setup.",
    "Distinguish cleaning from sanitizing and explain why both may matter.",
    "Map a simple food-processing flow from raw material to finished product.",
    "Identify critical hygiene and quality checks at each processing step.",
    "Use basic records for batches, dates, ingredients and observations.",
    "Compare simple packaging and storage choices using safety, quality and waste criteria.",
    "Use AI or digital tools to organize procedures or checklists while verifying all food-safety advice against facilitator-approved guidance."
  ],
  vocabulary:["hygiene","contamination","cross-contamination","cleaning","sanitizing","raw material","processing","batch","quality","storage","temperature","packaging","label","traceability","waste","inspection","procedure","record","allergen","shelf life"],
  materials:["soap and safe handwashing station","clean water","disposable paper towels or approved drying method","clean washable work surfaces","food-safe utensils for supervised low-risk tasks","separate trays or containers","sample packaging materials","batch-record template","process-flow cards","thermometer demonstration where appropriate and facilitator-controlled","optional digital checklist tool"],
  safety:[
    "Use only facilitator-approved low-risk foods and activities; do not conduct canning, pressure processing, fermentation control, meat processing or other higher-risk preservation as learner practical work.",
    "Wash hands correctly before handling food and after contamination risks such as touching waste, soil, face or unclean surfaces.",
    "Keep raw and ready-to-eat foods separated where relevant to the activity.",
    "Do not taste food that has been used for experiments, temperature-abuse demonstrations or unknown-storage examples.",
    "Knives, heat sources, electrical appliances and chemicals must be handled only according to age, supervision and site safety rules; substitute pre-cut ingredients where needed.",
    "Food allergies and dietary restrictions must be checked before any tasting activity; participation in tasting must never be required.",
    "AI-generated food-safety temperatures, shelf-life claims or processing instructions must not be used without approved authoritative guidance."
  ],
  lessons:[
    {id:"PE-06-L1",title:"How Food Becomes Contaminated",objective:"Identify common contamination routes and explain how safe handling interrupts them.",teaching:["Contamination can move from hands, water, surfaces, tools, pests, waste or other foods.","Cross-contamination happens when contamination is transferred from one place or food to another.","Good hygiene uses barriers such as handwashing, separation, clean equipment and controlled storage."],activity:"Trace contamination routes through illustrated food-preparation scenarios and mark where a control could break each route.",diy:"Create a Contamination Pathway Map with at least six risks and matching controls.",aiLayer:"AI Layer 1 — Hazard identification: compare an AI-generated list of food-hygiene risks with the classroom scenario and remove hazards not supported by the actual situation while adding any observed risks the AI missed.",enterprise:"Food businesses depend on customer trust; poor hygiene can create waste, complaints, illness risk and reputational damage.",quiz:[{question:"What is cross-contamination?",options:["Transfer of contamination from one place or food to another","A type of crop","A packaging colour","A pricing method"],answer:0},{question:"Which can reduce contamination risk?",options:["Handwashing and clean tools","Using dirty water","Mixing waste with food","Ignoring surfaces"],answer:0},{question:"Why are hygiene controls important?",options:["They help interrupt contamination pathways","They guarantee every food lasts forever","They replace supervision","They make records unnecessary"],answer:0}]},
    {id:"PE-06-L2",title:"Clean Hands, Clean Surfaces, Safe Setup",objective:"Demonstrate personal hygiene and organize a safer preparation area.",teaching:["Effective handwashing uses soap, safe water, friction, rinsing and hygienic drying.","Cleaning removes visible dirt and food residues; sanitizing reduces microorganisms on already-clean food-contact surfaces when an approved method is required.","A work area should separate clean utensils, ingredients, waste and completed food to reduce recontamination."],activity:"Practise correct handwashing and arrange a mock preparation station into CLEAN / IN USE / WASTE zones using empty containers and utensils.",diy:"Develop a Pre-Processing Hygiene Checklist for hands, clothing, surfaces, utensils, water, waste and ingredient condition.",aiLayer:"AI Layer 2 — Procedure checking: compare an AI-generated hygiene checklist with the site's approved procedure and flag missing, excessive or unsafe steps.",enterprise:"Standard hygiene checklists help workers produce more consistently and reduce preventable loss.",quiz:[{question:"What does cleaning primarily remove?",options:["Dirt and food residues","Every possible microorganism automatically","Only labels","Heat"],answer:0},{question:"When is sanitizing most effective?",options:["After proper cleaning when required by the approved procedure","Instead of cleaning visible dirt","On food itself without guidance","Only after packaging"],answer:0},{question:"Why separate waste from clean food areas?",options:["To reduce recontamination","To increase clutter","To make work slower","It has no purpose"],answer:0}]},
    {id:"PE-06-L3",title:"From Raw Ingredient to Process Flow",objective:"Sequence a simple low-risk processing operation and identify checks at each step.",teaching:["Processing changes a raw ingredient through steps such as sorting, washing, peeling or cutting, mixing, heating where appropriate, cooling, portioning and packaging.","Each step should have a purpose and a hygiene or quality check.","A process flow helps teams see where errors, delays or contamination could occur."],activity:"Arrange process cards for a facilitator-approved example such as fruit preparation or a simple non-hazardous drink demonstration and add one check to each stage.",diy:"Create a Process Flow Chart showing RAW MATERIAL → PREPARATION → PROCESS → PACK → STORE, with one control at every stage.",aiLayer:"AI Layer 3 — Sequence review: ask AI for a generic process flow, then compare it against the actual school method and correct unsafe or irrelevant steps.",enterprise:"Process mapping helps small enterprises train workers, estimate time and standardize product quality.",quiz:[{question:"Why create a process flow?",options:["To show the sequence of work and checks","To avoid hygiene","To hide ingredients","To guarantee profit"],answer:0},{question:"What should each step have?",options:["A clear purpose and appropriate check","No purpose","A marketing slogan only","A private password"],answer:0},{question:"Should a generic AI process replace the approved school procedure?",options:["No","Yes always","Only if longer","Only if technical"],answer:0}]},
    {id:"PE-06-L4",title:"Time, Temperature and Storage Awareness",objective:"Explain why time and storage conditions affect food safety and quality without performing high-risk temperature control tasks.",teaching:["Many foods change over time, and some require controlled temperatures to stay safe.","A thermometer can provide evidence about temperature, but correct limits depend on the specific food and approved food-safety guidance.","Storage areas should protect food from contamination, pests, moisture, heat or damage as relevant."],activity:"Compare illustrated storage scenarios and rank them using cleanliness, protection, time and temperature-awareness criteria.",diy:"Create a Safe Storage Decision Card that asks: WHAT FOOD? HOW LONG? WHAT TEMPERATURE CONTROL IS REQUIRED? HOW IS IT PROTECTED? WHAT GUIDANCE APPLIES?",aiLayer:"AI Layer 4 — Claim verification: examine AI-generated storage or shelf-life advice and identify which details must be verified against authoritative local or product-specific guidance.",enterprise:"Poor storage creates spoilage, waste and customer risk; good records and stock rotation support quality and cost control.",quiz:[{question:"Why can time matter in food storage?",options:["Food quality and safety can change over time","Time never matters","Only packaging colour matters","It replaces hygiene"],answer:0},{question:"What does a thermometer provide?",options:["A temperature measurement","A shelf-life guarantee","A contamination diagnosis","A price"],answer:0},{question:"How should AI shelf-life claims be treated?",options:["Verified before use","Accepted automatically","Used without product details","Treated as a legal standard"],answer:0}]},
    {id:"PE-06-L5",title:"Packaging, Labels and Traceability",objective:"Explain how packaging and simple records support protection, information and traceability.",teaching:["Packaging can protect food from handling, contamination, moisture loss or physical damage depending on the product.","Labels can communicate product identity, ingredients, dates and other required information, but exact legal requirements vary by jurisdiction.","Traceability means being able to connect a product or sample to its ingredients, batch and handling records."],activity:"Compare three sample packaging options for a dry or low-risk food using protection, material use, closure, visibility and waste criteria.",diy:"Create a mock Batch Record containing batch code, date, ingredient list, process steps, checks and disposition; do not invent regulatory approvals or commercial certifications.",aiLayer:"AI Layer 5 — Label review: use AI to suggest informational fields, then separate general recordkeeping ideas from claims or legal requirements that need authoritative verification.",enterprise:"Packaging and traceability support quality assurance, customer communication and problem investigation, while excessive packaging can increase cost and waste.",quiz:[{question:"What is traceability?",options:["Ability to connect a product to its batch and records","A guarantee of long shelf life","A logo design","A pricing strategy"],answer:0},{question:"What is one role of packaging?",options:["Protecting food from damage or contamination","Replacing hygiene","Guaranteeing safety forever","Eliminating storage"],answer:0},{question:"Should learners invent regulatory approvals on mock labels?",options:["No","Yes","Only if the package looks professional","Only for school projects"],answer:0}]},
    {id:"PE-06-L6",title:"Run a Safe Mini Processing System",objective:"Integrate hygiene, process flow, records, quality checks and waste reduction in a supervised low-risk activity.",teaching:["A controlled process begins with preparation, approved ingredients and clear roles.","Quality checks can include cleanliness, appearance, measured quantity, packaging closure or completion of records, depending on the product.","After processing, teams should review what went well, what waste occurred and what control should be improved next time."],activity:"Teams complete a supervised low-risk processing simulation or preparation activity using a written hygiene checklist, process flow and batch record.",diy:"Complete a Mini Processing Evidence Pack: hygiene checklist, process flow, batch record, quality check, waste log and improvement note.",aiLayer:"Integration — process improvement: ask AI for three efficiency ideas, then reject any suggestion that weakens hygiene, safety, traceability or evidence requirements.",enterprise:"Reliable small-scale processing requires repeatable procedures, records, quality checks and waste awareness before marketing is considered.",quiz:[{question:"What should happen before processing starts?",options:["Prepare the hygienic work area and approved materials","Skip checks","Package first","Delete records"],answer:0},{question:"Why keep a waste log?",options:["To identify avoidable losses and improvement opportunities","To guarantee zero waste","To replace a batch record","To hide mistakes"],answer:0},{question:"What should happen to an efficiency idea that reduces hygiene?",options:["Reject it","Use it immediately","Use it if cheaper","Use it if AI generated it"],answer:0}]}
  ],
  finalAssessment:{
    mcq:[
      {question:"What is cross-contamination?",options:["Transfer of contamination from one food, surface or source to another","A packaging defect only","A price change","A crop disease"],answer:0},
      {question:"What is the difference between cleaning and sanitizing?",options:["Cleaning removes residues; sanitizing reduces microorganisms on already-clean surfaces when required","They are always identical","Sanitizing replaces cleaning","Cleaning is only for floors"],answer:0},
      {question:"Why use a process flow?",options:["To show steps, checks and possible failure points","To avoid records","To guarantee sales","To replace supervision"],answer:0},
      {question:"Why can storage temperature matter?",options:["Some foods require controlled temperatures for safety or quality","Temperature never matters","It only changes package colour","It replaces hygiene"],answer:0},
      {question:"What does a batch record support?",options:["Traceability and process documentation","A shelf-life guarantee","Advertising only","Password storage"],answer:0},
      {question:"Which statement about packaging is best?",options:["It should protect the product while considering material use and waste","More packaging is always better","Packaging replaces sanitation","Packaging guarantees safety forever"],answer:0},
      {question:"How should AI food-safety advice be used?",options:["Only after checking against approved authoritative guidance","As automatic operational instructions","As a legal standard","Instead of supervision"],answer:0},
      {question:"What is a useful process-improvement principle?",options:["Reduce avoidable loss without weakening hygiene or safety","Remove records to save time","Skip handwashing if busy","Use unknown ingredients to cut costs"],answer:0}
    ],
    theory:[
      "Draw a contamination pathway for a simple food-preparation activity and explain four controls that could interrupt it.",
      "Explain the difference between cleaning and sanitizing and why cleaning comes first when visible residues are present.",
      "Create a five-step process flow for a low-risk food or beverage activity and identify one hygiene or quality check at each step.",
      "Explain how packaging, batch records and traceability work together to support food quality and problem investigation.",
      "Describe one appropriate use of AI in a food-processing workflow and two kinds of food-safety information that must be verified independently."
    ],
    practical:"Complete a supervised low-risk food-processing or simulation task. Demonstrate correct hand hygiene, set up a clean work area, follow a process flow, prevent cross-contamination, complete a batch record, perform at least two quality checks, document waste and propose one improvement that does not weaken food safety."
  },
  evidence:["Contamination Pathway Map","Pre-Processing Hygiene Checklist","Process Flow Chart","Safe Storage Decision Card","Mock Batch Record","Packaging comparison sheet","Mini Processing Evidence Pack","Facilitator practical assessment record"],
  passport:[
    "K: explains contamination, cleaning, sanitation, storage, packaging and traceability concepts",
    "P: demonstrates supervised hygienic setup and follows a low-risk processing sequence",
    "D: completes batch and quality records and critiques AI-generated food-safety claims",
    "S: applies hand hygiene, separation, allergen awareness and age-appropriate tool/heat boundaries",
    "E: connects standard procedures, waste reduction, packaging and quality to responsible enterprise operations",
    "L: works in assigned roles, checks peers respectfully and recommends evidence-based process improvements"
  ],
  trainerNotes:[
    "Use low-risk school food activities and local public-health or food-safety guidance appropriate to the jurisdiction.",
    "Do not turn this module into informal commercial food production by minors.",
    "Where heat or sharp tools are unnecessary, use pre-cut ingredients or simulations to keep the focus on hygiene systems.",
    "Avoid teaching exact shelf-life or critical temperature numbers unless they come from current authoritative guidance for the specific food and context.",
    "If tasting is allowed, check allergies and permissions and maintain an equivalent non-tasting learning pathway.",
    "Rotate hygiene lead, recorder, process checker and quality observer roles so all learners practise different competencies."
  ],
  remediation:"Use a picture-based preparation sequence with four steps. Learner demonstrates handwashing, identifies one contamination risk at each step, and completes a simplified batch record with date, ingredients and check boxes before returning to the full process task.",
  extension:"Learners compare two packaging systems for the same low-risk product using protection, material mass, reusability/recyclability, cost assumptions and traceability needs, then defend a recommendation without making unsupported shelf-life claims.",
  imagePrompts:[
    "Photorealistic African learners ages 11–14 in a supervised school food laboratory washing hands and preparing a clean work surface, soap, clean water, separate trays and covered ingredients visible, inclusive boys and girls, no readable text.",
    "Clean educational illustration showing a simple food-processing flow from raw ingredient to washing, preparation, processing, packaging and storage with hygiene-control icons and arrows, no readable text.",
    "Photorealistic supervised classroom processing station with colour-separated clean utensils, ingredient tray, waste container, batch-record clipboard and simple food-safe packaging materials, no branding, no readable text."
  ]
};

export const pe06ByLanguage: Partial<Record<AppLanguage,PE06Module>> = { en };
export function getPE06(language:AppLanguage):PE06Module { return pe06ByLanguage[language] ?? en; }
