import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "../pathways-foundation/pf-01";

type PE09Module = Omit<PF01Module,"code"> & { code:"PE-09" };

const en: PE09Module = {
  code:"PE-09", title:"Digital Records", level:"Pathways Explorer", age:"Approximately 11–14 years; digital tools should be used with supervision and without exposing personal or sensitive data.", duration:"6 guided lessons plus a supervised digital-record project and assessment", fieldworkHours:3,
  bigQuestion:"How can we collect, organize, protect and use digital records so they remain accurate, useful and safe?",
  whyItMatters:"Digital records support learning, gardens, food production, water management, maintenance and enterprise operations. Their value depends on data quality, consistent structure, traceability, privacy and responsible interpretation. Learners move from paper observations to simple digital tables, learn basic validation and file organization, create charts, and use AI only as an assistant for checking and interpretation—not as a source of invented data.",
  outcomes:["Explain why records need a clear purpose, consistent fields and units.","Convert a paper observation sheet into a structured digital table.","Enter, sort and filter simple records accurately.","Recognize missing, duplicate, inconsistent and implausible values.","Create a basic chart from a suitable dataset and describe the pattern without overstating causation.","Use clear file names, dates and version practices for traceability.","Apply privacy and data-minimization principles to learner-facing records.","Use AI or digital tools to check structure and summarize data while preserving source evidence and human verification."],
  vocabulary:["record","data","field","row","column","table","dataset","entry","validation","missing value","duplicate","filter","sort","chart","file name","version","backup","privacy","traceability","metadata"],
  materials:["paper garden or activity records","computers or tablets where available","facilitator-approved spreadsheet tool","sample datasets","offline templates if internet is unavailable","notebooks","projector optional","USB or local storage managed by facilitator where permitted","optional AI tool using non-sensitive sample data"],
  safety:["Do not enter home addresses, phone numbers, passwords, health information, safeguarding details or other sensitive personal data in learner practice datasets.","Use only facilitator-approved devices, accounts and storage locations.","Never share passwords or authentication tokens in a worksheet, screenshot or AI prompt.","Do not upload identifiable learner data to public AI or online tools unless the organization has explicitly approved that workflow.","Keep original evidence when correcting records; do not silently invent or overwrite missing observations.","Report suspicious links, unexpected login requests or device warnings to an adult facilitator."],
  lessons:[
    {id:"PE-09-L1",title:"What Makes a Good Record?",objective:"Define the purpose, fields, units and evidence source for a useful record.",teaching:["A record should answer a clear operational or learning question.","Fields describe what is recorded; entries should use consistent formats and units.","Good records are traceable to an observation, measurement or authorized source."],activity:"Compare three sample garden records and identify which fields are clear, ambiguous or missing.",diy:"Create a Record Design Card with PURPOSE → REQUIRED FIELDS → UNITS → SOURCE → WHO USES IT.",aiLayer:"AI Layer 1 — Schema check: ask AI to suggest fields for a sample garden log, then remove unnecessary or sensitive fields and justify the final structure.",enterprise:"Clear records support stock control, quality checks, maintenance, planning and accountability.",quiz:[{question:"What should a record have first?",options:["A clear purpose","A decorative title only","As many fields as possible","No units"],answer:0},{question:"Why use consistent units?",options:["To make entries comparable","To make data longer","To hide errors","To avoid measurement"],answer:0},{question:"What makes a record traceable?",options:["A clear source and date","A guess","No source","AI-generated values"],answer:0}]},
    {id:"PE-09-L2",title:"Build a Digital Table",objective:"Convert observations into a structured digital table.",teaching:["Rows usually represent individual records while columns represent fields.","Dates and units should follow one agreed format.","Each row should represent one complete observation or transaction type defined by the table."],activity:"Enter a small paper dataset into a spreadsheet with fields such as date, plot ID, plant height, unit and note.",diy:"Create a 10-row Digital Garden Log from facilitator-provided or learner-collected non-sensitive records.",aiLayer:"AI Layer 2 — Structure review: compare the table with an AI-suggested structure and retain only changes that improve clarity without altering source values.",enterprise:"Structured tables make stock, production and service records easier to search and summarize.",quiz:[{question:"What does a spreadsheet column usually represent?",options:["A field","A complete dataset always","A password","A chart only"],answer:0},{question:"Why standardize date format?",options:["To reduce ambiguity","To create more rows","To remove traceability","To hide errors"],answer:0},{question:"Should source values be changed just to match an AI suggestion?",options:["No","Yes","Always","Only when convenient"],answer:0}]},
    {id:"PE-09-L3",title:"Check Data Quality",objective:"Identify and handle common data-quality problems without inventing corrections.",teaching:["Common problems include missing values, duplicates, impossible values, inconsistent units and typing mistakes.","Validation checks flag suspicious entries but do not automatically prove the correct value.","Corrections should be traceable to source evidence; otherwise the value should remain missing or flagged."],activity:"Audit a prepared dataset containing five planted data-quality errors and document each issue and proposed action.",diy:"Complete a Data Quality Checklist: MISSING → DUPLICATE → FORMAT → RANGE → UNIT → SOURCE CHECK.",aiLayer:"AI Layer 3 — Error detection: let AI inspect a non-sensitive sample table for anomalies, then verify every flagged issue manually against the source sheet.",enterprise:"Poor data can create wrong orders, incorrect costing, stock losses and weak operational decisions.",quiz:[{question:"What should happen when a value has no supporting evidence?",options:["Leave it missing or flagged","Invent a likely value","Copy another row","Ask AI to guess"],answer:0},{question:"Is every unusual value necessarily wrong?",options:["No","Yes","Always","Only if large"],answer:0},{question:"Why check duplicates?",options:["They can distort totals and counts","They improve accuracy automatically","They replace missing data","They are required"],answer:0}]},
    {id:"PE-09-L4",title:"Sort, Filter and Summarize",objective:"Use simple spreadsheet functions to find and summarize relevant records.",teaching:["Sorting changes the order of records; filtering temporarily shows records meeting selected conditions.","Simple totals, counts or averages can summarize data when appropriate.","A summary is only meaningful if the underlying records are valid and the calculation fits the question."],activity:"Sort a sample garden log by date, filter one plot or crop, and calculate a simple count or average using facilitator guidance.",diy:"Produce a one-page Digital Summary with one filtered table and two calculated indicators.",aiLayer:"AI Layer 4 — Calculation verification: compare spreadsheet results with calculator or AI checks and investigate discrepancies.",enterprise:"Filters and summaries help teams review sales, stock, maintenance and production without reading every row manually.",quiz:[{question:"What does filtering do?",options:["Shows records meeting selected conditions","Deletes all other data","Changes every value","Creates passwords"],answer:0},{question:"What does sorting do?",options:["Changes record order","Changes source measurements","Removes missing values","Creates a chart automatically"],answer:0},{question:"When is an average useful?",options:["When it fits the data and question","For every dataset","When values are invented","Without units"],answer:0}]},
    {id:"PE-09-L5",title:"Charts and Evidence",objective:"Choose a simple chart and describe what it shows without claiming unsupported causes.",teaching:["Charts can make patterns easier to see but do not improve bad source data.","Line charts are useful for change over ordered time; bar charts are useful for comparing categories.","A visible pattern does not by itself prove why it occurred."],activity:"Create one chart from a clean sample dataset and write three evidence statements that include actual values or categories.",diy:"Make a Chart Evidence Card with QUESTION → CHART TYPE → DATA SOURCE → PATTERN → LIMITATION.",aiLayer:"AI Layer 5 — Interpretation check: ask AI to summarize the chart, then mark any statements that imply unsupported causation or omit uncertainty.",enterprise:"Clear visual summaries can support meetings and decisions, but misleading charts can create poor decisions.",quiz:[{question:"Which chart often suits change over time?",options:["Line chart","Random icon","Password table","No chart"],answer:0},{question:"Does a chart prove cause?",options:["No","Yes","Always","Only if colourful"],answer:0},{question:"What should a chart description cite?",options:["Actual evidence from the data","A guess","Only AI text","No values"],answer:0}]},
    {id:"PE-09-L6",title:"Protect and Trace Digital Records",objective:"Apply safe file naming, versioning, backup and privacy practices.",teaching:["Useful file names identify subject, date or version without exposing sensitive personal data.","Version control helps teams know which file is current and what changed.","Data minimization means collecting only what is necessary for the stated purpose."],activity:"Reorganize a messy fictional folder into a clear naming and version structure, identifying files that contain unnecessary personal information.",diy:"Create a Digital Records Protocol covering FILE NAME → VERSION → STORAGE → BACKUP → ACCESS → PRIVACY → CORRECTION RULE.",aiLayer:"Integration — governance check: compare the protocol with an AI-generated checklist and reject any suggestion that weakens privacy, traceability or source preservation.",enterprise:"Reliable file practices reduce lost work, duplicate versions and confidentiality mistakes.",quiz:[{question:"What is data minimization?",options:["Collecting only data needed for the purpose","Collecting everything possible","Deleting all records","Sharing all files"],answer:0},{question:"Why use version names?",options:["To identify which file is current and trace changes","To hide files","To remove dates","To replace backups"],answer:0},{question:"Should passwords be stored in learner data tables?",options:["No","Yes","Always","Only for convenience"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"What gives a record meaning?",options:["A clear purpose and defined fields","Many colours","A large file","No source"],answer:0},{question:"What should happen to a missing value with no source evidence?",options:["Leave it missing or flagged","Invent it","Copy another value","Ask AI to fill it"],answer:0},{question:"What does a filter do?",options:["Shows records matching criteria","Deletes the dataset","Changes every value","Creates a password"],answer:0},{question:"What can duplicates affect?",options:["Counts and totals","Only colours","Only file names","Nothing"],answer:0},{question:"Which chart often suits change over time?",options:["Line chart","Pie chart always","No chart","Image only"],answer:0},{question:"What is versioning for?",options:["Tracing which file is current and what changed","Hiding mistakes","Replacing backups","Removing dates"],answer:0},{question:"What is data minimization?",options:["Collecting only necessary information","Collecting all personal details","Publishing records","Deleting evidence"],answer:0},{question:"How should AI be used with records?",options:["To assist checking and interpretation while source evidence remains primary","To invent missing values","To replace privacy rules","To overwrite source data"],answer:0}],theory:["Explain how you would design a digital garden record from a paper observation sheet.","Describe four common data-quality problems and how each should be handled.","Explain the difference between sorting and filtering and give one practical use for each.","Describe how to choose between a line chart and bar chart and state one limitation of charts.","Write a simple protocol for naming, storing, versioning and protecting a shared digital record."],practical:"Create a supervised Digital Records Pack from a non-sensitive sample or field dataset. Define the purpose and fields, enter at least 10 records, apply consistent units and dates, perform a documented quality check, use one filter or sort, calculate one appropriate indicator, create one chart, and save the file using an approved name/version structure with a short privacy and traceability note."},
  evidence:["Record Design Card","10-row Digital Garden Log","Data Quality Checklist","Digital Summary","Chart Evidence Card","Digital Records Protocol","Final Digital Records Pack","Facilitator practical assessment record"],
  passport:["K: explains records, fields, validation, filtering, charting, versioning and privacy","P: creates and maintains a simple structured digital table","D: checks data quality, performs simple summaries and critiques AI interpretations","S: protects credentials, personal data and approved storage boundaries","E: connects reliable records to inventory, quality, maintenance and operational decisions","L: documents corrections, preserves traceability and communicates evidence limitations"],
  trainerNotes:["Use non-sensitive practice datasets and keep privacy examples concrete.","Do not require cloud accounts where offline spreadsheets or paper-to-digital practice are more appropriate.","Teach that 'cleaning' data does not mean replacing inconvenient observations.","Model file naming with dates and versions rather than personal names where unnecessary.","Require chart titles/labels in actual implementation where the interface supports them, but keep assessment focused on interpretation and data integrity.","Enterprise examples should focus on operations and employability skills rather than commercial activity by minors."],
  remediation:"Use a five-row paper table. Learner enters it digitally, checks units and dates, finds one planted error, filters one category and saves the file with an approved name.",
  extension:"Create a reusable spreadsheet template with dropdown validation or protected headers where available, then document how the template reduces errors and what risks it does not solve.",
  imagePrompts:["Photorealistic African learners ages 11–14 using supervised tablets and laptops beside a school garden, transferring non-sensitive plant measurements from paper sheets into a simple spreadsheet, inclusive group, no readable screen text.","Clean educational illustration of digital record flow: field observation, paper note, structured table, validation check, chart, secure storage, simple icons and arrows, no readable text.","Photorealistic classroom data-quality workshop with African adolescents comparing paper records and a spreadsheet on a projected screen, facilitator supervising, privacy-safe environment, no readable personal data."]
};

export const pe09ByLanguage: Partial<Record<AppLanguage,PE09Module>> = { en };
export function getPE09(language:AppLanguage):PE09Module { return pe09ByLanguage[language] ?? en; }
