import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "../pathways-foundation/pf-01";

type PE10Module = Omit<PF01Module,"code"> & { code:"PE-10" };

const en: PE10Module = {
  code:"PE-10", title:"Problem Solving", level:"Pathways Explorer", age:"Approximately 11–14 years; use safe, age-appropriate school, garden, food, water and energy challenges.", duration:"6 guided lessons plus a supervised problem-solving challenge and assessment", fieldworkHours:3,
  bigQuestion:"How can we define a real problem, investigate its causes, generate options, test a solution and improve it using evidence?",
  whyItMatters:"Strong problem solving is more than choosing the first idea. Learners need to describe a problem clearly, gather evidence, distinguish symptoms from causes, generate alternatives, compare constraints, test safely, learn from results and communicate what changed. These habits support learning, technical work, teamwork and future enterprise.",
  outcomes:["Write a clear problem statement based on observable evidence.","Separate symptoms, causes, constraints and stakeholder needs.","Generate multiple solution options before selecting one.","Compare options using criteria such as safety, cost, effort, benefit and feasibility.","Design a small safe test with a success indicator.","Record results and distinguish evidence from opinion.","Revise a solution after testing rather than treating failure as final.","Use AI for idea generation and critique while verifying suggestions against local evidence and safety."],
  vocabulary:["problem","symptom","cause","constraint","criterion","evidence","option","prototype","test","indicator","result","iteration","trade-off","assumption","stakeholder","feasibility","priority","decision","reflection","improvement"],
  materials:["problem scenario cards","large paper","markers","sticky notes","comparison matrix sheets","simple prototyping materials such as cardboard, string and containers","measuring tools appropriate to the chosen challenge","record sheets","optional calculator or AI tool"],
  safety:["Choose only facilitator-approved problems and tests that can be completed without hazardous tools, chemicals, mains electricity or unsafe food handling.","Do not test solutions on people without appropriate consent and supervision.","Protect personal information when problems involve learners, families or community members.","Stop any trial that creates physical, food-safety, electrical, environmental or safeguarding concerns.","AI-generated solutions must be screened for age appropriateness, feasibility and safety before consideration.","Learners should never bypass established safety controls to make a prototype work."],
  lessons:[
    {id:"PE-10-L1",title:"Define the Real Problem",objective:"Turn a vague complaint into a specific evidence-based problem statement.",teaching:["A useful problem statement describes what is happening, where, when, who or what is affected and what evidence exists.","A symptom is not automatically the root cause.","Good problem statements avoid blaming people before causes are investigated."],activity:"Rewrite vague statements such as 'the garden is bad' into precise statements using observations and measurements.",diy:"Create a Problem Definition Card using WHAT → WHERE → WHEN → EVIDENCE → IMPACT → UNKNOWN.",aiLayer:"AI Layer 1 — Framing critique: compare the learner problem statement with an AI rewrite and reject wording that invents facts or assumes a cause.",enterprise:"Clear problem definitions reduce wasted effort and help teams focus resources on what actually needs improvement.",quiz:[{question:"What belongs in a strong problem statement?",options:["Observable evidence","An invented cause","A guaranteed solution","A slogan"],answer:0},{question:"Is a symptom always the cause?",options:["No","Yes","Always","Only in gardens"],answer:0},{question:"Why avoid blame early?",options:["Causes should be investigated with evidence","Blame is faster","Evidence is unnecessary","It guarantees agreement"],answer:0}]},
    {id:"PE-10-L2",title:"Investigate Causes and Constraints",objective:"Identify plausible causes, constraints and stakeholder needs before proposing solutions.",teaching:["Possible causes should be treated as hypotheses until evidence supports them.","Constraints may include time, safety, budget, space, materials, rules or skills.","Stakeholders can value different outcomes, so needs should be identified explicitly."],activity:"Use a cause-and-evidence map for a scenario such as low seedling survival or excessive water use.",diy:"Complete a Cause–Constraint Sheet with at least three possible causes, evidence needed for each and five relevant constraints.",aiLayer:"AI Layer 2 — Hypothesis generation: ask AI for additional possible causes, then classify them as plausible, unsupported or unsafe to investigate.",enterprise:"Ignoring constraints can make a technically attractive solution unusable in practice.",quiz:[{question:"What is a hypothesis?",options:["A possible explanation to test","A proven fact","A final answer","A price"],answer:0},{question:"Which can be a constraint?",options:["Time","Only colour","Only opinion","Nothing"],answer:0},{question:"Why identify stakeholders?",options:["Different people may have different needs","Only one person matters","It removes evidence","It guarantees agreement"],answer:0}]},
    {id:"PE-10-L3",title:"Generate More Than One Option",objective:"Use divergent thinking to create several possible responses before choosing.",teaching:["The first idea may be workable, but generating alternatives creates comparison and learning.","Ideas can change a process, tool, schedule, layout, information flow or behaviour.","Brainstorming is for generating possibilities; evaluation comes afterward."],activity:"Teams generate at least eight possible responses to one defined problem, then group similar ideas.",diy:"Create an Option Board with eight ideas and label each as process, design, behaviour, information or resource change.",aiLayer:"AI Layer 3 — Idea expansion: use AI for additional options, then remove suggestions that are unsafe, irrelevant, too costly or inconsistent with the problem evidence.",enterprise:"Innovation often comes from comparing several ways to deliver the same required outcome.",quiz:[{question:"Why generate several options?",options:["To enable comparison","To avoid decisions forever","Because every idea is good","To replace evidence"],answer:0},{question:"When should brainstorming ideas be judged?",options:["After initial generation","Before anyone speaks","Never","Only by AI"],answer:0},{question:"Can a solution change a process instead of buying equipment?",options:["Yes","No","Never","Only in business"],answer:0}]},
    {id:"PE-10-L4",title:"Choose with Criteria",objective:"Compare solution options using explicit decision criteria and trade-offs.",teaching:["Criteria make the basis of a decision visible.","Common criteria include safety, expected benefit, cost, time, maintainability, inclusion and environmental impact.","A decision matrix supports comparison but does not remove judgment or uncertainty."],activity:"Score three shortlisted options against agreed criteria and discuss why different teams may weight criteria differently.",diy:"Complete a Solution Decision Matrix and write one sentence explaining the main trade-off in the chosen option.",aiLayer:"AI Layer 4 — Decision audit: ask AI to challenge the selected option and identify one overlooked criterion or assumption.",enterprise:"Transparent criteria improve procurement, project selection and resource allocation.",quiz:[{question:"What is a decision criterion?",options:["A factor used to compare options","A guaranteed result","A random score","A solution itself"],answer:0},{question:"Does the highest matrix score always guarantee success?",options:["No","Yes","Always","Only if AI agrees"],answer:0},{question:"What is a trade-off?",options:["A benefit in one area may involve a cost elsewhere","A perfect solution","A measurement unit","A final grade"],answer:0}]},
    {id:"PE-10-L5",title:"Test Small and Learn",objective:"Design and run a safe small-scale test with clear indicators.",teaching:["A prototype or trial should test a specific assumption rather than attempt everything at once.","A success indicator states what evidence would suggest improvement.","A failed trial can still produce useful information if it was documented well."],activity:"Plan a low-risk test such as comparing two watering schedules on identical empty containers or two record-sheet layouts with sample data.",diy:"Write a Test Plan: ASSUMPTION → CHANGE → CONTROL/COMPARISON → INDICATOR → SAFETY → DATA → DURATION.",aiLayer:"AI Layer 5 — Test-design critique: ask AI what would make the test unfair or inconclusive, then improve the plan without adding unsafe procedures.",enterprise:"Small trials reduce risk before committing more time, materials or money.",quiz:[{question:"What should a small test examine?",options:["A specific assumption","Everything at once","A guaranteed outcome","No indicator"],answer:0},{question:"What is a success indicator?",options:["Evidence used to judge whether the change helped","A slogan","A price only","A random number"],answer:0},{question:"Can a failed trial still be useful?",options:["Yes, if it produces learning","No","Never","Only if hidden"],answer:0}]},
    {id:"PE-10-L6",title:"Improve and Communicate",objective:"Use test evidence to revise the solution and communicate the reasoning clearly.",teaching:["Iteration means making a change, testing, learning and revising.","Reports should distinguish what was observed, what was inferred and what remains uncertain.","A recommendation should include next steps and conditions under which it may need to change."],activity:"Teams review sample test results, decide whether to keep, modify or reject the solution and prepare a two-minute evidence briefing.",diy:"Complete a Problem-Solving Cycle: DEFINE → INVESTIGATE → OPTIONS → DECIDE → TEST → LEARN → IMPROVE → COMMUNICATE.",aiLayer:"Integration — reflection: compare the team conclusion with an AI-generated conclusion and identify unsupported claims, missing caveats or useful alternatives.",enterprise:"Continuous improvement is a core work and enterprise capability because operations rarely become perfect after one change.",quiz:[{question:"What is iteration?",options:["Testing, learning and revising","Repeating without learning","Avoiding evidence","Guaranteeing success"],answer:0},{question:"What should a report separate?",options:["Observation, inference and uncertainty","Evidence from decisions","Units from values","Safety from action"],answer:0},{question:"What should a recommendation include?",options:["Evidence and next steps","A guarantee","No limitations","Invented data"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"What makes a problem statement useful?",options:["Specific evidence","A guessed cause","A fixed solution","A slogan"],answer:0},{question:"What is a constraint?",options:["A condition that limits possible actions","A guaranteed benefit","A final answer","A chart type"],answer:0},{question:"Why generate multiple options?",options:["To compare alternatives","To delay forever","Because all are equal","To avoid criteria"],answer:0},{question:"What does a decision matrix do?",options:["Makes comparison criteria explicit","Guarantees the best outcome","Removes judgment","Creates evidence automatically"],answer:0},{question:"Why test on a small scale?",options:["To learn with lower risk and cost","To guarantee success","To avoid measurement","To skip safety"],answer:0},{question:"What is a success indicator?",options:["Evidence for judging a test","A product name","An opinion only","A password"],answer:0},{question:"What is iteration?",options:["Improve through repeated testing and learning","Do the same thing without checking","Stop after one attempt","Copy AI output"],answer:0},{question:"How should AI support problem solving?",options:["Generate and critique ideas that are then verified","Replace local evidence","Authorize unsafe tests","Guarantee decisions"],answer:0}],theory:["Write a strong problem statement for a real school, garden or community challenge.","Explain the difference among a symptom, possible cause and constraint.","Describe how you would compare three solution options fairly.","Design a small safe test for one proposed solution, including a success indicator.","Explain how evidence from a failed or mixed-result test can guide the next iteration."],practical:"Complete a supervised Problem-Solving Challenge. Define a real low-risk problem, gather evidence, map at least three possible causes, identify constraints and stakeholder needs, generate at least five options, compare three options with criteria, design or conduct one safe small-scale test, interpret results and present a revised recommendation with limitations."},
  evidence:["Problem Definition Card","Cause–Constraint Sheet","Option Board","Solution Decision Matrix","Test Plan","Problem-Solving Cycle record","Final Problem-Solving Challenge","Facilitator practical assessment record"],
  passport:["K: explains problem definition, causes, constraints, options, criteria, testing and iteration","P: constructs comparison tools and carries out supervised low-risk tests","D: records evidence, uses simple decision data and critiques AI suggestions","S: screens options and tests for physical, food, electrical, environmental and safeguarding risk","E: connects problem solving to operations, innovation, resource use and continuous improvement","L: collaborates, communicates reasoning, responds constructively to failure and revises decisions"],
  trainerNotes:["Select problems small enough to investigate within the learning environment.","Do not reward fast answers over careful evidence and safe testing.","Ensure all learners rotate through defining, measuring, ideating, testing and presenting roles.","Use failure as evidence; discourage hiding results that do not support the preferred idea.","Keep AI in a supporting role and require learners to label assumptions.","Enterprise links should remain age-appropriate and educational, not commercial recruitment."],
  remediation:"Use one simple classroom problem and a three-step scaffold: describe what is observed, list two possible causes, compare two safe options. Add testing only after the learner can separate evidence from assumptions.",
  extension:"Learners run a second iteration after changing one feature of the solution, compare first- and second-round evidence, and explain whether the improvement is large enough to justify adoption.",
  imagePrompts:["Photorealistic African learners ages 11–14 solving a school garden problem with observation sheets, sticky notes and a comparison matrix, inclusive teamwork, facilitator nearby, natural daylight, no readable text.","Educational problem-solving cycle illustration with visual icons for observe, investigate, generate options, compare, prototype, test, improve and communicate, clean white background, no readable text.","Photorealistic adolescent learner team testing a simple low-risk cardboard or water-management prototype in a school garden, rulers and notebooks visible, safe supervised setting, no readable text."]
};

export const pe10ByLanguage: Partial<Record<AppLanguage,PE10Module>> = { en };
export function getPE10(language:AppLanguage):PE10Module { return pe10ByLanguage[language] ?? en; }
