import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "../pathways-foundation/pf-01";

type PE11Module = Omit<PF01Module,"code"> & { code:"PE-11" };

const en: PE11Module = {
  code:"PE-11", title:"Skills and Careers", level:"Pathways Explorer", age:"Approximately 11–14 years; career exploration should remain broad, inclusive and non-deterministic.", duration:"6 guided lessons plus a supervised skills-and-careers exploration and assessment", fieldworkHours:2,
  bigQuestion:"What skills am I building now, where can they be used, and how can I explore future learning and work pathways responsibly?",
  whyItMatters:"Young people benefit from seeing how school, practical projects, digital literacy, teamwork and problem solving connect to real roles. This module helps learners recognize transferable skills, explore food-energy-water and green-economy roles, understand that occupations require different combinations of knowledge and practice, challenge stereotypes, identify safe learning pathways and create an evidence-based personal development plan.",
  outcomes:["Distinguish knowledge, practical, digital, safety, enterprise and life skills.","Identify transferable skills developed through Pathways Explorer modules.","Describe several roles across food, water, energy, digital, technical and community systems.","Match example tasks to relevant competencies rather than stereotypes.","Explain the difference among a job, occupation, career, enterprise and learning pathway.","Use evidence from personal work to identify current strengths and development needs.","Create a realistic short-term skills-development plan.","Use AI for career exploration while checking role descriptions against trusted local or occupational sources."],
  vocabulary:["skill","competency","knowledge","practice","transferable","occupation","career","job","enterprise","pathway","qualification","training","mentor","portfolio","evidence","strength","development","goal","role","responsibility"],
  materials:["skills cards","career-role cards","previous learner work or portfolio evidence","large paper","markers","goal-planning sheets","sample role descriptions","optional internet-connected facilitator device or AI tool","reflection journal"],
  safety:["Do not collect or publicly display sensitive personal information during career activities.","Avoid telling learners that gender, disability, ethnicity, family income or background determines what careers are suitable for them.","Any workplace visit, interview or mentoring activity must follow safeguarding procedures.","Minors must not be recruited into commercial selling, hazardous work or unsupervised technical work through this module.","AI career advice can be incomplete or biased and must not be treated as a definitive placement decision.","Career exploration should present multiple pathways and acknowledge that interests and opportunities can change."],
  lessons:[
    {id:"PE-11-L1",title:"What Counts as a Skill?",objective:"Classify different kinds of skills and recognize evidence of competence.",teaching:["Skills include technical and practical abilities as well as communication, teamwork, safety, digital and problem-solving capabilities.","A claim such as 'I can measure accurately' is stronger when supported by evidence from a completed task.","Transferable skills can be useful across many roles and sectors."],activity:"Sort skill cards into Knowledge, Practical, Data/Digital, Safety, Enterprise/Employability and Leadership/Life categories.",diy:"Create a My Skills Evidence Map with six skill categories and one piece of evidence for each available category.",aiLayer:"AI Layer 1 — Skill identification: compare an AI-generated list of skills from a sample project with learner-identified skills and remove unsupported claims.",enterprise:"Enterprises need people who can combine technical competence with reliability, communication, records and problem solving.",quiz:[{question:"What makes a skill claim stronger?",options:["Evidence from a task","A slogan","A guess","A title only"],answer:0},{question:"What is a transferable skill?",options:["A skill useful across different roles","A skill used once","A secret skill","A certificate only"],answer:0},{question:"Is teamwork a real workplace skill?",options:["Yes","No","Only for managers","Only in school"],answer:0}]},
    {id:"PE-11-L2",title:"Explore Green and FEW Roles",objective:"Identify diverse roles across food, energy, water and supporting systems.",teaching:["Food-energy-water systems include growers, irrigation technicians, food processors, laboratory staff, electrical technicians, data workers, designers, educators, logistics staff, maintenance workers, entrepreneurs and many others.","Roles differ in training, responsibility, risk and working environment.","No single occupation represents the whole green economy."],activity:"Create role chains for a school garden, irrigation service or food product showing at least six different occupations or functions.",diy:"Build three Career Role Cards with ROLE → TASKS → SKILLS → TRAINING → SAFETY RESPONSIBILITIES.",aiLayer:"AI Layer 2 — Role research: use AI to suggest tasks for one role, then verify important duties and qualification claims against a trusted career or training source where available.",enterprise:"Understanding roles helps teams know when specialized expertise, partnerships or services are needed.",quiz:[{question:"Which can be part of a food-energy-water system?",options:["Data technician","Only farmer","Only engineer","Only seller"],answer:0},{question:"Do all roles require the same training?",options:["No","Yes","Always","Only digital roles differ"],answer:0},{question:"Why identify safety responsibilities?",options:["Some tasks carry specific risks and duties","Safety is optional","Only adults need safety","It replaces skills"],answer:0}]},
    {id:"PE-11-L3",title:"Jobs, Careers, Enterprise and Learning",objective:"Differentiate forms of work and routes for developing competence.",teaching:["A job is a specific position or piece of work; an occupation is a type of work; a career can include many roles and learning stages over time.","Enterprise involves organizing resources to provide a product or service and carries responsibility and risk.","Learning pathways may include school, vocational education, apprenticeships, supervised practice, certifications and higher education."],activity:"Match fictional learner goals with several possible learning pathways rather than one fixed route.",diy:"Draw a Pathway Map from current learning to three possible future destinations, including at least two alternative routes.",aiLayer:"AI Layer 3 — Pathway comparison: ask AI for possible routes, then identify which details require local verification such as entry requirements, fees or age rules.",enterprise:"Enterprise is one future option for eligible adults, not the only definition of success or employment.",quiz:[{question:"What is an occupation?",options:["A type of work","One school lesson","A guaranteed income","A hobby only"],answer:0},{question:"Can one career include several jobs or roles?",options:["Yes","No","Never","Only for adults over 50"],answer:0},{question:"What should be verified locally?",options:["Training entry requirements","A learner's interests","Basic arithmetic","The alphabet"],answer:0}]},
    {id:"PE-11-L4",title:"Challenge Career Stereotypes",objective:"Evaluate career assumptions and support inclusive participation.",teaching:["Career stereotypes can exclude capable people before their skills are considered.","Tasks should be matched to competence, training, accessibility and safety rather than gender or social background.","Workplaces can use reasonable accommodations and adapted tools to widen participation."],activity:"Review stereotype statements and rewrite them as competency-based statements.",diy:"Create an Inclusive Role Profile describing required competencies, possible accommodations and fair evidence of readiness.",aiLayer:"AI Layer 4 — Bias check: inspect an AI-generated role description for gendered, cultural or ability-based assumptions and rewrite it inclusively.",enterprise:"Inclusive teams can widen the talent pool and improve problem solving when roles are assigned by capability and support needs.",quiz:[{question:"What should determine role readiness?",options:["Competence, training and safety","Gender","Family status","Stereotype"],answer:0},{question:"What is an accommodation?",options:["A reasonable adjustment that supports participation","A guarantee of a job","A lower standard automatically","A punishment"],answer:0},{question:"Can AI reproduce stereotypes?",options:["Yes","No","Never","Only offline"],answer:0}]},
    {id:"PE-11-L5",title:"Build a Skills Portfolio",objective:"Select evidence that demonstrates developing competencies.",teaching:["A portfolio is a curated collection of evidence, not every activity completed.","Strong evidence explains the task, learner role, method, result and reflection.","Photos or digital records should follow privacy and safeguarding rules."],activity:"Review previous Explorer evidence and select examples that demonstrate at least four competency domains.",diy:"Create four Portfolio Evidence Cards with TASK → MY ROLE → EVIDENCE → WHAT I LEARNED → NEXT IMPROVEMENT.",aiLayer:"AI Layer 5 — Reflection support: ask AI to suggest reflection questions, but write the final reflection from the learner's actual experience.",enterprise:"Portfolios can help communicate capability to future training providers, mentors and employers.",quiz:[{question:"What is a portfolio?",options:["A selected collection of evidence","Every file without explanation","A guaranteed certificate","A password"],answer:0},{question:"What should evidence show?",options:["What the learner actually did","Only team results with no role","Invented experience","Only a title"],answer:0},{question:"Why protect photos and personal data?",options:["Privacy and safeguarding matter","They have no value","Records should always be public","AI requires them"],answer:0}]},
    {id:"PE-11-L6",title:"Plan the Next Skill Step",objective:"Create a realistic short-term development goal linked to evidence and opportunity.",teaching:["A development goal should be specific enough to act on and review.","The next step may be practice, a course, mentoring, reading, a supervised project or improving an existing skill.","Plans should include evidence of progress and a review date rather than promises of a particular career outcome."],activity:"Learners identify one strength to deepen and one skill gap to improve, then peer-review whether the goal is realistic and safe.",diy:"Complete a 90-Day Skills Plan: GOAL → WHY → PRACTICE → SUPPORT → EVIDENCE → BARRIER → RESPONSE → REVIEW DATE.",aiLayer:"Integration — plan critique: ask AI to identify vague or unrealistic parts of the plan, then revise using real available resources and constraints.",enterprise:"Continuous skill development increases adaptability in employment, technical training and future enterprise.",quiz:[{question:"What makes a development goal useful?",options:["A clear action and evidence of progress","A guaranteed career","No review date","A vague wish only"],answer:0},{question:"Can a next step be supervised practice?",options:["Yes","No","Only a paid job counts","Only university counts"],answer:0},{question:"What should a skills plan include?",options:["A review point","A guaranteed salary","Hidden assumptions","No evidence"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"What is transferable skill?",options:["A skill useful in different settings","A job title","A school building","A certificate number"],answer:0},{question:"What best supports a claim of competence?",options:["Evidence","Opinion alone","Age","Stereotype"],answer:0},{question:"Which can be a green-economy role?",options:["Irrigation technician","Only farmer","Only scientist","Only business owner"],answer:0},{question:"Can careers include multiple jobs and learning stages?",options:["Yes","No","Never","Only in one industry"],answer:0},{question:"What should guide role selection?",options:["Competence, interest, training and safety","Gender stereotype","Family income only","AI alone"],answer:0},{question:"What is a portfolio for?",options:["Showing selected evidence of capability","Guaranteeing employment","Replacing learning","Collecting private data publicly"],answer:0},{question:"What is a good short-term skills goal?",options:["Specific, actionable and reviewable","Guaranteed","Secret","Impossible to measure"],answer:0},{question:"How should AI career advice be used?",options:["As exploration that must be verified","As a final placement decision","To predict guaranteed income","To exclude people"],answer:0}],theory:["Explain the difference among knowledge, practical skill and transferable skill using examples from Explorer modules.","Describe three different roles connected to food, energy or water systems and the competencies each needs.","Explain the difference among a job, occupation, career and enterprise.","Describe how stereotypes can limit participation and how competency-based role descriptions improve fairness.","Create a short skills-development goal and explain what evidence would show progress."],practical:"Prepare and present a Skills and Careers Portfolio containing a personal competency map, three researched role cards, one inclusive role profile, four evidence cards from completed learning and a 90-day development plan. Clearly separate verified role information from AI-generated suggestions or assumptions."},
  evidence:["My Skills Evidence Map","Career Role Cards","Pathway Map","Inclusive Role Profile","Portfolio Evidence Cards","90-Day Skills Plan","Final Skills and Careers Portfolio","Facilitator assessment record"],
  passport:["K: explains skill categories, occupations, careers, enterprise and learning pathways","P: organizes portfolio evidence and creates role/pathway maps","D: uses digital research and AI critically while verifying career information","S: applies safeguarding, privacy and role-safety principles to career exploration","E: recognizes employment, training and adult enterprise pathways without guaranteed outcomes","L: reflects on strengths, challenges stereotypes, sets goals and seeks appropriate support"],
  trainerNotes:["Present many roles and pathways; do not steer learners toward a single occupation based on background or current performance.","Use local role examples where possible but distinguish current local opportunities from general occupational descriptions.","Do not publish learner portfolios or photographs without appropriate permissions.","Avoid salary promises, income projections or commercial recruitment.","Invite vetted role models or mentors only through approved safeguarding processes.","Treat learner interests as changeable and encourage exploration rather than premature specialization."],
  remediation:"Use three familiar roles and a simple skill-match exercise. Learner identifies one task, one required skill and one piece of their own evidence for each role before developing a one-month practice goal.",
  extension:"Learners compare two different training routes toward one occupational area, identifying entry requirements to verify, likely competencies developed, time commitment, costs that require confirmation and fallback options.",
  imagePrompts:["Photorealistic African adolescents ages 11–14 exploring green careers with visual role cards showing farming, irrigation, electrical, food processing, data and technical work, inclusive boys and girls, classroom setting, no readable text.","Photorealistic learner portfolio review with notebooks, garden measurement evidence, digital tablet and practical project photos laid out on a table, diverse African students, safe supervised environment, no readable text.","Educational illustration of multiple learning pathways branching toward food, water, energy, digital and technical careers, inclusive human figures, no readable text."]
};

export const pe11ByLanguage: Partial<Record<AppLanguage,PE11Module>> = { en };
export function getPE11(language:AppLanguage):PE11Module { return pe11ByLanguage[language] ?? en; }
