import Link from "next/link";
import { LanguageMenu } from "@/components/language-menu";
import { programsByArm, assessmentStandard, competencyDomains, deliveryStandard, evidenceStandard } from "@/lib/curriculum";
import { localizeHref, normalizeLanguage } from "@/lib/i18n6";

type PageProps = { searchParams?: Promise<{ lang?: string }> };
const audiences=["Almajiri learners","Never-enrolled children","Out-of-school children","Out-of-school girls","School dropouts","Over-age learners","Underserved adolescents","Transitioning youth"];

export default async function PathwaysPage({ searchParams }: PageProps) {
  const params=searchParams?await searchParams:{}; const language=normalizeLanguage(params.lang); const rtl=language==="ar"; const programs=programsByArm("pathways");
  return <div className="shell public-shell" dir={rtl?"rtl":"ltr"}><aside className="sidebar compact-sidebar"><Link href={localizeHref("/",language)} className="brand-lockup"><img className="brand-logo" src="/lifews-mark.svg" alt="LIFEWS logo"/><div className="brand">LIFEWS Pathways<small>A GreenSkills Program</small></div></Link><LanguageMenu currentLanguage={language}/><nav className="nav"><Link href={localizeHref("/",language)}>GreenSkills</Link><Link className="active" href={localizeHref("/pathways",language)}>Pathways Home</Link><Link href={localizeHref("/learner",language)}>Learner space</Link><Link href={localizeHref("/login",language)}>Staff workspace</Link><a href="#curriculum">Curriculum</a></nav><div className="sidebar-note">Learning • Skills • Opportunity • Transition</div></aside><main className="main public-main">
    <header className="hero-simple"><div className="eyebrow">A LIFEWS GREENSKILLS PROGRAM</div><h1>LIFEWS Pathways</h1><p className="hero-line">Learning • Skills • Opportunity • Transition</p><p className="subtitle hero-copy">An inclusive learning and transition program for Almajiri learners, out-of-school children and girls, never-enrolled learners, school dropouts, over-age learners, underserved adolescents and transitioning youth.</p><div className="hero-actions"><Link className="primary-action" href={localizeHref("/learner",language)}>Enter learner space</Link><Link className="gold-action" href={localizeHref("/login",language)}>Staff sign in</Link></div></header>
    <section className="gold-strip">{["REACH","ASSESS","LEARN","GROW","BUILD","TRANSITION","THRIVE"].map((step,i,arr)=><span key={step}>{step}{i<arr.length-1&&<b> → </b>}</span>)}</section>
    <section className="simple-section"><div><div className="eyebrow">WHO PATHWAYS SERVES</div><h2>Flexible routes back into learning and opportunity</h2></div><div className="audience-pills">{audiences.map(a=><span key={a}>{a}</span>)}</div></section>
    <section className="program-content-section" id="curriculum"><div className="gs-section-heading"><div><div className="gs-eyebrow">THREE PATHWAYS PROGRAMS</div><h2>Age-responsive progression with practical learning.</h2></div><p>Pathways Foundation, Explorer and Transition provide a staged route from foundational learning into education re-entry, Kadara, GreenTech, apprenticeship or other appropriate next destinations.</p></div><div className="curriculum-program-grid">{programs.map(program=><article className="curriculum-program-card" key={program.code}><div className="curriculum-card-head"><span>{program.code}</span><small>{program.age}</small></div><h3>{program.title}</h3><p>{program.purpose}</p><div className="lesson-stack">{program.lessons.map(lesson=><details key={lesson.code}><summary><b>{lesson.code}</b> {lesson.title}</summary><p><strong>Competency:</strong> {lesson.competency}</p><p><strong>DIY / practical:</strong> {lesson.diy}</p></details>)}</div></article>)}</div></section>
    <section className="competency-framework"><div><div className="gs-eyebrow">COMMON COMPETENCY FRAMEWORK</div><h2>Six domains follow the learner.</h2></div><div className="competency-domain-grid">{competencyDomains.map(([code,name])=><article key={code}><span>{code}</span><strong>{name}</strong></article>)}</div></section>
    <section className="fieldworks-callout"><div><div className="gs-eyebrow">ASSESSMENT & EVIDENCE</div><h2>Every lesson includes a practical proof point.</h2><p>{assessmentStandard}</p><p>{evidenceStandard}</p><p>{deliveryStandard}</p></div><div className="fieldworks-metrics">{["8 MCQs","5 theory questions","Mandatory DIY","Practical checklist","Evidence upload","Skills Passport update"].map(item=><span key={item}>{item}</span>)}</div></section>
  </main></div>;
}
