-- Session-bound learner submissions for AI logs, enterprise tasks, assessment records and FieldWorks evidence.
create or replace function public.submit_greentech_learner_record(p_session_token text,p_lesson_code text,p_record_type text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path='public' as $$
declare v_participant uuid;v_lesson uuid;v_type text:=upper(coalesce(p_record_type,''));v_id uuid;v_section int;v_text text;
begin
 if p_session_token is null or length(p_session_token)<>64 then raise exception 'Invalid learner session';end if;
 select las.participant_id into v_participant from public.learner_access_sessions las join public.participants p on p.id=las.participant_id where las.token_hash=encode(digest(p_session_token,'sha256'),'hex') and las.revoked_at is null and las.expires_at>now() and p.active=true limit 1;
 if v_participant is null then raise exception 'Learner session expired';end if;select id into v_lesson from public.greenskills_lessons where lesson_code=p_lesson_code and active=true limit 1;if v_lesson is null then raise exception 'Unknown GreenTech module';end if;if pg_column_size(p_payload)>100000 then raise exception 'Submission too large';end if;
 if v_type='PROGRESS' then v_section:=coalesce((p_payload->>'section_no')::int,0);if v_section not between 1 and 7 then raise exception 'Invalid section';end if;insert into public.greentech_module_progress(participant_id,lesson_id,section_no,completed,reflection) values(v_participant,v_lesson,v_section,true,left(nullif(p_payload->>'reflection',''),4000)) on conflict(participant_id,lesson_id,section_no) do update set completed=true,reflection=excluded.reflection,updated_at=now() returning id into v_id;
 elsif v_type='AI_LOG' then if length(trim(coalesce(p_payload->>'task','')))<3 or length(trim(coalesce(p_payload->>'final_decision','')))<3 then raise exception 'AI task and final decision are required';end if;insert into public.greentech_ai_work_logs(participant_id,lesson_id,ai_layer,task,input_summary,ai_use,output_summary,verification_method,errors_or_limitations,correction,final_decision,privacy_check,independent_reasoning_verified,status) values(v_participant,v_lesson,nullif(p_payload->>'ai_layer','')::int,left(p_payload->>'task',4000),left(p_payload->>'input_summary',8000),left(p_payload->>'ai_use',8000),left(p_payload->>'output_summary',8000),left(p_payload->>'verification_method',8000),left(p_payload->>'errors_or_limitations',8000),left(p_payload->>'correction',8000),left(p_payload->>'final_decision',8000),coalesce((p_payload->>'privacy_check')::boolean,false),coalesce((p_payload->>'independent_reasoning_verified')::boolean,false),'SUBMITTED') returning id into v_id;
 elsif v_type='ENTERPRISE' then if length(trim(coalesce(p_payload->>'customer_problem','')))<3 or length(trim(coalesce(p_payload->>'service_scope','')))<3 then raise exception 'Customer problem and service scope are required';end if;insert into public.greentech_enterprise_tasks(participant_id,lesson_id,customer_type,customer_problem,service_scope,deliverables,exclusions,materials_cost,consumables_cost,labor_cost,transport_cost,equipment_allowance,overhead_cost,contingency_cost,customer_price,after_service,status) values(v_participant,v_lesson,left(p_payload->>'customer_type',500),left(p_payload->>'customer_problem',8000),left(p_payload->>'service_scope',8000),left(p_payload->>'deliverables',8000),left(p_payload->>'exclusions',8000),greatest(coalesce(nullif(p_payload->>'materials_cost','')::numeric,0),0),greatest(coalesce(nullif(p_payload->>'consumables_cost','')::numeric,0),0),greatest(coalesce(nullif(p_payload->>'labor_cost','')::numeric,0),0),greatest(coalesce(nullif(p_payload->>'transport_cost','')::numeric,0),0),greatest(coalesce(nullif(p_payload->>'equipment_allowance','')::numeric,0),0),greatest(coalesce(nullif(p_payload->>'overhead_cost','')::numeric,0),0),greatest(coalesce(nullif(p_payload->>'contingency_cost','')::numeric,0),0),greatest(coalesce(nullif(p_payload->>'customer_price','')::numeric,0),0),left(p_payload->>'after_service',8000),'SUBMITTED') returning id into v_id;
 elsif v_type='ASSESSMENT' then if coalesce((p_payload->>'mcq_score')::numeric,-1) not between 0 and 100 or coalesce((p_payload->>'theory_score')::numeric,-1) not between 0 and 100 then raise exception 'Assessment scores must be 0-100';end if;insert into public.greenskills_lesson_assessments(participant_id,lesson_id,theory_score,mcq_score,evidence_note,status) values(v_participant,v_lesson,(p_payload->>'theory_score')::numeric,(p_payload->>'mcq_score')::numeric,left(p_payload->>'evidence_note',12000),'SUBMITTED') returning id into v_id;
 elsif v_type='FIELDWORK' then v_text:=trim(coalesce(p_payload->>'file_url',''));if v_text<>'' and v_text !~ '^https://[^[:space:]]+$' then raise exception 'Evidence link must use HTTPS';end if;insert into public.fieldwork_evidence(participant_id,lesson_id,evidence_type,title,description,file_url,verification_status) values(v_participant,v_lesson,coalesce(nullif(left(p_payload->>'evidence_type',100),''),'OTHER'),coalesce(nullif(left(p_payload->>'title',500),''),p_lesson_code||' evidence'),left(p_payload->>'description',12000),nullif(left(v_text,2000),''),'PENDING') returning id into v_id;
 else raise exception 'Unsupported record type';end if;return jsonb_build_object('ok',true,'id',v_id,'type',v_type);end $$;
revoke all on function public.submit_greentech_learner_record(text,text,text,jsonb) from public;grant execute on function public.submit_greentech_learner_record(text,text,text,jsonb) to anon,authenticated;
