import type { PF01Module } from "./pf-01";

type PF08Module = Omit<PF01Module,"code"> & { code:"PF-08" };

export const pf08Yo: PF08Module = {
 code:"PF-08", title:"Ọwọ́ Mímọ́, Oúnjẹ Àìléwu", level:"Pathways Foundation", age:"Ní ìwọ̀n ọdún 8–11; kí a ṣe àwọn iṣẹ́ àṣà ìmọ́ṣe gẹ́gẹ́ bí ìmúrasílẹ̀ akẹ́kọ̀ọ́ àti ìtọ́sọ́nà ààbò oúnjẹ agbègbè.", duration:"Ẹ̀kọ́ amọ̀nà 6 pẹ̀lú ìṣe ìmọ́tótó àti ìdánwò", fieldworkHours:3,
 bigQuestion:"Báwo ni ọwọ́ mímọ́, irinṣẹ́ mímọ́ àti mímú oúnjẹ pẹ̀lú ìtọ́jú ṣe lè dá ènìyàn àti oúnjẹ láàbò?",
 whyItMatters:"Ààbò oúnjẹ bẹ̀rẹ̀ pẹ̀lú àṣà ojoojúmọ́. Módù yìí ń kọ́ nípa ìbàjẹ́ tàbí ìdọ̀tí oúnjẹ, fífọ ọwọ́, fífọ àyè iṣẹ́, pípa àwọn oúnjẹ kan sọ́tọ̀, ìpamọ́ àti ìbánisọ̀rọ̀ tó ní ojúṣe, láìfi ọmọ sí ewu kemika, oúnjẹ aise tó léwu tàbí iṣẹ́ títà.",
 outcomes:["Ṣàlàyé bí kòkòrò arun, ìdọ̀tí, omi tí kò ní ààbò àti mímú oúnjẹ lọ́nà búburú ṣe lè ba oúnjẹ jẹ́.","Ṣe àfihàn ilana fífọ ọwọ́ pipe ní àkókò tó yẹ.","Ṣe ìyàtọ̀ láàárín ìṣe mímọ́ àti ìṣe tí kò mọ́ nípa irinṣẹ́ àti ibi tí oúnjẹ ń fọwọ́ kan.","Ṣàlàyé ìdí tí a fi yẹ kí oúnjẹ aise kan yà sí oúnjẹ tó ti ṣetan láti jẹ.","Mọ̀ pé ìpamọ́ oúnjẹ láìléwu dá lórí irú oúnjẹ, àkókò, ooru àti ìtọ́sọ́nà tó ṣeé gbẹ́kẹ̀lé.","Lo àtòjọ ayẹwo ìmọ́tótó láti ṣàyẹ̀wò àti mú iṣẹ́ tó wà lábẹ́ àbójútó dára.","Ṣàyẹ̀wò ìmọ̀ràn AI tàbí oni-nọ́mbà pẹ̀lú ìtọ́sọ́nà tó gbẹ́kẹ̀lé."],
 vocabulary:["ààbò oúnjẹ","ìmọ́tótó","ìbàjẹ́/ìdọ̀tí","kòkòrò arun","mímọ́","ìdọ̀tí","fífọ ọwọ́","fọ́ mọ́","ọṣẹ","ojú ilẹ̀","irinṣẹ́","yà sọ́tọ̀","ìpamọ́","ooru","ẹ̀gbin","àtòjọ ayẹwo","ẹ̀rí"],
 materials:["ibùdó fífọ ọwọ́ pẹ̀lú omi tó ní ààbò","ọṣẹ","ọ̀nà mímọ́ fún gbígbẹ ọwọ́","káàdì ìtẹ̀síwájú ìgbésẹ̀","irinṣẹ́ àti àpò mímọ́ fún àfihàn","káàdì àpẹẹrẹ ààbò oúnjẹ","ìwé akẹ́kọ̀ọ́","àtòjọ ayẹwo ìmọ́tótó","ẹ̀rọ oni-nọ́mbà lábẹ́ iṣakoso olùkọ́ bí ó bá wà"],
 safety:["Lo ohun èlò àfihàn tí olùkọ́ fọwọ́ sí; kò sí ìdánwò jíjẹ oúnjẹ tó jẹ dandan.","Àwọn ọmọ kò gbọ́dọ̀ mú ẹran aise, ẹyin aise, kemika ìfọ̀mọ́ tó lewu tàbí ohun èlò gbígbóná.","Nu omi tó tú sílẹ̀ lẹ́sẹ̀kẹsẹ̀.","Má ṣe pinnu pé oúnjẹ ní ààbò nípa ìrí, oorun tàbí adùn nìkan.","Bọ̀wọ̀ fún àìlera oúnjẹ, ìlànà ẹ̀sìn àti àìní pataki àwọn akẹ́kọ̀ọ́.","Ṣàyẹ̀wò gbogbo ìmọ̀ràn AI nípa ààbò oúnjẹ pẹ̀lú ìtọ́sọ́nà agbègbè àti ti olùkọ́."],
 lessons:[
  {id:"PF-08-L1",title:"Bí Oúnjẹ Ṣe Lè Di Aláìléwu",objective:"Mọ bí ìdọ̀tí ṣe lè rìn láti ọwọ́, omi, ojú ilẹ̀ tàbí oúnjẹ mìíràn sí oúnjẹ tí a fẹ́ jẹ.",teaching:["Ìdọ̀tí oúnjẹ ni bí nkan tí kò yẹ tàbí tó lewu ṣe wọ oúnjẹ.","Ọwọ́, omi tí kò mọ́, irinṣẹ́ tí kò mọ́, kokoro àti ìfọwọ́kan oúnjẹ le gbe ìdọ̀tí.","Diẹ ninu kòkòrò arun kò ṣeé rí, kò ní oorun tàbí adùn."],activity:"Lo káàdì àwòrán láti tọpa ọ̀nà ìdọ̀tí, kí o sì samisi ibi tí a lè dá a dúró.",diy:"Ṣẹ̀dá àwòrán ORÍSUN → IFỌ́WỌ́KAN → OÚNJẸ → ÌDENA.",aiLayer:"AI 1 — Ìdánimọ̀: wo àpẹẹrẹ AI, kí akẹ́kọ̀ọ́ sọ bóyá ó ṣeé ṣe, kò dájú tàbí kò tọ́.",enterprise:"Agbe, aláṣiṣẹ́ oúnjẹ àti olùtajà ń pa iye ọja mọ́ nípa dídènà ìdọ̀tí kí ó tó ṣẹlẹ̀.",quiz:[{question:"Kí ni ìdọ̀tí oúnjẹ?",options:["Wíwọ nkan tí kò yẹ tàbí tó lewu sínú oúnjẹ","Ṣíṣe oúnjẹ ní awọ̀","Kíkà àpò","Gbingbin irúgbìn"],answer:0},{question:"Ṣé a lè rí gbogbo kòkòrò arun tó lewu?",options:["Rárá","Bẹ́ẹ̀ni nígbà gbogbo","Nínú omi nìkan","Lórí irin nìkan"],answer:0},{question:"Kí ló lè gbe ìdọ̀tí?",options:["Ọwọ́ tí kò mọ́","Ìwé tó pa","Pẹ́ńsù mímọ́","Àpótí tó ṣofo"],answer:0}]},
  {id:"PF-08-L2",title:"Fọ Ọwọ́ Ní Ọ̀nà Tó Tọ́",objective:"Ṣe àfihàn ìgbà àti ọ̀nà tó yẹ láti fọ ọwọ́ dáadáa ṣáájú iṣẹ́ oúnjẹ.",teaching:["Fọ ọwọ́ ṣáájú mímú oúnjẹ àti lẹ́yìn iṣẹ́ tí ó lè ba ọwọ́ jẹ́.","Fífọ ọwọ́ tó pé lo omi tó ní ààbò, ọṣẹ, fifọ gbogbo agbègbè ọwọ́, rírìnṣẹ́ omi àti gbígbẹ ní ọ̀nà mímọ́.","Ríru omi lórí ọwọ́ láìlo ọṣẹ kì í tó."],activity:"Olùkọ́ ṣe àfihàn, lẹ́yìn náà àwọn akẹ́kọ̀ọ́ ṣe ní tọkọtaya pẹ̀lú káàdì ìgbésẹ̀.",diy:"Ṣẹ̀dá káàdì ìgbésẹ̀ mẹ́fà, kí o sì ṣe àfihàn láìrí ìrànlọ́wọ́.",aiLayer:"AI 2 — Ayẹwo ìtẹ̀síwájú: fi ìgbésẹ̀ akẹ́kọ̀ọ́ wé ti AI, kí o wa ohun tí ó ṣòfo tàbí tí a fi sí ibi tí kò yẹ.",enterprise:"Àṣà ìmọ́tótó tó dájú jẹ́ apá pataki ti iṣakoso didara ní iṣẹ́ oúnjẹ.",quiz:[{question:"Kí ni a nílò fún fífọ ọwọ́ deede?",options:["Omi tó ní ààbò àti ọṣẹ","Ilẹ̀ nìkan","Epo","Àwọ̀"],answer:0},{question:"Nígbà wo ni a yẹ kí a fọ ọwọ́?",options:["Ṣáájú mímú oúnjẹ àti lẹ́yìn iṣẹ́ tí ó lè dọ́tí ọwọ́","Lẹ́ẹ̀kan lọ́sẹ̀","Lẹ́yìn jíjẹ nìkan","Kò sí ìgbà"],answer:0},{question:"Kí ló dé tí a fi yẹ kí a gbẹ ọwọ́ ní ọ̀nà mímọ́?",options:["Kí ọwọ́ mímọ́ má bàjẹ́ lẹ́ẹ̀kansi","Kí oúnjẹ dùn","Láti wọn omi","Láti rọ́pò ọṣẹ"],answer:0}]},
  {id:"PF-08-L3",title:"Irinṣẹ́ Mímọ́ àti Ojú Ilẹ̀ Mímọ́",objective:"Ṣe ìyàtọ̀ láàárín ohun elo mímọ́ àti ìṣe tí ó lè tún wọn dọ́tí.",teaching:["Ojú ilẹ̀ àti irinṣẹ́ tí oúnjẹ ń fọwọ́ kan yẹ kí ó mọ́ kí a tó lo.","Aṣọ tàbí irinṣẹ́ tí kò mọ́ le tan ìdọ̀tí.","Ìfọ̀mọ́ yẹ kí ó tẹ̀lé ọ̀nà tí agbalagba fọwọ́ sí àti àṣẹ ọja."],activity:"Ṣàyẹ̀wò tábìlì àfihàn, kí o yan ìṣe tó dára àti tó burú.",diy:"Ṣẹ̀dá àtòjọ MÍMỌ́ / NÍLÒ ÀTÚNṢE pẹ̀lú nkan mẹjọ.",aiLayer:"AI 3 — Ayẹwo pẹ̀lú ìtọ́sọ́nà: fi àtòjọ kíláàsì wé ti AI, kí o pa ohun tí kò bá ọjọ́ ori tàbí agbegbe mu rẹ́.",enterprise:"Ìfọ̀mọ́ àti ayẹwo deede dinku asonu ati isoro didara.",quiz:[{question:"Kí ni a yẹ kí a ṣe sí ibi tí oúnjẹ yóò fọwọ́ kan ṣáájú lilo?",options:["Fọ́ ọ dáadáa","Bo pẹlu ilẹ̀","Má ṣe ṣàyẹ̀wò","Lo fún gbogbo nkan láìfọ́"],answer:0},{question:"Ṣé aṣọ tí kò mọ́ le tan ìdọ̀tí?",options:["Bẹ́ẹ̀ni","Rárá","Níta nìkan","Ní alẹ́ nìkan"],answer:0},{question:"Kí ni àtòjọ ayẹwo fún?",options:["Láti ṣàyẹ̀wò pé a ń tẹ̀lé ìṣe tó yẹ","Láti jẹrisi èrè","Láti rọ́pò fífọ ọwọ́","Láti fi ìṣòro pamọ́"],answer:0}]},
  {id:"PF-08-L4",title:"Yà Àwọn Oúnjẹ Kan Sọ́tọ̀",objective:"Ṣàlàyé idi tí a fi yẹ kí a yà diẹ ninu oúnjẹ ati irinṣẹ́ sọ́tọ̀ lati dinku ìdọ̀tí kọjá.",teaching:["Ìdọ̀tí kọjá máa ń ṣẹlẹ̀ nigbati ìdọ̀tí ba rìn lati ohun kan, ojú ilẹ̀ kan tabi irinṣẹ́ kan si omiran.","Oúnjẹ ẹranko aise le gbe ewu si oúnjẹ tó setan lati jẹ.","Ní ipele yi, akẹ́kọ̀ọ́ lo àwòrán ati irinṣẹ́ mímọ́; agbalagba ni yóò mu oúnjẹ aise tó lewu."],activity:"Pín káàdì si AISE / TÓ ṢETÁN LÁTI JẸ / IRINṢẸ́ MÍMỌ́, kí o yàn agbegbe lọtọ.",diy:"Ṣe àwòrán bi ibi siseto oúnjẹ ṣe le ya nkan ewu kuro ni oúnjẹ tó setan lati jẹ.",aiLayer:"AI 4 — Ìrònú lori àpẹẹrẹ: ṣàyẹ̀wò àpẹẹrẹ ibi idana ounje ti AI, kí o wa ọna ifọwọkan ti ko ni aabo.",enterprise:"Eto iṣẹ́ to dára dinku ọna ti ìdọ̀tí le gba.",quiz:[{question:"Kí ni ìdọ̀tí kọjá?",options:["Gbigbe ìdọ̀tí lati nkan kan si omiran","Sise ounje deede","Kika eroja","Gbingbin irugbin meji"],answer:0},{question:"Kí ló de ti a fi ya oúnjẹ ẹranko aise kuro ni oúnjẹ tó setan lati jẹ?",options:["Lati dinku gbigbe ewu","Lati yi awo pada","Lati fi iwe pamọ","Lati yago fun fifọ"],answer:0},{question:"Ṣe ọmọ yẹ kí o mu ẹran aise ninu modulu yi?",options:["Rárá","Bẹẹni laisi abojuto","Ti AI ba so bẹẹ","Pẹ̀lú ọwọ́ lasan"],answer:0}]},
  {id:"PF-08-L5",title:"Pa Oúnjẹ Mọ́ Pẹ̀lú Itọju",objective:"Mọ̀ pé ipamọ́ to ni aabo dale lori irú oúnjẹ, akoko, otutu ati itosona to gbẹkẹle.",teaching:["Oúnjẹ oriṣiriṣi ni ibeere ipamọ́ oriṣiriṣi.","Oúnjẹ ti o rorun lati baje le nilo iṣakoso otutu.","Aami ọja, itosona agbegbe ati agbalagba to ni ojuse yẹ kí o dari ipinnu ipamọ́."],activity:"Pín àpẹẹrẹ si BÉÈRÈ LỌ́WỌ́ ÀGBÀ / IPAMỌ́ GBÍGBẸ TÓ DÁABÒ BO / IPAMỌ́ PẸ̀LÚ IṢAKOSO OTUTU.",diy:"Ṣẹ̀dá káàdì: MỌ OÚNJẸ → ṢAYẸ̀WÒ AAMI/ITOSONA → LO APOTI MIMO → FI SI IBI TO TO → ṢAYẸ̀WÒ LẸẸKANSI.",aiLayer:"AI 5 — Ijerisi: fi imọran ipamọ́ AI we aami ọja tabi itosona ti oluko fọwọ́ si.",enterprise:"Ipamọ́ to peye n daabo bo ohun elo, dinku asonu ati mu didara duro.",quiz:[{question:"Ṣe gbogbo oúnjẹ ni ibeere ipamọ́ kanna?",options:["Rárá","Bẹẹni","Apoti nikan lo yatọ","Eso nikan"],answer:0},{question:"Kí ni a yẹ kí o ṣayẹwo ti o ko ba da ọ loju?",options:["Itosona to gbẹkẹle tabi aami ọja","Asọtẹlẹ","Irisi nikan","Agbasọ"],answer:0},{question:"Kí ló de ti a fi lo apoti mimo?",options:["Lati daabo bo oúnjẹ lodi si ìdọ̀tí","Lati ropo itutu","Lati jẹrisi pe ko ni baje laelae","Lati yago fun aami"],answer:0}]},
  {id:"PF-08-L6",title:"Ṣe Ayẹwo Ààbò Oúnjẹ",objective:"Lo imo imototo lati ṣayẹwo ibi ẹ̀kọ́ to wa labẹ abojuto ati daba atunse lori eri.",teaching:["Ààbò oúnjẹ je eto: ọwọ́ mimo, omi to ni aabo, irinṣẹ́ mimo, yiyapa, ipamọ́ to dara ati abojuto.","Atokọ ayẹwo yi ofin pada si iṣe ti a le ri.","Ti a ba ri iṣoro, duro, tun un se ni aabo, ki o si kọ ohun ti a tun se."],activity:"Ẹgbẹ ṣayẹwo ibi ounje afarawe, kọ o kere ju akiyesi marun ati atunse meji.",diy:"Pari AYẸWO ÀÀBÒ OÚNJẸ: ṢAYẸ̀WÒ → RI → TUNṢE → JẸRISI → KỌ SÍLẸ̀.",aiLayer:"Isopọpọ — Ayẹwo lori eri: fi ayẹwo ẹgbẹ we ti AI, ki o kọ imọran ti o tako eri, aami tabi ofin agbegbe.",enterprise:"Iṣeduro didara tumo si idena iṣoro, kikọ ayẹwo si ati atunse iyapa ṣaaju ki ọja tabi iṣẹ de ọdọ olumulo.",quiz:[{question:"Kí ni a yẹ kí o ṣe nigbati a ba ri ipo ti ko ni aabo?",options:["Duro ki o tun un se ni aabo","Fi pamọ","Tẹsiwaju","Pa igbasilẹ rẹ"],answer:0},{question:"Kí ló de ti a fi jẹrisi atunse?",options:["Lati mọ pe iṣoro ti yanju gangan","Lati gun iwe","Lati yago fun ojuse","Lati jẹrisi ọjọ iwaju"],answer:0},{question:"Ewo ni apakan eto aabo ounje?",options:["Ọwọ́ mimo, irinṣẹ́ mimo, yiyapa ati ipamọ́ to dara","Didanwo ounje aimọ nipa jijẹ","Kikọ aami silẹ","Lilo aṣọ idọti kan fun gbogbo nkan"],answer:0}]}
 ],
 finalAssessment:{mcq:[{question:"Kí ló le ba oúnjẹ jẹ?",options:["Ọwọ́ ti ko mọ́","Kikọ ninu iwe","Kika apoti ti o tii","Yiya aworan eweko"],answer:0},{question:"Kí ni pataki fun fifọ ọwọ́?",options:["Omi to ni aabo ati ọṣẹ","Iyanrin","Oje","Epo"],answer:0},{question:"Ṣe irisi mimo nikan le jẹrisi ailewu?",options:["Rárá","Bẹẹni","Ti o ba tutu nikan","Ti o ba wa ninu yara nikan"],answer:0},{question:"Kí ló de ti a fi ya ounje aise si ounje to setan lati je?",options:["Lati dinku idoti koja","Lati yi awo pada","Lati fi iwe pamọ","Lati yago fun fifọ"],answer:0},{question:"Kí ni o yẹ kí o dari ipamọ́ ti o ko ba da ọ loju?",options:["Aami ati itosona to gbẹkẹle","Asọtẹlẹ","Oorun nikan","Idahun AI ti a ko ṣayẹwo"],answer:0},{question:"Kí ni atokọ ayẹwo imototo fun?",options:["Lati jẹ ki iṣe han ati se ayẹwo","Lati ropo ọṣẹ","Lati jẹrisi èrè","Lati yago fun abojuto"],answer:0},{question:"Báwo ni a yẹ kí a lo imọran AI lori aabo ounje?",options:["Gẹgẹ bi imọran ti a gbọdọ ṣayẹwo","Gẹgẹ bi aṣẹ ikẹhin","Dipo aami","Dipo agbalagba"],answer:0},{question:"Ewo ni iṣe to ni ojuse?",options:["Ri iṣoro, tun un se, ki o jẹrisi","Fi iṣoro pamọ","Tẹsiwaju pelu ewu","Yi igbasilẹ pada"],answer:0}],theory:["Ṣàlàyé ọna mẹta ti idoti le wọ ounje ati ọna idena fun ọkọọkan.","Ṣàlàyé ilana fifọ ọwọ́ pipe ati akoko mẹta ti o ṣe pataki.","Ṣàlàyé idoti kọja pelu apẹẹrẹ kan.","Ṣàlàyé idi ti aami ati itosona to gbẹkẹle fi yẹ lati dari ipamọ́.","Fun apẹẹrẹ kan ti AI le ran lọwọ ninu ẹ̀kọ́ aabo ounje ati idi ti a fi gbọdọ ṣayẹwo rẹ."],practical:"Ṣe àfihàn fifọ ọwọ́ pipe, lẹhinna lo atokọ ayẹwo imototo lati ṣayẹwo ibi ounje afarawe. Ri iṣe to dara mẹta, iṣoro meji, atunse to yẹ ati ọna kan lati jẹrisi atunse."},
 evidence:["Àwòrán ọna idoti","Káàdì igbesẹ mẹfa fifọ ọwọ́","Àfihàn fifọ ọwọ́","Atokọ Mimo/Nilo Atunse","Àwòrán yiyapa","Káàdì ipinnu ipamọ́","Ayẹwo Aabo Ounje","Igbasilẹ ayẹwo olukọ"],
 passport:["K: ṣàlàyé idoti, imototo ọwọ́, yiyapa ati ipamọ́","P: ṣe àfihàn fifọ ọwọ́ ati ayẹwo imototo","D: lo atokọ ayẹwo ati jẹrisi imọran AI/dijital","S: tẹle opin aabo ounje to ba ọjọ ori mu","E: so imototo, eto iṣẹ ati didara pọ mọ iṣẹ/owo to ni ojuse","L: sọ iṣoro aabo, ṣiṣẹ pọ ati jẹrisi atunse"],
 trainerNotes:["Fi gbogbo ilana han ṣaaju ki akẹ́kọ̀ọ́ ṣe e.","Lo apẹẹrẹ ounje agbegbe lai kẹgan asa tabi agbegbe kankan.","Ma jẹ ki ọmọ mu kemika lewu, omi gbigbona, irinṣẹ́ didasilẹ ti ko ba ọjọ ori mu tabi ounje aise to lewu.","Tẹle itosona ilera agbegbe ti o ba ni alaye to peye ju.","Ṣe ayẹwo ohun ti akẹ́kọ̀ọ́ le fi han, kii ṣe oro ti o ranti nikan.","Jẹ ki ẹ̀kọ́ iṣowo dojukọ didara, iṣẹ ati ojuse; ko si dandan fun ọmọde lati ta ọja."],
 remediation:"Pada si ilana mẹta: ọwọ́ mimo, oju ilẹ̀ mimo ati yiyapa ifọwọkan ewu. Lo aworan, àfihàn ati atunwi atokọ ayẹwo.",
 extension:"Akẹ́kọ̀ọ́ ṣe apẹrẹ ilana ailewu fun iṣẹ siseto eso ni ile-iwe, ri ibi ti idoti le ṣẹlẹ ati ṣàlàyé bi a ṣe le ṣayẹwo gbogbo iṣakoso.",
 imagePrompts:[]
};