import type { PF01Module } from "./pf-01";

type PF08Module = Omit<PF01Module,"code"> & { code:"PF-08" };

export const pf08Ig: PF08Module = {
 code:"PF-08", title:"Aka Dị Ọcha, Nri Dị Nchekwa", level:"Pathways Foundation", age:"Ihe dị ka afọ 8–11; gbanwee ọrụ omume dabere na njikere ụmụakwụkwọ na nduzi nchekwa nri mpaghara.", duration:"Nkuzi ndu 6 tinyere omume ịdị ọcha na nyocha", fieldworkHours:3,
 bigQuestion:"Kedu ka aka dị ọcha, ngwaọrụ dị ọcha na ijikwa nri nke ọma ga-esi chebe mmadụ na nri?",
 whyItMatters:"Nchekwa nri na-amalite site n'omume kwa ụbọchị. Modul a na-akụzi mmetọ nri, ịsa aka, idebe ebe ọrụ ọcha, ikewapụ nri, nchekwa nri na nkwurịta okwu nwere ọrụ, n'enweghị ikpughe ụmụaka na kemịkal dị ize ndụ, nri anụ adịghị esi nke nwere nnukwu ihe egwu, ma ọ bụ ọrụ ire ahịa.",
 outcomes:["Kọwaa etu nje, unyi, mmiri na-adịghị nchebe na njikwa nri na-adịghị mma nwere ike imetọ nri.","Gosi usoro zuru ezu nke ịsa aka n'oge kwesịrị ekwesị.","Chọpụta omume dị ọcha na nke na-adịghị ọcha n'ihe gbasara elu na ngwaọrụ na-emetụ nri.","Kọwaa ihe kpatara nri ụfọdụ adịghị esi kwesịrị ịdị iche na nri dị njikere iri.","Ghọta na nchekwa nri dabere n'ụdị nri, oge, okpomọkụ na nduzi a pụrụ ịtụkwasị obi.","Jiri ndepụta nyocha ịdị ọcha nyochaa ma meziwanye ọrụ a na-elekọta.","Nyochaa ndụmọdụ AI ma ọ bụ dijitalụ site na isi mmalite a pụrụ ịtụkwasị obi."],
 vocabulary:["nchekwa nri","ịdị ọcha","mmetọ","nje","ọcha","unyi","ịsa aka","ịsacha","ncha","elu","ngwaọrụ","ikewapụ","nchekwa","okpomọkụ","mkpofu","ndepụta nyocha","ihe akaebe"],
 materials:["ebe ịsa aka nwere mmiri dị nchebe","ncha","usoro ihicha aka dị ọcha","kaadị usoro","ngwaọrụ na akpa ngosi dị ọcha","kaadị ọnọdụ nchekwa nri","akwụkwọ nwaakwụkwọ","ndepụta nyocha ịdị ọcha","ngwa dijitalụ onye nkuzi na-achịkwa ma ọ bụrụ na ọ dị"],
 safety:["Jiri naanị ihe ngosi onye nkuzi kwadoro; a naghị achọ ka ụmụakwụkwọ rie ihe maka ule.","Ụmụaka ekwesịghị ijide anụ adịghị esi, akwa adịghị esi, kemịkal nhicha dị ize ndụ ma ọ bụ ngwa esi nri dị ọkụ.","Hichaa mmiri wụfuru ozugbo.","Ejila anya, isi ma ọ bụ ụtọ naanị kpebie na nri dị nchebe.","Kwanyere ihe nfụkasị nri, iwu okpukpe na mkpa ndị nwere nkwarụ ùgwù.","Nyochaa ndụmọdụ AI gbasara nchekwa nri site na nduzi mpaghara na ntuziaka onye nkuzi."],
 lessons:[
  {id:"PF-08-L1",title:"Otu Nri Si Enwe Ike Ịghọ Ihe Na-adịghị Nchebe",objective:"Mata ụzọ mmetọ nwere ike isi site n'aka, mmiri, elu ma ọ bụ nri ọzọ banye na nri a ga-eri.",teaching:["Mmetọ pụtara na ihe na-achọghị ma ọ bụ ihe na-emerụ ahụ abanyela na nri.","Aka, mmiri ruru unyi, ngwaọrụ na-adịghị ọcha, ụmụ ahụhụ na mmetụ n'etiti nri nwere ike ibufe mmetọ.","Ụfọdụ nje na-emerụ ahụ anaghị ahụ anya, isi ma ọ bụ ụtọ."],activity:"Jiri kaadị onyonyo soro ụzọ mmetọ wee kọwaa ebe a pụrụ igbochi ụzọ ọ bụla.",diy:"Mepụta eserese ISI MMETỌ → MMETỤ → NRI → MGBOCHI.",aiLayer:"AI 1 — Ịmata: lelee ihe atụ AI ma kewaa ha dịka kwe omume, ejighị n'aka ma ọ bụ na-ezighi ezi.",enterprise:"Ndị na-akụ ihe, ndị na-ahazi nri na ndị na-ere nri na-echekwa uru site n'igbochi mmetọ tupu ọ mee.",quiz:[{question:"Gịnị bụ mmetọ nri?",options:["Ihe na-achọghị ma ọ bụ ihe na-emerụ ahụ ịbanye na nri","Ime ka nri mara mma","Ịgụ ngwugwu","Ịkụ mkpụrụ"],answer:0},{question:"Anyị nwere ike ịhụ nje niile na-emerụ ahụ?",options:["Mba","Ee mgbe niile","N'ime mmiri naanị","N'elu ígwè naanị"],answer:0},{question:"Gịnị nwere ike ibufe mmetọ?",options:["Aka ruru unyi","Akwụkwọ mechiri emechi","Pensụl dị ọcha","Kabinet efu"],answer:0}]},
  {id:"PF-08-L2",title:"Saa Aka Nke Ọma",objective:"Gosi mgbe na otu esi asa aka nke ọma tupu ọrụ metụtara nri.",teaching:["Saa aka tupu ijide nri na mgbe emechara ihe nwere ike ime ka aka metọọ.","Ịsa aka nke ọma chọrọ mmiri dị nchebe, ncha, ịsacha akụkụ aka niile, ịsacha ncha pụọ na ihicha aka n'ụzọ dị ọcha.","Ịtụ mmiri naanị n'aka anaghị dochie ịsa aka na ncha."],activity:"Onye nkuzi gosipụta usoro, ụmụakwụkwọ wee mee ya abụọ abụọ site na kaadị usoro na ndepụta nyocha.",diy:"Mepụta kaadị usoro isii ma gosi usoro ahụ n'enweghị enyemaka.",aiLayer:"AI 2 — Nyocha usoro: tụnyere usoro nwaakwụkwọ na nke AI wee chọpụta nzọụkwụ furu efu ma ọ bụ nke nọ ebe na-ezighi ezi.",enterprise:"Omume ịdị ọcha a pụrụ ịdabere na ya bụ akụkụ bụ isi nke njikwa ogo n'ọrụ nri.",quiz:[{question:"Gịnị ka a chọrọ maka ịsa aka?",options:["Mmiri dị nchebe na ncha","Aja naanị","Mmanụ","Agba"],answer:0},{question:"Kedu mgbe a kwesịrị ịsa aka?",options:["Tupu ijide nri na mgbe ihe nwere ike imetọ aka","Otu ugboro n'izu","Mgbe erichara nri naanị","Ọ dịghị mgbe"],answer:0},{question:"Gịnị mere eji akpọọ aka nkụ n'ụzọ dị ọcha?",options:["Ka aka dị ọcha ghara imetọ ọzọ","Ka nri dị ụtọ","Iji tụọ mmiri","Iji dochie ncha"],answer:0}]},
  {id:"PF-08-L3",title:"Ngwaọrụ Dị Ọcha na Elu Dị Ọcha",objective:"Kewaa ihe dị ọcha na omume nwere ike ime ka ha metọọ ọzọ.",teaching:["Elu na ngwaọrụ na-emetụ nri kwesịrị ịdị ọcha tupu eji ha.","Akwa ma ọ bụ ngwaọrụ ruru unyi nwere ike gbasaa mmetọ.","Nhicha kwesịrị iso usoro ndị okenye kwadoro na ntuziaka ngwaahịa."],activity:"Nyochaa tebụl ngosi wee mata omume ọma na omume na-adịghị mma.",diy:"Mepụta ndepụta ỌCHA / CHỌRỌ NLEKỌTA nwere ihe asatọ a pụrụ ịhụ anya.",aiLayer:"AI 3 — Nyocha nduzi: tụnyere ndepụta klaasị na nke AI, debe naanị ihe kwesịrị afọ na ọnọdụ mpaghara.",enterprise:"Nhicha na nyocha mgbe niile na-ebelata mmebi ngwaahịa na nsogbu ogo.",quiz:[{question:"Gịnị ka a ga-eme n'elu ebe nri ga-emetụ tupu eji ya?",options:["Hichaa ya nke ọma","Kpuchie ya n'ala","Elela ya anya","Jiri ya maka ihe niile n'enweghị nhicha"],answer:0},{question:"Akwa ruru unyi nwere ike gbasaa mmetọ?",options:["Ee","Mba","N'èzí naanị","N'abalị naanị"],answer:0},{question:"Gịnị bụ ọrụ ndepụta nyocha?",options:["Ileba anya ma a na-eme ihe achọrọ","Ikwado uru ahịa","Dochie ịsa aka","Izobe nsogbu"],answer:0}]},
  {id:"PF-08-L4",title:"Kewapụ Ụfọdụ Nri",objective:"Kọwaa ihe kpatara ụfọdụ nri na ngwaọrụ kwesịrị ịdị iche iji belata mmetọ gafee.",teaching:["Mmetọ gafee na-eme mgbe mmetọ si n'otu nri, elu ma ọ bụ ngwaọrụ gaa na nke ọzọ.","Nri anụ adịghị esi nwere ike ibufe ihe egwu gaa na nri dị njikere iri.","N'ogo a, ụmụakwụkwọ na-eji onyonyo na ngwa ngosi dị ọcha; ndị okenye na-elekọta nri adịghị esi nke nwere nnukwu ihe egwu."],activity:"Kewaa kaadị n'ime ADỊGHỊ ESI / DỊ NJIKERE IRI / NGWA DỊ ỌCHA ma họrọ ebe dị iche iche.",diy:"See mapu dị mfe nke na-egosi etu ebe nkwadebe nri ga-esi kewapụ ihe ize ndụ na nri dị njikere iri.",aiLayer:"AI 4 — Echiche ọnọdụ: lelee ọnọdụ kichin AI wee mata ụzọ mmetụ na-adịghị nchebe.",enterprise:"Nhazi ọrụ ọma na-ebelata ụzọ mmetọ nwere ike isi gbasaa.",quiz:[{question:"Gịnị bụ mmetọ gafee?",options:["Mmetọ ịkwaga site n'otu ihe gaa na nke ọzọ","Isi nri n'otu ụzọ","Ịgụ ihe oriri","Ịkụ mkpụrụ abụọ"],answer:0},{question:"Gịnị mere e ji kewapụ nri anụ adịghị esi na nri dị njikere iri?",options:["Iji belata nnyefe ihe egwu","Iji gbanwee agba","Iji chekwaa akwụkwọ","Iji zere nhicha"],answer:0},{question:"Ụmụaka kwesịrị ijide anụ adịghị esi na modul a?",options:["Mba","Ee n'enweghị nlekọta","Ọ bụrụ na AI kwuru ya","Site n'aka efu"],answer:0}]},
  {id:"PF-08-L5",title:"Chekwaa Nri Nke Ọma",objective:"Ghọta na nchekwa nri dabere n'ụdị nri, oge, okpomọkụ, ịdị ọcha na nduzi a pụrụ ịdabere na ya.",teaching:["Nri dị iche iche nwere mkpa nchekwa dị iche iche.","Nri na-emebi ngwa ngwa nwere ike ịchọ njikwa okpomọkụ.","Aha ngwaahịa, nduzi mpaghara na ndị okenye kwesịrị iduzi mkpebi nchekwa."],activity:"Kewaa ihe atụ n'ime JỤ OKELE / NCHEKWA AKỌRỌ AKỌRỌ / NCHEKWA A NA-EJIKWA OKPOMỌKỤ.",diy:"Mepụta kaadị: MATA NRI → NYOCHAA AHA/NDUZI → JIRI AKPA DỊ ỌCHA → TINYE N'EZIGBO EBE → NYOCHAA ỌZỌ.",aiLayer:"AI 5 — Nkwenye: tụnyere ndụmọdụ nchekwa AI na aha ngwaahịa ma ọ bụ nduzi onye nkuzi kwadoro.",enterprise:"Nchekwa kwesịrị ekwesị na-echekwa ihe eji arụ ọrụ, na-ebelata mkpofu ma na-edobe ogo.",quiz:[{question:"Nri niile nwere otu mkpa nchekwa?",options:["Mba","Ee","Ngwugwu naanị ka dị iche","Mkpụrụ osisi naanị"],answer:0},{question:"Gịnị ka a ga-eleba anya ma ị maghị?",options:["Nduzi a pụrụ ịdabere na ya ma ọ bụ aha ngwaahịa","Amụma","Anya naanị","Asịrị"],answer:0},{question:"Gịnị mere eji akpa dị ọcha?",options:["Iji chebe nri pụọ na mmetọ","Iji dochie oyi","Iji kwado na nri agaghị emebi mgbe niile","Iji zere aha"],answer:0}]},
  {id:"PF-08-L6",title:"Mee Nnyocha Omume Nchekwa Nri",objective:"Jiri ihe ọmụma ịdị ọcha nyochaa ebe mmụta a na-elekọta ma tụọ aro mmezi dabere na ihe akaebe.",teaching:["Nchekwa nri bụ usoro: aka dị ọcha, mmiri dị nchebe, ngwaọrụ dị ọcha, ikewapụ, nchekwa kwesịrị ekwesị na nlekọta.","Ndepụta nyocha na-eme ka iwu bụrụ omume a pụrụ ịhụ.","Ọ bụrụ na achọpụtara nsogbu, kwụsị, dozie ya n'enweghị ihe egwu, wee dekọọ ihe a gbanwere."],activity:"Ndị otu nyochaa ebe nri emere dịka ihe atụ, dee ihe ise ha hụrụ ma họrọ mmezi abụọ.",diy:"Mezue NYOCHA NCHEKWA NRI: NYOCHAA → CHỌPỤTA → DOZIE → KWADO → DEE.",aiLayer:"Njikọ — Nyocha dabere na ihe akaebe: tụnyere nnyocha otu na nke AI ma jụ aro na-emegide ihe akaebe, aha ngwaahịa ma ọ bụ iwu mpaghara.",enterprise:"Nkwado ogo pụtara igbochi nsogbu, idekọ nyocha na idozi mmejọ tupu ngwaahịa ma ọ bụ ọrụ erute onye ọrụ.",quiz:[{question:"Gịnị ka a ga-eme ma achọpụta ọnọdụ na-adịghị nchebe?",options:["Kwụsị ma dozie ya n'enweghị ihe egwu","Zoo ya","Gaa n'ihu","Hichapụ ndekọ"],answer:0},{question:"Gịnị mere eji akwado na mmezi rụpụtara?",options:["Iji mara na e doziri nsogbu n'ezie","Iji mee akwụkwọ ogologo","Iji zere ọrụ","Iji kwado ihe niile n'ọdịnihu"],answer:0},{question:"Kedu nke bụ akụkụ nke usoro nchekwa nri?",options:["Aka dị ọcha, ngwaọrụ dị ọcha, ikewapụ na nchekwa","Ịtọ nri amaghị ụtọ","Ileghara aha anya","Iji otu akwa ruru unyi maka ihe niile"],answer:0}]}
 ],
 finalAssessment:{mcq:[{question:"Gịnị nwere ike imetọ nri?",options:["Aka ruru unyi","Ide n'akwụkwọ","Ịgụ ngwugwu mechiri emechi","Ise osisi"],answer:0},{question:"Gịnị dị mkpa maka ịsa aka?",options:["Mmiri dị nchebe na ncha","Aja","Juice","Mmanụ"],answer:0},{question:"Ịdị ọcha n'anya naanị na-egosi na nri dị nchebe mgbe niile?",options:["Mba","Ee","Ọ bụrụ na oyi naanị","Ọ bụrụ na ọ nọ n'ime ụlọ naanị"],answer:0},{question:"Gịnị mere eji kewapụ nri adịghị esi na nri dị njikere iri?",options:["Iji belata mmetọ gafee","Iji gbanwee agba","Iji chekwaa akwụkwọ","Iji zere nhicha"],answer:0},{question:"Gịnị kwesịrị iduzi nchekwa ma ị maghị?",options:["Aha na nduzi a pụrụ ịdabere na ya","Amụma","Isi naanị","Azịza AI a na-enyochaghị"],answer:0},{question:"Gịnị ka ndepụta nyocha ịdị ọcha na-eme?",options:["Na-eme ka omume bụrụ ihe a pụrụ ịhụ ma nyochaa","Dochie ncha","Kwado uru ahịa","Zere nlekọta"],answer:0},{question:"Kedu ka ndụmọdụ AI gbasara nchekwa nri kwesịrị isi jiri ya?",options:["Dịka aro a ga-enyocha","Dịka ikike ikpeazụ","Dochie aha ngwaahịa","Dochie okenye"],answer:0},{question:"Kedu omume nwere ọrụ?",options:["Chọpụta nsogbu, dozie ya, wee kwado mmezi","Zoo nsogbu","Gaa n'ihu n'agbanyeghị ihe egwu","Gbanwee ndekọ"],answer:0}],theory:["Kọwaa ụzọ atọ mmetọ nwere ike isi ruo nri na otu mgbochi maka nke ọ bụla.","Kọwaa usoro zuru ezu nke ịsa aka na oge atọ ọ dị mkpa.","Kọwaa mmetọ gafee site n'otu ihe atụ.","Kọwaa ihe kpatara aha ngwaahịa na nduzi a pụrụ ịdabere na ya ji dị mkpa maka nchekwa nri.","Nye otu ụzọ AI nwere ike isi nyere aka n'ịmụ nchekwa nri na ihe kpatara a ga-eji nyochaa azịza ya."],practical:"Gosi usoro ịsa aka zuru ezu, jiri ndepụta ịdị ọcha nyochaa ebe nri atụ. Chọpụta omume ọma atọ, nsogbu abụọ, mmezi kwesịrị ekwesị na otu ụzọ iji kwado mmezi."},
 evidence:["Akwụkwọ eserese ụzọ mmetọ","Kaadị usoro isii nke ịsa aka","Ngosipụta ịsa aka","Ndepụta Ọcha/Chọrọ Nlekọta","Mapu ikewapụ","Kaadị mkpebi nchekwa","Nnyocha Nchekwa Nri","Ndekọ nyocha onye nkuzi"],
 passport:["K: kọwaa mmetọ, ịdị ọcha aka, ikewapụ na nchekwa","P: gosi ịsa aka ma mee nnyocha ịdị ọcha","D: jiri ndepụta nyocha ma kwado ndụmọdụ AI/dijitalụ","S: soro oke nchekwa nri kwesịrị afọ","E: jikọta ịdị ọcha, usoro ọrụ na ogo na ọrụ azụmahịa nwere ọrụ","L: kọọ nsogbu nchekwa, rụọ ọrụ ọnụ ma kwado mmezi"],
 trainerNotes:["Gosi usoro ọ bụla tupu ụmụakwụkwọ emee ya.","Jiri ihe atụ nri mpaghara n'enweghị ileda omenala ma ọ bụ obodo anya.","Ekwela ka ụmụaka jiri kemịkal dị ize ndụ, mmiri esi ọkụ, ngwa dị nkọ na-adịghị kwesị afọ ma ọ bụ nri adịghị esi nke dị nnukwu ihe egwu.","Soro nduzi ahụike ọha mpaghara ma ọ bụrụ na ọ na-enye nkọwa kpọmkwem.","Tulee omume nwaakwụkwọ gosiri, ọ bụghị naanị okwu o chetara.","Mee ka akụkụ azụmahịa lekwasị anya na ogo, ọrụ na ibu ọrụ; ụmụaka anaghị achọ ire ngwaahịa."],
 remediation:"Laghachi na omume atọ: aka dị ọcha, elu dị ọcha na ikewapụ mmetụ dị ize ndụ. Jiri onyonyo, ngosipụta na omume ndepụta nyocha ugboro ugboro.",
 extension:"Nwaakwụkwọ chepụta usoro ọrụ dị nchebe maka nkwadebe mkpụrụ osisi n'ụlọ akwụkwọ, chọpụta ebe mmetọ nwere ike ime ma kọwaa otu esi enyocha njikwa ọ bụla.",
 imagePrompts:[]
};