import type { PF01Module } from "./pf-01";

export const pf01Ha: PF01Module = {
  code:"PF-01", title:"Barka da Zuwa Koyo da Dama", level:"Pathways Foundation", age:"Kusan shekaru 8–11; a sanya ɗalibi bisa tantancewar koyo, ba shekaru kaɗai ba.", duration:"Darussa 6 masu jagora tare da aikin hannu da lokacin tantancewa", fieldworkHours:2,
  bigQuestion:"Ta yaya koyo zai taimaka mini in fahimci kaina, al’ummata da damar da ke kewaye da ni?",
  whyItMatters:"Yawancin ɗaliban da ke shiga Pathways sun fuskanci katsewar makaranta, ƙarancin damar ilimi ko rashin samun ilimin boko gaba ɗaya. Wannan modu yana gina jin kasancewa, ƙarfin gwiwa, hanyoyin koyo masu aminci da alaƙa tsakanin koyo, rayuwar yau da kullum da damar gaba.",
  outcomes:["Bayyana menene LIFEWS Pathways da dalilin da ya sa kake son koyo.","Gane ƙarfinka, abubuwan da kake sha’awa da wuraren da kake son bunƙasa.","Gane mutane, wurare da halaye masu aminci a wajen koyo.","Saita manufa ta koyo mai yiwuwa a kusa kuma ka gano matakan cimma ta.","Gane cewa ƙwarewa masu amfani na iya ƙara daraja ga iyali da al’umma.","Yi amfani da aikin dijital ko AI cikin kulawar baligi cikin alhaki."],
  vocabulary:["koyo","dama","manufa","ƙarfi","ƙwarewa","al’umma","zaɓi","motsa jiki","shaida","alhaki"],
  materials:["takarda ko littafin ɗalibi","fensir/crayon","katunan hoto","taswirar al’umma","samfurin katin manufa","na’urar hannu ko waya da ake rabawa ƙarƙashin kulawar mai koyarwa idan akwai"],
  safety:["Kada a tilasta wa ɗalibi ya bayyana abin da ya taɓa masa zuciya.","Yi amfani da kalmomi masu kyau waɗanda ba sa ƙasƙantar da tarihin makarantar ɗalibi.","Ana amfani da na’urar dijital ƙarƙashin kulawar mai koyarwa; kada ɗalibi ya ba AI bayanan sirri.","Ayyukan biyu-biyu da na ƙungiya su haɗa ’yan mata, masu nakasa da waɗanda ƙwarewar karatunsu ke tasowa."],
  lessons:[
    {id:"PF-01-L1",title:"Ina Da Matsayi A Nan",objective:"Bayyana Pathways a matsayin wuri mai aminci don koyo, yin atisaye da shirya makoma.",teaching:["Koyo na iya faruwa a aji, lambu, gida, bita da cikin al’umma.","Ɗalibai na iya farawa daga matakai daban; inda ka fara ba ya ƙayyade abin da za ka iya zama.","Pathways yana haɗa koyo da ƙwarewar aiki da damar gaba."],activity:"Ƙirƙiri yarjejeniyar aji da hotuna ko kalmomi game da mutuntawa, sauraro, shiga aiki, tsaro da kulawa.",diy:"Yi katin ‘Ni ɗalibi ne’ da hoto ko alamar wani abu da kake son koya.",aiLayer:"AI Mataki 1 — Ganewa: mai koyarwa ya nuna kayan aikin da za su iya amsa tambaya ko tsara bayanai, sannan ya bayyana cewa AI kayan aiki ne, ba mutum ko hukuma ba.",enterprise:"Ƙirƙirar daraja na farawa da warware matsala mai amfani. Ɗalibai su ambaci aikin taimako guda ɗaya da ake yi a al’ummarsu.",quiz:[{question:"Wane aiki ne ke taimakawa wajen sa wurin koyo ya zama mai aminci?",options:["Sauraro cikin mutuntawa","Yi wa kuskure dariya","Boye kayan aiki","Hana wasu magana"],answer:0},{question:"A ina koyo zai iya faruwa?",options:["A makaranta kaɗai","A intanet kaɗai","A wurare da yawa","A wurin aiki kaɗai"],answer:2},{question:"Me ya kamata ka yi idan ba ka fahimta ba?",options:["Ka nuna kamar ka gane","Ka nemi taimako","Ka tafi","Ka kwafa ba tare da tunani ba"],answer:1}]},
    {id:"PF-01-L2",title:"Ƙarfina da Abubuwan da Nake Sha’awa",objective:"Gano aƙalla ƙarfi ko sha’awa biyu kuma ka bayyana yadda atisaye zai bunƙasa su.",teaching:["Ƙarfi ya haɗa da abubuwan da za mu iya yi, yadda muke taimakawa da kyawawan halaye.","Sha’awa ita ce abin da muke jin daɗin koya ko yi.","Ƙwarewa na ƙaruwa da atisaye mai aminci, shawarwari da dagewa."],activity:"Da’irar ƙarfi: ɗalibai su zaɓi katunan hoto na ayyukan da suke so ko suke iya yi, su bayyana zaɓi ɗaya ga abokin aiki.",diy:"Yi garkuwar ƙarfi mai sassa uku: Zan iya…, Ina son…, Ina son inganta….",aiLayer:"AI Mataki 2 — Mu’amala mai jagora: tare da mai koyarwa, kwatanta abin da mutane suka lura da shi game da ƙarfi da jerin da AI ya bayar; tattauna dalilin da ya sa mutane ne za su tabbatar da abin da ya dace.",enterprise:"Ƙarfi daban-daban na iya zama ƙwarewa masu amfani. Haɗa misalan auna da kyau, noma, gyara, bayani ko tsarawa da bukatun al’umma.",quiz:[{question:"Ƙarfi shi ne…",options:["wani abu mai amfani da za ka iya bunƙasa","hukunci","gini","farashi"],answer:0},{question:"Ƙwarewa yawanci na inganta ta…",options:["atisaye","ɓoyewa","hasashe kaɗai","janyewa"],answer:0},{question:"Wace magana ce ke nuna tunanin ci gaba?",options:["Ba zan iya koya ba","Zan iya inganta da atisaye","Wasu kaɗai ke da ƙwarewa","Kuskure yana kawo ƙarshen koyo"],answer:1}]},
    {id:"PF-01-L3",title:"Koyo A Kewaye da Ni",objective:"Gane damar koyo a kullum cikin abinci, ruwa, makamashi, gida da al’umma.",teaching:["Karanta alama, kirga abubuwa, auna ruwa da lura da tsire-tsire duk koyo ne.","Tsarin abinci-makamashi-ruwa yana cikin rayuwar yau da kullum.","Lura sosai yana taimaka mana mu yi tambayoyi masu kyau."],activity:"Yawon koyo: gano abubuwa biyar da suka ƙunshi karatu, kirga, auna, lura ko yanke shawara.",diy:"Zana taswirar ‘koyo a kewaye da ni’ da aƙalla wurare huɗu da ƙwarewar da ake amfani da ita a kowane wuri.",aiLayer:"AI Mataki 3 — Rarrabewa: raba katunan hoto zuwa abinci, makamashi, ruwa ko fiye da rukuni ɗaya; mai koyarwa zai iya nuna wata rarrabewar AI sannan ɗalibai su duba ta.",enterprise:"Gano wata bukata a gari da wata ƙwarewa da za ta taimaka, ba tare da sa yara yin tallace-tallace ba.",quiz:[{question:"Auna ruwa na amfani da…",options:["lissafi","barci","shiru","sa’a"],answer:0},{question:"Lura yana nufin…",options:["duba da kyau","manta","ɓoye","sayarwa"],answer:0},{question:"Wanne zai iya zama aikin koyo?",options:["Karanta alamar kasuwa","Jarabawa kaɗai","Aikin gida kaɗai","Babu"],answer:0}]},
    {id:"PF-01-L4",title:"Manufofi da Ƙananan Matakai",objective:"Saita manufa ta koyo guda ɗaya a sarari sannan ka raba ta zuwa matakai masu yiwuwa.",teaching:["Manufa tana bayyana abin da muke son cimmawa.","Ana iya raba kyakkyawar manufa zuwa ƙananan ayyuka.","Shaida tana taimaka mana mu ga ci gaba."],activity:"Mayar da buri kamar ‘Ina son karatu na ya fi kyau’ zuwa matakan atisaye uku da za a iya gani.",diy:"Yi matattarar manufa ta kwana bakwai da ƙaramin aiki guda, mai taimako da hanyar nuna ci gaba.",aiLayer:"AI Mataki 4 — Tambaya cikin iyaka: mai koyarwa ya nuna yadda za a nemi ra’ayoyin atisaye uku daga AI; ɗalibai su tantance wanne ya fi aminci, yiwuwa da amfani.",enterprise:"Tsare-tsare na da amfani a koyo da sana’a: manufa → albarkatu → aiki → duba sakamako.",quiz:[{question:"Manufa mai amfani ya kamata ta samu…",options:["matakai a sarari","babu aiki","babu hanyar duba","buri kaɗai"],answer:0},{question:"Shaidar ci gaba na iya zama…",options:["shafin atisaye da aka kammala","jita-jita","babu komai","aikin wani"],answer:0},{question:"Idan mataki ya yi wuya, ya kamata ka…",options:["raba shi zuwa ƙananan matakai","ka daina nan take","ka ɓoye shi","ka zargi wani"],answer:0}]},
    {id:"PF-01-L5",title:"Zaɓi Masu Aminci da Alhaki",objective:"Gane zaɓi masu aminci a koyo, dijital da al’umma kuma ka san lokacin neman taimakon baligi amintacce.",teaching:["Tsaro ya haɗa da lafiyar jiki, zuciya da dijital.","Ba a ba mutanen da ba a sani ba ko kayan AI bayanan sirri.","Baligi amintacce na iya taimakawa idan wani abu yana da haɗari ko rikitarwa."],activity:"Raba katunan yanayi zuwa AMINCI, TAMBAYI BALIGI, da BA AMINCI BA, sannan a tattauna dalili.",diy:"Yi hannun taimako: mutum ko sabis mai aminci ɗaya a kowane yatsa, da sunaye ko alamomin da suka dace.",aiLayer:"AI Mataki 5 — Warware matsala cikin alhaki: duba amsar AI ta ƙirƙira sannan a gano bayanan da ya kamata a tabbatar da su da malami ko baligi amintacce.",enterprise:"Aiki cikin alhaki yana nufin gaskiya, tsaro, kula da albarkatu da adalci ga wasu.",quiz:[{question:"Ya kamata ka ba AI adireshin gidanka?",options:["A’a","Kullum","Don wasa kaɗai","Duk lokacin da ya tambaya"],answer:0},{question:"Idan wani abu yana da haɗari, mataki mai kyau shi ne…",options:["faɗa wa baligi amintacce","ɓoye shi","bi baƙo","raba bayanan sirri"],answer:0},{question:"Aiki cikin alhaki ya haɗa da…",options:["gaskiya da tsaro","lalata kayan aiki","yaudara","ware wasu"],answer:0}]},
    {id:"PF-01-L6",title:"Taswirar Koyona da Dama",objective:"Haɗa ƙarfi, manufofi, damar al’umma da mutanen tallafi cikin taswirar koyo ta kanka.",teaching:["Hanyar koyo tana haɗa inda muke yanzu da matakai na gaba.","Mutane na iya samun hanyoyi daban-daban kuma su canja manufofi yayin da suke koyo.","Tallafi, atisaye da shaida suna taimakawa ɗalibi ya ci gaba."],activity:"Duba modu sannan ka zaɓi ƙarfi ɗaya, manufa ɗaya, ƙwarewar aiki ɗaya, mai taimako ɗaya da mataki na gaba.",diy:"Ƙirƙiri ka gabatar da taswira: NI → ƘARFI → MANUFA → ATISAYE → MAI TAIMAKO → MATAKI NA GABA.",aiLayer:"Haɗawa: mai koyarwa na iya amfani da AI wajen ba da misalan matakai na gaba; ɗalibi da mai koyarwa su zaɓi zaɓi masu dacewa da shekaru, masu aminci kuma masu yiwuwa a wurin.",enterprise:"Haɗa ƙarfi da ƙirƙirar daraja: taimakawa, yin abu, noma, gyara, bayyana ko tsarawa—ba tare da ɗaukar yara a matsayin ma’aikatan kasuwanci ba.",quiz:[{question:"Hanyar koyo ita ce…",options:["hanya daga yanzu zuwa mataki na gaba","hukunci","aiki guda ɗaya na dindindin","sirri"],answer:0},{question:"Wa ya kamata ya zaɓi manufar koyonka tare da kai?",options:["kai tare da tallafin da ya dace","baƙo","AI kaɗai","babu kowa"],answer:0},{question:"Me ya kamata ya kasance a taswirar dama?",options:["ƙarfi da matakai na gaba","password na sirri","umarni mai haɗari","bayanin wani"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Menene ɗaya daga manufofin Pathways?",options:["Tallafawa koyo da ci gaba","Dakatar da aikin hannu","Maye gurbin duk shawarar iyali","Sa kowa bin hanya ɗaya"],answer:0},{question:"Me ke taimakawa ƙwarewa ta inganta?",options:["Atisaye da shawara","Janyewa","Ɓoye kuskure","Guje wa tambaya"],answer:0},{question:"Kyakkyawar manufa ta koyo ya kamata ta kasance…",options:["a sarari kuma za a iya aiwatarwa","ba za a iya dubawa ba","ta wani","sirri ga masu taimako"],answer:0},{question:"Wanne hali na dijital ne mai aminci?",options:["Kare bayanan sirri","Raba password","Ba baƙo adireshi","Yarda da kowace amsar AI"],answer:0},{question:"Menene shaida?",options:["Abin da ke nuna abin da ka yi ko ka koya","Hasashe","Jita-jita","Hukunci"],answer:0},{question:"Ƙirƙirar daraja na iya nufin…",options:["warware matsala mai amfani","cutar da wasu","ɓarnatar da albarkatu","ɓoye ƙwarewa"],answer:0},{question:"Idan amsar AI ta yi kamar ba daidai ba, ya kamata ka…",options:["tabbatar da ita da ingantaccen bayani ko mai koyarwa","ka yarda da ita kullum","ka raba nan take","ka saka bayanan sirri"],answer:0},{question:"Wanne ya fi bayyana hanyar koyo?",options:["Jerin matakai masu yiwuwa zuwa manufa","Hanya ɗaya da kowa dole ya bi","Jarabawar makaranta kaɗai","Password"],answer:0}],theory:["Bayyana abubuwa biyu da kake son koya da dalilin da ya sa suke da muhimmanci.","Ambaci ƙarfi biyu da kake da su da hanyar yin atisaye a kowanne.","Bayyana ƙa’idoji uku da ke sa wurin koyo ya zama mai aminci da mutuntawa.","Bayyana wata bukatar al’umma da ƙwarewar da za ta taimaka.","Bayyana dalilin da ya sa ya kamata ɗalibi ya tabbatar da muhimman bayanan da AI ya bayar da mutum ko tushen da ake yarda da shi."],practical:"Gabatar da Taswirar Koyo da Dama mai ɗauke da ƙarfi ɗaya, manufa ɗaya, aƙalla ƙananan matakai uku, ƙwarewar aiki ɗaya, mai taimako amintacce ɗaya, abu ɗaya na shaida da damar gaba da ta dace da shekaru."},
  evidence:["Garkuwar ƙarfi da aka kammala","Matattarar manufa ta kwana bakwai","Hannun taimako amintacce","Taswirar koyo a kewaye da ni","Taswirar Koyo da Dama ta ƙarshe","Rubutun lura da aikin ɗalibi na mai koyarwa"],
  passport:["K: yana bayyana koyo, manufofi da dama","P: yana ƙirƙira da gabatar da taswirar koyo mai amfani","D: yana nuna amfani da AI cikin jagora tare da kula da sirri","S: yana gane zaɓi masu aminci da masu taimako amintattu","E: yana gane ƙwarewa a matsayin hanyar ƙirƙirar daraja ga al’umma","L: yana saita manufa, bayyana ƙarfi kuma yana shiga cikin mutuntawa"],
  trainerNotes:["Yi amfani da baki, hoto da nunawa ga ɗaliban da karatunsu ke tasowa.","Kada a kwatanta ɗalibai bisa tarihin makarantar da suka yi.","Yi amfani da misalan gida da sana’o’i amma kada a tura yara zuwa aiki mai haɗari ko wanda bai dace da shekaru ba.","’Yan mata da maza su riƙa musayar matsayin jagoranci, kayan aiki da gabatarwa.","Ayyukan AI zaɓi ne idan babu na’ura ko intanet; a koyar da ƙwarewar tunani da ke ƙasa ba tare da intanet ba."],
  remediation:"Sake koyar da muhimman abubuwa da hotuna masu jere, kwaikwayon rawa da saita manufa kai-tsaye. Rage nauyin rubutu amma a bar manufar ƙwarewa yadda take.",
  extension:"Ɗalibi ya tattauna da baligi amintacce game da ƙwarewar da ya koya yana ƙarami, sannan ya ƙara hanyar koyon a taswirar damar al’umma.",
  imagePrompts:[]
};