import type { PF01Module } from "./pf-01";

type PF04Module = Omit<PF01Module,"code"> & { code:"PF-04" };

export const pf04Ig: PF04Module = {
  code:"PF-04",
  title:"Osisi Gbara Anyị G gburugburu",
  level:"Pathways Foundation",
  age:"Ihe dịka afọ 8–11; a ga-ahazi ọrụ aka ka ha kwekọọ na ọnọdụ obodo na mkpa ụmụ akwụkwọ.",
  duration:"Ihe ọmụmụ nduzi isii tinyere nlele, ọrụ ubi na nyocha",
  fieldworkHours:3,
  bigQuestion:"Gịnị ka osisi pụrụ ịkụziri anyị gbasara nri, mmiri, nlekọta, ngwaahịa bara uru na ebe anyị bi?",
  whyItMatters:"Osisi bụ ụzọ dị mfe ịbanye na sayensị, usoro nri na nlele bara uru. Modul a na-enyere ụmụ akwụkwọ aka ịmata akụkụ osisi, tụnyere osisi bara uru, ghọta mkpa uto bụ isi ma jikọta osisi na nri, ụzọ ndụ, nlekọta gburugburu na mmụta GreenSkills n’ọdịnihu.",
  outcomes:["Mata akụkụ osisi ndị bụ isi ma kọwaa ọrụ dị mfe nke ha.","Kewaa mgbọrọgwụ, azuokokoosisi, akwụkwọ, ifuru, mkpụrụ osisi na mkpụrụ site n’ihe atụ obodo.","Kọwaa mkpa osisi dịka mmiri, ìhè, ikuku, nri na oghere.","Lelee ma deba ọdịiche dị mfe n’etiti osisi.","Jikọta osisi na nri, ihe eji eme ihe, ndo, mma na ụzọ ndụ.","Mezue nlele na ọrụ nlekọta osisi dị nchebe n’okpuru nduzi ma jiri ihe akaebe."],
  vocabulary:["osisi","mgbọrọgwụ","azuokokoosisi","akwụkwọ","ifuru","mkpụrụ osisi","mkpụrụ","ala","mmiri","ìhè anyanwụ","nri","lelee","tụnyere","nlekọta","owuwe ihe ubi"],
  materials:["ihe atụ osisi obodo dị nchebe ma ọ bụ osisi dị ndụ","magnifying glass ma ọ bụrụ na ọ dị","akwụkwọ na pensụl","kaadị onyonyo akụkụ osisi","obere akpa ma ọ bụ akwa ubi","akpa ịwụ mmiri","aha-akara","tablet/ekwentị n’okpuru njikwa onye nduzi maka ntụnyere onyonyo ma ọ bụrụ na ọ dị mkpa"],
  safety:["Erila osisi a na-amaghị.","Zere osisi nsi, ndị na-akpasu ahụ iwe ma ọ bụ ndị nwere ogwu n’ọrụ ụmụaka.","Saa aka mgbe emechara ala ma ọ bụ ihe osisi.","Jiri naanị ngwaọrụ ụmụaka dị nchebe n’okpuru nlekọta.","Hazie ọrụ maka ụmụ akwụkwọ nwere allergy ma ọ bụ nsogbu mmegharị.","Ejila azịza AI naanị kpebie na osisi amaghi ama dị mma iri ma ọ bụ ọgwụ."],
  lessons:[
    {id:"PF-04-L1",title:"Mata Otu Osisi",objective:"Ghọta osisi dịka ihe dị ndụ nwere akụkụ na mkpa a pụrụ ịhụ.",teaching:["Osisi bụ ihe dị ndụ na-eto ma na-agbanwe.","Osisi dị iche iche nwere ike ịdị iche nke ukwuu ma kesaa ụfọdụ àgwà.","Nlele nlezianya na-enyere anyị aka ịkọwa ihe anyị hụrụ tupu anyị akọwa ihe kpatara ya."],activity:"Lelee osisi obodo abụọ dị nchebe ma dee ma ọ bụ see ihe atọ ha yiri na ihe atọ ha dị iche.",diy:"Mepụta kaadị nlele osisi nwere eserese, ebe ọ dị, ntule nha na àgwà abụọ a na-ahụ anya.",aiLayer:"AI Ogo 1 — Ịmata: onye nduzi gosipụta otú AI si akọwa onyonyo ma mata àgwà a na-ahụ anya, ụmụ akwụkwọ tụnyere ya na nlele ha.",enterprise:"Ndị mmadụ na-emepụta uru site n’ịkụ, ilekọta, ibuga na iji osisi n’ọrụ n’ụzọ nwere ọrụ.",quiz:[{question:"Osisi bụ…",options:["ihe dị ndụ","igwe","nkume","nọmba"],answer:0},{question:"Onye na-ele nke ọma kwesịrị…",options:["ilebara anya","tụọ n’amaghị ama","mebie osisi","leghara ọdịiche anya"],answer:0},{question:"Osisi abụọ nwere ike…",options:["kesaa ụfọdụ àgwà ma dị iche n’ụfọdụ","dị otu mgbe niile","ghara ịchọ mmiri","ghara inwe akụkụ"],answer:0}]},
    {id:"PF-04-L2",title:"Mgbọrọgwụ, Azuokokoosisi na Akwụkwọ",objective:"Mata mgbọrọgwụ, azuokokoosisi na akwụkwọ ma kọwaa ọrụ ha bụ isi.",teaching:["Mgbọrọgwụ na-enyere osisi aka ịnọgide n’ala ma na-amị mmiri na nri.","Azuokokoosisi na-akwado akwụkwọ ma na-ebufe mmiri na ihe ndị ọzọ n’ime osisi.","Akwụkwọ na-ejide ìhè ma nyere osisi aka ime nri."],activity:"Jikọta ihe atụ ma ọ bụ onyonyo na MGBỌRỌDGỤ, AZUOKOKOOSISI na AKWỤKWỌ, wee soro ụzọ mmiri nwere ike isi n’ala gaa elu.",diy:"Wuo ụdị osisi dị mfe nwere aha-akara site na akwụkwọ, osisi nta ma ọ bụ ihe a na-emegharị eji.",aiLayer:"AI Ogo 2 — Ntụnyere nduzi: jiri ngwa onyonyo onye nduzi na-achịkwa tụnyere mgbọrọgwụ, azuokokoosisi ma ọ bụ akwụkwọ pụrụ iche, wee nyochaa ya site n’ihe ọmụmụ a tụkwasịrị obi.",enterprise:"Ịghọta akụkụ osisi na-enyere ndị na-akụ ihe aka ijikwa ihe ọkụkụ nke ọma ma belata mmebi.",quiz:[{question:"Kedu akụkụ na-ejide osisi n’ala?",options:["mgbọrọgwụ","ifuru","mkpụrụ osisi","aha-akara"],answer:0},{question:"Akwụkwọ na-ejidekarị…",options:["ìhè","ego","plastik","mkpọtụ"],answer:0},{question:"Azuokokoosisi na-enyere…",options:["nkwado na mbufe","ihichapụ mgbọrọgwụ","ịkwụsị uto","dochie ala"],answer:0}]},
    {id:"PF-04-L3",title:"Ifuru, Mkpụrụ Osisi na Mkpụrụ",objective:"Kọwaa njikọ dị n’etiti ifuru, mkpụrụ osisi na mkpụrụ site n’ihe atụ dị mfe.",teaching:["Ọtụtụ osisi na-ama ifuru na-emepụta ifuru dịka akụkụ ọmụmụ.","Mkpụrụ osisi na-echebe ma ọ bụ na-eburu mkpụrụ.","Mkpụrụ nwere ike ito bụrụ osisi ọhụrụ ma ọnọdụ dị mma."],activity:"Kewaa ihe atụ osisi ma ọ bụ onyonyo dị nchebe n’otu ifuru, mkpụrụ osisi na mkpụrụ, tụlee njikọ ha.",diy:"Mepụta kaadị usoro atọ IFURU → MKPỤRỤ OSISI → MKPỤRỤ site n’otu ihe ọkụkụ a maara.",aiLayer:"AI Ogo 3 — Usoro na nhazi: tụnyere usoro ndụ ụmụ akwụkwọ kere na usoro onye nduzi sitere na AI, wee chọpụta mmejọ.",enterprise:"Mkpụrụ, mkpụrụ osisi na ifuru nwere ike ịbụ ngwaahịa bara uru, mana ogo na-adabere na mmepụta na njikwa dị nchebe.",quiz:[{question:"Mkpụrụ nwere ike…",options:["ito bụrụ osisi ọhụrụ","ghọọ ígwè","dochie mmiri","mee ọkụ eletrik ozugbo"],answer:0},{question:"Mkpụrụ osisi na-enwekarị…",options:["mkpụrụ","ngwaọrụ","waya","nkume naanị"],answer:0},{question:"Kedu usoro na-adịkarị ziri ezi?",options:["ifuru → mkpụrụ osisi → mkpụrụ","mkpụrụ → ígwè → mkpụrụ osisi","akwụkwọ → batrị → mgbọrọgwụ","ala → waya → ifuru"],answer:0}]},
    {id:"PF-04-L4",title:"Ihe Osisi Chọrọ",objective:"Mata ọnọdụ bụ isi osisi chọrọ ka ha too nke ọma.",teaching:["Osisi chọrọ mmiri, ìhè, ikuku, nri na oghere kwesịrị ekwesị.","Obere ma ọ bụ ọtụtụ ihe karịrị akarị nwere ike ibute nsogbu.","Osisi dị iche iche nwere ike ịchọ mmiri, ìhè na oghere n’ogo dị iche."],activity:"Tụnyere seedlings abụọ yiri ibe ha etinyere n’ọnọdụ abụọ dị nchebe ma buru amụma ihe nwere ike ime.",diy:"Mepụta wheel mkpa-osisi na-egosi mmiri, ìhè, ikuku, nri na oghere.",aiLayer:"AI Ogo 4 — Amụma: onye nduzi jụọ AI maka amụma n’otu ọnọdụ nlekọta osisi; ụmụ akwụkwọ tụnyere ya na ihe akaebe sitere na nlele ha.",enterprise:"Njikwa akụrụngwa ọma nwere ike belata mmefu mmiri, ihe ala na ihe ịkụ.",quiz:[{question:"Kedu otu mkpa osisi bụ isi?",options:["mmiri","egwuregwu plastik","paswọọdụ","agba"],answer:0},{question:"Mmiri karịrị akarị nwere ike imerụ ụfọdụ osisi?",options:["Ee","Mba, ọ dịghị mgbe","N’abalị naanị","N’ịntanetị naanị"],answer:0},{question:"Osisi dị iche iche nwere ike ịchọ…",options:["ogo akụrụngwa dị iche","otu nlekọta mgbe niile","enweghị ìhè","enweghị oghere"],answer:0}]},
    {id:"PF-04-L5",title:"Osisi Bara Uru Gbara Anyị G gburugburu",objective:"Kewaa osisi a maara dịka ọrụ ha n’ime nri, ndo, ihe eji eme ihe, mma ma ọ bụ ụzọ ndụ.",teaching:["Otu osisi nwere ike inwe ọtụtụ ojiji.","Ndị mmadụ na-adabere na osisi maka nri na ọtụtụ ihe eji eme ihe.","Iji osisi n’ọrụ n’ụzọ nwere ọrụ gụnyere ilekọta ala, mmiri na ihe ga-adị n’ọdịnihu."],activity:"Mepụta tebụl ojiji osisi n’obodo nwere ngalaba dịka nri, ndo, eriri/ihe eji eme ihe, ịchọ mma na ego/ụzọ ndụ.",diy:"Jụọ onye okenye ị tụkwasịrị obi gbasara otu osisi obodo bara uru, deba akụkụ a na-eji na otú e si elekọta ya.",aiLayer:"AI Ogo 5 — Nkwenye: onye nduzi gosipụta na AI nwere ike ịtụ aro ojiji osisi, mana njirimara obodo na nkwupụta nchekwa ga-enyocha site n’aka ndị mmadụ ma ọ bụ isi mmalite a tụkwasịrị obi.",enterprise:"Nyochaa otú ihe ọmụma osisi si akwado nursery, ugbo, nhazi nri, landscaping na ụzọ ndụ ndị ọzọ na-acha akwụkwọ ndụ n’enweghị ịnye ụmụaka ọrụ azụmahịa.",quiz:[{question:"Otu osisi nwere ike inwe ọtụtụ ojiji?",options:["Ee","Mba","Osisi a bubatara naanị","Osisi ukwu naanị"],answer:0},{question:"Ozi ojiji osisi kwesịrị…",options:["enyocha izi ezi ya","bụ ihe e chepụtara","hapụ ya n’enweghị nchekwa","dabere na AI naanị"],answer:0},{question:"Iji osisi n’ọrụ n’ụzọ nwere ọrụ gụnyere…",options:["ilekọta akụrụngwa","imefusị ihe","mmebi","owuwe ihe ubi n’enweghị nchekwa"],answer:0}]},
    {id:"PF-04-L6",title:"Lekọta Osisi Dị Ndụ",objective:"Tinye nlele na nlekọta bụ isi n’ọrụ n’osisi a na-elekọta ma deba ihe akaebe mgbanwe.",teaching:["Nlekọta osisi bụ usoro: lelee → kpebie → mee → nyochaa.","Ndekọ na-enyere anyị aka ịhụ mgbanwe n’oge.","Nlekọta ọma na-ezere imefusị ihe ma zaghachi ezigbo mkpa osisi."],activity:"N’otu abụọ, lelee osisi ma ọ bụ obere akwa ubi, chọpụta otu mkpa nlekọta ma mee ihe n’okpuru nlekọta dịka ịwụ mmiri, mulching ma ọ bụ iwepụ ihe mkpofu dị nchebe.",diy:"Debe ndekọ nlekọta osisi ugboro atọ nwere ụbọchị, nlele, ihe emere na nsonaazụ.",aiLayer:"Njikọta: tụnyere mkpebi nlekọta gị na aro AI onye nduzi nyere, wee kwado nhọrọ ikpeazụ site n’ihe akaebe a hụrụ na nduzi obodo.",enterprise:"Nlekọta a pụrụ ịdabere na ya, ide ndekọ na nlele ogo bụ àgwà ọrụ bụ isi n’ugbe na ọrụ ndụ akwụkwọ ndụ.",quiz:[{question:"Kedu usoro nlekọta bara uru?",options:["lelee → kpebie → mee → nyochaa","mee → leghara → chefuo","tụọ → mefuo → pụọ","detuo → zoo → kwụsị"],answer:0},{question:"Gịnị mere e ji edebe ndekọ nlekọta osisi?",options:["iji soro mgbanwe","iji zoo ihe akaebe","iji zere nlele","iji dochie osisi"],answer:0},{question:"Mkpebi nlekọta ọma kwesịrị iji…",options:["nlele na nduzi a tụkwasịrị obi","ịtụ n’amaghị ama","paswọọdụ nzuzo","ntuziaka dị ize ndụ"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Kedu akụkụ osisi na-amịkarị mmiri site n’ala?",options:["Mgbọrọgwụ","Ifuru","Mkpụrụ osisi","Mkpụrụ naanị"],answer:0},{question:"Kedu akụkụ na-ejidekarị ìhè?",options:["Akwụkwọ","Mgbọrọgwụ","Mkpụrụ osisi naanị","Aha-akara"],answer:0},{question:"Gịnị ka mkpụrụ nwere ike bụrụ ma ọnọdụ dị mma?",options:["Osisi ọhụrụ","Ígwè","Plastik","Batrị"],answer:0},{question:"Kedu mkpa osisi bụ isi?",options:["Mmiri","Paswọọdụ","Agba","Mmanụ naanị"],answer:0},{question:"Gịnị mere e ji atụnyere osisi?",options:["Iji hụ ihe ha yiri na ihe ha dị iche","Iji mebie ha","Iji zere mmụta","Iji mee ka ha bụrụ otu"],answer:0},{question:"AI naanị nwere ike ikwenye na osisi amaghi ama dị mma iri?",options:["Mba","Ee mgbe niile","Ọ bụrụ na foto doro anya naanị","Ọ bụrụ na nwa jụrụ naanị"],answer:0},{question:"Kedu ihe bụ ezigbo ihe akaebe nlekọta osisi?",options:["Ndekọ nlele nwere ụbọchị","Asịrị","Ntule n’enweghị nlele","Ọrụ onye ọzọ na-abụghị nke a"],answer:0},{question:"Ihe ọmụma osisi nwere ike kwado ụzọ ndụ site na…",options:["ịkụ, nursery, processing na nlekọta","imefusị ihe naanị","njikwa n’enweghị nchekwa","izo ozi"],answer:0}],theory:["Kpọọ akụkụ bụ isi nke otu osisi ị maara ma kọwaa otu ọrụ nke nke ọ bụla.","Kọwaa ihe ise osisi nwere ike ịchọ ka ha too nke ọma.","Kọwaa otu osisi obodo bara uru na ụzọ abụọ ndị mmadụ si eji ya.","Kọwaa ihe mere ndekọ nlekọta osisi ji nyere onye na-akụ ihe aka ime mkpebi ka mma.","Kọwaa ihe mere ozi AI gbasara osisi amaghi ama ji kwesị nyocha tupu mmadụ eri ma ọ bụ jiri ya."],practical:"Lelee otu osisi dị ndụ ma dị nchebe, mata opekata mpe akụkụ ma ọ bụ àgwà anọ, nyochaa otu mkpa nlekọta, mee otu ọrụ nlekọta n’okpuru nlekọta, ma gosipụta obere ndekọ ihe akaebe nke nlele, ihe emere na nsonaazụ a tụrụ anya."},
  evidence:["Kaadị nlele osisi","Ụdị akụkụ osisi","Kaadị ifuru-mkpụrụ osisi-mkpụrụ","Wheel mkpa osisi","Tebụl ojiji osisi obodo ma ọ bụ ndekọ ajụjụ ọnụ","Ndekọ nlekọta osisi ugboro atọ","Ndekọ nlele ọrụ aka onye nduzi"],
  passport:["K: na-amata akụkụ osisi, mkpa na ojiji a na-ahụkarị","P: na-eme nlele na ọrụ nlekọta osisi n’okpuru nduzi","D: na-atụnyere aro dijitalụ/AI na ihe akaebe ozugbo na isi mmalite a tụkwasịrị obi","S: na-agbaso iwu nchekwa osisi, ala na ngwaọrụ","E: na-ejikọta ihe ọmụma osisi na ngwaahịa, ọrụ na nlekọta akụrụngwa","L: na-arụkọ ọrụ, na-edeba nlele ma na-ekwupụta mkpebi nlekọta"],
  trainerNotes:["Jiri osisi ụmụ akwụkwọ na-ahụ n’obodo ha mgbe ọ dị nchebe.","Egosi nkwupụta ọgwụ dịka eziokwu kwadoro na modul ntọala a.","Nye nhọrọ ọnụ, onyonyo na tactile maka ndị ka na-amalite ịgụ.","Gbanwee ọrụ nlele, ịwụ mmiri, nha na mkpesa n’ụzọ ziri ezi.","Ọ bụrụ na ubi adịghị, jiri osisi n’akpa ma ọ bụ onyonyo dị mma, tinyere opekata mpe otu nlele osisi dị ndụ n’okpuru nlekọta ma ọ bụrụ na o kwere mee."],
  remediation:"Belata ọnụ ọgụgụ akụkụ osisi a na-akụzi n’otu oge, jiri matching ugboro ugboro na ihe n’ezie ma ọ bụ tactile models, ma mụta usoro lelee–kpọọ aha–ọrụ.",
  extension:"Nwa akwụkwọ mepụta profaịlụ otu peeji nke otu ihe ọkụkụ obodo dị mkpa na-egosi akụkụ osisi, otu mkpa uto, otu ojiji na otu ọrụ nlekọta.",
  imagePrompts:["Ụmụaka Africa afọ 8–11 na-ele osisi ubi dị nchebe na onye nduzi na-enyere ha aka, na-atụ aka na mgbọrọgwụ, azuokokoosisi na akwụkwọ, ubi ụlọ akwụkwọ-obodo na-etinye mmadụ niile, ìhè eke, enweghị ederede a pụrụ ịgụ, agba ndụ ndụ na ọlaedo LIFEWS.","Ihe osise botani maka ụmụaka na-egosi osisi nri na-ama ifuru nwere mgbọrọgwụ, azuokokoosisi, akwụkwọ, ifuru, mkpụrụ osisi na mkpụrụ doro anya, ndabere ọcha, enweghị aha ma ọ bụ ederede.","Obere ìgwè ụmụ akwụkwọ Africa na-awụ mmiri ma na-mulch ubi n’akpa n’okpuru nlekọta ka ha na-edekọ nlele n’akwụkwọ, ngwaọrụ dị nchebe, mmekọrịta, enweghị ederede a pụrụ ịgụ."]
};