import type { PF01Module } from "./pf-01";

type PF02Module = Omit<PF01Module,"code"> & { code:"PF-02" };

export const pf02Fr: PF02Module = {
  code:"PF-02",
  title:"Lire le monde autour de moi",
  level:"Fondation Pathways",
  age:"Environ 8 à 11 ans ; le placement en littératie doit suivre une évaluation de départ.",
  duration:"6 leçons guidées plus pratique de lecture, activité pratique et évaluation",
  fieldworkHours:2,
  bigQuestion:"Comment les mots, les images, les panneaux et les symboles peuvent-ils m’aider à comprendre le monde autour de moi et à agir en sécurité ?",
  whyItMatters:"La littératie de base devient plus utile lorsque les apprenants relient l’écrit à la vie quotidienne. Ce module développe l’observation, le langage oral, le vocabulaire, le décodage et la lecture fonctionnelle à partir de contextes familiers liés à l’alimentation, à l’eau, à l’énergie, au jardin et à la communauté, tout en respectant les différents niveaux de départ.",
  outcomes:[
    "Reconnaître que l’écrit, les images, les panneaux et les symboles transmettent du sens.",
    "Lire et utiliser un ensemble de mots familiers liés à l’environnement et aux systèmes alimentaires.",
    "Associer des mots entendus, des images et des mots écrits.",
    "Utiliser le contexte et l’observation pour proposer puis vérifier un sens.",
    "Créer un support utile combinant image, mot et information.",
    "Utiliser un soutien numérique ou d’IA guidé pour comparer, classer ou vérifier des mots sans partager d’informations privées."
  ],
  vocabulary:["mot","lettre","son","image","panneau","symbole","étiquette","sens","lire","vérifier","aliment","eau","plante","énergie","sécurité"],
  materials:["cartes illustrées adaptées au contexte local","cartes de mots","cartes alphabet/phonétique adaptées à la langue d’enseignement","emballages propres ou étiquettes reproduites","objets sûrs du jardin ou du ménage","papier et feutres","appareil facultatif sous contrôle du facilitateur"],
  safety:[
    "Utiliser uniquement des objets et emballages propres et sûrs.",
    "Ne jamais ridiculiser ou classer les apprenants à partir de leurs erreurs de lecture.",
    "Adapter l’enseignement phonétique à la langue choisie ; ne pas appliquer mécaniquement les règles de l’anglais au haoussa, à l’arabe, au yoruba, à l’igbo ou au français.",
    "Ne pas demander aux apprenants de photographier ou de téléverser des personnes identifiables, des adresses ou des documents privés dans des outils d’IA."
  ],
  lessons:[
    {id:"PF-02-L1",title:"Images, panneaux et sens",objective:"Expliquer comment les images, les panneaux, les symboles et les mots communiquent une information.",teaching:["Nous lisons plus que des livres : nous lisons aussi des panneaux, des symboles, des images, des étiquettes et des situations.","Un symbole peut communiquer rapidement, mais son sens dépend d’une compréhension partagée.","Un bon lecteur observe avant de décider ce que quelque chose signifie."],activity:"Chasse au sens : examiner des panneaux familiers et des cartes illustrées, puis expliquer ce que chacun cherche à communiquer.",diy:"Créer un symbole simple de sécurité ou d’entretien pour le jardin d’apprentissage ou la classe et l’expliquer oralement.",aiLayer:"Couche IA 1 — Reconnaissance : distinguer un panneau créé par une personne, un résultat de recherche numérique et une suggestion générée par IA ; toutes ces sources exigent encore une interprétation humaine.",enterprise:"Des panneaux et des étiquettes clairs aident à comprendre les produits, les lieux et les services ; une bonne communication crée de la valeur pratique.",quiz:[{question:"Qu’est-ce qui peut communiquer du sens ?",options:["Des mots, des images et des symboles","Seulement de longs livres","Seulement des nombres","Rien autour de nous"],answer:0},{question:"Avant de décider ce qu’un panneau signifie, il faut…",options:["observer attentivement","l’ignorer","l’endommager","deviner sans regarder"],answer:0},{question:"Une étiquette sert à…",options:["identifier ou expliquer quelque chose","cacher toute information","rendre la lecture impossible","remplacer la sécurité"],answer:0}]},
    {id:"PF-02-L2",title:"Les mots de l’alimentation, de l’eau et de l’énergie",objective:"Reconnaître et lire des mots fréquents provenant de situations quotidiennes liées aux systèmes alimentaires, à l’eau et à l’énergie.",teaching:["Les mots familiers sont plus faciles à apprendre lorsqu’ils sont reliés à des objets et des actions réels.","Les mots peuvent nommer des choses, des actions et des qualités.","La lecture répétée développe la fluidité et la confiance."],activity:"Passer par des postes de mots sur les aliments, l’eau, les plantes, les outils et l’énergie ; associer chaque carte-mot à une image ou à un objet sûr.",diy:"Créer dix cartes personnelles image-mot et s’entraîner à les lire à un partenaire.",aiLayer:"Couche IA 2 — Interaction guidée : le facilitateur demande à un outil d’IA des phrases simples utilisant certains mots ; les apprenants vérifient si les phrases sont compréhensibles et adaptées au contexte local.",enterprise:"Les personnes ont besoin de mots exacts pour nommer, décrire et organiser des biens et des services utiles.",quiz:[{question:"Qu’est-ce qui aide à apprendre un nouveau mot ?",options:["Le relier à une image ou à un objet","Ne jamais le revoir","Le cacher","Ignorer tous les sons"],answer:0},{question:"La lecture répétée peut améliorer…",options:["la confiance et la fluidité","automatiquement la qualité de l’eau","la météo","la taille d’une batterie"],answer:0},{question:"Lequel est un mot lié au système alimentaire ?",options:["graine","mot de passe","satellite uniquement","silence"],answer:0}]},
    {id:"PF-02-L3",title:"Lettres, sons et parties de mots",objective:"Utiliser des correspondances lettres-sons ou des régularités d’écriture adaptées à la langue pour décoder des mots familiers.",teaching:["Les langues écrites représentent la parole de différentes façons.","On peut rechercher des lettres, des sons, des syllabes ou des parties de mots déjà connues.","Lorsqu’un mot est difficile, on peut ralentir, le segmenter et utiliser le contexte."],activity:"Construire des mots familiers avec des lettres mobiles, des cartes de syllabes ou d’autres unités d’écriture adaptées à la langue d’enseignement.",diy:"Créer une échelle de cinq mots liés et marquer la partie reconnue dans chacun.",aiLayer:"Couche IA 3 — Reconnaissance de motifs : regrouper les mots selon un motif visuel ou sonore, puis comparer ce regroupement avec une suggestion numérique générée par le facilitateur.",enterprise:"La reconnaissance de motifs soutient le comptage précis, l’étiquetage, la tenue de registres et le contrôle qualité.",quiz:[{question:"Lorsqu’un mot est difficile, une bonne stratégie consiste à…",options:["le décomposer en parties plus faciles","abandonner immédiatement","inventer n’importe quel mot","le cacher"],answer:0},{question:"Les six langues du programme utilisent-elles exactement les mêmes règles lettres-sons ?",options:["Non","Oui","Seulement le lundi","Seulement au jardin"],answer:0},{question:"Repérer des parties répétées dans les mots est une forme de…",options:["reconnaissance de motifs","gaspillage","dissimulation","tarification"],answer:0}]},
    {id:"PF-02-L4",title:"Lire des étiquettes et des consignes",objective:"Extraire une information simple et utile d’une étiquette, d’un panneau ou d’une consigne adaptée à l’âge.",teaching:["La lecture fonctionnelle aide à faire des choix sûrs au quotidien.","Les titres, les images, les nombres et les mots-clés peuvent aider à trouver une information.","Il faut demander l’aide d’un adulte de confiance lorsque les informations de sécurité ne sont pas claires."],activity:"Lire des étiquettes préparées par l’enseignant pour des sachets de graines, des contenants d’eau ou des outils de jardin, puis identifier le nom, l’usage et une consigne.",diy:"Créer une étiquette en trois parties pour un objet de classe ou de jardin : NOM → USAGE → ENTRETIEN/SÉCURITÉ.",aiLayer:"Couche IA 4 — Questionnement encadré : le facilitateur montre comment demander une explication simple d’une étiquette non sensible ; les apprenants comparent l’explication avec l’original et repèrent ce qui manque.",enterprise:"Un étiquetage exact soutient la confiance, la sécurité et l’entreprise responsable ; des étiquettes fausses ou ambiguës peuvent nuire aux personnes.",quiz:[{question:"Pourquoi lisons-nous les consignes ?",options:["Pour agir correctement et en sécurité","Pour les faire disparaître","Pour éviter de comprendre","Seulement pour décorer"],answer:0},{question:"Si une information de sécurité n’est pas claire, il faut…",options:["demander à un adulte de confiance","deviner avec un outil dangereux","l’ignorer","modifier l’étiquette"],answer:0},{question:"Une bonne étiquette doit être…",options:["claire et exacte","volontairement trompeuse","illisible","secrète"],answer:0}]},
    {id:"PF-02-L5",title:"Vérifier le sens",objective:"Utiliser le contexte, les images et une aide fiable pour vérifier qu’une interprétation est raisonnable.",teaching:["Un bon lecteur vérifie le sens au lieu d’accepter sa première supposition.","Les images et les mots voisins fournissent des indices de contexte.","Les outils numériques et l’IA peuvent se tromper ; les informations importantes doivent donc être vérifiées."],activity:"Lire de courtes phrases illustrées contenant volontairement un mot qui ne correspond pas, puis identifier et corriger l’erreur.",diy:"Créer une carte ou un marque-page « Lire–Réfléchir–Vérifier » avec trois étapes visuelles.",aiLayer:"Couche IA 5 — Évaluation : le facilitateur présente une description correcte et une description incorrecte générées par IA pour un objet familier ; les apprenants utilisent des indices visibles pour choisir la meilleure.",enterprise:"Vérifier l’information évite les erreurs dans les registres, les étiquettes, les quantités et la communication avec les clients.",quiz:[{question:"Un indice de contexte aide à…",options:["comprendre le sens","oublier le texte","partager des mots de passe","éviter de regarder"],answer:0},{question:"Faut-il accepter automatiquement chaque description générée par IA ?",options:["Non","Oui","Toujours si elle est longue","Seulement si elle est colorée"],answer:0},{question:"Quelle séquence est utile ?",options:["Lire–Réfléchir–Vérifier","Deviner–Cacher–Partir","Copier–Oublier–Partager","Sauter–Sauter–Sauter"],answer:0}]},
    {id:"PF-02-L6",title:"Mon guide image-mot",objective:"Créer et présenter un guide fonctionnel image-mot en utilisant un vocabulaire et des étiquettes exacts.",teaching:["Les auteurs choisissent l’information en fonction d’un public et d’un objectif.","Un guide utile doit être organisé, lisible et exact.","Créer de l’information est aussi une responsabilité : on vérifie avant de partager."],activity:"Planifier un mini-guide sur un thème : jardin scolaire, eau propre, ingrédients alimentaires, utilisation sûre de l’énergie ou apprentissage communautaire.",diy:"Produire un guide image-mot de six entrées avec une image, un mot-clé et un court fait ou une consigne pour chaque entrée, puis le lire ou le présenter aux autres.",aiLayer:"Intégration : l’IA peut proposer des mots ou des phrases simples sous contrôle du facilitateur ; l’apprenant doit sélectionner, corriger et expliquer le contenu final.",enterprise:"Un produit d’information clair crée de la valeur par la communication et le design ; la qualité signifie utilité, exactitude et soin.",quiz:[{question:"Qu’est-ce qu’un public ?",options:["Les personnes pour lesquelles l’information est créée","Seulement l’auteur","Un type de graine","Un mot de passe"],answer:0},{question:"Avant de partager un guide, il faut…",options:["vérifier son exactitude","ajouter des données privées","enlever toutes les étiquettes","copier sans lire"],answer:0},{question:"Un bon produit d’information doit être…",options:["utile et compréhensible","trompeur","dangereux","impossible à lire"],answer:0}]}
  ],
  finalAssessment:{
    mcq:[
      {question:"Quel est un exemple de lecture fonctionnelle ?",options:["Lire un panneau de sécurité","Ignorer une étiquette","Cacher un mot","Détruire des consignes"],answer:0},
      {question:"Qu’est-ce qui aide à comprendre un mot inconnu ?",options:["Le contexte et les parties du mot","Fermer la page","Deviner au hasard","Ignorer tous les indices"],answer:0},
      {question:"Pourquoi les images sont-elles utiles au début de l’apprentissage de la lecture ?",options:["Elles peuvent soutenir le sens","Elles rendent les mots inutiles pour toujours","Elles remplacent la sécurité","Elles garantissent toute interprétation"],answer:0},
      {question:"Quelle qualité est importante pour une étiquette ?",options:["L’exactitude","La tromperie","La confusion","Le secret"],answer:0},
      {question:"Que faut-il faire avant de partager une information importante produite par IA ?",options:["La vérifier","Rien","Ajouter des données privées","Ignorer le texte source"],answer:0},
      {question:"Quelle séquence aide à lire avec attention ?",options:["Observer–Lire–Réfléchir–Vérifier","Deviner–Partager–Oublier","Cacher–Copier–Partir","Se presser–Ignorer–Publier"],answer:0},
      {question:"Pourquoi l’enseignement de la littératie peut-il différer entre l’anglais, l’arabe et le yoruba ?",options:["Leurs systèmes d’écriture et de sons diffèrent","Toutes les langues sont identiques","Une seule possède des mots","Elles ne peuvent pas être enseignées"],answer:0},
      {question:"Un guide image-mot crée de la valeur lorsqu’il est…",options:["utile, clair et exact","faux","dangereux","illisible"],answer:0}
    ],
    theory:["Expliquez trois choses de votre communauté que l’on peut « lire » en dehors des livres.","Choisissez cinq mots familiers et expliquez une stratégie utilisée pour les reconnaître ou les décoder.","Expliquez comment les images ou les indices de contexte peuvent aider à comprendre un nouveau mot.","Expliquez pourquoi les étiquettes et les consignes doivent être exactes et faciles à comprendre.","Décrivez une façon de vérifier une explication numérique ou produite par IA avant de l’utiliser."],
    practical:"Créer et présenter oralement un guide image-mot de six entrées sur un thème familier lié à l’alimentation, à l’eau, à l’énergie, au jardin ou à l’apprentissage communautaire. Chaque entrée doit contenir un visuel pertinent, un mot-clé exact et un court fait ou une consigne produit par l’apprenant. Le facilitateur évalue la reconnaissance, le sens, l’organisation, l’exactitude et la communication plutôt que la seule écriture."
  },
  evidence:["Dix cartes personnelles image-mot","Échelle de motifs de mots","Étiquette fonctionnelle en trois parties","Carte Lire–Réfléchir–Vérifier","Guide image-mot de six entrées","Fiche d’observation du facilitateur sur la lecture orale et la compréhension"],
  passport:["K : reconnaît que les mots, panneaux, symboles et textes fonctionnels sont des sources de sens","P : crée et utilise des étiquettes et un guide d’information image-mot","D : utilise un soutien numérique/IA guidé pour classer ou vérifier le langage tout en protégeant la vie privée","S : lit les informations de sécurité de base ou demande de l’aide","E : explique pourquoi une communication et un étiquetage exacts créent de la valeur et de la confiance","L : lit ou présente devant les autres, accepte les retours et vérifie son travail avant de le partager"],
  trainerNotes:["Enseigner la littératie dans la langue d’instruction choisie ; adapter le décodage et la phonétique à cette langue au lieu de traduire mécaniquement la phonétique anglaise.","Autoriser les réponses orales, le tracé, l’appariement et la sélection d’images pendant que la littératie se développe.","Utiliser des objets locaux et des images culturellement familières sans recourir aux stéréotypes.","Pour l’arabe, utiliser des supports RTL appropriés ; pour le yoruba et l’igbo, préserver les signes diacritiques nécessaires ; pour le français, enseigner les relations sons-graphies pertinentes.","Évaluer la compréhension et les progrès, pas l’accent."],
  remediation:"Réduire le nombre de mots actifs, augmenter les associations image-objet, utiliser la lecture orale répétée et un travail multisensoriel sur les lettres ou syllabes, tout en conservant le même objectif de littératie fonctionnelle.",
  extension:"L’apprenant réalise, sous supervision, un audit des panneaux et étiquettes de l’espace d’apprentissage et propose une nouvelle étiquette ou une amélioration pour l’accessibilité ou la sécurité.",
  imagePrompts:["Leçon photoréaliste de littératie fondamentale en Afrique, garçons et filles de 8 à 11 ans associant des cartes illustrées à des mots sur les plantes, l’eau, les aliments et des objets simples liés à l’énergie, facilitateur bienveillant, espace communautaire propre, aucun texte lisible, accents LIFEWS vert et jaune chaleureux.","Illustration éducative adaptée aux enfants montrant l’observation d’un sachet de graines, d’un récipient d’eau, d’un symbole de plante et d’un panneau de sécurité avec une loupe, fond blanc propre, uniquement des icônes, sans texte.","Petit groupe photoréaliste d’enfants africains créant un guide image-mot avec des dessins de cultures du jardin et d’objets liés à l’eau, crayons et cartes sur la table, collaboration inclusive, lumière naturelle, aucun texte lisible."]
};