import type { PF01Module } from "./pf-01";

type PF05Module = Omit<PF01Module,"code"> & { code:"PF-05" };

export const pf05Ha: PF05Module = {
  code:"PF-05",
  title:"Iri da Fara Tsiro",
  level:"Pathways Foundation",
  age:"Kimanin shekaru 8–11; sanya ɗalibi da ba shi rawar aiki ya dogara da shirinsa.",
  duration:"Darussa 6 masu jagoranci tare da binciken tsiro na kwanaki 7–10 da tantancewa",
  fieldworkHours:3,
  bigQuestion:"Me ke cikin iri, me ke taimaka masa ya fara girma, kuma ta yaya za mu gwada ra’ayoyinmu da shaida?",
  whyItMatters:"Iri yana haɗa abinci, noma, bambancin halittu da hanyoyin rayuwa na gaba. Ta binciken tsiro, ɗalibai suna koyon lura, fair test, aunawa, rubuta bayanai, kula da albarkatu, amfani da AI cikin alhaki da tunanin sana’a na farko, tare da samar da shaida daga tsarin halitta mai rai.",
  outcomes:["Gane iri a matsayin tsarin shuka mai rai wanda zai iya samar da sabuwar shuka a yanayi mai dacewa.","Gane siffofin iri na yau da kullum da bambanta iri da abubuwan da ba iri ba.","Bayyana cewa tsiro yana bukatar danshi, iska da zafin jiki mai dacewa, yayin da ƙaramar shuka bayan fitowa kuma take bukatar haske da gina jiki.","Shirya gwajin tsiro mai sauƙi da adalci inda sharadi guda ɗaya kawai ya canza.","Lura, ƙirga, auna da rubuta shaidar tsiro a tsawon lokaci.","Duba shawarar dijital ko AI da tunani sannan a tabbatar da ita da gwaji da tushe mai aminci.","Haɗa ingancin iri, kulawa da shi da rubuta bayanai da samar da abinci da aikin nursery cikin alhaki."],
  vocabulary:["iri","tsiro","fatar iri","embryo","danshi","iska","zafin jiki","ƙaramar shuka","tushe","harbi","variable","lura","auna","rubuta","kwatanta","shaida"],
  materials:["iri na gida masu aminci kamar wake, masara ko wake fari","kofuna masu bayyane ko kwantena marasa zurfi","auduga mai tsabta, tawul ɗin takarda ko matsakaicin shuka mai dacewa","ruwa mai tsabta","lakabi","fensir da littafin ɗalibi","ma’auni","grid na ƙirga ko tebur mai sauƙi","na’urar dijital ta zaɓi ƙarƙashin kulawar mai koyarwa"],
  safety:["Yi amfani da iri sanannu, marasa guba, waɗanda mai koyarwa ya bayar ko amince da su kawai.","Irin da aka yi amfani da su wajen gwaji ba don ci ba ne bayan an taɓa su ko sun fara tsiro.","A wanke hannu kafin da bayan aikin hannu kuma a kiyaye wurin aiki da tsabta.","A goge ruwan da ya zube da sauri don hana zamewa.","Kada a bari ɗalibai su taɓa sinadaran seed-treatment ko magungunan kashe ƙwari.","Shawarar AI game da seed treatment, sinadarai ko amincin abinci ba za ta taɓa maye gurbin umarnin mai koyarwa ko umarnin samfur ba."],
  lessons:[
    {id:"PF-05-L1",title:"Iri Na Iya Zama Shuka",objective:"Gane iri da bayyana rawarsa wajen fara sabuwar shuka.",teaching:["Iri yana ɗauke da ƙaramin shuka da ajiyar abinci waɗanda fatar iri ke karewa.","Iri na bambanta da girma, launi, siffa da taɓawa.","Ba kowane ƙaramin abu ne iri ba; tantancewa ya kamata ta dogara da lura da bayani mai aminci."],activity:"Rarraba haɗin iri masu aminci da abubuwan da ba iri ba, sannan a bayyana kowane iri da girma, launi, siffa da yanayin samansa.",diy:"Ƙirƙiri katin lura da iri shida da zane ko samfur, suna idan an sani, da siffofi biyu da ake gani ga kowanne.",aiLayer:"Matakin AI 1 — Ganewa da tambaya: kwatanta bayanin ɗalibi da bayanin AI ƙarƙashin kulawar mai koyarwa sannan a gano abin da za a iya tabbatarwa ta lura kai tsaye.",enterprise:"Masu samar da iri da nurseries suna ƙirƙirar ƙima ta samar da kayan dasa shuki da aka tantance daidai, masu rai da kuma bayanai masu inganci.",quiz:[{question:"Me iri mai kyau zai iya samarwa?",options:["Sabuwar shuka","Kayan ƙarfe","Baturi","Kwalbar roba"],answer:0},{question:"Wace siffa za ka iya gani kai tsaye?",options:["Launin iri","Farashin sayarwa na gaba","Kalmar sirri da ba a gani","Yawan amfanin gona da aka tabbatar"],answer:0},{question:"Me ya sa ake tantance iri da kyau?",options:["Iri daban-daban suna haifar da shuke-shuke daban-daban","Duk iri iri ɗaya ne","Lakabi ba ya da muhimmanci","Zato yana ƙara inganci"],answer:0}]},
    {id:"PF-05-L2",title:"Abin da ke Cikin Iri",objective:"Gane fatar iri, ajiyar abinci da embryo ta lura da iri da aka jika cikin aminci.",teaching:["Fatar iri tana kare cikin iri.","Yawancin iri suna da ajiyar abinci da ke tallafawa farkon ci gaba.","Embryo shi ne ƙaramin shuka da ke fara ci gaba yayin tsiro."],activity:"Mai koyarwa ya shirya wake ko cowpea da aka jika. Ɗalibai su buɗe iri ɗaya a hankali su kwatanta abin da ke ciki da zane, ba tare da ɗanɗana ba.",diy:"Yi babban samfurin iri da takarda ko kayan sake amfani da su wanda ke nuna murfin kariya, ajiyar abinci da ƙaramin shuka.",aiLayer:"Matakin AI 2 — Bayani da kwatantawa: nemi bayani mai sauƙi kan sassan iri sannan a duba kowace magana da ainihin irin da zane mai aminci.",enterprise:"Fahimtar tsarin iri yana bayyana dalilin da ya sa mu’amala mai tsauri, ajiya mara kyau da kwari ke rage ingancin iri.",quiz:[{question:"Me ke kare wajen iri da yawa?",options:["Fatar iri","Fatar fure","Waya","Murfin baturi"],answer:0},{question:"Menene embryo?",options:["Ƙaramar shuka mai tasowa","Kayan lambu","Wani nau’in ƙasa","Lakabin kunshi"],answer:0},{question:"Me ya sa iri zai iya samun ajiyar abinci?",options:["Don tallafawa farkon ci gaba","Don samar da wutar lantarki","Don maye gurbin iska","Don zama roba"],answer:0}]},
    {id:"PF-05-L3",title:"Abin da Tsiro Ke Bukata",objective:"Bayyana muhimman sharuddan tsiro da bambanta su da bukatun ƙaramar shuka bayan fitowa.",teaching:["Yawancin iri suna bukatar danshi, oxygen da zafin jiki mai dacewa domin tsiro.","Ruwa kaɗan zai iya hana tsiro; ruwa mai yawa zai iya rage iska da ƙara matsala.","Bukatar haske na bambanta tsakanin iri, kuma bayan fitowa ƙananan tsire-tsire suna bukatar haske da gina jiki masu dacewa."],activity:"Yi amfani da hotunan yanayi don hasashen ko iri zai tsiro idan ya bushe, ya sami danshi mai kyau, ya nutse, ya yi zafi sosai ko ya kasance a wani yanayi mara kyau, sannan a bayyana dalili.",diy:"Yi dabaran bukatun tsiro wanda ya raba SHARUDDAN TSIRO da BUKATUN ƘARAMAR SHUKA DAGA BAYA.",aiLayer:"Matakin AI 3 — Hasashe: kwatanta hasashen AI na yanayi biyu da hasashen ɗalibai, sannan a nuna abin da gwajin zai iya gwadawa a zahiri.",enterprise:"Tsiro mai kyau yana rage ɓarnar iri, ruwa, sarari da aiki a noma da nursery.",quiz:[{question:"Wace haɗuwa ce yawanci muhimmiyar ga tsiro?",options:["Danshi, iska da zafin jiki masu dacewa","Fenti, roba da hayaniya","Kuɗi, lakabi da baturi","Haske mai ƙarfi kawai"],answer:0},{question:"Ruwa mai yawa zai iya haifar da matsala?",options:["Eh","A’a","Ga irin roba kawai","A yanar gizo kawai"],answer:0},{question:"Da me ya kamata a kwatanta hasashe?",options:["Shaidar da aka lura","Jita-jita","Zato kawai","Kalmar sirri"],answer:0}]},
    {id:"PF-05-L4",title:"Shirya Gwajin Tsiro Mai Adalci",objective:"Shirya kwatanci mai sauƙi inda sharadi guda ɗaya ke canzawa yayin da sauran muhimman sharudda suke zama iri ɗaya gwargwadon iko.",teaching:["Fair comparison yana canza babban sharadi guda ɗaya kuma yana barin sauran muhimman sharudda iri ɗaya gwargwadon iko.","Kowane kwantena yana bukatar lakabi bayyananne don kada bayanai su gauraya.","Rikodin farko ya haɗa da kwanan wata, nau’in iri, adadin iri da treatment."],activity:"A matsayin aji, tsara treatments biyu masu aminci kamar danshi mai kyau da bushe. Tattauna abin da zai canza, abin da zai tsaya iri ɗaya da abin da za a ƙirga.",diy:"Shirya kwantenan tsiro biyu masu lakabi da iri iri ɗaya, adadi iri ɗaya da babban sharadi guda ɗaya da aka canza.",aiLayer:"Matakin AI 4 — Binciken hanya: mai koyarwa ya nemi AI ya duba gwajin; ɗalibai su ƙi shawarar da ke canza variables da yawa ko kawo kayan haɗari.",enterprise:"Gwaje-gwaje masu aminci suna taimaka wa masu noma su yanke shawara kafin amfani da iri, ruwa ko aiki masu yawa.",quiz:[{question:"A fair comparison, babban sharadi nawa ya kamata ya canza?",options:["Guda ɗaya","Dukansu","Babu ko da yake ana kiran sa kwatanci","Da yawa gwargwadon iko"],answer:0},{question:"Me ya sa ake saka lakabi?",options:["Don treatment da rikodi su kasance bayyanannu","Don iri ya tsiro nan take","Don maye gurbin lura","Don ɓoye sakamako"],answer:0},{question:"Wane rikodin farko ne mai amfani?",options:["Kwanan wata da adadin iri","Kalmar sirri","Zanen da ba shi da alaƙa","Babu bayani"],answer:0}]},
    {id:"PF-05-L5",title:"Ƙirga, Auna da Kwatanta",objective:"Tattara bayanan tsiro da amfani da su wajen kwatantawa ba tare da canza abin da aka gani domin ya dace da hasashe ba.",teaching:["A ƙirga irin da ya tsiro da ka’ida iri ɗaya a kowace ranar lura.","Auna sifa mai sauƙi kamar tsawon tushe ko harbi ne kawai idan ba zai lalata gwajin ba.","Shaida na iya sabawa hasashe; mai bincike nagari yana rubuta abin da ya faru, ba abin da yake so ya faru ba."],activity:"Lura da treatments biyu, ƙirga irin da ya tsiro, rubuta aunawa ko bayanin gani sannan kwatanta sakamakon.",diy:"Ajiye germination log mai aƙalla shigarwa uku da kwanan wata, treatment, adadin da ya tsiro, lura da aunawa idan ya dace.",aiLayer:"Matakin AI 5 — Fassarar bayanai: shigar da teburin bayanan misali cikin AI, kwatanta fassararsa da ta ɗalibai, sannan a duba lissafi da ikirari.",enterprise:"Nursery da kasuwancin seedlings suna dogara da ƙirga daidai, duba inganci da rikodi maimakon ikirari da aka ƙara.",quiz:[{question:"Me ya kamata ka rubuta idan sakamakon ya sabawa hasashe?",options:["Abin da ya faru a zahiri","Sakamakon da aka canza","Babu komai","Sakamakon wani"],answer:0},{question:"Me ya sa ake ƙirga iri da ka’ida iri ɗaya?",options:["Don kwatantawa ya zama daidaitacce","Don tabbatar da nasara","Don ɓoye gazawa","Don guje wa shaida"],answer:0},{question:"Rikodin bayanai mai amfani ya ƙunshi…",options:["kwanan wata, treatment da lura","take kawai","kalmomin sirri","riba da aka tabbatar"],answer:0}]},
    {id:"PF-05-L6",title:"Daga Shaida Zuwa Ingantaccen Noma",objective:"Yi amfani da shaidar tsiro wajen bayyana sakamako, gane iyaka da ba da shawarar mataki na gaba mai alhaki.",teaching:["Kammalawa ya kamata ya amsa tambayar bincike ta amfani da shaidar da aka rubuta.","Ƙaramin gwaji guda ɗaya ba ya tabbatar da cewa kowane iri ko wuri zai yi iri ɗaya.","Ingantawa na iya zama maimaita gwaji, amfani da iri da yawa, inganta lakabi ko gwada wani sharadi mai aminci."],activity:"Ƙungiyoyi su gabatar da treatments, shaida da kammalawa. Abokan karatu su yi tambayar shaida guda ɗaya kuma su ba da shawarar ingantawa guda ɗaya.",diy:"Kammala Seed Germination Investigation Poster: TAMBAYA → HASASHE → HANYA → BAYANAI → KAMMALAWA → INGANTAWA.",aiLayer:"Haɗawa — tabbatarwa da tunani: kwatanta kammalawar ƙungiya da ta AI, sannan a riƙe maganganun da bayanan gaske ke tallafawa kawai.",enterprise:"Haɗa ƙwarewar tsiro da nursery mai alhaki, crop establishment da seed-quality; yara suna koyon ra’ayoyin ba tare da tilasta musu sayar da kaya ba.",quiz:[{question:"Kyakkyawan kammalawa ya kamata ya yi amfani da…",options:["Shaidar da aka rubuta","Zato kawai","Alkawarin sayarwa","Labarin da ba shi da alaƙa"],answer:0},{question:"Ƙaramin gwaji guda ɗaya yana tabbatar da cewa duk iri a ko’ina zai yi iri ɗaya?",options:["A’a","Eh koyaushe","Idan AI ya ce haka kawai","Idan duk iri ya tsiro kawai"],answer:0},{question:"Wanne ingantawa ne mai ma’ana?",options:["Maimaita gwajin da rikodi mai kyau","Goge bayanan da ba a zata ba","Canza sharudda da yawa ba tare da rubutawa ba","Da’awar sakamako tabbatacce"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Menene tsiro?",options:["Farkon girma daga iri","Girbin amfanin gona balagagge","Marufin abinci","Cajin baturi"],answer:0},{question:"Wane sharadi ake bukata sau da yawa don tsiro?",options:["Danshi mai dacewa","Fenti","Roba","Rasidin sayarwa"],answer:0},{question:"Me ya sa iri mai tsiro yake bukatar iska?",options:["Kwayoyin halitta suna bukatar oxygen don numfashi","Iska tana mayar da iri ƙarfe","Iska tana maye gurbin embryo","Ba shi da muhimmanci"],answer:0},{question:"Me ke sa kwatancin tsiro ya fi adalci?",options:["Canza babban sharadi guda ɗaya","Canza komai","Haɗa nau’in iri da sharudda daban-daban","Cire lakabi"],answer:0},{question:"Menene kyakkyawar shaida?",options:["Lura da ƙirga masu kwanan wata daga gwajin","Jita-jita","Hasashe da aka rubuta a matsayin sakamako","Hoton da ba shi da alaƙa"],answer:0},{question:"Idan AI ya ba da kammalawa daban da bayananka, me ka yi?",options:["Bincika bayanai da dalili kafin karɓar amsar AI","Goge bayananka","Yarda da AI koyaushe","Ƙirƙiri sabbin lambobi"],answer:0},{question:"Me ya sa tsiro mai kyau yake da muhimmanci ga masu noma?",options:["Zai iya rage ɓarnar iri da albarkatu","Yana tabbatar da riba","Yana kawar da duk haɗarin noma","Yana maye gurbin kula da amfanin gona"],answer:0},{question:"Wace magana ce mai alhaki?",options:["Ƙaramin gwajinmu yana tallafa wa wannan kammalawa a sharuddan da muka gwada","Gwajinmu ya tabbatar da cewa duk iri a ko’ina iri ɗaya ne","AI ya tabbatar da sakamakon","Rikodi ba ya da muhimmanci"],answer:0}],theory:["Bayyana sharudda uku da iri ke bukata don tsiro da dalilin da ya sa sharudda marasa dacewa ke rage nasara.","Bayyana aikin fatar iri da embryo cikin sauƙi.","Bayyana yadda za ka yi kwatancin tsiro na treatments biyu cikin adalci.","Bayyana yadda ƙirga da lura ke taimaka maka sanin treatment da ya fi aiki.","Ba da hanya ɗaya da AI zai tallafa wa binciken tsiro sannan ka bayyana yadda za ka tabbatar da fitarwarsa."],practical:"Shirya ko gabatar da binciken tsiro mai treatments biyu da nau’in iri iri ɗaya da adadin farawa iri ɗaya. Bayyana sharadin da aka canza, nuna lakabi daidai da mu’amala mai aminci, gabatar da aƙalla lura uku masu kwanan wata, kwatanta shaida sannan ka faɗi kammalawa guda ɗaya mai dalili da ingantawa guda ɗaya."},
  evidence:["Katin lura da iri shida","Samfurin sassan iri","Dabaran bukatun tsiro","Takardar tsara fair test","Treatments tsiro biyu masu lakabi","Germination log shigarwa uku","Seed Germination Investigation Poster","Rikodin tantance aikin hannu na mai koyarwa"],
  passport:["K: yana bayyana tsarin iri da sharuddan tsiro na asali","P: yana shirya da kula da kwatancin tsiro mai sauƙi cikin aminci","D: yana ƙirga, auna, rubuta da tabbatar da fassarar AI da shaida","S: yana bin tsafta, sarrafa ruwan da ya zube da dokokin mu’amala da iri cikin aminci","E: yana haɗa ingancin tsiro da ingancin amfani da albarkatu da nursery da samar da amfanin gona cikin alhaki","L: yana yin hasashe, aiki tare, gabatar da shaida da ba da shawarar ingantawa"],
  trainerNotes:["Zaɓi iri masu saurin tsiro, da aka saba da su kuma ba a yi musu treatment ba idan zai yiwu.","Fara aikin da wuri domin a sami lura na kwanaki da yawa; ainihin lokacin tsiro ya bambanta da iri da yanayi.","Kada a bayyana nasara da cewa duk iri ya tsiro; sakamakon da ba a zata ba shaida ce mai amfani.","Yi amfani da baka, hoto, abin taɓawa da taimakon abokai ga masu farawa a karatu.","A guji sinadaran seed treatment masu haɗari a ayyukan yara.","A mayar da tattaunawar enterprise kan inganci, ƙima da stewardship, ba sayar da yara ko alkawarin kuɗi ba."],
  remediation:"Yi amfani da babban iri guda da aka saba da shi, hotunan matakai da kwatancin moist-versus-dry guda ɗaya. Maimaita iri → tushe ya fito → harbi ya taso, sannan a sake gina teburin bayanai tare ta alamu ko tally.",
  extension:"Ɗalibi ya maimaita binciken da nau’in iri na biyu mai aminci ko wani sharadi mai sarrafawa, ya lissafa germination percentage mai sauƙi tare da taimakon mai koyarwa, sannan ya kwatanta ko kammalawar farko har yanzu tana aiki.",
  imagePrompts:["Yara Afirka shekaru 8–11 a wurin koyon GreenSkills ƙarƙashin kulawa suna shirya kofunan germination na wake ko cowpea, kayan aiki masu tsabta, lakabi ba tare da rubutu mai karantawa ba, littattafan lura, haɗa kowa, hasken rana, kore na LIFEWS da zinariya.","Zanen kimiyya na yara yana nuna irin wake daga iri cikakke zuwa tushen da ya fara fitowa, harbi da ganyen farko, farin bango, tsari daidai, babu lakabi ko rubutu.","Ɗalibin Afirka mai kama da hoto na gaske yana kwatanta treatments tsiro biyu masu aminci yana rubuta ƙirga da ma’auni yayin da mai koyarwa ke sa ido, wurin koyon lambu mai mayar da hankali kan shaida, babu rubutu mai karantawa."]
};