import type { PF01Module } from "./pf-01";

type PF06Module = Omit<PF01Module,"code"> & { code:"PF-06" };

export const pf06Yo: PF06Module = {
  code:"PF-06",
  title:"Omi Fún Ìyè",
  level:"Pathways Foundation",
  age:"Ní àárín ọdún 8 sí 11; iṣẹ́ gbọ́dọ̀ bá ìmúrasílẹ̀ akẹ́kọ̀ọ́ àti ipo omi agbègbè mu.",
  duration:"Ẹ̀kọ́ amọ̀nà mẹ́fà pẹ̀lú ìwádìí ọwọ́ àti ìdánwò",
  fieldworkHours:3,
  bigQuestion:"Kí ló dé tí omi fi ṣe pàtàkì fún ìyè, báwo la ṣe ń lò ó, àti báwo la ṣe lè dáàbò bo o kí a sì lò ó pẹ̀lú ọgbọ́n?",
  whyItMatters:"Omi so ilera, iṣelọpọ oúnjẹ, ecosystem, agbára, ilé àti ọ̀nà ìgbésí-ayé pọ̀. Ẹ̀ka yìí ń kọ́ ìmọ̀ omi ìpilẹ̀ nípasẹ̀ ìṣàkíyèsí, ìwọn, conservation, erongba treatment rọrùn àti ìpinnu pẹ̀lú ojúṣe, láìfi iṣẹ́ treatment omi tó lewu fún ọmọ.",
  outcomes:["Ṣàlàyé ọ̀nà mẹ́rin o kere tan tí ènìyàn, ewéko àti ẹranko fi gbára lé omi.","Yà lílo omi ilé àti àwùjọ sí ọ̀tọ̀, kí o sì mọ ibi tí a lè dín ìsòfò kù.","Wọn kí o sì fi iye omi rọrùn wé pẹ̀lú irinṣẹ́ tó yẹ fún ọjọ́-ori.","Mọ àmì tí a lè rí pé omi lè jẹ́ aláìní ààbò, nígbà tí o tún lóye pé omi kedere kì í ṣe omi mímu tó dájú nigbagbogbo.","Ṣàlàyé ìdènà ìpilẹ̀ tó lè dáàbò bo didara omi, bíi ìtọju orísun, ìpamọ́ mọ́ àti treatment lábẹ́ àgbàlagbà.","Ṣe ìṣàkíyèsí lílo omi rọrùn, kí o sì daba ìṣe conservation kan tó ṣeé ṣe.","Lo ìmọ̀ràn AI tàbí díjítà gẹ́gẹ́ bí ero tí a gbọdọ̀ jẹ́rìí, kì í ṣe rọ́pò ìtọ́sọ́nà ààbò omi tó dájú."],
  vocabulary:["omi","orísun","ààbò","mọ́","contamination","ìpamọ́","conserve","ìsòfò","lítà","iwọn omi","wọn","filter","sise omi","treatment","irigeson","túnlò","ẹ̀rí"],
  materials:["omi mímọ́ fún àfihàn","ago tàbí igo tí a lè rí inú wọn","ago ìwọn tàbí àpò pẹ̀lú àmì ìwọn","agolo omi kékeré","funnel","aṣọ mọ́ àti gravel/sand fún awoṣe filtration tí a kò ní mu","water-use tally sheet","káàdì àwòrán","ẹ̀rọ díjítà lábẹ́ ìṣàkóso olùkọ́ bí ó bá yẹ"],
  safety:["Má jẹ́ kí akẹ́kọ̀ọ́ tọ́ omi tí a kò mọ̀ wò tàbí pinnu ààbò omi mímu pẹ̀lú ìrísí, oorun tàbí adùn.","Gbogbo àfihàn gbọ́dọ̀ lo omi tí olùkọ́ fọwọ́ sí àti àpò mọ́.","Awoṣe filter yàrá kì í jẹ́ kí omi dájú fún mímu; a kò gbọdọ̀ mu omi àfihàn tí a filter.","Sise omi, disinfection kemika, pump, kanga àti eto omi ina mọnamọna jẹ́ koko lábẹ́ àgbàlagbà nìkan ní ipele yìí.","Nu omi tó dà sílẹ̀ lẹ́sẹ̀kẹsẹ̀ kí ẹni má bà a yọ.","Ìmọ̀ràn AI nípa ààbò omi gbọ́dọ̀ jẹ́rìí pẹ̀lú ìtọ́sọ́nà ilera gbogbogbo agbègbè àti olùkọ́."],
  lessons:[
    {id:"PF-06-L1",title:"Kí Ló Dé Tí Ohun Alààyè Fi Nílò Omi",objective:"Ṣàlàyé bí ènìyàn, ewéko àti ẹranko ṣe gbára lé omi.",teaching:["Ènìyàn nílò omi fún mímu, sise oúnjẹ, ìmọ́tótó àti ọ̀pọ̀ iṣẹ́ ojoojúmọ́.","Ewéko nílò omi fún ìdagbasoke àti gbigbe eroja onjẹ ká nínú ara wọn.","Ẹranko tún gbára lé omi taara tàbí nípasẹ̀ oúnjẹ àti ibùgbé wọn."],activity:"Ṣe water-dependence web: so káàdì ènìyàn, irugbin, ẹran-ọ̀sìn, igi, sise àti ìmọ́tótó mọ́ omi pẹ̀lú ọfà, kí o sì ṣàlàyé ní ẹnu.",diy:"Ṣẹ̀dá kẹ̀kẹ́ ‘Omi ń Ṣe Atilẹyin Ìyè’ pẹ̀lú àpẹẹrẹ mẹ́fà o kere tan láti ilé, ilé-ẹ̀kọ́, oko tàbí àwùjọ.",aiLayer:"AI Ipele 1 — Ìdámọ̀: olùkọ́ béèrè lọwọ AI fún àpẹẹrẹ lílo omi; akẹ́kọ̀ọ́ pín sí ÈNÌYÀN, EWÉKO, ẸRANKO tàbí JU Ẹ̀KA KAN LỌ, kí wọ́n sì tako àpẹẹrẹ tí kò bá agbègbè mu.",enterprise:"Ọ̀pọ̀ iṣẹ́ tó wúlò gbára lé omi—ọgbin oúnjẹ, ìmọ́tótó, processing àti irigeson—nítorí náà lílo omi pẹ̀lú ojúṣe ń dáàbò bo ènìyàn àti orísun.",quiz:[{question:"Àwọn ohun alààyè wo ni nílò omi?",options:["Ènìyàn, ewéko àti ẹranko","Ènìyàn nìkan","Ewéko nìkan","Ẹran-ọ̀sìn nìkan"],answer:0},{question:"Kí ló dé tí ewéko fi nílò omi?",options:["Fún ìdagbasoke àti gbigbe eroja onjẹ","Láti di plastiki","Láti ṣe batiri","Láti yí àwọ̀ padà nìkan"],answer:0},{question:"Èwo ni lílo omi ilé?",options:["Sise oúnjẹ","Fifi fóònù sínú omi láti charge","Kun ọ̀run","Kò sí"],answer:0}]},
    {id:"PF-06-L2",title:"Ibi Tí Omi Ti Ń Wá",objective:"Mọ orísun omi wọ́pọ̀ kí o sì ṣàlàyé idi tí ìtọju orísun fi ṣe pàtàkì.",teaching:["Àwùjọ lè gba omi láti òjò, odò, spring, borehole, kanga, reservoir tàbí pipe.","Didara omi lè yí padà láàárín orísun àti ibi tí ènìyàn ti máa lò ó.","Ìtọju orísun àti ibi ìpamọ́ ń dín ànfààní contamination kù."],activity:"Ṣe maapu orísun omi agbègbè pẹ̀lú aami; jíròrò bí omi ṣe lè rin láti orísun lọ sí ilé, ilé-ẹ̀kọ́ tàbí ọgbà.",diy:"Ya àtẹ̀le ORÍSUN → GBIgba → ÌPAMỌ́ → ÌLÒ, kí o sì samisi ibi méjì tí a gbọ́dọ̀ dáàbò bo omi.",aiLayer:"AI Ipele 2 — Fífiwé lábẹ́ amọ̀nà: fi àtòjọ orísun omi AI wé pẹ̀lú orísun gidi àwùjọ, kí o sì mọ ohun tí ìmọ̀ agbègbè fi kun.",enterprise:"Ipese omi tó dájú ń ṣe atilẹyin oko, iṣowo oúnjẹ, ilé-ẹ̀kọ́ àti ilé; ìtọju infrastructure àti orísun ń dín ìpòfo àti ìdálẹ́kun kù.",quiz:[{question:"Èwo lè jẹ́ orísun omi?",options:["Omi òjò","Pẹ́ńsù","Bàtà","Batiri gbẹ"],answer:0},{question:"Ṣé omi lè di contaminated lẹ́yìn tí ó kúrò ní orísun?",options:["Bẹ́ẹ̀ ni","Rárá","Lórí intanẹẹti nìkan","Ní ìlú nìkan"],answer:0},{question:"Kí ló dé tí a fi ń dáàbò bo ìpamọ́ omi?",options:["Láti dín contamination kù","Láti jẹ́ kí omi parí","Láti pọ̀si ìsòfò","Láti rọ́pò ìwọn"],answer:0}]},
    {id:"PF-06-L3",title:"Wọn Omi",objective:"Lo àpò ìwọn láti fi iye omi wé, kí o sì kọ ọ sílẹ̀ ní pípé.",teaching:["Iwọn omi ń sọ iye aaye tí omi gba.","Lítà àti millilitre jẹ́ ẹ̀ka ìwọn omi tó wọ́pọ̀.","Ìwọn ń ràn wa lọwọ láti fi lílo wé, gbero irigeson àti rí ìsòfò."],activity:"Fojú sùn, lẹ́yìn náà wọn iye omi bí 250 mL, 500 mL àti 1 L, kí o sì fi ìfojúsùn wé pẹ̀lú ìwọn gidi.",diy:"Ṣe igo ìwọn omi rọrùn pẹ̀lú reference volume tí olùkọ́ pèsè, kí o sì kọ ìwọn mẹ́ta sílẹ̀.",aiLayer:"AI Ipele 3 — Ṣàyẹ̀wò nọ́mbà: yanju ìfiwéra volume rọrùn kọ́kọ́, lẹ́yìn náà lo calculator tàbí AI lábẹ́ olùkọ́ láti ṣàyẹ̀wò idahun àti jíròrò ìyàtọ̀.",enterprise:"Ìwọn tó péye ṣe pàtàkì nígbà tí a ń fi omi ránṣẹ́, tọju rẹ̀, lò ó fún irugbin tàbí darapọ̀ mọ́ eroja; gboju lè ṣòfò orísun tàbí dín didara kù.",quiz:[{question:"Kí ni volume ń ṣàpèjúwe?",options:["Aaye tí omi gba","Owó tita rẹ̀","Àwọ̀ rẹ̀ nìkan","Ọ̀rọ̀ aṣínà rẹ̀"],answer:0},{question:"Èwo ni ẹ̀ka ìwọn omi wọ́pọ̀?",options:["Lítà","Kilomita ni wakati","Degree nìkan","Watt nìkan"],answer:0},{question:"Kí ló dé tí a fi ń wọn omi?",options:["Láti fi lílo wé àti ṣàkóso rẹ̀","Láti jẹ́ kí àkọsílẹ̀ má péye","Láti fi ìsòfò pamọ́","Láti yọ gbogbo ìpinnu kúrò"],answer:0}]},
    {id:"PF-06-L4",title:"Omi Kedere Kò Túmọ̀ Sí Ààbò Nigbagbogbo",objective:"Ṣàlàyé idi tí a kò fi lè pinnu ààbò omi pẹ̀lú ìrísí nìkan.",teaching:["A lè rí contamination kan, ṣùgbọ́n ọ̀pọ̀ microorganism tàbí kemika lewu kò hàn sí ojú.","Omi kedere kì í ṣe omi mímu tó dájú laifọwọyi.","Ìpinnu omi mímu gbọ́dọ̀ tẹ̀lé ìtọ́sọ́nà agbègbè tó dájú àti treatment tó fọwọ́ sí."],activity:"Fi àwòrán tàbí sample àfihàn tí a ti pa mọ́ ti omi ìdọ̀tí hàn wé pẹ̀lú omi kedere; jíròrò ohun tí ìrísí lè sọ àti ohun tí kò lè sọ.",diy:"Ṣe kaadi ÌPÌNNÚ ÀÀBÒ OMI: WO → MÁ TỌ́ OMI TÍ A KÒ MỌ̀ WÒ → BÉÈRÈ/LO ÌTỌ́SỌ́NÀ TÓ DÁJÚ → LO ORÍSUN/TREATMENT TÓ FỌWỌ́ SÍ.",aiLayer:"AI Ipele 4 — Ìjẹ́rìí ààbò: olùkọ́ fi ìsọ̀rọ̀ AI àròsọ hàn bíi ‘omi kedere máa ń dájú nigbagbogbo’; akẹ́kọ̀ọ́ ṣàlàyé idi tí kò fi dájú àti orísun ìtọ́sọ́nà tí a yẹ kí a lo.",enterprise:"Iṣẹ́ oúnjẹ àti ohun mímu gbára lé omi tó ní ààbò àti mímu pẹ̀lú ìmọ́tótó; ìrísí nìkan kì í ṣe quality control.",quiz:[{question:"Ṣé omi kedere máa ń dájú fún mímu nigbagbogbo?",options:["Rárá","Bẹ́ẹ̀ ni nigbagbogbo","Tí ó bá tutù nìkan","Tí ó bá wà nínú plastiki nìkan"],answer:0},{question:"Ṣé akẹ́kọ̀ọ́ yẹ kí ó tọ́ omi tí a kò mọ̀ wò?",options:["Rárá","Bẹ́ẹ̀ ni","Lẹ́ẹ̀kan nìkan","Nigbakugba tí AI bá daba"],answer:0},{question:"Kí ni yẹ kí ó dari ààbò omi mímu?",options:["Ìtọ́sọ́nà tó dájú tí a fọwọ́ sí","Ìrísí nìkan","Ahọ́n","Gboju lasan"],answer:0}]},
    {id:"PF-06-L5",title:"Dáàbò Bo, Tọju àti Conserve",objective:"Mọ ọ̀nà gidi láti jẹ́ kí omi ìpamọ́ mọ́ síi àti dín ìpòfo omi kù.",teaching:["Ìpamọ́ mọ́ tó ní ìderí lè dín contamination lẹ́yìn gbigba omi kù.","Títì tap, tún leak ṣe, lo iye irigeson tó yẹ àti tún omi tí kò contaminated lò níbi tó ní ààbò lè dín ìsòfò kù.","Conservation túmọ̀ sí lílo omi pẹ̀lú ṣiṣe, kì í ṣe fífi ènìyàn sílẹ̀ láìní omi fún ilera àti iyi."],activity:"Water-waste detective: ṣàyẹ̀wò scenario tí olùkọ́ pèsè pẹ̀lú tap tó ń drip, àpò ṣíṣi, overwatering tàbí omi tó ń ṣàn láìnídí, kí o daba ìmúdára.",diy:"Ṣe one-day water-use tally lábẹ́ amọ̀nà fún iṣẹ́ yàrá tàbí ọgbà kan, kí o sì mọ ayípadà conservation kan.",aiLayer:"AI Ipele 5 — Ìtìlẹ́yìn ìpinnu: fi ìmọ̀ràn conservation AI mẹ́ta wé pẹ̀lú ààbò, ìṣeéṣe, ìdájọ́ àti bí ó ṣe lè fipamọ́ omi; yan ohun tí ẹ̀rí ń ṣe atilẹyin nìkan.",enterprise:"Dín leak àti lílo aláìnídí kù ń dín owó orísun kù, ó sì ń ṣe atilẹyin iṣẹ́ tó dúró ṣinṣin láìba ìmọ́tótó tàbí didara ọja jẹ́.",quiz:[{question:"Kí ni lè dín contamination ní ìpamọ́ kù?",options:["Àpò mọ́ tó ní ìderí","Fi sílẹ̀ ṣí lẹ́gbẹ̀ẹ́ ìdọ̀tí","Fi ọwọ́ ìdọ̀tí sínú rẹ̀","Darapọ̀ mọ́ omi tí a kò mọ̀"],answer:0},{question:"Kí ni water conservation?",options:["Lílo omi pẹ̀lú ṣiṣe nígbà tí a ń pade aini gidi","Má lo omi rárá","Má fọ ọwọ́","Fi leak pamọ́"],answer:0},{question:"Èwo ni ìṣe conservation tó bójú mu?",options:["Tún leak ṣe","Fi tap sílẹ̀ ṣí","Overwater gbogbo ewéko","Foju kọ pipe tó bàjẹ́"],answer:0}]},
    {id:"PF-06-L6",title:"Ètò Water Stewardship Mi",objective:"Lo ìṣàkíyèsí àti ìwọn láti daba ìṣe ìtọju tàbí conservation omi tó dá lórí ẹ̀rí.",teaching:["Stewardship plan ń mọ iṣoro, ẹ̀rí, ìṣe, ẹni tó lè ràn lọ́wọ́ àti ọ̀nà ṣàyẹ̀wò ìmúdára.","Ìṣe tó dáa jẹ́ aláàbò, ṣeé ṣe, ó sì bá ipo agbègbè mu.","Ìmúdára kékeré tí a jẹ́rìí lè ní ipa bí ènìyàn púpọ̀ bá ń ṣe e léraléra."],activity:"Ẹgbẹ́ ṣàyẹ̀wò ìṣàkíyèsí lílo omi, kí wọ́n yan iṣoro kan tí wọ́n lè ní ipa lórí rẹ̀ ní ààbò, bíi ríròyìn tap tó ń drip, ìpamọ́ ọgbà tí kò ní ìderí tàbí overwatering.",diy:"Ṣẹ̀dá kí o sì ṣàfihàn Water Stewardship Plan: IṢORO → Ẹ̀RÍ → ÌṢE → OLÙRÀNLỌ́WỌ́ → ṢÀYẸ̀WÒ → ABAJADE.",aiLayer:"Ìṣọ̀kan — ìmọ̀ràn pẹ̀lú ojúṣe: olùkọ́ lè béèrè lọwọ AI fún ìṣe tó ṣeé ṣe; akẹ́kọ̀ọ́ fi ọkọọkan sí ìwọ̀n ẹ̀rí, ìṣeéṣe agbègbè àti ààbò kí wọ́n tó gba tàbí kọ.",enterprise:"Stewardship orísun jẹ́ apá iṣowo tó dáa: wọn inputs, dènà ìsòfò, dáàbò bo didara, kí o sì kọ ìmúdára sílẹ̀.",quiz:[{question:"Kí ni stewardship plan yẹ kí ó bẹ̀rẹ̀ pẹ̀lú?",options:["Iṣoro tí a kíyèsi kedere","Èrè tó dájú","Ọ̀rọ̀ aṣínà","Slogan lasan"],answer:0},{question:"Báwo ni a ṣe yẹ kí a yan ìṣe?",options:["Pẹ̀lú ẹ̀rí, ààbò àti ìṣeéṣe","Daakọ lasan","Yan eyi tó gbowó jù","Foju kọ ipo agbègbè"],answer:0},{question:"Kí ló dé tí a fi ń ṣàyẹ̀wò abajade?",options:["Láti rí bóyá ìṣe ràn lọ́wọ́","Láti yàgò fún ẹ̀kọ́","Láti yọ ẹ̀rí kúrò","Láti guarantee gbogbo ọjọ́ iwájú"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Kí ló dé tí omi fi ṣe pàtàkì fún ewéko?",options:["Ó ń ṣe atilẹyin ìdagbasoke àti gbigbe eroja onjẹ","Ó ń sọ ewé di irin","Ó ń rọ́pò oorun patapata","Kò ní ipa"],answer:0},{question:"Èwo lè jẹ́ orísun omi àwùjọ?",options:["Borehole","Ìwé àkọsílẹ̀","Gilasi panel oorun","Pẹ́ńsù"],answer:0},{question:"Kí ni lítà ń wọn?",options:["Iwọn omi","Ooru","Akoko","Iyara"],answer:0},{question:"Ṣé omi kedere dájú fún mímu laifọwọyi?",options:["Rárá","Bẹ́ẹ̀ ni","Nínú igo nìkan","Tí ó bá tutù nìkan"],answer:0},{question:"Ìṣe ìpamọ́ wo ló sábà ní ààbò síi?",options:["Ìpamọ́ mọ́ tó ní ìderí","Àpò ìdọ̀tí ṣíṣi","Fifi ọwọ́ aláìfọ́ sínú omi","Darapọ̀ mọ́ omi tí a kò mọ̀"],answer:0},{question:"Ìṣe wo lè conserve omi?",options:["Tún leak ṣe","Fi tap ṣí","Overwater","Foju kọ pipe tó bàjẹ́"],answer:0},{question:"Báwo la ṣe yẹ kí a ṣe pẹ̀lú ìmọ̀ràn AI pataki nípa ààbò omi?",options:["Jẹ́rìí pẹ̀lú ìtọ́sọ́nà tó dájú","Gba laifọwọyi","Lo dipo àgbàlagbà","Pín ṣáájú ṣàyẹ̀wò"],answer:0},{question:"Èwo ni ìpinnu omi tó dá lórí ẹ̀rí?",options:["Wọn lílo, mọ ìsòfò, ṣe ìṣe, ṣàyẹ̀wò abajade","Gboju láìwọn","Daakọ ìsọ̀rọ̀ láìṣàyẹ̀wò","Foju kọ ipo agbègbè"],answer:0}],theory:["Ṣàlàyé ọ̀nà mẹ́rin tí ènìyàn, ewéko tàbí ẹranko fi gbára lé omi.","Ṣàpèjúwe ọ̀nà omi láti orísun dé ibi ìlò, kí o sì mọ ibi méjì tí contamination lè ṣẹlẹ̀.","Ṣàlàyé idi tí omi tó kedere fi tún lè jẹ́ aláìní ààbò fún mímu.","Ṣàpèjúwe ìṣe conservation omi méjì àti bí ọkọọkan ṣe dín ìsòfò kù láìba ìmọ́tótó jẹ́.","Ṣàlàyé bí ìwọn àti ìsọfúnni tí a jẹ́rìí ṣe lè ràn ilé, ọgbà ilé-ẹ̀kọ́ tàbí iṣowo kékeré lọwọ láti ṣàkóso omi dáadáa."],practical:"Wọn kí o sì kọ iye omi mímọ́ àfihàn kan sílẹ̀, mọ iṣoro lílo tàbí ìtọju omi kan nínú scenario lábẹ́ amọ̀nà, kí o sì ṣàfihàn Water Stewardship Plan pẹ̀lú ẹ̀rí, ìṣe aláàbò, olùrànlọ́wọ́ tó ní ojúṣe àti ọ̀nà láti ṣàyẹ̀wò bóyá ìṣe ṣiṣẹ́."},
  evidence:["Kẹ̀kẹ́ Omi ń Ṣe Atilẹyin Ìyè","Maapu orísun-sí-ìlò","Ìwọn volume mẹ́ta tí a kọ sílẹ̀","Kaadi ìpinnu Ààbò Omi","One-day water-use tally","Water Stewardship Plan","Àkọsílẹ̀ ìṣàkíyèsí iṣẹ́ olùkọ́"],
  passport:["K: ṣàlàyé aini omi, orísun, erongba ààbò àti conservation","P: wọn volume omi àti ṣe ìṣàkíyèsí lílo omi lábẹ́ amọ̀nà","D: kọ data omi rọrùn àti ṣe ìdánilójú ìmọ̀ràn AI/díjítà pẹ̀lú ẹ̀rí àti ìtọ́sọ́nà tó dájú","S: yàgò fún títọ́ omi tí a kò mọ̀ wò àti tẹ̀lé ààbò ìpamọ́, spill àti treatment","E: so ìwọn omi tó péye, ìtọju didara àti dídín ìsòfò kù mọ́ enterprise pẹ̀lú ojúṣe","L: ṣiṣẹ́ pọ̀ lórí stewardship, sọ ìmọ̀ràn àti mọ àgbàlagbà tó yẹ láti ràn lọ́wọ́"],
  trainerNotes:["Mú àpẹẹrẹ bá ipo omi agbègbè gidi mu láìpe àwùjọ ní aláìní tàbí aláàbò.","Má jẹ́ kí akẹ́kọ̀ọ́ ro pé aṣọ, iyanrin tàbí gravel filter àfihàn ń mú omi dájú fún mímu.","Bí ìtọ́sọ́nà ilera gbogbogbo agbègbè bá wà fún omi mímu, lo o fún ẹ̀kọ́ ààbò.","Lo iṣẹ́ ìwọn láti túbọ̀ mú PF-03 numeracy lagbara.","Fún gbogbo akẹ́kọ̀ọ́ ní ànfààní tó dọ́gba nínú ìwọn, ìkọ̀wé àti ìròyìn.","Níbi tí omi ti ṣọwọn, lo omi díẹ̀ fún àfihàn kí o sì tún omi mímọ́ àfihàn lò fún ewéko tí kì í ṣe oúnjẹ bí ó bá yẹ."],
  remediation:"Lo títẹ̀lé àwòrán, àpò ìwọn kan àti erongba pataki: NÍLÒ OMI → GBA OMI → DÁÀBÒ BO O → LO OHUN TÍ A NÍLÒ → ṢÀYẸ̀WÒ. Gba idahun ẹnu àti adaṣe ìwọn léraléra.",
  extension:"Pẹ̀lú olùkọ́, fi lílo omi ọjọ́ méjì wé fún iṣẹ́ aláàbò kan, ṣe ìṣirò ìyàtọ̀, kí o sì daba target conservation nígbà tí o ṣàlàyé idi tí omi ìmọ́tótó pataki kò yẹ kí a dín kù.",
  imagePrompts:["Àwọn ọmọ Africa ọdún 8–11 nínú ọgbà ilé-ẹ̀kọ́ lábẹ́ amọ̀nà ń wọn omi mímọ́ pẹ̀lú àpò graduated tí a lè rí inú rẹ̀ àti agolo omi, ọmọkùnrin àti ọmọbìnrin pọ̀, ọ̀nà gbẹ tó ní ààbò, ìmọ́lẹ̀ adayeba, kò sí ọrọ̀ tí a lè ka, àwọ̀ LIFEWS aláwọ̀-ewe igbo àti goolu.","Àwòrán ẹ̀kọ́ ọmọde tó fi irin-ajo omi hàn láti òjò tàbí borehole sí ìpamọ́ tó ní ìderí, sí ilé àti ọgbà, ọfà àti aami rọrùn nìkan, abẹ́lẹ̀ funfun, kò sí ọ̀rọ̀.","Ìwádìí water-conservation photorealistic nínú yàrá pẹ̀lú akẹ́kọ̀ọ́ Africa ń kíyèsi àpò ìpamọ́ mọ́ tó pa, model tap àti sheet ìwọn rọrùn, olùkọ́ wà níbẹ̀, kò sí ẹni tó ń mu sample, kò sí ọrọ̀ tí a lè ka."]
};