import type { PF01Module } from "./pf-01";

type PF02Module = Omit<PF01Module,"code"> & { code:"PF-02" };

export const pf02Ig: PF02Module = {
  code:"PF-02",
  title:"Ịgụ Ụwa Gbara M G gburugburu",
  level:"Pathways Foundation",
  age:"Ihe dịka afọ 8–11; itinye nwa akwụkwọ n’ọkwa ọgụgụ kwesịrị ịdabere na nyocha mmalite, ọ bụghị naanị afọ.",
  duration:"Ihe ọmụmụ nduzi isii tinyere omume ọgụgụ, ọrụ aka na nyocha",
  fieldworkHours:2,
  bigQuestion:"Kedu ka okwu, onyonyo, akara na akara ngosi ga-esi nyere m aka ịghọta ụwa gbara m gburugburu ma mee ihe n’enweghị ihe ize ndụ?",
  whyItMatters:"Nkà ọgụgụ isi bụ isi na-aba uru karị mgbe ụmụ akwụkwọ jikọtara ihe e dere na ndụ kwa ụbọchị. Modul a na-ewulite nlebara anya, asụsụ ọnụ, mkpụrụokwu, ịgụ akụkụ okwu na ọgụgụ bara uru site n’ihe atụ metụtara nri, mmiri, ike, ubi na obodo, ma na-akwanyere ndị na-amalite ọgụgụ n’ogo dị iche iche ùgwù.",
  outcomes:[
    "Ghọta na ederede, onyonyo, akara na akara ngosi na-ebufe ihe pụtara.",
    "Gụọ ma jiri otu mkpụrụokwu ndị a na-ahụkarị gbasara gburugburu na usoro nri.",
    "Jikọta okwu a nụrụ, onyonyo na okwu e dere.",
    "Jiri ọnọdụ okwu na nlebara anya chọpụta ma nyochaa ihe pụtara.",
    "Mepụta ihe ọmụma bara uru nwere onyonyo, okwu na ozi.",
    "Jiri nkwado dijitalụ ma ọ bụ AI n’okpuru nduzi tụnyere, kewaa ma ọ bụ nyochaa okwu n’enweghị ikpughe ozi nzuzo."
  ],
  vocabulary:["okwu","mkpụrụedemede","ụda","onyonyo","akara","akara ngosi","aha-akara","ihe pụtara","gụ","nyochaa","nri","mmiri","osisi","ike","nchekwa"],
  materials:["kaadị onyonyo kwekọrọ n’obodo","kaadị okwu","kaadị mkpụrụedemede/ụda kwekọrọ n’asụsụ nkuzi","ngwugwu nri dị ọcha ma ọ bụ oyiri aha-akara","ihe ubi ma ọ bụ ụlọ dị nchebe","akwụkwọ na pensụl/marka","ngwa dijitalụ nhọrọ n’okpuru njikwa onye nduzi"],
  safety:[
    "Jiri naanị ihe na ngwugwu dị ọcha ma dị nchebe.",
    "Ekwela ka mmejọ ọgụgụ bụrụ ihe ihere ma ọ bụ ụzọ iji kpọọ ụmụ akwụkwọ ọkwa.",
    "Hazie nkuzi ụda na mkpụrụedemede maka asụsụ ahọpụtara; ewerela iwu Bekee mee ka ha bụrụ otu maka Hausa, Arabic, Yoruba, Igbo ma ọ bụ French.",
    "Arịọla ụmụ akwụkwọ ka ha see foto ma ọ bụ bulite ndị mmadụ a pụrụ ịmata, adreesị ma ọ bụ akwụkwọ nzuzo n’ọrụ AI."
  ],
  lessons:[
    {id:"PF-02-L1",title:"Onyonyo, Akara na Ihe Pụtara",objective:"Kọwaa otú onyonyo, akara, akara ngosi na okwu si ekwupụta ozi.",teaching:["Anyị anaghị agụ akwụkwọ naanị; anyị na-agụkwa akara, akara ngosi, onyonyo, aha-akara na ọnọdụ.","Akara ngosi nwere ike ikwupụta ihe ngwa ngwa, mana ihe ọ pụtara na-adabere na nghọta ndị mmadụ nwere ọnụ.","Onye na-agụ nke ọma na-elebara anya tupu o kpebie ihe ihe pụtara."],activity:"Ịchọ ihe pụtara: lee akara ndị a maara na kaadị onyonyo ma kọwaa ozi nke ọ bụla na-agbalị ikwu.",diy:"Mepụta otu akara nchekwa ma ọ bụ nlekọta maka ubi mmụta ma ọ bụ klas ma kọwaa ya n’ọnụ.",aiLayer:"AI Ogo 1 — Ịmata: kewaa akara mmadụ mere, nsonaazụ nchọ dijitalụ na aro AI; ha niile ka chọrọ ntụgharị uche mmadụ.",enterprise:"Akara na aha-akara doro anya na-enyere ndị mmadụ ịghọta ngwaahịa, ebe na ọrụ; nkwukọrịta ọma na-emepụta uru.",quiz:[{question:"Gịnị nwere ike ibufe ihe pụtara?",options:["Okwu, onyonyo na akara ngosi","Naanị akwụkwọ ogologo","Naanị ọnụọgụ","Ọ dịghị ihe"],answer:0},{question:"Tupu anyị ekpebie ihe akara pụtara, anyị kwesịrị…",options:["ilebara ya anya nke ọma","ileghara ya anya","bibie ya","tụọ n’amaghị ama"],answer:0},{question:"Aha-akara na-enyere anyị…",options:["ịmata ma ọ bụ kọwaa ihe","izochi ozi niile","ime ka ọgụgụ ghara ịdị mfe","dochie nchekwa"],answer:0}]},
    {id:"PF-02-L2",title:"Okwu n’Ihe Banyere Nri, Mmiri na Ike",objective:"Mata ma gụọ okwu bara uru sitere n’ọnọdụ kwa ụbọchị gbasara nri, mmiri na ike.",teaching:["Okwu a maara na-adị mfe ịmụta mgbe ejikọtara ha na ihe na omume n’ezie.","Okwu nwere ike ịkpọ ihe, omume ma ọ bụ àgwà.","Ịgụ ugboro ugboro na-ewulite ọsọ na ntụkwasị obi."],activity:"Gaa n’ọdụ okwu maka nri, mmiri, osisi, ngwaọrụ na ike; jikọta kaadị okwu ọ bụla na onyonyo ma ọ bụ ihe dị nchebe.",diy:"Mepụta kaadị onyonyo-okwu iri nke gị ma mụta ịgụ ha nye onye òtù gị.",aiLayer:"AI Ogo 2 — Mmekọrịta nduzi: onye nduzi jụọ AI ka o mepụta ahịrịokwu dị mfe nwere okwu ahọpụtara; ụmụ akwụkwọ nyochaa ma ha nwere ezi uche ma dabara na mpaghara ha.",enterprise:"A chọrọ okwu ziri ezi iji kpọọ, kọwaa ma hazie ngwaahịa na ọrụ bara uru.",quiz:[{question:"Gịnị na-enyere aka ịmụta okwu ọhụrụ?",options:["Ijikọ ya na onyonyo ma ọ bụ ihe","Ịghara ịhụ ya ọzọ","Izochi ya","Ịwụfe ụda niile"],answer:0},{question:"Ịgụ ugboro ugboro nwere ike ime ka…",options:["ntụkwasị obi na ịdị mfe ọgụgụ bawanye","mmiri dị ọcha n’onwe ya","ihu igwe gbanwee","batrị too"],answer:0},{question:"Kedu nke bụ okwu usoro nri?",options:["mkpụrụ","paswọọdụ","satellite naanị","jụụ"],answer:0}]},
    {id:"PF-02-L3",title:"Mkpụrụedemede, Ụda na Akụkụ Okwu",objective:"Jiri usoro mkpụrụedemede na ụda ma ọ bụ usoro edemede kwekọrọ n’asụsụ gụọ okwu ndị a maara.",teaching:["Asụsụ e dere ede na-anọchi anya okwu ọnụ n’ụzọ dị iche iche.","Anyị nwere ike ịchọ mkpụrụedemede, ụda, nkeji okwu ma ọ bụ akụkụ okwu anyị maraworị.","Mgbe okwu siri ike, anyị nwere ike belata ọsọ, kewaa ya ma jiri ọnọdụ okwu nyere anyị aka."],activity:"Wuo okwu ndị a maara site na mkpụrụedemede a na-ebugharị, kaadị nkeji okwu ma ọ bụ akụkụ edemede dabara n’asụsụ nkuzi.",diy:"Mepụta ọkwa okwu ise jikọrọ ọnụ ma gosipụta akụkụ ị matara na nke ọ bụla.",aiLayer:"AI Ogo 3 — Ịmata usoro: kewaa okwu dabere n’usoro a hụrụ ma ọ bụ nụrụ, wee tụnyere ya na aro dijitalụ nke onye nduzi nyere.",enterprise:"Ịmata usoro na-akwado ịgụ ọnụ ọgụgụ ziri ezi, ịkpọ aha, ide ndekọ na nyocha ogo.",quiz:[{question:"Mgbe okwu siri ike, ụzọ bara uru bụ…",options:["ikewa ya n’akụkụ dị mfe","ịkwụsị ozugbo","ịmepụta okwu ọ bụla","ikpuchi ya"],answer:0},{question:"Asụsụ isii niile hà na-eji otu iwu mkpụrụedemede-ụda?",options:["Mba","Ee","Naanị Mọnde","Naanị n’ubi"],answer:0},{question:"Ịchọpụta akụkụ okwu na-emegharị bụ ụdị…",options:["ịmata usoro","imefusị ihe","izo ihe","ịnye ọnụahịa"],answer:0}]},
    {id:"PF-02-L4",title:"Ịgụ Aha-Akara na Ntuziaka",objective:"Wepụta ozi dị mfe ma bara uru site na aha-akara, akara ma ọ bụ ntuziaka kwekọrọ n’afọ.",teaching:["Ọgụgụ bara uru na-enyere anyị aka ime nhọrọ dị nchebe kwa ụbọchị.","Isiokwu, onyonyo, ọnụọgụ na okwu ndị bụ isi na-enyere aka ịchọta ozi.","Anyị kwesịrị ịjụ onye okenye anyị tụkwasịrị obi mgbe ozi nchekwa adịghị doo anya."],activity:"Gụọ aha-akara onye nkuzi kwadebere maka akpa mkpụrụ, akpa mmiri ma ọ bụ ngwaọrụ ubi, chọpụta aha, ọrụ na otu ntuziaka.",diy:"Mepụta aha-akara akụkụ atọ maka ihe dị na klas ma ọ bụ ubi: AHA → OJI YA → NLEKỌTA/NCHEKWA.",aiLayer:"AI Ogo 4 — Ajụjụ nwere oke: onye nduzi gosipụta otú e si arịọ nkọwa dị mfe gbasara aha-akara na-abụghị nke nzuzo; ụmụ akwụkwọ tụnyere nkọwa ahụ na ihe mbụ wee chọpụta ihe fọdụrụ.",enterprise:"Aha-akara ziri ezi na-ewulite ntụkwasị obi, nchekwa na azụmahịa nwere ọrụ; aha ụgha ma ọ bụ mgbagwoju anya nwere ike imerụ mmadụ.",quiz:[{question:"Gịnị mere anyị ji agụ ntuziaka?",options:["Ka anyị mara ime ihe n’ụzọ ziri ezi ma dị nchebe","Ka ha pụọ","Ka anyị ghara ịghọta","Naanị maka ịchọ mma"],answer:0},{question:"Ọ bụrụ na ozi nchekwa adịghị doo anya, ị kwesịrị…",options:["jụọ onye okenye ị tụkwasịrị obi","tụọ n’amaghị ama jiri ngwaọrụ dị ize ndụ","leghara ya anya","gbanwee aha-akara"],answer:0},{question:"Aha-akara ọma kwesịrị ịbụ…",options:["doro anya ma ziri ezi","nke na-eduhie n’amaghị ama","nke a na-apụghị ịgụ","nzuzo"],answer:0}]},
    {id:"PF-02-L5",title:"Nyochaa Ihe Pụtara",objective:"Jiri ọnọdụ, onyonyo na enyemaka a pụrụ ịtụkwasị obi nyochaa ma nkọwa ọ dabara.",teaching:["Onye na-agụ nke ọma na-enyocha ihe pụtara kama ịnakwere echiche mbụ ozugbo.","Onyonyo na okwu gbara okwu gburugburu na-enye ihe ngosi ọnọdụ.","Ngwa dijitalụ na AI nwere ike mehie, ya mere ozi dị mkpa ga-enyocha."],activity:"Gụọ ahịrịokwu dị mkpirikpi nwere onyonyo ebe e tinyere otu okwu na-adabaghị; chọpụta ma dozie ya.",diy:"Mepụta kaadị ‘Gụọ–Chee Echiche–Nyochaa’ nwere nzọụkwụ anya atọ.",aiLayer:"AI Ogo 5 — Nyocha: onye nduzi gosi otu nkọwa AI ziri ezi na otu na-ezighi ezi gbasara ihe a maara; ụmụ akwụkwọ jiri ihe ha na-ahụ kwado nke kacha mma.",enterprise:"Nyocha ozi na-egbochi mmejọ n’ime ndekọ, aha-akara, ọnụọgụ na nkwukọrịta ndị ahịa.",quiz:[{question:"Ihe ngosi ọnọdụ na-enyere anyị…",options:["ịchọpụta ihe pụtara","ichefu ederede","ikekọrịta paswọọdụ","ịghara ile anya"],answer:0},{question:"Anyị kwesịrị ịnakwere nkọwa AI niile ozugbo?",options:["Mba","Ee","Mgbe ọ dị ogologo naanị","Mgbe ọ mara mma naanị"],answer:0},{question:"Kedu usoro bara uru?",options:["Gụọ–Chee Echiche–Nyochaa","Tụọ–Zoo–Pụọ","Detuo–Chefuo–Kekọrịta","Wụfee–Wụfee–Wụfee"],answer:0}]},
    {id:"PF-02-L6",title:"Nduzi Onyonyo-Okwu M",objective:"Mepụta ma gosi nduzi onyonyo-okwu bara uru site n’iji mkpụrụokwu na aha-akara ziri ezi.",teaching:["Onye odee na-ahọrọ ozi dabere na onye ga-agụ ya na ebumnuche ya.","Nduzi bara uru kwesịrị ịdị haziri, dị mfe ịgụ ma bụrụ eziokwu.","Ịmepụta ozi bụkwa ọrụ: anyị na-enyocha tupu ịkekọrịta."],activity:"Hazie obere nduzi gbasara otu isiokwu: ubi ụlọ akwụkwọ, mmiri dị ọcha, ihe oriri, iji ike n’enweghị ihe ize ndụ ma ọ bụ mmụta obodo.",diy:"Mepụta Nduzi Onyonyo-Okwu nwere ntinye isii; ntinye ọ bụla nwee onyonyo, isi okwu na obere eziokwu ma ọ bụ ntuziaka, wee gụọ ma ọ bụ gosi ya ndị ọzọ.",aiLayer:"Njikọta: AI nwere ike ịtụ aro okwu ma ọ bụ ahịrịokwu n’okpuru njikwa onye nduzi; nwa akwụkwọ ga-ahọrọ, dozie ma kọwaa ihe ikpeazụ.",enterprise:"Ngwa ozi doro anya na-emepụta uru site na nkwukọrịta na imewe; ogo pụtara ịdị bara uru, izi ezi na nlekọta.",quiz:[{question:"Ònye bụ ndị e mere ozi maka ha?",options:["Ndị mmadụ e mere ozi ahụ maka ha","Naanị onye odee","Ụdị mkpụrụ","Paswọọdụ"],answer:0},{question:"Tupu ịkekọrịta nduzi, ị kwesịrị…",options:["nyochaa izi ezi ya","tinye ozi nzuzo","wepụ aha niile","detuo n’enweghị ịgụ"],answer:0},{question:"Ngwa ozi ọma kwesịrị ịbụ…",options:["bara uru ma dị mfe nghọta","na-eduhie","dị ize ndụ","a na-apụghị ịgụ"],answer:0}]}
  ],
  finalAssessment:{
    mcq:[{question:"Kedu ihe bụ ihe atụ ọgụgụ bara uru?",options:["Ịgụ akara nchekwa","Ileghara aha-akara anya","Izo okwu","Ibibi ntuziaka"],answer:0},{question:"Gịnị na-enyere onye na-agụ aka ịghọta okwu ọ na-amaghị?",options:["Ọnọdụ na akụkụ okwu","Imechi peeji","Ịtụ naanị","Ịwụfe ihe ngosi niile"],answer:0},{question:"Gịnị mere onyonyo ji baa uru n’oge mmalite ọgụgụ?",options:["Ha nwere ike nyere ihe pụtara aka","Ha na-eme ka okwu ghara ịdị mkpa ruo mgbe ebighị ebi","Ha na-anọchi nchekwa","Ha na-ekwe nkwa nkọwa niile"],answer:0},{question:"Kedu àgwà dị mkpa n’aha-akara?",options:["Izi ezi","Aghụghọ","Mgbagwoju anya","Nzuzo"],answer:0},{question:"Gịnị kwesịrị ime tupu e kesaa ozi AI dị mkpa?",options:["A ga-enyocha ya","Ọ dịghị ihe","Tinye ozi nzuzo","Leghara isi ederede anya"],answer:0},{question:"Kedu usoro na-akwado ọgụgụ nlezianya?",options:["Lelee–Gụọ–Chee Echiche–Nyochaa","Tụọ–Kekọrịta–Chefuo","Zoo–Detuo–Pụọ","Mee Ngwa ngwa–Leghara Anya–Ziga"],answer:0},{question:"Gịnị mere nkuzi ọgụgụ nwere ike ịdị iche n’etiti Bekee, Arabic na Yoruba?",options:["Usoro ederede na ụda ha dị iche","Asụsụ niile bụ otu","Naanị otu nwere okwu","A pụghị ịkụziri ha"],answer:0},{question:"Nduzi onyonyo-okwu na-emepụta uru mgbe ọ bụ…",options:["bara uru, doro anya ma ziri ezi","ụgha","dị ize ndụ","a na-apụghị ịgụ"],answer:0}],
    theory:["Kọwaa ihe atọ n’obodo gị a pụrụ ‘ịgụ’ e wezụga akwụkwọ.","Họrọ okwu ise ị maara ma kọwaa ụzọ ị si amata ma ọ bụ gụọ ha.","Kọwaa otú onyonyo ma ọ bụ ihe ngosi ọnọdụ si nyere gị aka ịghọta okwu ọhụrụ.","Kọwaa ihe mere aha-akara na ntuziaka ji kwesị ịbụ eziokwu ma dị mfe nghọta.","Kọwaa otu ụzọ esi enyocha nkọwa dijitalụ ma ọ bụ AI tupu iji ya."],
    practical:"Mepụta ma gosi n’ọnụ Nduzi Onyonyo-Okwu nwere ntinye isii gbasara isiokwu a maara nke metụtara nri, mmiri, ike, ubi ma ọ bụ mmụta obodo. Ntinye ọ bụla ga-enwe onyonyo dabara, isi okwu ziri ezi na obere eziokwu ma ọ bụ ntuziaka nwa akwụkwọ mepụtara. Onye nduzi ga-enyocha ịmata, ihe pụtara, nhazi, izi ezi na nkwukọrịta, ọ bụghị naanị mma ederede aka."
  },
  evidence:["Kaadị onyonyo-okwu iri","Ọkwa usoro okwu","Aha-akara ọrụ akụkụ atọ","Kaadị Gụọ–Chee Echiche–Nyochaa","Nduzi Onyonyo-Okwu ntinye isii","Ndekọ onye nduzi gbasara ọgụgụ ọnụ na nghọta"],
  passport:["K: na-amata okwu, akara, akara ngosi na ederede bara uru dịka ụzọ isi nweta ihe pụtara","P: na-emepụta ma na-eji aha-akara na nduzi onyonyo-okwu","D: na-eji nkwado dijitalụ/AI n’okpuru nduzi kewaa ma ọ bụ nyochaa asụsụ ma chekwaa nzuzo","S: na-agụ ozi nchekwa bụ isi ma ọ bụ na-achọ enyemaka","E: na-akọwa otú nkwukọrịta na aha-akara ziri ezi si emepụta uru na ntụkwasị obi","L: na-agụ ma ọ bụ na-egosi ndị ọzọ, na-anabata nzaghachi ma na-enyocha ọrụ tupu ịkekọrịta"],
  trainerNotes:["Kụzie ọgụgụ n’asụsụ nkuzi ahọpụtara; hazie phonics na decoding maka asụsụ ahụ kama ịtụgharị phonics Bekee ozugbo.","Kwe ka azịza ọnụ, ịsụgharị akara, ijikọ na ịhọrọ onyonyo bụrụ ihe akaebe ka ọgụgụ na-etolite.","Jiri ihe mpaghara na onyonyo ndị ụmụ akwụkwọ maara, ma zere stereotypes.","Maka Arabic jiri ihe RTL kwesịrị ekwesị; maka Yoruba na Igbo chekwaa diacritics ebe a chọrọ; maka French kụzie njikọ ụda na mkpụrụedemede kwesịrị ekwesị.","Nyochaa nghọta na ọganihu, ọ bụghị accent."],
  remediation:"Belata ọnụ ọgụgụ okwu a na-arụ ọrụ na ya, bawanye ijikọ onyonyo na ihe, jiri ọgụgụ ọnụ ugboro ugboro na ọrụ mkpụrụedemede/nkeji okwu n’ụzọ sensory dị iche iche, ma debe ebumnuche ọgụgụ bara uru.",
  extension:"Nwa akwụkwọ na-eme nyocha akara na aha-akara n’ebe mmụta n’okpuru nlekọta, wee tụọ aro otu akara ọhụrụ ma ọ bụ mmezi maka nnweta ma ọ bụ nchekwa.",
  imagePrompts:["Ihe nkiri photorealistic nke mmụta ọgụgụ bụ isi n’Africa, ụmụ nwoke na ụmụ nwanyị afọ 8–11 na-ejikọta kaadị onyonyo na okwu banyere osisi, mmiri, nri na ihe ike dị mfe, onye nduzi na-enyere ha aka, ebe mmụta obodo dị ọcha, enweghị ederede a pụrụ ịgụ, agba ndụ ndụ LIFEWS na odo ọkụ.","Ihe osise mmụta maka ụmụaka na-egosi akpa mkpụrụ, akpa mmiri, akara osisi na akara nchekwa tinyere akara magnifying glass, ndabere ọcha dị ọcha, akara ngosi naanị, enweghị ederede.","Obere ìgwè ụmụaka Africa na-emepụta nduzi onyonyo-okwu nwere eserese ihe ọkụkụ na ihe mmiri, pensụl na kaadị n’elu tebụl, mmekọrịta na itinye onye ọ bụla, ìhè eke, enweghị ederede a pụrụ ịgụ."]
};