import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "./pf-01";

type PF04Module = Omit<PF01Module,"code"> & { code:"PF-04" };

const en: PF04Module = {
 code:"PF-04", title:"Plants Around Us", level:"Pathways Foundation", age:"Approximately 8–11 years; practical activities should be adjusted to local conditions and learner needs.", duration:"6 guided lessons plus observation, garden practical and assessment time", fieldworkHours:3,
 bigQuestion:"What can plants teach us about food, water, care, useful products and the places where we live?",
 whyItMatters:"Plants are an accessible entry point into science, food systems and practical observation. This module helps learners recognize plant parts, compare useful plants, understand basic needs for growth and connect plants to food, livelihoods, environmental care and future GreenSkills learning.",
 outcomes:["Identify major plant parts and describe simple functions.","Distinguish roots, stems, leaves, flowers, fruits and seeds using local examples.","Explain basic plant needs including water, light, air, nutrients and space.","Observe and record simple differences among plants.","Connect plants to food, materials, shade, beauty and livelihoods.","Complete a safe supervised plant observation and care task using evidence."],
 vocabulary:["plant","root","stem","leaf","flower","fruit","seed","soil","water","sunlight","nutrient","observe","compare","care","harvest"],
 materials:["safe local plant samples or live plants","magnifying glass if available","paper and pencils","plant-part picture cards","small containers or garden bed","watering container","labels","optional facilitator-controlled tablet/phone for guided image comparison"],
 safety:["Do not taste unknown plants.","Avoid poisonous, irritating or thorny species in child activities.","Wash hands after handling soil or plant material.","Use only child-safe tools with supervision.","Learners with allergies or mobility limitations should receive adapted roles.","Do not identify edible or medicinal safety based on AI output alone."],
 lessons:[
  {id:"PF-04-L1",title:"Meet a Plant",objective:"Recognize a plant as a living organism with observable parts and needs.",teaching:["Plants are living things that grow and change.","Different plants can look very different but share common features.","Careful observation helps us describe what we see before we explain why."],activity:"Observe two safe local plants and list or draw three similarities and three differences.",diy:"Create a plant observation card with a drawing, location, size estimate and two visible features.",aiLayer:"AI Layer 1 — Recognition: facilitator shows how an AI image description may identify visible features, then learners compare it with their own observation.",enterprise:"People create value by growing, caring for, transporting and using plants responsibly.",quiz:[{question:"Plants are…",options:["living things","machines","rocks","numbers"],answer:0},{question:"A good observer should…",options:["look carefully","guess without looking","damage the plant","ignore differences"],answer:0},{question:"Two plants may…",options:["share some features and differ in others","always be identical","never need water","have no parts"],answer:0}]},
  {id:"PF-04-L2",title:"Roots, Stems and Leaves",objective:"Identify roots, stems and leaves and describe their basic roles.",teaching:["Roots help anchor plants and take up water and nutrients.","Stems support leaves and move water and materials through the plant.","Leaves capture light and help the plant make food."],activity:"Match real samples or pictures to ROOT, STEM and LEAF, then trace the path water might take from soil upward.",diy:"Build a simple labelled plant model from paper, sticks or recycled materials.",aiLayer:"AI Layer 2 — Guided comparison: use a facilitator-controlled image tool to compare unusual roots, stems or leaves, then verify with trusted learning materials.",enterprise:"Understanding plant parts helps growers handle crops correctly and reduce damage.",quiz:[{question:"Which part usually anchors a plant?",options:["root","flower","fruit","label"],answer:0},{question:"Leaves mainly help capture…",options:["light","money","plastic","noise"],answer:0},{question:"Stems help…",options:["support and transport","erase roots","stop growth","replace soil"],answer:0}]},
  {id:"PF-04-L3",title:"Flowers, Fruits and Seeds",objective:"Explain the relationship among flowers, fruits and seeds using simple examples.",teaching:["Many flowering plants produce flowers as part of reproduction.","Fruits often protect or carry seeds.","Seeds can grow into new plants when conditions are suitable."],activity:"Sort safe plant examples or pictures into flower, fruit and seed groups and discuss which are connected.",diy:"Create a three-stage sequence card: FLOWER → FRUIT → SEED using one familiar crop.",aiLayer:"AI Layer 3 — Sequencing and classification: compare learner-made life-cycle sequences with a facilitator-generated sequence and identify any errors.",enterprise:"Seeds, fruits and flowers can be important products, but quality depends on safe production and handling.",quiz:[{question:"Seeds can…",options:["grow into new plants","turn into metal","replace water","make electricity directly"],answer:0},{question:"A fruit often contains…",options:["seeds","tools","wires","stones only"],answer:0},{question:"Which sequence is often correct?",options:["flower → fruit → seed","seed → metal → fruit","leaf → battery → root","soil → wire → flower"],answer:0}]},
  {id:"PF-04-L4",title:"What Plants Need",objective:"Identify basic conditions plants need to grow well.",teaching:["Plants need water, light, air, nutrients and suitable space.","Too little or too much of a resource can cause problems.","Different plants may need different amounts of water, light and space."],activity:"Compare two identical seedlings placed under different safe conditions and predict what may happen.",diy:"Make a plant-needs wheel showing water, light, air, nutrients and space.",aiLayer:"AI Layer 4 — Prediction: facilitator asks an AI tool for a prediction about one plant-care scenario; learners compare the prediction with evidence from their own observation.",enterprise:"Good resource management can reduce waste of water, soil inputs and planting materials.",quiz:[{question:"Which is a basic plant need?",options:["water","plastic toys","passwords","paint"],answer:0},{question:"Can too much water harm some plants?",options:["Yes","No, never","Only at night","Only online"],answer:0},{question:"Different plants may need…",options:["different amounts of resources","exactly identical care always","no light","no space"],answer:0}]},
  {id:"PF-04-L5",title:"Useful Plants Around Us",objective:"Classify familiar plants by one or more useful roles in food, shade, materials, beauty or livelihood.",teaching:["Plants can serve more than one purpose.","People depend on plants for food and many materials.","Using plants responsibly includes care for soil, water and future supply."],activity:"Create a community plant-use chart with categories such as food, shade, fibre/material, decoration and income/livelihood.",diy:"Interview a trusted adult about one useful local plant and record what part is used and how it is cared for.",aiLayer:"AI Layer 5 — Verification: facilitator demonstrates that AI may suggest plant uses, but local identification and safety claims must be checked with reliable people or sources.",enterprise:"Explore how plant knowledge supports nursery work, farming, food processing, landscaping and other livelihoods without assigning commercial work to children.",quiz:[{question:"Can one plant have several uses?",options:["Yes","No","Only imported plants","Only trees"],answer:0},{question:"Plant-use information should be…",options:["checked for accuracy","invented","kept unsafe","based only on AI"],answer:0},{question:"Responsible plant use includes…",options:["care for resources","waste","damage","unsafe harvesting"],answer:0}]},
  {id:"PF-04-L6",title:"Care for a Living Plant",objective:"Apply observation and basic care to a supervised plant and document evidence of change.",teaching:["Plant care is a cycle: observe → decide → act → check.","Records help us notice change over time.","Good care avoids waste and responds to what the plant actually needs."],activity:"In pairs, inspect a plant or small bed, identify one care need and complete a supervised action such as watering, mulching or removing safe debris.",diy:"Maintain a three-entry plant-care log with date, observation, action and result.",aiLayer:"Integration: learners compare their care decision with an AI suggestion provided by the facilitator, then justify the final choice using observed evidence and local guidance.",enterprise:"Reliable care, record keeping and quality observation are foundational work habits across agriculture and green livelihoods.",quiz:[{question:"A useful care cycle is…",options:["observe → decide → act → check","act → ignore → forget","guess → waste → leave","copy → hide → stop"],answer:0},{question:"Why keep a plant-care record?",options:["to track change","to hide evidence","to avoid observation","to replace the plant"],answer:0},{question:"A good care decision should use…",options:["observation and reliable guidance","random guessing","private passwords","unsafe instructions"],answer:0}]}
 ],
 finalAssessment:{mcq:[{question:"Which plant part usually takes up water from soil?",options:["Roots","Flowers","Fruit","Seeds only"],answer:0},{question:"Which plant part commonly captures light?",options:["Leaves","Roots","Fruit only","Labels"],answer:0},{question:"What can seeds become under suitable conditions?",options:["New plants","Metal","Plastic","Batteries"],answer:0},{question:"Which is a basic plant need?",options:["Water","Password","Paint","Fuel only"],answer:0},{question:"Why compare plants?",options:["To notice similarities and differences","To damage them","To avoid learning","To make them identical"],answer:0},{question:"Can AI alone safely confirm whether an unknown plant is edible?",options:["No","Yes always","Only if the photo is bright","Only if a child asks"],answer:0},{question:"Which is good plant-care evidence?",options:["A dated observation log","A rumor","A guess with no observation","Someone else's unrelated work"],answer:0},{question:"Plant knowledge can support livelihoods through…",options:["growing, nursery work, processing and care","waste only","unsafe handling","hiding information"],answer:0}],theory:["Name the main parts of a familiar plant and describe one function of each.","Explain five things plants may need to grow well.","Describe one useful local plant and at least two ways people use it.","Explain why a plant-care record can help a grower make better decisions.","Explain why AI-generated information about an unknown plant should be checked before anyone eats or uses it."],practical:"Observe a safe living plant, identify at least four visible parts or features, assess one care need, complete one supervised care action and present a short evidence record showing observation, action and expected result."},
 evidence:["Plant observation card","Plant-part model","Flower-fruit-seed sequence card","Plant-needs wheel","Community plant-use chart or interview record","Three-entry plant-care log","Facilitator practical observation record"],
 passport:["K: identifies plant parts, needs and common uses","P: performs a supervised plant observation and care task","D: compares digital/AI suggestions with direct evidence and trusted sources","S: follows safe plant, soil and tool handling rules","E: connects plant knowledge to useful products, services and resource stewardship","L: works cooperatively, records observations and communicates care decisions"],
 trainerNotes:["Use plants learners actually encounter locally where safe.","Do not present medicinal claims as established facts in this foundation module.","Use oral, pictorial and tactile options for emerging readers.","Rotate observation, watering, measuring and reporting roles equitably.","Where no garden is available, use container plants or high-quality images plus one supervised live-plant observation if possible."],
 remediation:"Reduce the number of plant parts introduced at once, use repeated matching with real objects or tactile models, and rehearse the observe–name–function sequence.",
 extension:"Learner creates a one-page profile of a locally important crop showing plant parts, one growth need, one use and one care action.",
 imagePrompts:["Photorealistic African children ages 8–11 observing safe garden plants with a supportive facilitator, pointing to roots, stems and leaves, inclusive school-community garden, natural daylight, no readable text, LIFEWS green and golden accents.","Child-friendly botanical teaching illustration showing a generic flowering food plant with clearly visible roots, stem, leaves, flower, fruit and seeds, clean white background, no labels or text.","Photorealistic small group of African learners watering and mulching a supervised container garden while recording observations on paper, safe tools, collaborative, no text." ]
};

export const pf04ByLanguage: Partial<Record<AppLanguage,PF04Module>> = { en };
export function getPF04(language:AppLanguage):PF04Module { return pf04ByLanguage[language] ?? en; }
