import type { PF01Module } from "./pf-01";

type PF03Module = Omit<PF01Module,"code"> & { code:"PF-03" };

export const pf03Ha: PF03Module = {
  code:"PF-03",
  title:"Lambobi a Rayuwar Yau da Kullum",
  level:"Pathways Foundation",
  age:"Kimanin shekaru 8–11; a sanya ɗalibi a matakin lissafi ne bisa gwajin farko.",
  duration:"Darussa 6 masu jagoranci tare da aikin hannu da tantancewa",
  fieldworkHours:2,
  bigQuestion:"Ta yaya lambobi ke taimaka mana mu ƙirga, kwatanta, auna, tsara da yanke shawarwari mafi kyau a rayuwar yau da kullum?",
  whyItMatters:"Lissafin amfani yana taimaka wa ɗalibai su shiga rayuwar yau da kullum, aikin hannu da horon sana’a na gaba da ƙarfin gwiwa. Wannan rukunin yana gina ƙirga, kwatantawa, kimantawa, aunawa, rubuta bayanai da warware matsaloli masu sauƙi ta misalan abinci, ruwa, lambu, gida da al’umma.",
  outcomes:["Ƙirga da wakiltar adadi ta amfani da abubuwa, alamomi da lambobi.","Kwatanta adadi ta amfani da fiye, ƙasa, daidai, mafi girma da mafi ƙanƙanta.","Auna tsawo, girman ruwa da nauyi da kayan aiki masu dacewa ko ma’aunin gargajiya.","Amfani da ƙari da ragi masu sauƙi a yanayin aiki.","Rubuta lura a tebur ko jadawalin tally mai sauƙi.","Amfani da taimakon dijital ko AI a ƙarƙashin jagoranci don bincika tsari ko lissafi yayin bayyana dalilin lissafin da kai."],
  vocabulary:["lamba","ƙirga","adadi","fiye","ƙasa","daidai","auna","tsawo","girma","nauyi","kimanta","ƙara","rage","tebur","tally"],
  materials:["abubuwan ƙirga kamar iri ko murfin kwalba","katunan lambobi","igiya/ma’auni/tef ɗin aunawa","kofuna ko kwantena na aunawa","ma’aunin nauyi mai sauƙi idan akwai","takarda da fensir","samfurin tally","kalkuleta ko kwamfutar hannu ƙarƙashin kulawa idan ana bukata"],
  safety:["Yi amfani da abubuwan ƙirga masu tsabta da ba su da kaifi.","Kada a yi amfani da kaya masu nauyi ko kwantena masu haɗari wajen aunawa.","A haɗa ɗalibai biyu-biyu domin masu farawa a lissafi su shiga ba tare da kunya ba.","Kada a bari ɗalibai su dogara ga kalkuleta ko AI kafin su nuna fahimtar dalilin lissafin.","Dukkan ayyukan aunawa na hannu su dace da shekaru kuma a sa ido a kansu."],
  lessons:[
    {id:"PF-03-L1",title:"Ƙirga Abin da Muke Gani",objective:"Ƙirga, rarraba da wakiltar abubuwan da aka saba da su daidai.",teaching:["Ƙirga yana gaya mana yawan abubuwan da ke cikin rukuni.","Rarraba abubuwa zuwa rukuni na iya sauƙaƙa ƙirga adadi mai yawa.","Ana iya nuna adadi da abubuwa, tally, kalmomi ko lambobi."],activity:"Ƙirga da rarraba iri, murfin kwalba ko katunan hoto zuwa rukuni na 2, 5 da 10; kwatanta hanyoyi daban-daban na nuna adadi ɗaya.",diy:"Ƙirƙiri farantin ƙirga mai sassa biyar sannan ka sanya adadi daban a kowane sashe.",aiLayer:"Matakin AI 1 — Ganewa: kwatanta ƙirgar ɗalibi da ƙirgar dijital da mai koyarwa ya shigar, sannan a tattauna yadda kayan aiki ke taimakawa bincike amma ba sa maye gurbin hankali.",enterprise:"Ƙirga daidai yana da muhimmanci wajen tsara kayan aiki, duba haja da raba albarkatu cikin adalci.",quiz:[{question:"Me ƙirga yake gaya mana?",options:["Yawan abubuwa","Launinsu","Mai mallakarsu","Shekarunsu"],answer:0},{question:"Rarraba zuwa rukuni yana taimaka mana mu…",options:["ƙirga adadi mai yawa","ɓoye abubuwa","guje wa lambobi","canza jimilla"],answer:0},{question:"Me zai iya wakiltar adadi?",options:["Alamomin tally","Kalmomi kaɗai","Hotuna kaɗai","Babu komai"],answer:0}]},
    {id:"PF-03-L2",title:"Fiye, Ƙasa da Daidai",objective:"Kwatanta adadi biyu ko fiye da amfani da kalmomin kwatantawa masu dacewa.",teaching:["Muna kwatanta adadi don ganin wanda ya fi, ya yi ƙasa ko ya yi daidai.","Daidai yana nufin adadi biyu suna da ƙima iri ɗaya.","Kwatantawa yana taimaka mana yanke shawara cikin adalci da inganci."],activity:"Kwatanta kwanoni na abubuwa, matakin ruwa a kwantena masu gani da tsawon igiya; bayyana kowane kwatanci da baki.",diy:"Yi katunan kwatantawa shida da zane da kalmomin FIYE, ƘASA ko DAIDAI.",aiLayer:"Matakin AI 2 — Hulɗa mai jagoranci: mai koyarwa ya nemi kayan dijital/AI ya kawo misalan kwatantawa masu sauƙi; ɗalibai su warware da farko sannan su duba amsar kayan aikin.",enterprise:"Kwatanta adadi yana taimaka wa mutane rage ɓarna da sanin yawan kayan da ake bukata.",quiz:[{question:"Daidai yana nufin…",options:["adadi iri ɗaya","fiye koyaushe","ƙasa koyaushe","ba a sani ba"],answer:0},{question:"Idan kwando A yana da ’ya’yan itace 8, B yana da 5, A yana da…",options:["fiye","ƙasa","daidai","sifili"],answer:0},{question:"Kwatantawa yana da amfani wajen…",options:["yanke shawara","guje wa duk aunawa","ɓoye bayanai","canza gaskiya"],answer:0}]},
    {id:"PF-03-L3",title:"Auna Tsawo da Nisa",objective:"Auna da kwatanta tsawo ta amfani da ma’auni na gargajiya da na daidaitacce idan akwai.",teaching:["Aunawa yana sanya lamba ga sifa kamar tsawo.","Ya kamata a yi amfani da ma’auni iri ɗaya idan ana kwatanta sakamako.","Kimantawa zato ne mai dalili da ake yi kafin aunawa."],activity:"Kimanta sannan auna tsawon tebur, gadon lambu, igiya ko abin aji ta amfani da tafin hannu, taku, sannan ma’auni ko tef idan akwai.",diy:"Ƙirƙiri rikodin aunawa na abubuwa biyar da ke nuna kimantawa, ainihin aunawa da bambanci.",aiLayer:"Matakin AI 3 — Gane tsari: kwatanta kuskuren kimantawa don ganin ko kimantawar tana yawan zama sama, ƙasa ko kusa da ainihi.",enterprise:"Aunawa daidai yana da muhimmanci wajen gini, shuka, yanke kayan aiki da tsara fili.",quiz:[{question:"Me ya sa ake amfani da ma’auni iri ɗaya wajen kwatantawa?",options:["Domin aunawar su zama masu kwatantuwa","Domin canza sakamako","Domin lissafi ya yi wahala","Ba shi da muhimmanci"],answer:0},{question:"Kimantawa ita ce…",options:["zato mai dalili kafin aunawa","abin da kullum yake daidai","lamba ta sirri","farashi"],answer:0},{question:"Wane kayan aiki ake auna tsawo da shi?",options:["Ma’auni ko tef","Kofi kaɗai","Cokali kaɗai","Taken littafi"],answer:0}]},
    {id:"PF-03-L4",title:"Auna Ruwa da Sauran Adadi",objective:"Auna girman ruwa da nauyi masu sauƙi cikin aminci ta kayan aiki ko ma’auni masu dacewa.",teaching:["Girma yana nuna yawan sararin da ruwa ke ɗauka.","Nauyi yana nuna yadda abu yake da nauyi idan aka kwatanta da ma’auni.","Aunawa da hankali yana rage kuskure da ɓarna."],activity:"Auna ruwa iri ɗaya a kwantena sannan kwatanta nauyin abubuwan aji ko lambu masu aminci da ma’aunin sauƙi.",diy:"Shirya teburin aunawa na abubuwa huɗu da abu, adadi, ma’auni da sakamako.",aiLayer:"Matakin AI 4 — Tambaya mai iyaka: mai koyarwa ya nemi misalan inda aunawa daidai yake da muhimmanci; ɗalibai su rarraba su zuwa abinci, ruwa, gini, noma ko gida.",enterprise:"Adadi mai daidaito yana da muhimmanci a girki, marufi, ban ruwa da amfani da albarkatu cikin alhaki.",quiz:[{question:"Girma yana gaya mana…",options:["sararin da ruwa ke ɗauka","ƙarfin sauti","shekarun abu","launinsa"],answer:0},{question:"Me ya sa ake auna da hankali?",options:["Don rage kuskure da ɓarna","Don bayanai su zama marasa amfani","Don ɓoye bambanci","Don guje wa alhaki"],answer:0},{question:"Wanne ma’auni ne?",options:["lita","lambu","malami","hoto"],answer:0}]},
    {id:"PF-03-L5",title:"Ƙari da Ragi a Rayuwa",objective:"Amfani da ƙari da ragi masu sauƙi don warware matsalolin yau da kullum.",teaching:["Ƙari yana haɗa adadi.","Ragi yana nuna abin da ya rage ko bambancin adadi biyu.","Zane, abubuwa da layin lambobi na iya taimaka wa warware matsala."],activity:"Warware labaran lissafi da suka shafi iri da aka shuka, kofunan ruwa da aka yi amfani da su, ’ya’yan itace da aka raba ko kayan aiki da aka ƙirga, ta amfani da abubuwa kafin lambobi.",diy:"Ƙirƙiri matsalolin ƙari biyu da ragi biyu daga yanayin al’umma ko lambu sannan ka warware su.",aiLayer:"Matakin AI 5 — Kimantawa: mai koyarwa ya nuna mafita ta dijital guda ɗaya daidai da ɗaya marar daidaito; ɗalibai su bayyana wacce ta dace da dalili.",enterprise:"Lissafi mai sauƙi yana taimakawa ƙirga haja, tsara kayan aiki da duba canji, amma ba a tilasta wa yara yin ciniki ba.",quiz:[{question:"Ana amfani da ƙari don…",options:["haɗa adadi","ɓoye adadi","goge duk lambobi","auna zafi kawai"],answer:0},{question:"Ragi na iya gaya mana…",options:["abin da ya rage","launi kaɗai","suna kaɗai","babu abin amfani"],answer:0},{question:"Hanya mai kyau ta binciken lissafi ita ce…",options:["amfani da abubuwa ko wata hanya","karɓar kowace amsa","tsallake matsala","kwafa ba tare da tunani ba"],answer:0}]},
    {id:"PF-03-L6",title:"Rubuta Lambobi da Gano Tsari",objective:"Rubuta bayanai masu sauƙi da gano tsari ko canji na asali.",teaching:["Tally yana nuna sau nawa wani abu ya faru.","Tebur yana tsara bayanai cikin layuka da ginshiƙai.","Tsari yana taimaka mana mu ga maimaitawa, canji da yiwuwar dangantaka."],activity:"Tattara ƙaramin bayanin aji ko lambu kamar yawan tsire-tsire, kofunan ruwa na rana ko ayyukan koyo da aka fi so, sannan a yi tally ko tebur.",diy:"Ƙirƙiri ƙaramin rikodin mako guda da lura aƙalla biyar sannan ka rubuta ko faɗi abubuwa biyu da ka lura da su.",aiLayer:"Haɗawa: mai koyarwa na iya shigar da bayanin a spreadsheet ko AI don yin taƙaitawa; ɗalibai su kwatanta taƙaitawar da abin da suka lura da kansu.",enterprise:"Rikodi yana taimaka wa mutane fahimtar abin da ya faru, rage zato da tsara abubuwa da kyau.",quiz:[{question:"Me tally yake nuna?",options:["Sau nawa abu ya faru","Sunaye kaɗai","Hotuna kaɗai","Kuɗi kaɗai"],answer:0},{question:"Tebur yana tsara bayanai da…",options:["layuka da ginshiƙai","launuka kaɗai","sirri","alamomi marasa tsari"],answer:0},{question:"Me ya sa ake ajiye rikodi?",options:["Don yanke shawara mafi kyau","Don bayanai su ɓace","Don guje wa koyo","Don maye gurbin lura"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Menene manufar ƙirga?",options:["Sanin yawan abubuwa","Sanin launi kaɗai","Ɓoye abubuwa","Canza ƙima"],answer:0},{question:"Wace kalma ke nufin adadi biyu suna daidai?",options:["Daidai","Fiye","Ƙasa","Kimantawa"],answer:0},{question:"Me ya kamata a yi da kimantawa?",options:["Kimanta, auna sannan kwatanta","Yi zato ka tsaya","Auna ba tare da rubutawa ba","Yi watsi da sakamako"],answer:0},{question:"Wace dabara ke haɗa adadi?",options:["Ƙari","Ragi kaɗai","Kwatantawa","Kimantawa"],answer:0},{question:"Ana amfani da lita wajen auna…",options:["girma","shekaru","launi","nisa tsakanin birane kaɗai"],answer:0},{question:"Me ya sa rikodi yake da amfani?",options:["Yana taimaka mana sanin abin da ya faru da tsara gaba","Yana cire shaida","Yana sa lambobi su zama marasa amfani","Yana hana kwatantawa"],answer:0},{question:"Idan AI ya ba da amsar lissafi daban da taka, me ya kamata ka yi?",options:["Bincika dalilin da abubuwa ko wata hanya","Ka ɗauka AI kullum daidai ne","Goge aikin ka","Raba bayanan sirri"],answer:0},{question:"Wace fasaha ce da amfani wajen tsara gadon lambu?",options:["Aunawa","Yi watsi da sarari","Zato kawai","Guje wa lambobi"],answer:0}],theory:["Bayyana hanyoyi biyu da ake amfani da lambobi a rayuwar yau da kullum.","Bayyana bambancin fiye, ƙasa da daidai da misalinka.","Bayyana dalilin da ya sa kimantawa na iya zama da amfani kafin aunawa.","Ƙirƙiri matsalar ƙari ko ragi ta amfani da misalin abinci, ruwa ko lambu sannan ka warware ta.","Bayyana dalilin da ya sa mutum ya kamata ya fahimci lissafi maimakon dogaro gaba ɗaya ga kalkuleta ko AI."],practical:"Yi ƙaramin binciken lissafi: kimanta sannan auna abubuwa ko adadi uku masu aminci, rubuta sakamakon a tebur, warware matsalar ƙari guda ɗaya da ragi guda ɗaya ta bayanan da aka tattara, sannan ka bayyana tsari ko kwatanci guda ɗaya da ka lura da shi."},
  evidence:["Farantin ƙirga ko rikodin rukuni","Katunan kwatantawa","Rikodin kimantawa da aunawa na abubuwa biyar","Teburin aunawa","Matsalolin lissafi da ɗalibi ya ƙirƙira","Rikodin bayanai na mako guda","Jerin lura na lissafi na mai koyarwa"],
  passport:["K: yana fahimtar ƙirga, kwatantawa, aunawa, ƙari, ragi da rikodin bayanai masu sauƙi","P: yana auna, rubutawa da warware matsalolin adadi na aiki","D: yana bincika sakamakon dijital/AI da dalilin kansa","S: yana amfani da kayan aunawa da kwantena cikin aminci","E: yana bayyana yadda ƙirga, aunawa da rikodi ke rage ɓarna da tallafa wa shiri","L: yana bayyana dalili, yana aiki tare da wasu kuma yana gyara kuskure cikin gina juna"],
  trainerNotes:["Yi amfani da abubuwa na zahiri kafin alamomin lissafi ga waɗanda suke bukata.","Yarda da bayanin baka da nuna aiki a matsayin shaida tare da rubutu.","Yi amfani da misalan da suka saba da al’adu da kayan aunawa da ake samu a gida.","Idan ba a kware ma’aunin daidaitacce ba, a fara da ma’auni na gargajiya mai daidaito sannan a koma na daidaitacce a hankali.","A guji gasar sauri da ke kunyata ɗalibai; a fi jaddada dalili da ci gaba."],
  remediation:"Komawa ga abubuwa na zahiri, daidaitawa ɗaya-da-ɗaya, layin lambobi da maimaita aunawa da ma’auni guda ɗaya a lokaci. Rage iyakar lambobi amma a ci gaba da aikin amfani iri ɗaya.",
  extension:"Ɗalibi ya ƙirƙiri ƙaramin ƙalubalen amfani da albarkatu, misali ƙirga kofunan ruwa da ake amfani da su ga wasu tsire-tsire a kowace rana, sannan ya ba da shawarar ingantawa bisa bayanai.",
  imagePrompts:["Yara Afirka shekaru 8–11 suna ƙirga iri, auna ruwa a kofuna masu bayyane da amfani da tef ɗin aunawa a lambun koyarwa ƙarƙashin kulawa, yara maza da mata tare, hasken rana, babu rubutu mai karantawa, kore da rawaya na LIFEWS.","Zanen koyarwa mai tsabta ga yara da alamomi shida: ƙirga, kwatantawa, ma’auni, girman ruwa, ƙari mai sauƙi da tally, farin bango, babu kalmomi.","Ƙaramin rukuni na ɗaliban Afirka suna rubuta yawan tsire-tsire a tebur mai sauƙi a kan takarda kusa da lambun makaranta, mai koyarwa a kusa, haɗin kai da ya dace da shekaru, babu rubutu mai karantawa."]
};