import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "./pf-01";

type PF02Module = Omit<PF01Module,"code"> & { code:"PF-02" };

const en: PF02Module = {
 code:"PF-02", title:"Reading the World Around Me", level:"Pathways Foundation", age:"Approximately 8–11 years; literacy placement should follow baseline assessment.", duration:"6 guided lessons plus reading practice, practical and assessment time", fieldworkHours:2,
 bigQuestion:"How can words, pictures, signs and symbols help me understand and act safely in the world around me?",
 whyItMatters:"Foundational literacy becomes more meaningful when learners can connect print to daily life. This module develops observation, oral language, vocabulary, decoding and functional reading through familiar food, water, energy, garden and community contexts while respecting learners who are beginning literacy at different ages.",
 outcomes:["Recognize that print, pictures, signs and symbols communicate meaning.","Read and use a core set of familiar environmental and food-system words.","Match spoken words, pictures and written words.","Use context clues and careful observation to make and check meaning.","Create a useful labelled picture-word information product.","Use guided AI or digital support to compare, classify or check words without sharing private information."],
 vocabulary:["word","letter","sound","picture","sign","symbol","label","meaning","read","check","food","water","plant","energy","safe"],
 materials:["locally relevant picture cards","word cards","alphabet/phonics cards appropriate to language of instruction","clean food packages or reproduced labels","garden/household object samples","paper and markers","optional facilitator-controlled device"],
 safety:["Use only clean, safe objects and packages.","Do not use literacy errors to shame or rank learners.","Adapt phonics instruction to the selected language; do not assume English sound-letter rules transfer to Hausa, Arabic, Yoruba, Igbo or French.","Do not ask learners to photograph or upload identifiable people, addresses or private documents to AI tools."],
 lessons:[
  {id:"PF-02-L1",title:"Pictures, Signs and Meaning",objective:"Explain how pictures, signs, symbols and words communicate information.",teaching:["We read more than books: we read signs, symbols, pictures, labels and situations.","A symbol can communicate quickly, but its meaning depends on shared understanding.","Good readers observe before deciding what something means."],activity:"Meaning hunt: examine familiar signs and picture cards and explain what each is trying to communicate.",diy:"Design one simple safety or care symbol for the learning garden or classroom and explain it orally.",aiLayer:"AI Layer 1 — Recognition: distinguish a human-made sign, a digital search result and an AI-generated suggestion; all are information sources that still require interpretation.",enterprise:"Clear signs and labels help people understand products, places and services; communication creates practical value.",quiz:[{question:"What can communicate meaning?",options:["Words, pictures and symbols","Only long books","Only numbers","Nothing around us"],answer:0},{question:"Before deciding what a sign means, we should…",options:["observe carefully","ignore it","damage it","guess without looking"],answer:0},{question:"A label is used to…",options:["identify or explain something","hide all information","make reading impossible","replace safety"],answer:0}]},
  {id:"PF-02-L2",title:"Words in Food, Water and Energy",objective:"Recognize and read familiar high-utility words from everyday FEW contexts.",teaching:["Familiar words are easier to learn when connected to real objects and actions.","Words can name things, actions and qualities.","Repeated reading builds speed and confidence."],activity:"Rotate through word stations for food, water, plants, tools and energy; match each word card to a picture or safe object.",diy:"Create ten personal picture-word cards and practise reading them to a partner.",aiLayer:"AI Layer 2 — Guided interaction: facilitator asks an AI tool for simple example sentences using selected words; learners check whether each sentence makes sense locally.",enterprise:"People need accurate words to name, describe and organize useful goods and services.",quiz:[{question:"Which helps you learn a new word?",options:["Connecting it to a picture or object","Never seeing it again","Hiding it","Skipping every sound"],answer:0},{question:"Repeated reading can improve…",options:["confidence and fluency","water quality automatically","weather","battery size"],answer:0},{question:"Which is a food-system word?",options:["seed","password","satellite only","silence"],answer:0}]},
  {id:"PF-02-L3",title:"Letters, Sounds and Word Parts",objective:"Use language-appropriate letter/sound or script patterns to decode selected familiar words.",teaching:["Written languages represent speech in different ways.","We can look for familiar letters, sounds, syllables or word parts.","When a word is difficult, we can slow down, segment it and use context."],activity:"Build familiar words using movable letters, syllable cards or script units appropriate to the instructional language.",diy:"Make a word ladder containing five related words and mark the part you recognize in each.",aiLayer:"AI Layer 3 — Pattern recognition: learners group words by a visible or audible pattern, then compare their grouping with a facilitator-generated digital suggestion.",enterprise:"Pattern recognition supports accurate counting, labeling, record keeping and quality checking.",quiz:[{question:"When a word is difficult, a useful strategy is…",options:["break it into manageable parts","give up immediately","invent any word","cover it"],answer:0},{question:"Do all six program languages use exactly the same sound-letter rules?",options:["No","Yes","Only on Mondays","Only in gardens"],answer:0},{question:"Finding repeated word parts is a form of…",options:["pattern recognition","waste","hiding","pricing"],answer:0}]},
  {id:"PF-02-L4",title:"Reading Labels and Instructions",objective:"Extract simple useful information from an age-appropriate label, sign or instruction.",teaching:["Functional reading helps us make safe everyday choices.","Titles, pictures, numbers and key words can help us locate information.","We should ask a trusted adult when safety information is unclear."],activity:"Read teacher-prepared labels for seed packets, water containers or garden tools and identify name, purpose and one instruction.",diy:"Create a three-part label for a classroom or garden item: NAME → USE → CARE/SAFETY.",aiLayer:"AI Layer 4 — Bounded prompting: facilitator demonstrates asking for a child-friendly explanation of a non-sensitive label; learners compare the explanation with the original and identify anything missing.",enterprise:"Accurate labeling supports trust, safety and responsible enterprise; false or unclear labels can harm people.",quiz:[{question:"Why do we read instructions?",options:["To know how to act safely and correctly","To make them disappear","To avoid understanding","Only to decorate"],answer:0},{question:"If safety information is unclear, you should…",options:["ask a trusted adult","guess with a dangerous tool","ignore it","change the label"],answer:0},{question:"A useful label should be…",options:["clear and accurate","deliberately misleading","unreadable","secret"],answer:0}]},
  {id:"PF-02-L5",title:"Check the Meaning",objective:"Use context, pictures and reliable help to check whether an interpretation is reasonable.",teaching:["Good readers check meaning rather than accepting the first guess.","Pictures and surrounding words provide context clues.","Digital and AI tools can make errors, so important information must be checked."],activity:"Read short picture-supported statements containing one deliberately mismatched word; identify and correct the mismatch.",diy:"Make a 'Read–Think–Check' bookmark or card with three visual steps.",aiLayer:"AI Layer 5 — Evaluation: facilitator presents one correct and one incorrect AI-generated description of a familiar object; learners cite visible evidence for which is better.",enterprise:"Checking information prevents mistakes in records, labels, quantities and customer communication.",quiz:[{question:"A context clue helps us…",options:["work out meaning","forget the text","share passwords","avoid looking"],answer:0},{question:"Should every AI-generated description be accepted automatically?",options:["No","Yes","Always if it is long","Only if colorful"],answer:0},{question:"Which sequence is useful?",options:["Read–Think–Check","Guess–Hide–Leave","Copy–Forget–Share","Skip–Skip–Skip"],answer:0}]},
  {id:"PF-02-L6",title:"My Picture-Word Guide",objective:"Create and present a functional picture-word guide using accurate vocabulary and labels.",teaching:["Authors choose information for an audience and purpose.","A useful guide should be organized, readable and accurate.","Creating information is also a responsibility: we check before sharing."],activity:"Plan a mini guide on one theme: school garden, clean water, healthy food ingredients, safe energy use or community learning.",diy:"Produce a six-entry Picture-Word Guide with a picture, key word and one short fact/instruction for each entry, then read/present it to peers.",aiLayer:"Integration: AI may suggest candidate words or simple sentences under facilitator control; the learner must select, correct and explain the final content.",enterprise:"A clear information product is an example of creating value through communication and design; quality means usefulness, accuracy and care.",quiz:[{question:"Who is an audience?",options:["The people information is made for","Only the author","A type of seed","A password"],answer:0},{question:"Before sharing a guide, you should…",options:["check its accuracy","add private data","remove all labels","copy without reading"],answer:0},{question:"A good information product should be…",options:["useful and understandable","misleading","unsafe","impossible to read"],answer:0}]}
 ],
 finalAssessment:{mcq:[{question:"Which is an example of functional reading?",options:["Reading a safety sign","Ignoring a label","Hiding a word","Destroying instructions"],answer:0},{question:"What helps a reader understand an unfamiliar word?",options:["Context and word parts","Closing the page","Random guessing only","Skipping every clue"],answer:0},{question:"Why are pictures useful in early literacy?",options:["They can support meaning","They make words unnecessary forever","They replace safety","They guarantee every interpretation"],answer:0},{question:"Which label quality is important?",options:["Accuracy","Deception","Confusion","Secrecy"],answer:0},{question:"What should happen before important AI-generated information is shared?",options:["It should be checked","Nothing","Private data should be added","The source text should be ignored"],answer:0},{question:"Which sequence supports careful reading?",options:["Observe–Read–Think–Check","Guess–Share–Forget","Hide–Copy–Leave","Rush–Ignore–Post"],answer:0},{question:"Why might literacy instruction differ across English, Arabic and Yoruba?",options:["Their writing and sound systems differ","All languages are identical","Only one has words","They cannot be taught"],answer:0},{question:"A picture-word guide creates value when it is…",options:["useful, clear and accurate","false","unsafe","unreadable"],answer:0}],theory:["Explain three different things in your community that people can 'read' besides books.","Choose five familiar words and explain a strategy you use to recognize or decode them.","Describe how pictures or context clues can help you understand a new word.","Explain why labels and instructions should be accurate and easy to understand.","Describe one way to check an AI or digital explanation before using it."],practical:"Create and orally present a six-entry Picture-Word Guide for a familiar food, water, energy, garden or community-learning theme. Each entry must contain a relevant visual, an accurate key word and a short learner-generated fact or instruction. The facilitator assesses recognition, meaning, organization, accuracy and communication rather than handwriting alone."},
 evidence:["Ten personal picture-word cards","Word-pattern ladder","Three-part functional label","Read–Think–Check card","Six-entry Picture-Word Guide","Facilitator oral-reading/meaning observation record"],
 passport:["K: recognizes words, signs, symbols and functional text as sources of meaning","P: creates and uses labels and a picture-word information guide","D: uses guided digital/AI support to classify or check language while protecting privacy","S: reads or seeks help with basic safety information","E: explains why accurate communication and labeling create value and trust","L: reads/presents to peers, accepts feedback and checks work before sharing"],
 trainerNotes:["Teach literacy in the learner's selected instructional language; adapt decoding/phonics to that language rather than translating English phonics mechanically.","Permit oral responses, tracing, matching and picture selection while literacy develops.","Use local objects and culturally familiar images, but avoid stereotypes.","For Arabic, use appropriate RTL materials and script progression; for Yoruba and Igbo preserve diacritics where required; for French teach relevant sound-spelling relationships.","Assess meaning and progress, not accent."],
 remediation:"Reduce the active word set, increase picture/object matching, use repeated oral reading and multisensory letter/syllable work. Keep the same functional-literacy purpose.",
 extension:"Learner conducts a supervised sign-and-label audit of the learning space and recommends one new or improved label for accessibility or safety.",
 imagePrompts:["Photorealistic African foundational literacy lesson, diverse boys and girls ages 8–11 matching picture cards to words about plants, water, food and simple energy objects, supportive facilitator, clean community learning space, no readable text, LIFEWS green and warm-yellow accents.","Child-friendly educational illustration showing observation of a seed packet, water container, plant symbol and safety sign with magnifying-glass motif, clean white background, icons only, no written labels.","Photorealistic small group of African children creating a picture-word guide with drawings of garden crops and water items, pencils and cards on table, collaborative and inclusive, natural daylight, no readable text." ]
};

export const pf02ByLanguage: Partial<Record<AppLanguage,PF02Module>> = { en };
export function getPF02(language:AppLanguage):PF02Module { return pf02ByLanguage[language] ?? en; }
