import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "./pf-01";

type PF03Module = Omit<PF01Module,"code"> & { code:"PF-03" };

const en: PF03Module = {
 code:"PF-03", title:"Numbers in Everyday Life", level:"Pathways Foundation", age:"Approximately 8–11 years; numeracy placement should follow baseline assessment.", duration:"6 guided lessons plus practical and assessment time", fieldworkHours:2,
 bigQuestion:"How do numbers help us count, compare, measure, plan and make better everyday decisions?",
 whyItMatters:"Functional numeracy helps learners participate confidently in daily life, practical learning and future skills training. This module builds counting, comparing, estimating, measuring, recording and simple problem solving through familiar food, water, garden, household and community contexts.",
 outcomes:["Count and represent quantities using objects, marks and numerals.","Compare quantities using more, less, equal, greater and smaller.","Measure length, volume and mass with age-appropriate tools or informal units.","Use simple addition and subtraction in practical situations.","Record observations in a simple table or tally chart.","Use guided digital or AI support to check patterns or calculations while explaining the reasoning independently."],
 vocabulary:["number","count","quantity","more","less","equal","measure","length","volume","mass","estimate","add","subtract","table","tally"],
 materials:["counting objects such as seeds or bottle caps","number cards","string/rulers/tape measures","cups or measuring containers","simple balance scale if available","paper and pencils","tally-chart template","optional facilitator-controlled calculator/tablet"],
 safety:["Use clean, non-sharp counting objects.","Do not use heavy loads or unsafe containers for measurement activities.","Pair learners so those with emerging numeracy can participate without embarrassment.","Do not let learners depend on calculators or AI before demonstrating the underlying reasoning.","Keep all practical measuring tasks age-appropriate and supervised."],
 lessons:[
  {id:"PF-03-L1",title:"Counting What We Can See",objective:"Count, group and represent familiar objects accurately.",teaching:["Counting tells us how many items are in a group.","Grouping objects can make larger quantities easier to count.","Numbers can be shown with objects, tally marks, words or numerals."],activity:"Count and group seeds, caps or picture cards into sets of 2, 5 and 10; compare different ways of representing the same total.",diy:"Create a counting tray with five labelled sections and arrange a different quantity in each section.",aiLayer:"AI Layer 1 — Recognition: compare a learner count with a facilitator-entered digital count and discuss why tools can help check but not replace careful counting.",enterprise:"Accurate counting matters when organizing materials, checking stock or sharing resources fairly.",quiz:[{question:"What does counting tell us?",options:["How many items there are","What color they are","Who owns them","How old they are"],answer:0},{question:"Grouping can help us…",options:["count larger quantities","hide objects","avoid numbers","change the total"],answer:0},{question:"Which can represent a quantity?",options:["Tally marks","Only words","Only pictures","Nothing"],answer:0}]},
  {id:"PF-03-L2",title:"More, Less and Equal",objective:"Compare two or more quantities and use appropriate comparison language.",teaching:["We compare quantities to see which has more, less or the same amount.","Equal means two quantities have the same value.","Comparison helps us make fair and efficient decisions."],activity:"Compare bowls of objects, water levels in transparent containers and lengths of string; explain each comparison orally.",diy:"Make six comparison cards using drawings and the words MORE, LESS or EQUAL.",aiLayer:"AI Layer 2 — Guided interaction: facilitator asks an AI or digital tool to generate simple comparison examples; learners solve first and then check the tool's answer.",enterprise:"Comparing quantities helps people avoid waste and decide how much material is needed.",quiz:[{question:"Equal means…",options:["the same amount","always more","always less","unknown"],answer:0},{question:"If basket A has 8 fruits and B has 5, A has…",options:["more","less","equal","zero"],answer:0},{question:"Comparison is useful for…",options:["making decisions","avoiding all measurement","hiding records","changing facts"],answer:0}]},
  {id:"PF-03-L3",title:"Measuring Length and Distance",objective:"Measure and compare lengths using informal and standard units when available.",teaching:["Measurement gives a number to a property such as length.","The same unit should be used when comparing measurements.","Estimation is a reasonable guess made before measuring."],activity:"Estimate and then measure the length of a table, garden bed, rope or classroom object using hand spans, steps and then a ruler or tape where available.",diy:"Create a measurement record for five objects showing estimate, actual measure and difference.",aiLayer:"AI Layer 3 — Pattern recognition: compare estimate errors and identify whether estimates tend to be too high, too low or close.",enterprise:"Measuring accurately is important for building, planting, cutting materials and planning space.",quiz:[{question:"Why should the same unit be used for comparison?",options:["To make measurements comparable","To change the result","To make counting harder","It does not matter"],answer:0},{question:"An estimate is…",options:["a reasonable guess before measuring","always exact","a secret number","a price"],answer:0},{question:"Which tool can measure length?",options:["Ruler or tape","Cup only","Spoon only","Book title"],answer:0}]},
  {id:"PF-03-L4",title:"Measuring Water and Other Quantities",objective:"Measure simple volumes and masses safely using appropriate tools or agreed units.",teaching:["Volume tells us how much space a liquid takes up.","Mass tells us how heavy an object is compared with a unit.","Careful measurement reduces waste and improves consistency."],activity:"Measure equal volumes of water into containers and compare masses of safe classroom or garden items using a simple balance.",diy:"Prepare a four-item measurement table with item, quantity, unit and result.",aiLayer:"AI Layer 4 — Bounded prompting: facilitator asks for examples of where accurate measurement matters; learners classify examples as food, water, construction, farming or household use.",enterprise:"Consistent quantities matter in food preparation, packaging, irrigation and responsible resource use.",quiz:[{question:"Volume tells us…",options:["how much space a liquid takes up","how loud something is","how old it is","its color"],answer:0},{question:"Why measure carefully?",options:["To reduce errors and waste","To make records less useful","To hide differences","To avoid responsibility"],answer:0},{question:"Which is a measurement unit?",options:["litre","garden","teacher","picture"],answer:0}]},
  {id:"PF-03-L5",title:"Adding and Subtracting in Real Life",objective:"Use simple addition and subtraction to solve familiar practical problems.",teaching:["Addition combines quantities.","Subtraction finds what remains or the difference between quantities.","Drawing, objects and number lines can help us solve problems."],activity:"Solve practical stories involving seeds planted, cups of water used, fruits shared or tools counted, using objects before numerals.",diy:"Create two addition and two subtraction story problems based on familiar community or garden situations and solve them.",aiLayer:"AI Layer 5 — Evaluation: facilitator shows one correct and one incorrect digital solution to a simple problem; learners explain which is correct and why.",enterprise:"Simple arithmetic supports basic stock counts, material planning and checking change, but children are not required to conduct commercial transactions.",quiz:[{question:"Addition is used to…",options:["combine quantities","hide quantities","erase all numbers","measure temperature only"],answer:0},{question:"Subtraction can tell us…",options:["what remains","only colors","only names","nothing useful"],answer:0},{question:"A good way to check a calculation is…",options:["use objects or another method","accept any answer","skip the problem","copy without thinking"],answer:0}]},
  {id:"PF-03-L6",title:"Recording Numbers and Finding Patterns",objective:"Record simple data and identify basic patterns or changes.",teaching:["A tally chart records how often something happens.","Tables organize information into rows and columns.","Patterns help us notice repetition, change and possible relationships."],activity:"Collect one small class or garden dataset such as plant counts, daily water cups or preferred learning activities and build a tally/table.",diy:"Create a one-week mini data record with at least five observations and write or say two things you notice.",aiLayer:"Integration: facilitator may enter the same dataset into a spreadsheet or AI tool to produce a summary; learners compare the tool's summary with their own observations.",enterprise:"Records help people understand what happened, reduce guesswork and make better plans.",quiz:[{question:"What does a tally chart show?",options:["how often something occurs","only names","only pictures","only money"],answer:0},{question:"Tables organize information using…",options:["rows and columns","only colors","secrets","random marks"],answer:0},{question:"Why keep records?",options:["To support better decisions","To make information disappear","To avoid learning","To replace observation"],answer:0}]}
 ],
 finalAssessment:{mcq:[{question:"What is the purpose of counting?",options:["To know how many","To know color only","To hide items","To change value"],answer:0},{question:"Which means two quantities are the same?",options:["Equal","More","Less","Estimate"],answer:0},{question:"What should usually happen before and after an estimate?",options:["Estimate, then measure and compare","Guess and stop","Measure without recording","Ignore the result"],answer:0},{question:"Which operation combines quantities?",options:["Addition","Subtraction only","Comparison","Estimation"],answer:0},{question:"A litre is commonly used to measure…",options:["volume","age","color","distance between cities only"],answer:0},{question:"Why are records useful?",options:["They help us see what happened and plan","They remove evidence","They make numbers meaningless","They prevent comparison"],answer:0},{question:"If an AI tool gives a different arithmetic answer from yours, what should you do?",options:["Check the reasoning with objects or another method","Assume AI is always correct","Delete your work","Share private information"],answer:0},{question:"Which skill is useful in planning a garden bed?",options:["Measurement","Ignoring space","Random guessing only","Avoiding numbers"],answer:0}],theory:["Explain two ways numbers are used in everyday life.","Describe the difference between more, less and equal using your own example.","Explain why an estimate can be useful before measuring.","Create one addition or subtraction problem using a food, water or garden example and solve it.","Explain why a person should understand a calculation instead of relying completely on a calculator or AI tool."],practical:"Complete a mini numeracy investigation: estimate and measure three safe objects or quantities, record the results in a table, solve one addition and one subtraction problem using the collected data, and explain one pattern or comparison you notice."},
 evidence:["Counting tray or grouping record","Comparison cards","Five-object estimate-and-measure record","Quantity measurement table","Learner-created arithmetic story problems","One-week mini data record","Facilitator numeracy observation checklist"],
 passport:["K: understands counting, comparison, measurement, addition, subtraction and simple data records","P: measures, records and solves practical quantity problems","D: checks digital/AI-supported numerical outputs against independent reasoning","S: uses measuring tools and containers safely","E: explains how counting, measurement and records reduce waste and support planning","L: communicates reasoning, works collaboratively and corrects errors constructively"],
 trainerNotes:["Use concrete objects before symbolic notation for learners who need it.","Accept oral explanations and demonstrations as evidence alongside written work.","Use culturally familiar examples and locally available measuring tools.","Where standard units are not yet mastered, begin with consistent informal units and transition gradually.","Avoid speed-based competition that embarrasses learners; emphasize reasoning and progress."],
 remediation:"Return to concrete objects, one-to-one matching, number lines and repeated measurement using one unit at a time. Reduce the number range while keeping the same functional task.",
 extension:"Learner designs a simple resource-use challenge, such as counting daily cups of water used for a small set of plants, then proposes one evidence-based improvement.",
 imagePrompts:["Photorealistic African children ages 8–11 counting seeds, measuring water in transparent cups and using a tape measure in a supervised learning garden, inclusive boys and girls, natural daylight, no readable text, LIFEWS green and golden-yellow accents.","Clean educational illustration for children showing counting objects, comparison, ruler measurement, water volume, simple addition and a tally chart as six visual icons, white background, no words.","Photorealistic small group of African learners recording plant counts in a simple table on paper beside a school garden, facilitator nearby, collaborative, age-appropriate, no readable text." ]
};

export const pf03ByLanguage: Partial<Record<AppLanguage,PF03Module>> = { en };
export function getPF03(language:AppLanguage):PF03Module { return pf03ByLanguage[language] ?? en; }
