import type { PF01Module } from "./pf-01";

type PF02Module = Omit<PF01Module,"code"> & { code:"PF-02" };

export const pf02Ha: PF02Module = {
  code:"PF-02",
  title:"Karanta Duniyar da ke Kewaye da Ni",
  level:"Pathways Foundation",
  age:"Kimanin shekaru 8–11; a sanya ɗalibi a matakin karatu ne bisa gwajin farko, ba shekaru kaɗai ba.",
  duration:"Darussa 6 masu jagoranci tare da atisayen karatu, aikin hannu da tantancewa",
  fieldworkHours:2,
  bigQuestion:"Ta yaya kalmomi, hotuna, alamomi da tambura za su taimaka mini in fahimci duniya da ke kewaye da ni kuma in yi aiki cikin aminci?",
  whyItMatters:"Ilimin karatu na asali yana fi amfani idan ɗalibai sun danganta rubutu da rayuwar yau da kullum. Wannan rukunin yana haɓaka lura, harshe na baka, ƙamus, warware kalmomi da karatun amfani ta cikin misalan abinci, ruwa, makamashi, lambu da al’umma, tare da girmama bambancin matakin farawa na ɗalibai.",
  outcomes:[
    "Gane cewa rubutu, hotuna, alamomi da tambura suna isar da ma’ana.",
    "Karanta da amfani da muhimman kalmomin yau da kullum da suka shafi muhalli da tsarin abinci.",
    "Daidaita kalmomin da aka ji da hotuna da kalmomin da aka rubuta.",
    "Amfani da yanayin magana da lura mai kyau wajen gano ma’ana da tabbatar da ita.",
    "Ƙirƙirar wani kayan bayani mai amfani wanda ya haɗa hoto, kalma da saƙo.",
    "Amfani da taimakon dijital ko AI a ƙarƙashin jagoranci wajen kwatantawa, rarrabawa ko binciken kalmomi ba tare da raba bayanan sirri ba."
  ],
  vocabulary:["kalma","harafi","sauti","hoto","alama","tambari","lakabi","ma’ana","karanta","bincika","abinci","ruwa","shuka","makamashi","aminci"],
  materials:["katunan hotuna na gida","katunan kalmomi","katunan haruffa/sauti da suka dace da harshen koyarwa","marufi masu tsabta ko kwafin lakabi","kayan lambu ko na gida masu aminci","takarda da fensir/alkalami","na’ura ta zaɓi ƙarƙashin kulawar mai koyarwa"],
  safety:[
    "A yi amfani da abubuwa da marufi masu tsabta da aminci kawai.",
    "Kada a kunyata ɗalibi ko a gwada darajarsa saboda kuskuren karatu.",
    "A daidaita koyar da sauti da haruffa da harshen da aka zaɓa; kada a ɗauka cewa dokokin Turanci suna aiki iri ɗaya a Hausa, Larabci, Yarbanci, Igbo ko Faransanci.",
    "Kada a nemi ɗalibai su ɗauki ko aika hotunan mutanen da za a iya gane su, adireshi ko takardun sirri zuwa kayan AI."
  ],
  lessons:[
    {id:"PF-02-L1",title:"Hotuna, Alamomi da Ma’ana",objective:"Bayyana yadda hotuna, alamomi, tambura da kalmomi ke sadar da bayani.",teaching:["Ba littattafai kaɗai muke karantawa ba; muna karanta alamomi, tambura, hotuna, lakabi da yanayi.","Tambari na iya sadar da saƙo cikin sauri, amma ma’anarsa tana buƙatar fahimtar da mutane suka yi tarayya a kai.","Mai karatu nagari yana lura kafin ya yanke hukunci kan ma’ana."],activity:"Neman ma’ana: duba alamomi da katunan hotuna da aka saba da su, sannan ka bayyana abin da kowannensu yake son sadarwa.",diy:"Ƙirƙiri tambarin aminci ko kulawa guda ɗaya don lambun koyarwa ko aji, sannan ka bayyana shi da baki.",aiLayer:"Matakin AI 1 — Ganewa: bambanta tsakanin alamar da mutum ya ƙirƙira, sakamakon binciken dijital da shawarar AI; dukansu suna buƙatar fassarar ɗan Adam.",enterprise:"Alamomi da lakabi masu bayyana suna taimaka wa mutane fahimtar kayayyaki, wurare da ayyuka; sadarwa mai kyau tana ƙirƙirar ƙima.",quiz:[{question:"Me zai iya sadar da ma’ana?",options:["Kalmomi, hotuna da tambura","Dogayen littattafai kaɗai","Lambobi kaɗai","Babu wani abu"],answer:0},{question:"Kafin mu yanke hukunci kan ma’anar alama, ya kamata mu…",options:["lura sosai","yi watsi da ita","lalata ta","yi zato ba tare da dubawa ba"],answer:0},{question:"Ana amfani da lakabi don…",options:["gane ko bayyana wani abu","ɓoye duk bayani","sa karatu ya gagara","maye gurbin aminci"],answer:0}]},
    {id:"PF-02-L2",title:"Kalmomi a Abinci, Ruwa da Makamashi",objective:"Gane da karanta kalmomi masu amfani daga yanayin yau da kullum na abinci, ruwa da makamashi.",teaching:["Kalmomin da aka saba da su sun fi sauƙin koyo idan an haɗa su da abubuwa da ayyuka na gaske.","Kalmomi na iya kiran abubuwa, ayyuka ko siffofi.","Maimaita karatu yana haɓaka saurin karatu da ƙarfin gwiwa."],activity:"Zagaya tashoshin kalmomi na abinci, ruwa, shuke-shuke, kayan aiki da makamashi; daidaita kowane katin kalma da hoto ko abu mai aminci.",diy:"Ƙirƙiri katunan hoto-kalma guda goma sannan ka yi atisayen karanta su ga abokin karatu.",aiLayer:"Matakin AI 2 — Hulɗa mai jagoranci: mai koyarwa ya nemi AI ya ba da jumloli masu sauƙi da kalmomin da aka zaɓa; ɗalibai su bincika ko jumlolin suna da ma’ana kuma sun dace da wurinsu.",enterprise:"Mutane suna buƙatar kalmomi madaidaici don suna, bayyana da tsara kayayyaki da ayyuka masu amfani.",quiz:[{question:"Me ke taimaka maka koyon sabuwar kalma?",options:["Haɗa ta da hoto ko abu","Kada ka sake ganinta","Ɓoye ta","Tsallake duk sautinta"],answer:0},{question:"Maimaita karatu na iya inganta…",options:["ƙarfin gwiwa da iya karatu","ingancin ruwa kai tsaye","yanayi","girman baturi"],answer:0},{question:"Wanne kalma ce ta tsarin abinci?",options:["iri","kalmar sirri","tauraron ɗan adam kawai","shiru"],answer:0}]},
    {id:"PF-02-L3",title:"Haruffa, Sauti da Sassan Kalma",objective:"Amfani da alaƙar harafi da sauti ko tsarin rubutu da ya dace da harshe wajen karanta kalmomin da aka sani.",teaching:["Harsuna rubutattu suna wakiltar magana ta hanyoyi daban-daban.","Za mu iya neman haruffa, sautuka, gaɓoɓi ko sassan kalmomin da muka saba da su.","Idan kalma ta yi wuya, za mu iya rage sauri, raba ta zuwa sassa, sannan mu yi amfani da yanayin jumla."],activity:"Gina kalmomi da aka saba da su ta amfani da haruffa masu motsi, katunan gaɓoɓi ko wasu sassan rubutu da suka dace da harshen koyarwa.",diy:"Yi tsani na kalmomi biyar masu alaƙa sannan ka nuna sashin da ka gane a kowace kalma.",aiLayer:"Matakin AI 3 — Gane tsari: rarraba kalmomi bisa tsarin da ake gani ko ji, sannan a kwatanta da shawarar dijital da mai koyarwa ya samar.",enterprise:"Gane tsari yana taimaka wa ƙididdiga, lakabi, rubuta bayanai da duba inganci.",quiz:[{question:"Idan kalma ta yi wuya, wace dabara ce mai amfani?",options:["Raba ta zuwa sassa masu sauƙi","Daina nan take","Ƙirƙiri wata kalma","Rufe ta"],answer:0},{question:"Shin duk harsuna shida suna amfani da dokokin harafi-sauti iri ɗaya?",options:["A’a","Eh","Ranar Litinin kawai","A lambu kawai"],answer:0},{question:"Gane sassan kalma da ake maimaitawa wani nau’i ne na…",options:["gane tsari","ɓarna","ɓoyewa","sanya farashi"],answer:0}]},
    {id:"PF-02-L4",title:"Karanta Lakabi da Umurni",objective:"Fitar da bayani mai sauƙi da amfani daga lakabi, alama ko umurni da ya dace da shekaru.",teaching:["Karatu na amfani yana taimaka mana mu yi zaɓi mai aminci a rayuwar yau da kullum.","Take, hoto, lamba da muhimman kalmomi na taimakawa wajen gano bayani.","Ya kamata mu tambayi babban mutum da muka yarda da shi idan bayanin aminci bai bayyana ba."],activity:"Karanta lakaban da malami ya shirya na buhun iri, kwantena na ruwa ko kayan lambu, sannan a gano suna, amfanin abu da umurni ɗaya.",diy:"Ƙirƙiri lakabi mai sassa uku ga wani abu a aji ko lambu: SUNA → AMFANI → KULAWA/AMINCI.",aiLayer:"Matakin AI 4 — Tambaya mai iyaka: mai koyarwa ya nuna yadda ake neman bayani mai sauƙi kan lakabin da ba na sirri ba; ɗalibai su kwatanta da asali su gano abin da ya ɓace.",enterprise:"Lakabi madaidaici yana ƙarfafa amana, aminci da kasuwanci mai alhaki; lakabi na ƙarya ko ruɗani na iya cutar da mutane.",quiz:[{question:"Me ya sa muke karanta umurni?",options:["Don mu san yadda ake yin abu daidai kuma cikin aminci","Don mu sa su ɓace","Don kada mu fahimta","Don ado kawai"],answer:0},{question:"Idan bayanin aminci bai bayyana ba, ya kamata ka…",options:["tambayi babban mutum da ka yarda da shi","yi zato da kayan haɗari","yi watsi da shi","canza lakabin"],answer:0},{question:"Lakabi mai kyau ya kamata ya zama…",options:["bayyananne kuma daidai","mai ruɗarwa da gangan","wanda ba za a iya karantawa ba","sirri"],answer:0}]},
    {id:"PF-02-L5",title:"Bincika Ma’ana",objective:"Amfani da yanayi, hotuna da taimako mai tabbas don bincika ko fassara ta dace.",teaching:["Mai karatu nagari yana bincika ma’ana maimakon karɓar zato na farko.","Hotuna da kalmomin da ke kewaye da magana suna ba da alamun yanayi.","Kayan dijital da AI na iya yin kuskure, don haka bayanai masu muhimmanci dole ne a tabbatar da su."],activity:"Karanta gajerun jimloli masu hoto inda aka saka kalma guda da ba ta dace ba; gano kalmar kuma a gyara ta.",diy:"Ƙirƙiri katin ‘Karanta–Yi Tunani–Bincika’ mai matakai uku na hoto.",aiLayer:"Matakin AI 5 — Kimantawa: mai koyarwa ya nuna bayanin AI guda ɗaya daidai da ɗaya marar daidaito kan wani abu da aka sani; ɗalibai su yi amfani da abin da suke gani don zabar mafi kyau.",enterprise:"Binciken bayani yana rage kuskure a bayanai, lakabi, adadi da sadarwar abokan ciniki.",quiz:[{question:"Alamar yanayi tana taimaka mana…",options:["gano ma’ana","manta rubutu","raba kalmomin sirri","guje wa dubawa"],answer:0},{question:"Ya kamata a karɓi duk bayanin AI kai tsaye?",options:["A’a","Eh","Idan dogo ne kawai","Idan yana da launi kawai"],answer:0},{question:"Wane tsari ne mai amfani?",options:["Karanta–Yi Tunani–Bincika","Yi Zato–Ɓoye–Tafi","Kwafa–Manta–Raba","Tsallake–Tsallake–Tsallake"],answer:0}]},
    {id:"PF-02-L6",title:"Jagorar Hoto-Kalma Ta",objective:"Ƙirƙira da gabatar da jagorar hoto-kalma mai amfani da ƙamus da lakabi madaidaici.",teaching:["Marubuci yana zaɓar bayani bisa wanda zai karanta da dalilin rubutun.","Jagora mai amfani ya kamata ya kasance tsararre, mai sauƙin karantawa kuma daidai.","Ƙirƙirar bayani nauyi ne; muna bincikawa kafin rabawa."],activity:"Shirya ƙaramin jagora kan ɗaya daga cikin: lambun makaranta, ruwa mai tsafta, sinadaran abinci, amfani da makamashi cikin aminci ko koyon al’umma.",diy:"Ƙirƙiri Jagorar Hoto-Kalma mai shigarwa shida, kowanne yana da hoto, muhimmin kalma da gajeren bayani ko umurni, sannan ka karanta ko gabatar wa abokan karatu.",aiLayer:"Haɗawa: AI na iya ba da shawarar kalmomi ko jimloli a ƙarƙashin kulawar mai koyarwa; ɗalibi ya zaɓa, gyara kuma ya bayyana abin da ya ƙare da shi.",enterprise:"Kayan bayani mai kyau yana ƙirƙirar ƙima ta hanyar sadarwa da zane; inganci yana nufin amfani, daidaito da kulawa.",quiz:[{question:"Su waye masu sauraro?",options:["Mutanen da aka yi bayanin domin su","Marubuci kaɗai","Wani irin iri","Kalmar sirri"],answer:0},{question:"Kafin ka raba jagora, ya kamata ka…",options:["bincika daidaitonsa","ƙara bayanan sirri","cire duk lakabi","kwafa ba tare da karantawa ba"],answer:0},{question:"Kyakkyawan kayan bayani ya kamata ya zama…",options:["mai amfani kuma mai sauƙin fahimta","mai ruɗarwa","mai haɗari","wanda ba a iya karantawa"],answer:0}]}
  ],
  finalAssessment:{
    mcq:[{question:"Wanne misali ne na karatu na amfani?",options:["Karanta alamar aminci","Yi watsi da lakabi","Ɓoye kalma","Lalata umurni"],answer:0},{question:"Me ke taimaka wa mai karatu fahimtar sabuwar kalma?",options:["Yanayi da sassan kalma","Rufe shafi","Yi zato kawai","Tsallake duk alamomi"],answer:0},{question:"Me ya sa hotuna suke da amfani a farkon koyon karatu?",options:["Suna iya taimaka wa ma’ana","Suna sa kalmomi su daina zama dole har abada","Suna maye gurbin aminci","Suna tabbatar da kowace fassara"],answer:0},{question:"Wace siffa ce muhimmiyar ga lakabi?",options:["Daidaito","Yaudara","Ruɗani","Sirri"],answer:0},{question:"Me ya kamata a yi kafin a raba muhimmin bayanin da AI ya samar?",options:["A bincika shi","Babu komai","A ƙara bayanan sirri","A yi watsi da asalin rubutu"],answer:0},{question:"Wane tsari ne ke tallafa wa karatu mai hankali?",options:["Lura–Karanta–Yi Tunani–Bincika","Yi Zato–Raba–Manta","Ɓoye–Kwafa–Tafi","Yi Gaggawa–Yi Watsi–Aika"],answer:0},{question:"Me ya sa koyon karatu zai bambanta tsakanin Turanci, Larabci da Yarbanci?",options:["Tsarin rubutu da sautinsu ya bambanta","Duk harsuna iri ɗaya ne","Harshe ɗaya kaɗai yake da kalmomi","Ba za a iya koyar da su ba"],answer:0},{question:"Jagorar hoto-kalma tana ƙirƙirar ƙima idan tana…",options:["da amfani, bayyananniya kuma daidai","ƙarya","mai haɗari","wanda ba a iya karantawa"],answer:0}],
    theory:["Bayyana abubuwa uku a al’ummarka da za a iya ‘karantawa’ ban da littattafai.","Zaɓi kalmomi biyar da ka saba da su, sannan ka bayyana dabarar da kake amfani da ita wajen gane ko karanta su.","Bayyana yadda hotuna ko alamun yanayi ke taimaka maka fahimtar sabuwar kalma.","Bayyana dalilin da ya sa lakabi da umurni ya kamata su zama daidai kuma masu sauƙin fahimta.","Bayyana hanya ɗaya ta binciken bayanin dijital ko AI kafin amfani da shi."],
    practical:"Ƙirƙiri kuma gabatar da baki Jagorar Hoto-Kalma mai shigarwa shida kan jigo da aka saba da shi na abinci, ruwa, makamashi, lambu ko koyon al’umma. Kowane shigarwa ya ƙunshi hoto mai dacewa, muhimmin kalma daidai da gajeren bayani ko umurnin da ɗalibi ya samar. Mai koyarwa zai tantance ganewa, ma’ana, tsari, daidaito da sadarwa, ba kyawun rubutun hannu kaɗai ba."
  },
  evidence:["Katunan hoto-kalma guda goma","Tsani na tsarin kalmomi","Lakabi mai sassa uku","Katin Karanta–Yi Tunani–Bincika","Jagorar Hoto-Kalma mai shigarwa shida","Takardar lura ta mai koyarwa kan karatun baka da fahimta"],
  passport:["K: yana gane kalmomi, alamomi, tambura da rubutun amfani a matsayin hanyoyin ma’ana","P: yana ƙirƙira da amfani da lakabi da jagorar hoto-kalma","D: yana amfani da taimakon dijital/AI a ƙarƙashin jagoranci don rarraba ko binciken harshe tare da kare sirri","S: yana karanta bayanin aminci na asali ko neman taimako","E: yana bayyana yadda sadarwa da lakabi madaidaici ke ƙirƙirar ƙima da amana","L: yana karantawa ko gabatarwa ga abokan karatu, yana karɓar gyara kuma yana bincika aiki kafin rabawa"],
  trainerNotes:["A koyar da karatu cikin harshen da aka zaɓa; a daidaita koyar da sauti da haruffa da wannan harshe maimakon fassarar phonics na Turanci kai tsaye.","A yarda da amsoshin baka, zane, daidaitawa da zaɓen hoto a matsayin shaida yayin da karatu ke bunƙasa.","A yi amfani da abubuwan gida da hotunan da ɗalibai suka saba da su ba tare da ƙage ko nuna wariya ba.","Ga Larabci, a yi amfani da kayan RTL; ga Yarbanci da Igbo, a kiyaye alamomin sautuka da ake buƙata; ga Faransanci, a koyar da alaƙar sauti da rubutu da ta dace.","A tantance fahimta da ci gaba, ba lafazi ba."],
  remediation:"A rage yawan kalmomin aiki, a ƙara daidaita hoto da abu, a yi maimaita karatun baka da atisayen harafi/gaɓa ta hanyoyi da dama, amma a ci gaba da manufar karatu na amfani.",
  extension:"Ɗalibi ya yi binciken alamomi da lakabi a wurin koyarwa ƙarƙashin kulawa, sannan ya ba da shawarar sabon lakabi ko gyara don samun dama ko aminci.",
  imagePrompts:["Yanayin koyon karatu na asali a Afirka mai kama da hoto na gaske, yara maza da mata shekaru 8–11 suna daidaita katunan hotuna da kalmomi kan shuke-shuke, ruwa, abinci da kayan makamashi masu sauƙi, mai koyarwa mai taimako, wurin koyo mai tsafta, babu rubutu mai karantawa, lafazin kore da rawaya na LIFEWS.","Zanen koyarwa na yara wanda ke nuna buhun iri, kwandon ruwa, alamar shuka da alamar aminci tare da alamar gilashin ƙara girma, farin bango, tambura kawai, babu rubutu.","Ƙaramin rukuni na yara Afirka suna ƙirƙirar jagorar hoto-kalma da zanen amfanin gona da kayan ruwa, fensir da katuna a tebur, haɗin kai da shiga kowa, hasken rana, babu rubutu mai karantawa."]
};