import type { PF01Module } from "./pf-01";

type PF04Module = Omit<PF01Module,"code"> & { code:"PF-04" };

export const pf04Ha: PF04Module = {
  code:"PF-04",
  title:"Tsire-Tsiren da ke Kewaye da Mu",
  level:"Pathways Foundation",
  age:"Kimanin shekaru 8–11; a daidaita ayyukan hannu da yanayin gida da bukatun ɗalibai.",
  duration:"Darussa 6 masu jagoranci tare da lura, aikin lambu da tantancewa",
  fieldworkHours:3,
  bigQuestion:"Me tsire-tsire za su koya mana game da abinci, ruwa, kulawa, kayayyaki masu amfani da wuraren da muke rayuwa?",
  whyItMatters:"Tsire-tsire hanya ce mai sauƙi ta shiga kimiyya, tsarin abinci da lura ta aikace. Wannan rukunin yana taimaka wa ɗalibai su gane sassan shuka, su kwatanta tsire-tsire masu amfani, su fahimci bukatun girma na asali, sannan su haɗa tsire-tsire da abinci, sana’o’i, kula da muhalli da koyon GreenSkills na gaba.",
  outcomes:["Gane manyan sassan shuka da bayyana aikinsu cikin sauƙi.","Bambance tushen shuka, kara, ganye, fure, ’ya’ya da iri ta misalan gida.","Bayyana bukatun shuka kamar ruwa, haske, iska, gina jiki da sarari.","Lura da rubuta bambance-bambance masu sauƙi tsakanin tsire-tsire.","Haɗa tsire-tsire da abinci, kayan aiki, inuwa, kyau da hanyoyin samun abin rayuwa.","Kammala aikin lura da kula da shuka cikin aminci a ƙarƙashin kulawa tare da shaida."],
  vocabulary:["shuka","tushe","kara","ganye","fure","’ya’yan itace","iri","ƙasa","ruwa","hasken rana","gina jiki","lura","kwatanta","kulawa","girbi"],
  materials:["samfurin tsire-tsire na gida masu aminci ko tsire-tsire masu rai","gilashin ƙara girma idan akwai","takarda da fensir","katunan hoton sassan shuka","ƙananan kwantena ko gadon lambu","kwandon ban ruwa","lakabi","tablet/waya a ƙarƙashin kulawar mai koyarwa don kwatanta hotuna idan ya dace"],
  safety:["Kada a ɗanɗana shukar da ba a sani ba.","A guji nau’ikan guba, masu tayar da fata ko masu ƙaya a ayyukan yara.","A wanke hannu bayan taɓa ƙasa ko kayan shuka.","A yi amfani da kayan aikin yara masu aminci kaɗai tare da kulawa.","A daidaita matsayin aiki ga ɗalibai masu rashin lafiyan jiki ko ƙuntataccen motsi.","Kada a yanke hukuncin cewa shuka tana da aminci don ci ko magani bisa amsar AI kaɗai."],
  lessons:[
    {id:"PF-04-L1",title:"Sanin Wata Shuka",objective:"Gane shuka a matsayin halitta mai rai wadda ke da sassa da bukatu da za a iya lura da su.",teaching:["Tsire-tsire halittu ne masu rai da ke girma da sauyawa.","Tsire-tsire daban-daban na iya yin kama sosai ko bambanta, amma suna iya raba wasu siffofi.","Lura da hankali yana taimaka mana mu bayyana abin da muka gani kafin mu bayyana dalili."],activity:"Lura da tsire-tsire na gida biyu masu aminci sannan a rubuta ko zana kamanceceniya uku da bambance-bambance uku.",diy:"Ƙirƙiri katin lura da shuka da zane, wurin da take, kimar girma da siffofi biyu da ake gani.",aiLayer:"Matakin AI 1 — Ganewa: mai koyarwa ya nuna yadda bayanin hoto na AI zai iya gano siffofin da ake gani, sannan ɗalibai su kwatanta shi da abin da suka lura da kansu.",enterprise:"Mutane suna ƙirƙirar ƙima ta hanyar shuka, kula, jigilar da amfani da tsire-tsire cikin alhaki.",quiz:[{question:"Tsire-tsire su ne…",options:["halittu masu rai","injuna","duwatsu","lambobi"],answer:0},{question:"Mai lura nagari ya kamata…",options:["ya duba sosai","ya yi zato ba tare da dubawa ba","ya lalata shuka","ya yi watsi da bambanci"],answer:0},{question:"Tsire-tsire biyu na iya…",options:["raba wasu siffofi kuma su bambanta a wasu","kullum su zama iri ɗaya","kada su taɓa bukatar ruwa","ba su da sassa"],answer:0}]},
    {id:"PF-04-L2",title:"Tushen Shuka, Kara da Ganye",objective:"Gane tushe, kara da ganye da bayyana aikinsu na asali.",teaching:["Tushen shuka yana taimakawa ɗaure shuka a ƙasa da sha ruwa da gina jiki.","Kara yana ɗaukar ganye kuma yana motsa ruwa da sauran abubuwa cikin shuka.","Ganye yana kama haske kuma yana taimaka wa shuka ta samar da abinci."],activity:"Daidaita samfurin gaske ko hotuna da TUSHE, KARA da GANYE, sannan a bi hanyar da ruwa zai iya bi daga ƙasa zuwa sama.",diy:"Gina samfurin shuka mai sauƙi da lakabi ta takarda, sanduna ko kayan da aka sake amfani da su.",aiLayer:"Matakin AI 2 — Kwatantawa mai jagoranci: amfani da kayan hoton da mai koyarwa ke sarrafawa wajen kwatanta tushe, kara ko ganye na musamman, sannan a tabbatar da abin da aka gani da kayan koyarwa masu aminci.",enterprise:"Fahimtar sassan shuka yana taimaka wa masu noma su kula da amfanin gona daidai da rage lalacewa.",quiz:[{question:"Wane sashe yakan ɗaure shuka a ƙasa?",options:["tushe","fure","’ya’yan itace","lakabi"],answer:0},{question:"Ganye yafi taimakawa kama…",options:["haske","kuɗi","roba","hayaniya"],answer:0},{question:"Kara yana taimakawa wajen…",options:["tallafawa da jigilar abubuwa","goge tushe","dakatar da girma","maye gurbin ƙasa"],answer:0}]},
    {id:"PF-04-L3",title:"Fure, ’Ya’yan Itace da Iri",objective:"Bayyana alaƙar fure, ’ya’yan itace da iri da misalai masu sauƙi.",teaching:["Yawancin tsire-tsire masu fure suna samar da furanni a matsayin wani ɓangare na haifuwa.","’Ya’yan itace sau da yawa suna kare ko ɗaukar iri.","Iri na iya girma su zama sabbin tsire-tsire idan yanayi ya dace."],activity:"Rarraba samfurori ko hotunan tsire-tsire masu aminci zuwa fure, ’ya’yan itace da iri sannan a tattauna alaƙarsu.",diy:"Ƙirƙiri katin matakai uku: FURE → ’YA’YAN ITACE → IRI ta amfani da amfanin gona da aka sani.",aiLayer:"Matakin AI 3 — Tsarawa da rarrabawa: kwatanta tsarin rayuwar da ɗalibai suka gina da wani tsari da aka samar a ƙarƙashin kulawar mai koyarwa sannan a gano kuskure.",enterprise:"Iri, ’ya’yan itace da furanni na iya zama kayayyaki masu muhimmanci, amma inganci ya dogara da samarwa da kula cikin aminci.",quiz:[{question:"Iri na iya…",options:["girma su zama sabbin tsire-tsire","zama ƙarfe","maye gurbin ruwa","samar da wutar lantarki kai tsaye"],answer:0},{question:"’Ya’yan itace yakan ƙunshi…",options:["iri","kayan aiki","wayoyi","duwatsu kaɗai"],answer:0},{question:"Wane tsari ne sau da yawa daidai?",options:["fure → ’ya’yan itace → iri","iri → ƙarfe → ’ya’yan itace","ganye → baturi → tushe","ƙasa → waya → fure"],answer:0}]},
    {id:"PF-04-L4",title:"Abin da Tsire-Tsire Ke Bukata",objective:"Gane muhimman yanayin da tsire-tsire ke bukata don girma da kyau.",teaching:["Tsire-tsire suna bukatar ruwa, haske, iska, gina jiki da sarari mai dacewa.","Ƙarancin ko yawan wata albarkatu na iya haifar da matsala.","Tsire-tsire daban-daban na iya bukatar ruwa, haske da sarari a adadi daban-daban."],activity:"Kwatanta ’yan tsire-tsire biyu iri ɗaya da aka sa a yanayi biyu masu aminci daban, sannan a hango abin da zai iya faruwa.",diy:"Yi dabaran bukatun shuka mai nuna ruwa, haske, iska, gina jiki da sarari.",aiLayer:"Matakin AI 4 — Hasashe: mai koyarwa ya tambayi AI hasashe kan wani yanayin kula da shuka; ɗalibai su kwatanta hasashen da shaidar da suka gani.",enterprise:"Kyakkyawan sarrafa albarkatu na iya rage ɓarnar ruwa, kayan ƙasa da kayan dasa shuki.",quiz:[{question:"Wanne bukata ce ta asali ga shuka?",options:["ruwa","kayan wasa na roba","kalmar sirri","fenti"],answer:0},{question:"Shin ruwa mai yawa zai iya cutar da wasu tsire-tsire?",options:["Eh","A’a, ba taɓa ba","Da dare kawai","A yanar gizo kawai"],answer:0},{question:"Tsire-tsire daban-daban na iya bukata…",options:["adadin albarkatu daban-daban","kulawa iri ɗaya koyaushe","babu haske","babu sarari"],answer:0}]},
    {id:"PF-04-L5",title:"Tsire-Tsire Masu Amfani a Kewayen Mu",objective:"Rarraba tsire-tsire da aka saba da su bisa rawarsu a abinci, inuwa, kayan aiki, ado ko hanyar samun abin rayuwa.",teaching:["Shuka guda na iya yin amfani fiye da ɗaya.","Mutane sun dogara da tsire-tsire don abinci da kayayyaki da yawa.","Amfani da tsire-tsire cikin alhaki yana nufin kula da ƙasa, ruwa da wadatar gaba."],activity:"Ƙirƙiri jadawalin amfanin tsire-tsire a al’umma da rukuni kamar abinci, inuwa, zare/kayan aiki, ado da samun kuɗi/hanyar rayuwa.",diy:"Yi hira da babban mutum da ka yarda da shi game da wata shuka mai amfani a gida, ka rubuta wane sashe ake amfani da shi da yadda ake kula da shi.",aiLayer:"Matakin AI 5 — Tabbatarwa: mai koyarwa ya nuna cewa AI na iya ba da shawarar amfanin shuka, amma tantancewar gida da batun aminci dole ne a duba su da mutane ko tushe masu tabbas.",enterprise:"Bincika yadda ilimin shuka ke tallafawa aikin nursery, noma, sarrafa abinci, gyaran fili da sauran sana’o’in kore ba tare da ɗora aikin kasuwanci ga yara ba.",quiz:[{question:"Shuka guda na iya samun amfani da yawa?",options:["Eh","A’a","Tsire-tsiren waje kaɗai","Bishiyoyi kaɗai"],answer:0},{question:"Bayanin amfanin shuka ya kamata…",options:["a tabbatar da daidaitonsa","a ƙirƙira shi","a bar shi marar aminci","a dogara da AI kawai"],answer:0},{question:"Amfani da shuka cikin alhaki ya haɗa da…",options:["kula da albarkatu","ɓarna","lalata","girbi marar aminci"],answer:0}]},
    {id:"PF-04-L6",title:"Kula da Shuka Mai Rai",objective:"Aiwatar da lura da kulawa ta asali ga shuka a ƙarƙashin kulawa sannan a rubuta shaidar canji.",teaching:["Kulawar shuka zagaye ne: lura → yanke shawara → yi aiki → bincika.","Rikodi yana taimaka mana mu ga canji a tsawon lokaci.","Kyakkyawan kulawa yana guje wa ɓarna kuma yana amsa ainihin bukatar shuka."],activity:"A biyu-biyu, duba shuka ko ƙaramin gado, gano bukatar kulawa guda ɗaya sannan a yi aiki a ƙarƙashin kulawa kamar ban ruwa, mulching ko cire tarkace masu aminci.",diy:"Ajiye rikodin kulawar shuka sau uku da kwanan wata, lura, aiki da sakamako.",aiLayer:"Haɗawa: kwatanta shawarar kulawar ku da shawarar AI da mai koyarwa ya samar, sannan ku kare zaɓin ƙarshe da shaidar da aka gani da shawarar gida.",enterprise:"Kulawa mai aminci, rubuta bayanai da lura da inganci su ne ɗabi’un aiki na asali a noma da sana’o’in kore.",quiz:[{question:"Wane zagayen kulawa ne mai amfani?",options:["lura → yanke shawara → yi aiki → bincika","yi aiki → yi watsi → manta","yi zato → ɓata → tafi","kwafa → ɓoye → tsaya"],answer:0},{question:"Me ya sa ake ajiye rikodin kulawar shuka?",options:["don bin canji","don ɓoye shaida","don guje wa lura","don maye gurbin shuka"],answer:0},{question:"Kyakkyawar shawarar kulawa ta kamata ta dogara da…",options:["lura da shawara mai tabbas","zato kawai","kalmomin sirri","umarnin haɗari"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Wane sashe na shuka yakan sha ruwa daga ƙasa?",options:["Tushe","Fure","’Ya’yan itace","Iri kaɗai"],answer:0},{question:"Wane sashe yakan kama haske?",options:["Ganye","Tushe","’Ya’yan itace kaɗai","Lakabi"],answer:0},{question:"Me iri zai iya zama idan yanayi ya dace?",options:["Sabuwar shuka","Ƙarfe","Roba","Baturi"],answer:0},{question:"Wanne bukata ce ta asali ga shuka?",options:["Ruwa","Kalmar sirri","Fenti","Mai kaɗai"],answer:0},{question:"Me ya sa muke kwatanta tsire-tsire?",options:["Don lura da kamanceceniya da bambanci","Don lalata su","Don guje wa koyo","Don sa su zama iri ɗaya"],answer:0},{question:"AI kaɗai zai iya tabbatar da cewa shukar da ba a sani ba tana da aminci a ci?",options:["A’a","Eh koyaushe","Idan hoton ya yi haske kaɗai","Idan yaro ya tambaya kaɗai"],answer:0},{question:"Wanne kyakkyawar shaida ce ta kulawar shuka?",options:["Rikodin lura mai kwanan wata","Jita-jita","Zato ba tare da lura ba","Aikin wani da ba shi da alaƙa"],answer:0},{question:"Ilimin shuka na iya tallafa wa hanyoyin rayuwa ta…",options:["noma, nursery, sarrafawa da kulawa","ɓarna kawai","mu’amala marar aminci","ɓoye bayanai"],answer:0}],theory:["Faɗi manyan sassan wata shuka da ka sani kuma bayyana aiki guda na kowanne.","Bayyana abubuwa biyar da shuka ke bukata don girma da kyau.","Bayyana wata shuka mai amfani a gida da hanyoyi biyu da mutane ke amfani da ita.","Bayyana dalilin da ya sa rikodin kulawar shuka zai iya taimaka wa mai noma yanke shawara mafi kyau.","Bayyana dalilin da ya sa bayanin AI game da shukar da ba a sani ba ya kamata a tabbatar kafin a ci ko a yi amfani da ita."],practical:"Lura da shuka mai rai mai aminci, gano aƙalla sassa ko siffofi huɗu, tantance bukatar kulawa guda ɗaya, yi aikin kulawa guda ɗaya a ƙarƙashin kulawa, sannan ka gabatar da gajeren rikodin shaida mai nuna lura, aiki da sakamakon da ake tsammani."},
  evidence:["Katin lura da shuka","Samfurin sassan shuka","Katin fure-’ya’yan itace-iri","Dabaran bukatun shuka","Jadawalin amfanin shuka na al’umma ko rikodin hira","Rikodin kulawar shuka sau uku","Rikodin lura na aikin hannu na mai koyarwa"],
  passport:["K: yana gane sassan shuka, bukatu da amfani na yau da kullum","P: yana yin lura da shuka da aikin kulawa a ƙarƙashin kulawa","D: yana kwatanta shawarar dijital/AI da shaida kai tsaye da tushe masu tabbas","S: yana bin dokokin aminci na shuka, ƙasa da kayan aiki","E: yana haɗa ilimin shuka da kayayyaki, ayyuka da kula da albarkatu","L: yana aiki tare, rubuta lura da sadar da shawarar kulawa"],
  trainerNotes:["Yi amfani da tsire-tsire da ɗalibai suke gani a yankinsu idan suna da aminci.","Kada a gabatar da da’awar magani a matsayin tabbatacciyar gaskiya a wannan matakin tushe.","Bayar da zaɓin baka, hoto da abin taɓawa ga masu farawa a karatu.","Juya matsayin lura, ban ruwa, aunawa da gabatarwa cikin adalci.","Idan babu lambu, yi amfani da tsire-tsire a tukwane ko hotuna masu inganci tare da aƙalla lura da shuka mai rai a ƙarƙashin kulawa idan zai yiwu."],
  remediation:"Rage yawan sassan shuka da ake gabatarwa lokaci guda, yi maimaita daidaita abubuwa da samfurin taɓawa, sannan a yi atisayen lura–suna–aiki.",
  extension:"Ɗalibi ya ƙirƙiri bayanin shafi guda na wani muhimmin amfanin gona na gida mai nuna sassan shuka, bukatar girma guda, amfani guda da aikin kulawa guda.",
  imagePrompts:["Yara Afirka shekaru 8–11 suna lura da tsire-tsiren lambu masu aminci tare da mai koyarwa, suna nuna tushe, kara da ganye, lambun makaranta-al’umma mai haɗa kowa, hasken rana, babu rubutu mai karantawa, lafazin kore da zinariya na LIFEWS.","Zanen koyarwa na tsirrai ga yara yana nuna shukar abinci mai fure da tushe, kara, ganye, fure, ’ya’yan itace da iri a bayyane, farin bango, babu lakabi ko rubutu.","Ƙaramin rukuni na ɗaliban Afirka suna ban ruwa da mulching a lambun kwantena a ƙarƙashin kulawa yayin rubuta lura a takarda, kayan aiki masu aminci, haɗin kai, babu rubutu mai karantawa."]
};