import type { PF01Module } from "./pf-01";

type PF08Module = Omit<PF01Module,"code"> & { code:"PF-08" };

export const pf08Ha: PF08Module = {
 code:"PF-08", title:"Tsabtatattun Hannaye, Abinci Mai Aminci", level:"Pathways Foundation", age:"Kimanin shekara 8–11; a daidaita ayyukan gwaji da shirye-shiryen ɗalibi da dokokin tsaron abinci na yankin.", duration:"Darussa 6 masu jagora tare da atisayen tsafta da tantancewa", fieldworkHours:3,
 bigQuestion:"Ta yaya tsaftatattun hannaye, kayan aiki masu tsafta da kulawa wajen sarrafa abinci za su kare mutane da abinci?",
 whyItMatters:"Tsaron abinci yana farawa da halaye na yau da kullum. Wannan sashe yana koyar da gurɓatawa, wanke hannu, tsaftar wuraren aiki, ware abinci, ajiyewa da sadarwa mai alhaki ba tare da sa yara cikin hadarin sinadarai masu haɗari, ɗanyen abinci mai babban haɗari ko aikin kasuwanci ba.",
 outcomes:["Bayyana yadda ƙwayoyin cuta, datti, ruwa mara aminci da rashin kulawa za su iya gurɓata abinci.","Nuna cikakken tsarin wanke hannu a lokutan da suka dace.","Bambance kyawawan da munanan hanyoyin kula da kayan da suke taɓa abinci.","Bayyana dalilin ware wasu ɗanyen abinci daga abincin da aka shirya ci.","Fahimtar cewa adana abinci lafiya ya danganta da nau'in abinci, lokaci, zafin jiki da sahihan umarni.","Amfani da jerin dubawa don duba tsaftar aikin koyo mai kulawa.","Duba shawarwarin AI ko na dijital da sahihan bayanai kafin a karɓe su."],
 vocabulary:["tsaron abinci","tsafta","gurɓatawa","ƙwayar cuta","tsabta","datti","wanke hannu","kurkure","sabulu","fili","kayan aiki","warewa","ajiya","zafin jiki","shara","jerin dubawa","shaida"],
 materials:["wurin wanke hannu da ruwa mai aminci","sabulu","hanyar busarwa mai tsafta","katunan matakai","kayan gwaji da kwantena masu tsafta","katunan yanayin tsaron abinci","littafin ɗalibi","jerin dubawar tsafta","na'urar dijital da mai koyarwa ke sarrafawa idan akwai"],
 safety:["A yi amfani kawai da kayan gwaji da mai koyarwa ya amince da su; ba a buƙatar ɗanɗanawa.","Yara kada su riƙe ɗanyen nama, ɗanyen ƙwai, sinadarai masu haɗari ko kayan girki masu zafi.","A share ruwan da ya zube nan da nan.","Kada a yanke hukuncin amincin abinci da kallo, wari ko ɗanɗano kawai.","A mutunta rashin lafiyan abinci, bukatun addini da bukatun nakasa.","A tabbatar da shawarar tsaron abinci ta AI da dokokin yankin da umarnin mai koyarwa."],
 lessons:[
  {id:"PF-08-L1",title:"Yadda Abinci Zai Iya Zama Mara Aminci",objective:"Gane yadda gurɓatawa ke iya motsawa daga hannu, ruwa, fili ko wani abinci zuwa abincin da za a ci.",teaching:["Gurɓatawa na nufin wani abu mara kyau ko mai cutarwa ya shiga abinci.","Hannu, ruwa mara tsafta, kayan aiki marasa tsafta, kwari da hulɗar abinci da abinci na iya ɗaukar gurɓatawa.","Wasu ƙwayoyin cuta ba a iya gani, jin wari ko ɗanɗanonsu."],activity:"Bi hanyoyin gurɓatawa ta katunan hoto sannan a nuna inda za a katse kowace hanya.",diy:"Ƙirƙiri zane: TUSHEN GURƁATAWA → TAƁAWA → ABINCI → HANA.",aiLayer:"AI 1 — Ganewa: a tantance misalan da AI ya bayar a matsayin masu yiwuwa, marasa tabbas ko kuskure.",enterprise:"Masu noma, masu sarrafawa da masu sayar da abinci suna kare ƙima ta hanyar hana gurɓatawa tun farko.",quiz:[{question:"Menene gurɓatawa?",options:["Shigar wani abu mara kyau ko mai cutarwa cikin abinci","Canza launin abinci","Ƙirga fakiti","Shuka iri"],answer:0},{question:"Ana iya ganin duk ƙwayoyin cuta masu haɗari?",options:["A'a","Eh kullum","A ruwa kawai","A ƙarfe kawai"],answer:0},{question:"Me zai iya ɗaukar gurɓatawa?",options:["Hannu marasa tsafta","Rufaffen littafi","Fensir mai tsafta","Kabadi mara abinci"],answer:0}]},
  {id:"PF-08-L2",title:"Wanke Hannu Daidai",objective:"Nuna lokacin da yadda za a wanke hannu sosai kafin ayyukan abinci.",teaching:["A wanke hannu kafin taɓa abinci da bayan ayyukan da ke gurɓata hannu.","Wanke hannu mai kyau yana amfani da ruwa mai aminci, sabulu, gogewa sosai, kurkurewa da busarwa mai tsafta.","Zuba ruwa kawai ba ya maye gurbin wanke hannu da sabulu."],activity:"Mai koyarwa ya nuna matakan, sannan ɗalibai su yi atisaye bibbiyu da katin matakai.",diy:"Yi katin matakai shida sannan a nuna su ba tare da taimako ba.",aiLayer:"AI 2 — Duba jerin matakai: kwatanta matakan ɗalibi da na AI sannan a gano abin da ya ɓace.",enterprise:"Tsarin tsafta mai inganci muhimmin bangare ne na sarrafa inganci a ayyukan abinci.",quiz:[{question:"Me ake bukata wajen wanke hannu?",options:["Ruwa mai aminci da sabulu","Yashi kawai","Mai","Fenti"],answer:0},{question:"Yaushe ya dace a wanke hannu?",options:["Kafin sarrafa abinci da bayan aikin da zai gurɓata hannu","Sau ɗaya a mako","Bayan cin abinci kawai","Ba a taɓa bukata"],answer:0},{question:"Me ya sa ake busar da hannu ta hanya mai tsafta?",options:["Don kada a sake gurɓata hannu","Don ƙara zaƙi","Don auna ruwa","Don maye gurbin sabulu"],answer:0}]},
  {id:"PF-08-L3",title:"Kayan Aiki da Fili Masu Tsafta",objective:"Bambance kayan da suke taɓa abinci masu tsafta daga hanyoyin da za su iya sake gurɓacewa.",teaching:["Fili da kayan aiki da ke taɓa abinci su kasance masu tsafta kafin amfani.","Zane ko kayan aiki mai datti na iya yada gurɓatawa.","A bi hanyoyin tsafta da manya suka amince da su da umarnin samfur."],activity:"Duba teburin gwaji a gano halaye masu kyau da marasa kyau.",diy:"Ƙirƙiri jerin TSAFTA / NA BUKATAR GYARA mai abubuwa takwas.",aiLayer:"AI 3 — Duba mai jagora: kwatanta jerin ajin da jerin AI, a bar abubuwan da suka dace da shekarun ɗalibai da yanayin yankin kawai.",enterprise:"Tsabtacewa da dubawa akai-akai na rage asara da matsalar inganci.",quiz:[{question:"Me ya kamata a yi wa wurin da abinci zai taɓa kafin amfani?",options:["A tsaftace shi yadda ya dace","A rufe shi da ƙasa","Kada a duba shi","A yi amfani da shi ga komai ba tare da tsaftacewa ba"],answer:0},{question:"Zane mai datti na iya yada gurɓatawa?",options:["Eh","A'a","A waje kawai","Da dare kawai"],answer:0},{question:"Menene amfanin jerin dubawa?",options:["Duba ko ana bin abin da ake bukata","Tabbatar da riba","Maye gurbin wanke hannu","Ɓoye matsala"],answer:0}]},
  {id:"PF-08-L4",title:"Ware Nau'ikan Abinci",objective:"Bayyana dalilin ware wasu abinci da kayan aiki don rage gurɓatawa ta giciye.",teaching:["Gurɓatawa ta giciye na faruwa idan gurɓatawa ta motsa daga wani abu ko fili zuwa wani.","Ɗanyen abincin dabba na iya ɗaukar haɗari zuwa abincin da aka shirya ci.","A wannan mataki yara suna amfani da hotuna da kayan gwaji masu tsafta; manya ne kawai ke sarrafa ɗanyen abinci mai babban haɗari."],activity:"Raba katuna zuwa ƊANYE / SHIRYE A CI / KAYAN AIKI MASU TSAFTA.",diy:"Zana taswirar yadda wurin shirya abinci zai ware kayan haɗari daga abincin da aka shirya ci.",aiLayer:"AI 4 — Nazarin yanayi: duba yanayin kicin da AI ya bayar, gano hanyar taɓawa mara aminci.",enterprise:"Tsarin aiki mai kyau yana rage yiwuwar gurɓatawa.",quiz:[{question:"Menene gurɓatawa ta giciye?",options:["Motsawar gurɓatawa daga abu ɗaya zuwa wani","Dafa abinci daidai","Ƙirga kayan haɗi","Shuka amfanin gona biyu"],answer:0},{question:"Me ya sa ake ware ɗanyen abincin dabba daga abincin da aka shirya ci?",options:["Don rage wucewar haɗari","Don canza launi","Don rage takarda","Don guje wa tsafta"],answer:0},{question:"Ya kamata yara su riƙe ɗanyen nama a wannan sashe?",options:["A'a","Eh ba tare da kulawa ba","Idan AI ya ce","Da hannu babu safar hannu"],answer:0}]},
  {id:"PF-08-L5",title:"Ajiye Abinci da Kulawa",objective:"Fahimtar cewa ajiya mai aminci ya danganta da nau'in abinci, lokaci, zafin jiki da sahihan umarni.",teaching:["Abinci daban-daban suna da bukatun ajiya daban.","Abincin da ke saurin lalacewa na iya bukatar sarrafa zafin jiki.","Alamar samfur, dokokin yankin da manya masu alhaki su jagoranci yadda ake ajiya."],activity:"Raba misalai zuwa TAMBAYI BABBAN MUTUM / BUSASSHEN AJIYA MAI KARIYA / AJIYA DA SARRAFA ZAFIN JIKI.",diy:"Yi katin: GANE ABINCI → DUBA ALAMA/UMARNI → KWANTENA MAI TSAFTA → WURI DA YA DACE → SAKE DUBA.",aiLayer:"AI 5 — Tabbatarwa: kwatanta shawarar AI da alamar samfur ko sahihin umarni.",enterprise:"Ajiya mai kyau yana kare samfur, rage sharar abinci da kiyaye inganci.",quiz:[{question:"Duk abinci suna da irin ajiya ɗaya?",options:["A'a","Eh","Fakiti kawai ke bambanta","'Ya'yan itace kawai"],answer:0},{question:"Me za a duba idan ba ka da tabbas?",options:["Sahihin umarni ko alamar samfur","Hasashe","Kallo kawai","Jita-jita"],answer:0},{question:"Me ya sa ake amfani da kwantena masu tsafta?",options:["Don kare abinci daga gurɓatawa","Don maye gurbin sanyi","Don tabbatar da abinci ba zai lalace ba har abada","Don guje wa alama"],answer:0}]},
  {id:"PF-08-L6",title:"Gudanar da Dubawar Tsaron Abinci",objective:"Amfani da ilimin tsafta wajen duba wurin koyo mai kulawa da bayar da gyara bisa shaida.",teaching:["Tsaron abinci tsari ne: hannaye masu tsafta, ruwa mai aminci, kayan aiki masu tsafta, warewa, ajiya mai kyau da kulawa.","Jerin dubawa yana sa dokoki su zama abubuwan da za a iya gani.","Idan an gano matsala a tsaya, a gyara lafiya sannan a rubuta abin da aka yi."],activity:"Ƙungiyoyi su duba wurin gwaji, su rubuta aƙalla abubuwa biyar sannan su gano gyare-gyare biyu.",diy:"Kammala Binciken Tsaron Abinci: DUBA → GANO → GYARA → TABABTAR → RUBUTA.",aiLayer:"Haɗewa — Bincike bisa shaida: kwatanta rahoton ƙungiya da na AI, a ƙi shawarar da ta saba da shaida ko dokokin yankin.",enterprise:"Tabbatar da inganci na nufin hana matsala, rubuta dubawa da gyara kuskure kafin samfur ko sabis ya isa mai amfani.",quiz:[{question:"Me ya kamata a yi idan an gano yanayi mara aminci?",options:["A tsaya a gyara lafiya","A ɓoye shi","A ci gaba","A goge rahoto"],answer:0},{question:"Me ya sa ake tabbatar da gyara?",options:["Don tabbatar matsalar ta warware","Don ƙara tsawon takarda","Don guje wa alhaki","Don tabbatar da nan gaba"],answer:0},{question:"Wanne bangare ne na tsarin tsaron abinci?",options:["Hannaye masu tsafta, kayan aiki masu tsafta, warewa da ajiya","Ɗanɗana abincin da ba a sani ba","Watsi da alama","Zane ɗaya mai datti ga komai"],answer:0}]}
 ],
 finalAssessment:{mcq:[{question:"Me zai iya gurɓata abinci?",options:["Hannu marasa tsafta","Rubutu a littafi","Ƙirga fakiti","Zana shuka"],answer:0},{question:"Me yake da muhimmanci wajen wanke hannu?",options:["Ruwa mai aminci da sabulu","Yashi","Ruwan 'ya'ya","Mai"],answer:0},{question:"Shin abin da yake kama da tsafta yana nufin aminci koyaushe?",options:["A'a","Eh","Idan sanyi ne kawai","Idan a cikin ɗaki ne"],answer:0},{question:"Me ya sa ake ware ɗanyen abinci daga abincin da aka shirya ci?",options:["Don rage gurɓatawa ta giciye","Don canza launi","Don ajiye takarda","Don guje wa tsafta"],answer:0},{question:"Me ya kamata ya jagoranci ajiya idan ba ka da tabbas?",options:["Sahihin umarni da alama","Hasashe","Wari kawai","Amsar AI ba tare da duba ba"],answer:0},{question:"Menene amfanin jerin dubawar tsafta?",options:["Mayar da ayyuka su zama abin gani da auna","Maye gurbin sabulu","Tabbatar da riba","Guje wa kulawa"],answer:0},{question:"Yaya ya kamata a yi amfani da shawarar AI ta tsaron abinci?",options:["A matsayin shawara da za a tabbatar","A matsayin hukunci na ƙarshe","A madadin alama","A madadin manya"],answer:0},{question:"Wanne aiki ne mai alhaki?",options:["Gano matsala, gyara, sannan tabbatar","Ɓoye matsala","Ci gaba duk da haɗari","Canza rahoto"],answer:0}],theory:["Bayyana hanyoyi uku da gurɓatawa zai iya shiga abinci da hanyar hana kowanne.","Bayyana cikakken tsarin wanke hannu da lokuta uku masu muhimmanci.","Bayyana gurɓatawa ta giciye da misali guda.","Bayyana dalilin amfani da alama da sahihin umarni wajen ajiya.","Faɗi hanyar da AI zai taimaka wajen koyon tsaron abinci da dalilin tabbatar da amsarsa."],practical:"Nuna cikakken wanke hannu, sannan yi amfani da jerin dubawa don duba wurin gwaji na abinci. Gano ayyuka masu kyau guda uku, matsaloli biyu, gyaransu da hanyar tabbatar da gyaran."},
 evidence:["Hoton hanyar gurɓatawa","Katin matakai shida na wanke hannu","Nuna wanke hannu","Jerin Tsabta/Na Bukatar Gyara","Taswirar warewa","Katin yanke shawarar ajiya","Binciken Tsaron Abinci","Rahoton tantancewar mai koyarwa"],
 passport:["K: yana bayyana gurɓatawa, tsaftar hannu, warewa da ajiya","P: yana nuna wanke hannu da yin binciken tsafta","D: yana amfani da jerin dubawa da tabbatar da shawarwarin AI","S: yana bin iyakokin tsaron abinci da suka dace da shekaru","E: yana haɗa tsafta, tsarin aiki da inganci da sana'a mai alhaki","L: yana sadar da matsalar tsaro, aiki tare da tabbatar da gyara"],
 trainerNotes:["A nuna kowane aiki kafin ɗalibai su yi shi.","A yi amfani da misalan abinci na yankin ba tare da raina wata al'ada ko al'umma ba.","Kada yara su riƙe sinadarai masu haɗari, tafasasshen ruwa, kayan kaifi marasa dacewa ko ɗanyen abinci mai babban haɗari.","A bi dokokin lafiyar jama'a na yankin idan sun fi takamaiman bayani.","A tantance abin da ɗalibi ya nuna a aikace, ba haddace kalmomi kawai ba.","A mayar da bangaren kasuwanci ga inganci, sabis da alhaki; ba a wajabta wa ƙananan yara sayarwa."],
 remediation:"A koma ga abubuwa uku: hannaye masu tsafta, fili mai tsafta da ware haɗarin taɓawa. A yi amfani da hotuna, kwaikwayo da maimaita jerin dubawa.",
 extension:"Ɗalibi ya zana tsarin aiki mai aminci don shirya 'ya'yan itace a makaranta, ya gano wuraren yiwuwar gurɓatawa da yadda za a tabbatar da kowane matakin kariya.",
 imagePrompts:[]
};