import type { PF01Module } from "./pf-01";

type PF05Module = Omit<PF01Module,"code"> & { code:"PF-05" };

export const pf05Ig: PF05Module = {
  code:"PF-05",
  title:"Mkpụrụ na Mmalite Ito",
  level:"Pathways Foundation",
  age:"Ihe dịka afọ 8–11; itinye nwa akwụkwọ n’ọkwa na ọrụ aka kwesịrị ịdabere na ịdị njikere ya.",
  duration:"Ihe ọmụmụ nduzi isii tinyere nyocha germination nke ụbọchị 7–10 na nyocha ikpeazụ",
  fieldworkHours:3,
  bigQuestion:"Gịnị dị n’ime mkpụrụ, gịnị na-enyere ya aka ịmalite ito, kedu ka anyị ga-esi nwalee echiche anyị site n’ihe akaebe?",
  whyItMatters:"Mkpụrụ na-ejikọta nri, ugbo, biodiversity na ụzọ ndụ n’ọdịnihu. Site n’ịchọpụta germination, ụmụ akwụkwọ na-amụta nlele, fair test, nha, ide ndekọ, ilekọta akụrụngwa, iji AI n’ụzọ nwere ọrụ na echiche enterprise mbụ, ma na-emepụta ihe akaebe sitere n’usoro ndụ n’ezie.",
  outcomes:["Mata mkpụrụ dịka akụkụ osisi dị ndụ nke nwere ike ịmepụta osisi ọhụrụ ma ọnọdụ dị mma.","Mata àgwà mkpụrụ a na-ahụkarị ma kewaa mkpụrụ na ihe na-abụghị mkpụrụ.","Kọwaa na germination chọrọ mmiri zuru oke, ikuku na okpomọkụ kwesịrị ekwesị, ebe seedling mgbe e mesịrị chọrọ ìhè na nri.","Hazie germination comparison dị mfe na nke ziri ezi ebe otu ọnọdụ naanị gbanwere.","Lelee, gụọ, tụọ ma deba ihe akaebe germination n’oge.","Jiri aro dijitalụ ma ọ bụ AI n’ụzọ nlezianya ma nyochaa ya site na nnwale na nduzi a tụkwasịrị obi.","Jikọta ogo mkpụrụ, nlekọta ya na ide ndekọ na mmepụta nri na nursery nwere ọrụ."],
  vocabulary:["mkpụrụ","germination","akpụkpọ mkpụrụ","embryo","mmiri","ikuku","okpomọkụ","seedling","mgbọrọgwụ","shoot","variable","lelee","tụọ","deba","tụnyere","ihe akaebe"],
  materials:["mkpụrụ obodo dị nchebe dịka beans, maize ma ọ bụ cowpea","iko doro anya ma ọ bụ akpa dị ala","cotton dị ọcha, paper towel ma ọ bụ growing medium kwesịrị ekwesị","mmiri dị ọcha","aha-akara","pensụl na akwụkwọ ndekọ","rula","grid ịgụ ma ọ bụ tebụl data dị mfe","ngwa dijitalụ nhọrọ n’okpuru onye nduzi"],
  safety:["Jiri naanị mkpụrụ ama ama, na-adịghị nsi, nke onye nduzi nyere ma ọ bụ kwadoro.","A naghị eri mkpụrụ ejiri mee nnwale mgbe e mesịrị, mgbe emetụrụ ha ma ọ bụ ha germinate.","Saa aka tupu na mgbe ọrụ aka gasịrị ma debe ebe ọrụ ọcha.","Hichaa mmiri wụsara ozugbo ka mmadụ ghara ịda.","Ekwela ka ụmụ akwụkwọ metụ seed-treatment chemicals ma ọ bụ pesticides.","Ndụmọdụ AI gbasara chemicals, seed treatment ma ọ bụ nchekwa nri agaghị dochie nduzi onye nkuzi ma ọ bụ ntuziaka ngwaahịa."],
  lessons:[
    {id:"PF-05-L1",title:"Mkpụrụ Pụrụ Ịghọ Osisi",objective:"Mata mkpụrụ ma kọwaa ọrụ ya n’ịmalite osisi ọhụrụ.",teaching:["Mkpụrụ nwere obere osisi na ihe oriri echekwara nke akpụkpọ mkpụrụ na-echebe.","Mkpụrụ dị iche n’ogo, agba, ọdịdị na texture.","Ọ bụghị obere ihe niile bụ mkpụrụ; njirimara kwesịrị ịdabere na nlele na ozi a tụkwasịrị obi."],activity:"Kewaa mkpụrụ dị nchebe na ihe na-abụghị mkpụrụ, wee kọwaa mkpụrụ ọ bụla site n’ogo, agba, ọdịdị na elu ya.",diy:"Mepụta kaadị nlele mkpụrụ isii nwere eserese ma ọ bụ sample, aha ma ọ bụrụ na amaara ya, na àgwà abụọ a na-ahụ anya nke ọ bụla.",aiLayer:"AI Ogo 1 — Ịmata na ajụjụ: tụnyere nkọwa ụmụ akwụkwọ na nkọwa AI n’okpuru onye nduzi, chọpụta ihe a pụrụ ikwenye site n’nlele ozugbo.",enterprise:"Ndị na-emepụta mkpụrụ na nurseries na-emepụta uru site n’inye planting material a matara nke ọma, dị ndụ ma nwee ozi ziri ezi.",quiz:[{question:"Gịnị ka mkpụrụ kwesịrị ekwesị nwere ike ịmepụta?",options:["Osisi ọhụrụ","Ngwa ígwè","Batrị","Karama plastik"],answer:0},{question:"Kedu àgwà ị nwere ike ịhụ ozugbo?",options:["Agba mkpụrụ","Ọnụ ahịa n’ọdịnihu","Paswọọdụ a na-adịghị ahụ anya","Yield e kwere nkwa"],answer:0},{question:"Gịnị mere e ji amata mkpụrụ nke ọma?",options:["Mkpụrụ dị iche na-emepụta osisi dị iche","Mkpụrụ niile bụ otu","Aha-akara adịghị mkpa","Ịtụ n’amaghị ama na-eme ogo ka mma"],answer:0}]},
    {id:"PF-05-L2",title:"Ihe Dị n’Ime Mkpụrụ",objective:"Mata akpụkpọ mkpụrụ, ihe oriri echekwara na embryo site na nlele mkpụrụ a tinyere n’ime mmiri n’ụzọ dị nchebe.",teaching:["Akpụkpọ mkpụrụ na-echebe ime mkpụrụ.","Ọtụtụ mkpụrụ nwere ihe oriri echekwara nke na-akwado uto mbụ.","Embryo bụ obere osisi na-amalite ito n’oge germination."],activity:"Onye nduzi kwadebe beans ma ọ bụ cowpea a tinyere n’ime mmiri. Ụmụ akwụkwọ mepee otu mkpụrụ nwayọọ wee tụnyere ime ya na diagram, n’enweghị iri ya.",diy:"Mee nnukwu model mkpụrụ site na akwụkwọ ma ọ bụ recycled materials nke na-egosi akpụkpọ nchebe, ihe oriri na obere osisi.",aiLayer:"AI Ogo 2 — Nkọwa na ntụnyere: jụọ maka nkọwa dị mfe gbasara akụkụ mkpụrụ, wee nyochaa okwu ọ bụla site n’mkpụrụ n’ezie na diagram a tụkwasịrị obi.",enterprise:"Ịghọta akụkụ mkpụrụ na-akọwa ihe mere handling siri ike, storage na-adịghị mma na pests ji belata ogo planting material.",quiz:[{question:"Gịnị na-echebe mpụta ọtụtụ mkpụrụ?",options:["Akpụkpọ mkpụrụ","Petal ifuru","Waya","Igbe batrị"],answer:0},{question:"Gịnị bụ embryo?",options:["Obere osisi na-etolite","Ngwa ubi","Ụdị ala","Aha ngwugwu"],answer:0},{question:"Gịnị mere mkpụrụ ji nwee ihe oriri echekwara?",options:["Ikwado uto mbụ","Ime ọkụ eletrik","Dochie ikuku","Ịghọ plastik"],answer:0}]},
    {id:"PF-05-L3",title:"Ihe Germination Chọrọ",objective:"Kọwaa ọnọdụ bụ isi germination chọrọ ma kewaa ha na mkpa seedling mgbe e mesịrị.",teaching:["Ọtụtụ mkpụrụ chọrọ mmiri kwesịrị ekwesị, oxygen na okpomọkụ kwesịrị ekwesị iji germinate.","Mmiri pere mpe nwere ike igbochi germination; mmiri karịrị akarị nwere ike belata ikuku ma kwalite nsogbu.","Mkpa ìhè dị iche site na mkpụrụ ruo mkpụrụ, ma mgbe seedlings pụtara ha chọrọ ìhè na nri kwesịrị ekwesị."],activity:"Jiri picture scenarios buru amụma ma mkpụrụ ga-germinate mgbe ọ kpọrọ nkụ, mmiri dị mma, idei mmiri, oke ọkụ ma ọ bụ ọnọdụ ọzọ na-adịghị mma, wee kọwaa amụma ọ bụla.",diy:"Mepụta wheel mkpa germination nke na-ekewa ỌNỌDỤ GERMINATION na MKPA SEEDLING MGBE E MESỊRỊ.",aiLayer:"AI Ogo 3 — Amụma: tụnyere amụma AI banyere ọnọdụ abụọ na nke ụmụ akwụkwọ ma kaa okwu ndị nnwale ga-enyocha n’ezie.",enterprise:"Germination ọma na-ebelata mkpụrụ, mmiri, oghere na ọrụ efu n’ugbe na nursery.",quiz:[{question:"Kedu ngwakọta dị mkpa maka germination?",options:["Mmiri kwesịrị ekwesị, ikuku na okpomọkụ","Agba, plastik na mkpọtụ","Ego, aha-akara na batrị","Ìhè siri ike naanị"],answer:0},{question:"Mmiri karịrị akarị nwere ike ibute nsogbu?",options:["Ee","Mba","Naanị mkpụrụ plastik","Naanị n’ịntanetị"],answer:0},{question:"Gịnị ka amụma kwesịrị ịtụnyere?",options:["Ihe akaebe a hụrụ","Asịrị","Ịtụ n’amaghị ama","Paswọọdụ"],answer:0}]},
    {id:"PF-05-L4",title:"Hazie Fair Germination Test",objective:"Hazie ntụnyere dị mfe ebe otu ọnọdụ na-agbanwe ma ndị ọzọ dị mkpa na-anọ otu ka o kwere mee.",teaching:["Fair comparison na-agbanwe otu main condition ma na-eme ka ndị ọzọ dị otu ka o kwere mee.","Akpa ọ bụla chọrọ aha-akara doro anya ka observations ghara ịgwakọta.","Starting record kwesịrị inwe ụbọchị, ụdị mkpụrụ, ọnụ ọgụgụ mkpụrụ na treatment."],activity:"Dịka klas, hazie treatments abụọ dị nchebe dịka moist na dry. Kwuo ihe ga-agbanwe, ihe ga-adị otu na ihe a ga-agụ.",diy:"Hazie akpa germination abụọ nwere aha-akara, otu ụdị mkpụrụ, otu starting number na otu condition gbanwere.",aiLayer:"AI Ogo 4 — Nyocha usoro: onye nduzi jụọ AI ka o nyochaa test; ụmụ akwụkwọ jụ aro ndị na-agbanwe variables ọtụtụ ma ọ bụ tinye ihe ize ndụ.",enterprise:"Trials a pụrụ ịtụkwasị obi na-enyere growers ime mkpebi tupu ha eji ọtụtụ mkpụrụ, mmiri ma ọ bụ labour.",quiz:[{question:"Na fair comparison, ole main conditions kwesịrị ịgbanwe?",options:["Otu","Ha niile","Ọ dịghị nke ọ bụla ma na-akpọ ya comparison","Dị ka o kwere mee"],answer:0},{question:"Gịnị mere e ji etinye aha-akara?",options:["Ka treatments na records doo anya","Ka mkpụrụ germinate ozugbo","Iji dochie observation","Iji zoo results"],answer:0},{question:"Kedu starting record bara uru?",options:["Ụbọchị na ọnụ ọgụgụ mkpụrụ","Paswọọdụ nzuzo","Eserese na-enweghị njikọ","Enweghị ozi"],answer:0}]},
    {id:"PF-05-L5",title:"Gụọ, Tụọ ma Tụnyere",objective:"Kpọkọta data germination ma jiri ya tụnyere treatments n’enweghị ịgbanwe observation ka ọ dabara na prediction.",teaching:["Gụọ mkpụrụ germinated site n’otu rule ahụ n’ụbọchị nlele ọ bụla.","Tụọ ihe dị mfe dịka root ma ọ bụ shoot length naanị ma ọ bụrụ na ọ gaghị emebi investigation.","Ihe akaebe nwere ike ikwesịghị prediction; ezigbo investigator na-ede ihe mere n’ezie."],activity:"Lelee treatments abụọ, gụọ germinated seeds, deba otu measurement ma ọ bụ descriptive observation ma tụnyere results.",diy:"Debe germination log nwere entries atọ ma ọ dịkarịa ala: ụbọchị, treatment, number germinated, observation na measurement optional.",aiLayer:"AI Ogo 5 — Data interpretation: tinye fictional ma ọ bụ facilitator-prepared data table n’AI, tụnyere interpretation ya na nke ụmụ akwụkwọ ma nyochaa arithmetic na claims.",enterprise:"Seedling na nursery businesses na-adabere na counts ziri ezi, quality checks na records, ọ bụghị exaggerated claims.",quiz:[{question:"Gịnị ka ị ga-ede ma results adabaghị na prediction?",options:["Ihe mere n’ezie","Result gbanwere","Ọ dịghị ihe","Result onye ọzọ"],answer:0},{question:"Gịnị mere e ji gụọ mkpụrụ site n’otu rule?",options:["Ka comparison bụrụ consistent","Iji guarantee success","Iji zoo failures","Iji zere evidence"],answer:0},{question:"Data record bara uru nwere…",options:["ụbọchị, treatment na observation","title naanị","private passwords","guaranteed profit"],answer:0}]},
    {id:"PF-05-L6",title:"Site n’Ihe Akaebe Ruo n’Uto Ka Mma",objective:"Jiri germination evidence kọwaa result, mata limitations ma tụọ aro next step nwere ọrụ.",teaching:["Conclusion kwesịrị ịza investigation question site n’recorded evidence.","Otu small experiment anaghị egosi na mkpụrụ niile ma ọ bụ ebe niile ga-eme otu ihe.","Improvement nwere ike ịbụ repetition, ọtụtụ mkpụrụ, labels ka mma ma ọ bụ testing another safe condition."],activity:"Teams gosipụta treatments, evidence na conclusion. Peers jụọ otu evidence question ma tụọ otu improvement.",diy:"Mezue Seed Germination Investigation Poster: AJỤJỤ → AMỤMA → METHOD → DATA → CONCLUSION → IMPROVEMENT.",aiLayer:"Integration — verification and reflection: tụnyere team conclusion na AI-generated conclusion, debe naanị claims data n’ezie na-akwado.",enterprise:"Jikọta germination competence na responsible nursery, crop establishment na seed-quality work; ụmụaka na-amụta echiche ahụ n’enweghị ịre ngwaahịa.",quiz:[{question:"Strong conclusion kwesịrị iji…",options:["Recorded evidence","Guess naanị","Sales promise","Story na-enweghị njikọ"],answer:0},{question:"Otu small test na-egosi na mkpụrụ niile n’ebe niile ga-eme otu ihe?",options:["Mba","Ee mgbe niile","Ọ bụrụ na AI kwuru ya","Ọ bụrụ na mkpụrụ niile germinate"],answer:0},{question:"Kedu improvement nwere ezi uche?",options:["Repeat test with careful records","Delete unexpected data","Change many conditions without recording","Claim guaranteed result"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Gịnị bụ germination?",options:["Mmalite uto site na mkpụrụ","Owuwe ihe ubi mature crop","Packaging food","Charging battery"],answer:0},{question:"Kedu condition a na-achọkarị maka germination?",options:["Suitable moisture","Paint","Plastic","Sales receipt"],answer:0},{question:"Gịnị mere germinating seed ji chọọ air?",options:["Living cells chọrọ oxygen maka respiration","Air na-eme mkpụrụ bụrụ metal","Air na-edochi embryo","Ọ dịghị mkpa"],answer:0},{question:"Gịnị na-eme simple germination comparison ka ọ bụrụ fair?",options:["Changing one main condition","Changing everything","Using different seed types and conditions together","Removing labels"],answer:0},{question:"Gịnị bụ good evidence?",options:["Dated observations and counts from the test","Rumor","Prediction rewritten as result","Unrelated photograph"],answer:0},{question:"Ọ bụrụ na AI nyere conclusion dị iche na data gị, gịnị ka ị ga-eme?",options:["Check data and reasoning before accepting AI","Delete data","Always trust AI","Invent numbers"],answer:0},{question:"Gịnị mere good germination ji dị mkpa nye growers?",options:["Ọ nwere ike belata wasted seed na resources","Ọ na-guarantee profit","Ọ na-ewepụ all farming risk","Ọ na-edochi crop care"],answer:0},{question:"Kedu statement nwere ọrụ?",options:["Our small test supports this conclusion under tested conditions","Our test proves every seed everywhere behaves identically","AI guarantees the result","Records are unnecessary"],answer:0}],theory:["Kọwaa conditions atọ a na-achọkarị maka germination na ihe mere unsuitable conditions ji belata success.","Kọwaa ọrụ seed coat na embryo n’ụzọ dị mfe.","Kọwaa otú ị ga-eme two-treatment germination comparison ka ọ bụrụ fair.","Kọwaa otú counts na observations si nyere gị ikpebi treatment rụrụ ọrụ ka mma.","Nye otu ụzọ AI nwere ike inyere germination investigation aka ma kọwaa otú ị ga-esi verify output ya."],practical:"Hazie ma ọ bụ gosi two-treatment seed-germination investigation site n’otu seed type na equal starting seed numbers. Kọwaa changed condition, gosi correct labelling na safe handling, gosipụta dated observations atọ ma ọ dịkarịa ala, tụnyere evidence ma kwuo justified conclusion na improvement otu."},
  evidence:["Kaadị nlele mkpụrụ isii","Seed-parts model","Germination-needs wheel","Fair-test planning sheet","Two labelled germination treatments","Three-entry germination log","Seed Germination Investigation Poster","Facilitator practical assessment record"],
  passport:["K: na-akọwa seed structure na basic germination conditions","P: na-ahazi ma na-elekọta safe simple germination comparison","D: na-agụ, tụọ, deba ma verify AI-supported interpretations against evidence","S: na-agbaso hygiene, spill-control na safe seed-handling rules","E: na-ejikọta germination quality na resource efficiency na responsible nursery na crop production","L: na-eme predictions, collaborates, presents evidence na proposes improvements"],
  trainerNotes:["Họrọ fast-germinating, familiar, untreated seeds ma ọ bụrụ na o kwere mee.","Bido practical n’oge ka e nwee observations ruo ọtụtụ ụbọchị; exact germination time dị iche site na seed na conditions.","Ekwela ka success bụrụ na seeds niile germinate; unexpected results bụ useful evidence.","Jiri oral, pictorial, tactile na peer-supported recording maka emerging readers.","Zere hazardous chemical seed treatments na child activities.","Debe enterprise discussion na quality, value na stewardship, ọ bụghị child selling ma ọ bụ income promises."],
  remediation:"Jiri otu familiar large seed, picture sequencing na otu moist-versus-dry comparison. Mụọ sequence seed → root emerges → shoot develops, wee wulite data table ọnụ site na symbols ma ọ bụ tally marks.",
  extension:"Nwa akwụkwọ repeat investigation na second safe seed type ma ọ bụ another controlled condition, calculate simple germination percentage na facilitator support, wee compare whether original conclusion still applies.",
  imagePrompts:["Ụmụaka Africa afọ 8–11 n’ebe GreenSkills a na-elekọta na-ahazi bean ma ọ bụ cowpea germination cups, clean materials, labels enweghị readable text, notebooks maka observations, inclusive participation, natural daylight, LIFEWS forest green na gold accents.","Child-friendly scientific illustration na-egosi bean seed site na intact seed ruo emerging root, young shoot na first leaves, clean white background, accurate sequence, no labels or readable text.","Photorealistic African learner na-atụnyere safe germination treatments abụọ ma na-edekọ counts na ruler na notebook ebe facilitator na-elekọta, evidence-focused school garden setting, no readable text."]
};