import type { PF01Module } from "./pf-01";

type PF03Module = Omit<PF01Module,"code"> & { code:"PF-03" };

export const pf03Fr: PF03Module = {
  code:"PF-03",
  title:"Les nombres dans la vie quotidienne",
  level:"Fondation Pathways",
  age:"Environ 8 à 11 ans ; le placement en numératie doit suivre une évaluation de départ.",
  duration:"6 leçons guidées plus activité pratique et évaluation",
  fieldworkHours:2,
  bigQuestion:"Comment les nombres nous aident-ils à compter, comparer, mesurer, planifier et prendre de meilleures décisions au quotidien ?",
  whyItMatters:"La numératie fonctionnelle aide les apprenants à participer avec confiance à la vie quotidienne, aux apprentissages pratiques et aux futures formations professionnelles. Ce module développe le comptage, la comparaison, l’estimation, la mesure, l’enregistrement de données et la résolution simple de problèmes à partir de contextes familiers liés à l’alimentation, à l’eau, au jardin, au foyer et à la communauté.",
  outcomes:["Compter et représenter des quantités à l’aide d’objets, de marques et de chiffres.","Comparer des quantités avec les notions de plus, moins, égal, supérieur et inférieur.","Mesurer la longueur, le volume et la masse avec des outils adaptés ou des unités informelles.","Utiliser des additions et soustractions simples dans des situations pratiques.","Enregistrer des observations dans un tableau ou un relevé de bâtons.","Utiliser un soutien numérique ou d’IA guidé pour vérifier des motifs ou des calculs tout en expliquant son propre raisonnement."],
  vocabulary:["nombre","compter","quantité","plus","moins","égal","mesurer","longueur","volume","masse","estimer","additionner","soustraire","tableau","bâton de comptage"],
  materials:["objets à compter comme des graines ou capsules","cartes de nombres","ficelle/règles/mètres rubans","tasses ou récipients gradués","balance simple si disponible","papier et crayons","modèle de tableau de comptage","calculatrice ou tablette facultative sous contrôle du facilitateur"],
  safety:["Utiliser des objets propres et non coupants pour compter.","Ne pas utiliser de charges lourdes ni de récipients dangereux pour les activités de mesure.","Mettre les apprenants en binômes afin que ceux qui débutent en numératie puissent participer sans gêne.","Ne pas laisser les apprenants dépendre d’une calculatrice ou de l’IA avant d’avoir montré le raisonnement de base.","Garder toutes les activités de mesure pratiques adaptées à l’âge et supervisées."],
  lessons:[
    {id:"PF-03-L1",title:"Compter ce que nous voyons",objective:"Compter, regrouper et représenter avec exactitude des objets familiers.",teaching:["Compter nous indique combien d’éléments se trouvent dans un groupe.","Regrouper les objets peut faciliter le comptage de grandes quantités.","Une quantité peut être représentée par des objets, des bâtons, des mots ou des chiffres."],activity:"Compter et regrouper des graines, capsules ou cartes en groupes de 2, 5 et 10 ; comparer différentes façons de représenter le même total.",diy:"Créer un plateau de comptage avec cinq sections et placer une quantité différente dans chaque section.",aiLayer:"Couche IA 1 — Reconnaissance : comparer le comptage de l’apprenant avec un comptage numérique saisi par le facilitateur et discuter de la façon dont un outil peut vérifier sans remplacer l’attention humaine.",enterprise:"Un comptage exact est utile pour organiser des matériaux, vérifier des stocks et partager les ressources équitablement.",quiz:[{question:"Que nous dit le comptage ?",options:["Combien d’éléments il y a","Leur couleur","À qui ils appartiennent","Leur âge"],answer:0},{question:"Le regroupement peut nous aider à…",options:["compter de plus grandes quantités","cacher des objets","éviter les nombres","changer le total"],answer:0},{question:"Qu’est-ce qui peut représenter une quantité ?",options:["Des bâtons de comptage","Seulement des mots","Seulement des images","Rien"],answer:0}]},
    {id:"PF-03-L2",title:"Plus, moins et égal",objective:"Comparer deux ou plusieurs quantités et utiliser le vocabulaire approprié.",teaching:["Nous comparons des quantités pour savoir laquelle est plus grande, plus petite ou identique.","Égal signifie que deux quantités ont la même valeur.","La comparaison aide à prendre des décisions justes et efficaces."],activity:"Comparer des bols d’objets, les niveaux d’eau dans des récipients transparents et des longueurs de ficelle ; expliquer oralement chaque comparaison.",diy:"Créer six cartes de comparaison avec des dessins et les mots PLUS, MOINS ou ÉGAL.",aiLayer:"Couche IA 2 — Interaction guidée : le facilitateur demande à un outil numérique ou d’IA de proposer des exemples simples de comparaison ; les apprenants répondent d’abord puis vérifient la réponse de l’outil.",enterprise:"Comparer les quantités aide à éviter le gaspillage et à déterminer la quantité de matériau nécessaire.",quiz:[{question:"Égal signifie…",options:["la même quantité","toujours plus","toujours moins","inconnu"],answer:0},{question:"Si le panier A contient 8 fruits et B en contient 5, A en a…",options:["plus","moins","autant","zéro"],answer:0},{question:"La comparaison est utile pour…",options:["prendre des décisions","éviter toute mesure","cacher des registres","modifier les faits"],answer:0}]},
    {id:"PF-03-L3",title:"Mesurer la longueur et la distance",objective:"Mesurer et comparer des longueurs avec des unités informelles et standards lorsque disponibles.",teaching:["La mesure attribue un nombre à une propriété comme la longueur.","La même unité doit être utilisée lorsque l’on compare des mesures.","Une estimation est une supposition raisonnable faite avant de mesurer."],activity:"Estimer puis mesurer la longueur d’une table, d’une planche de culture, d’une corde ou d’un objet de classe avec des empans, des pas puis une règle ou un mètre ruban si disponible.",diy:"Créer une fiche de mesure pour cinq objets avec estimation, mesure réelle et différence.",aiLayer:"Couche IA 3 — Reconnaissance de motifs : comparer les erreurs d’estimation et déterminer si les estimations ont tendance à être trop élevées, trop faibles ou proches de la réalité.",enterprise:"Mesurer avec précision est important pour construire, planter, couper des matériaux et organiser l’espace.",quiz:[{question:"Pourquoi utiliser la même unité pour comparer ?",options:["Pour rendre les mesures comparables","Pour changer le résultat","Pour compliquer le comptage","Cela n’a aucune importance"],answer:0},{question:"Une estimation est…",options:["une supposition raisonnable avant de mesurer","toujours exacte","un nombre secret","un prix"],answer:0},{question:"Quel outil peut mesurer une longueur ?",options:["Une règle ou un mètre ruban","Une tasse seulement","Une cuillère seulement","Le titre d’un livre"],answer:0}]},
    {id:"PF-03-L4",title:"Mesurer l’eau et d’autres quantités",objective:"Mesurer en sécurité des volumes et des masses simples avec des outils ou des unités appropriés.",teaching:["Le volume indique l’espace occupé par un liquide.","La masse indique à quel point un objet est lourd par rapport à une unité.","Une mesure soigneuse réduit le gaspillage et améliore la régularité."],activity:"Mesurer des volumes égaux d’eau dans des récipients et comparer la masse d’objets sûrs de classe ou de jardin avec une balance simple.",diy:"Préparer un tableau de mesure de quatre éléments avec l’objet, la quantité, l’unité et le résultat.",aiLayer:"Couche IA 4 — Questionnement encadré : demander des exemples de situations où une mesure précise est importante ; classer les exemples en alimentation, eau, construction, agriculture ou usage domestique.",enterprise:"Des quantités constantes sont importantes dans la préparation des aliments, l’emballage, l’irrigation et l’utilisation responsable des ressources.",quiz:[{question:"Le volume indique…",options:["l’espace occupé par un liquide","le niveau sonore","l’âge d’un objet","sa couleur"],answer:0},{question:"Pourquoi mesurer avec soin ?",options:["Pour réduire les erreurs et le gaspillage","Pour rendre les registres inutiles","Pour cacher les différences","Pour éviter la responsabilité"],answer:0},{question:"Laquelle est une unité de mesure ?",options:["litre","jardin","enseignant","image"],answer:0}]},
    {id:"PF-03-L5",title:"Additionner et soustraire dans la vie réelle",objective:"Utiliser des additions et soustractions simples pour résoudre des problèmes pratiques familiers.",teaching:["L’addition rassemble des quantités.","La soustraction permet de trouver ce qui reste ou la différence entre deux quantités.","Des dessins, des objets et une droite numérique peuvent aider à résoudre un problème."],activity:"Résoudre des problèmes pratiques sur des graines plantées, des tasses d’eau utilisées, des fruits partagés ou des outils comptés, d’abord avec des objets puis avec des chiffres.",diy:"Créer deux problèmes d’addition et deux de soustraction à partir de situations familières de la communauté ou du jardin, puis les résoudre.",aiLayer:"Couche IA 5 — Évaluation : le facilitateur montre une solution numérique correcte et une incorrecte ; les apprenants expliquent laquelle est juste et pourquoi.",enterprise:"L’arithmétique simple soutient le comptage des stocks, la planification des matériaux et la vérification de la monnaie, sans demander aux enfants de réaliser des transactions commerciales.",quiz:[{question:"L’addition sert à…",options:["combiner des quantités","cacher des quantités","effacer tous les nombres","mesurer seulement la température"],answer:0},{question:"La soustraction peut nous dire…",options:["ce qui reste","seulement les couleurs","seulement les noms","rien d’utile"],answer:0},{question:"Une bonne façon de vérifier un calcul est…",options:["utiliser des objets ou une autre méthode","accepter n’importe quelle réponse","ignorer le problème","copier sans réfléchir"],answer:0}]},
    {id:"PF-03-L6",title:"Enregistrer des nombres et repérer des motifs",objective:"Enregistrer des données simples et identifier des motifs ou changements de base.",teaching:["Un tableau de bâtons indique combien de fois quelque chose se produit.","Les tableaux organisent l’information en lignes et colonnes.","Les motifs nous aident à repérer répétitions, changements et relations possibles."],activity:"Collecter un petit ensemble de données de classe ou de jardin, comme le nombre de plantes, les tasses d’eau quotidiennes ou les activités préférées, puis créer un tableau ou un relevé de bâtons.",diy:"Créer un mini-enregistrement sur une semaine avec au moins cinq observations et écrire ou dire deux choses remarquées.",aiLayer:"Intégration : le facilitateur peut saisir le même ensemble de données dans un tableur ou un outil d’IA pour produire un résumé ; les apprenants le comparent à leurs propres observations.",enterprise:"Les registres aident à comprendre ce qui s’est passé, à réduire les suppositions et à mieux planifier.",quiz:[{question:"Que montre un relevé de bâtons ?",options:["combien de fois quelque chose se produit","seulement des noms","seulement des images","seulement de l’argent"],answer:0},{question:"Les tableaux organisent les informations avec…",options:["des lignes et des colonnes","seulement des couleurs","des secrets","des marques aléatoires"],answer:0},{question:"Pourquoi tenir des registres ?",options:["Pour prendre de meilleures décisions","Pour faire disparaître l’information","Pour éviter d’apprendre","Pour remplacer l’observation"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Quel est le but du comptage ?",options:["Savoir combien il y en a","Connaître seulement la couleur","Cacher des éléments","Changer leur valeur"],answer:0},{question:"Quel mot signifie que deux quantités sont identiques ?",options:["Égal","Plus","Moins","Estimation"],answer:0},{question:"Que faut-il généralement faire avec une estimation ?",options:["Estimer, puis mesurer et comparer","Deviner puis arrêter","Mesurer sans enregistrer","Ignorer le résultat"],answer:0},{question:"Quelle opération combine des quantités ?",options:["Addition","Soustraction seulement","Comparaison","Estimation"],answer:0},{question:"Un litre mesure généralement…",options:["un volume","un âge","une couleur","seulement une distance entre villes"],answer:0},{question:"Pourquoi les registres sont-ils utiles ?",options:["Ils aident à comprendre ce qui s’est passé et à planifier","Ils suppriment les preuves","Ils rendent les nombres inutiles","Ils empêchent la comparaison"],answer:0},{question:"Si un outil d’IA donne un résultat différent du vôtre, que faut-il faire ?",options:["Vérifier le raisonnement avec des objets ou une autre méthode","Supposer que l’IA a toujours raison","Effacer son travail","Partager des informations privées"],answer:0},{question:"Quelle compétence est utile pour planifier une planche de jardin ?",options:["La mesure","Ignorer l’espace","Deviner au hasard","Éviter les nombres"],answer:0}],theory:["Expliquez deux façons dont les nombres sont utilisés dans la vie quotidienne.","Décrivez la différence entre plus, moins et égal à l’aide de votre propre exemple.","Expliquez pourquoi une estimation peut être utile avant de mesurer.","Créez un problème d’addition ou de soustraction à partir d’un exemple d’alimentation, d’eau ou de jardin et résolvez-le.","Expliquez pourquoi une personne doit comprendre un calcul au lieu de dépendre entièrement d’une calculatrice ou de l’IA."],practical:"Réaliser une mini-enquête de numératie : estimer puis mesurer trois objets ou quantités sûrs, enregistrer les résultats dans un tableau, résoudre un problème d’addition et un de soustraction avec les données recueillies, puis expliquer un motif ou une comparaison observée."},
  evidence:["Plateau de comptage ou fiche de regroupement","Cartes de comparaison","Fiche estimation-mesure de cinq objets","Tableau de mesure de quantités","Problèmes arithmétiques créés par l’apprenant","Mini-enregistrement de données sur une semaine","Grille d’observation de numératie du facilitateur"],
  passport:["K : comprend le comptage, la comparaison, la mesure, l’addition, la soustraction et les registres simples","P : mesure, enregistre et résout des problèmes pratiques de quantité","D : vérifie les résultats numériques ou d’IA avec un raisonnement indépendant","S : utilise les outils de mesure et les récipients en sécurité","E : explique comment le comptage, la mesure et les registres réduisent le gaspillage et soutiennent la planification","L : communique son raisonnement, travaille avec les autres et corrige les erreurs de manière constructive"],
  trainerNotes:["Utiliser des objets concrets avant les symboles pour les apprenants qui en ont besoin.","Accepter les explications orales et les démonstrations comme preuves en plus du travail écrit.","Utiliser des exemples culturellement familiers et des outils de mesure disponibles localement.","Lorsque les unités standards ne sont pas encore maîtrisées, commencer par des unités informelles cohérentes puis faire une transition progressive.","Éviter les compétitions de vitesse qui peuvent humilier ; valoriser le raisonnement et le progrès."],
  remediation:"Revenir aux objets concrets, à la correspondance un-à-un, aux droites numériques et aux mesures répétées avec une seule unité à la fois. Réduire l’étendue des nombres tout en gardant la même tâche fonctionnelle.",
  extension:"L’apprenant conçoit un petit défi d’utilisation des ressources, par exemple compter chaque jour les tasses d’eau utilisées pour quelques plantes, puis propose une amélioration fondée sur les données.",
  imagePrompts:["Enfants africains de 8 à 11 ans comptant des graines, mesurant de l’eau dans des tasses transparentes et utilisant un mètre ruban dans un jardin d’apprentissage supervisé, garçons et filles inclus, lumière naturelle, aucun texte lisible, accents LIFEWS verts et jaune doré.","Illustration éducative propre pour enfants montrant six icônes : comptage, comparaison, règle, volume d’eau, addition simple et tableau de bâtons, fond blanc, sans mots.","Petit groupe photoréaliste d’apprenants africains enregistrant le nombre de plantes dans un tableau simple sur papier près d’un jardin scolaire, facilitateur à proximité, collaboration adaptée à l’âge, aucun texte lisible."]
};