import type { PF01Module } from "./pf-01";

type PF04Module = Omit<PF01Module,"code"> & { code:"PF-04" };

export const pf04Yo: PF04Module = {
  code:"PF-04",
  title:"Àwọn Ewéko Tó Yí Wa Ká",
  level:"Pathways Foundation",
  age:"Ní àárín ọdún 8 sí 11; iṣẹ́ ọwọ́ gbọ́dọ̀ bá ipo agbègbè àti aini akẹ́kọ̀ọ́ mu.",
  duration:"Ẹ̀kọ́ amọ̀nà mẹ́fà pẹ̀lú ìṣàkíyèsí, iṣẹ́ ọgbà àti ìdánwò",
  fieldworkHours:3,
  bigQuestion:"Kí ni ewéko lè kọ́ wa nípa oúnjẹ, omi, ìtọju, ọjà tó wúlò àti ibi tá a ń gbé?",
  whyItMatters:"Ewéko jẹ́ ọ̀nà rọrùn láti wọ sáyẹ́nsì, eto oúnjẹ àti ìṣàkíyèsí iṣẹ́ ọwọ́. Ẹ̀ka yìí ń ràn akẹ́kọ̀ọ́ lọwọ láti mọ apá ewéko, fi ewéko tó wúlò wé, lóye ohun tí ewéko nílò fún ìdagbasoke, kí o sì so ewéko mọ́ oúnjẹ, iṣẹ́ ìgbésí-ayé, ìtọju ayíká àti ẹ̀kọ́ GreenSkills ọjọ́ iwájú.",
  outcomes:["Mọ apá pataki ewéko kí o sì ṣàlàyé iṣẹ́ rọrùn tí ọkọọkan ń ṣe.","Yà gbongbo, igi-ara, ewé, òdòdó, eso àti irúgbìn sí ọ̀tọ̀ pẹ̀lú àpẹẹrẹ agbègbè.","Ṣàlàyé aini ìpilẹ̀ ewéko gẹ́gẹ́ bí omi, ìmọ́lẹ̀, afẹ́fẹ́, eroja onjẹ àti aaye.","Kíyèsi kí o sì kọ ìyàtọ̀ rọrùn láàárín ewéko sílẹ̀.","So ewéko mọ́ oúnjẹ, ohun èlò, ojiji, ẹwa àti ọ̀nà ìgbésí-ayé.","Ṣe iṣẹ́ ìṣàkíyèsí àti ìtọju ewéko lábẹ́ amọ̀nà pẹ̀lú ẹ̀rí."],
  vocabulary:["ewéko","gbongbo","igi-ara","ewé","òdòdó","eso","irúgbìn","ilẹ̀","omi","ìmọ́lẹ̀ oorun","eroja onjẹ","kíyèsi","fiwé","tọju","ikórè"],
  materials:["àpẹẹrẹ ewéko agbègbè tó ní ààbò tàbí ewéko alààyè","gilasi ìtóbi bí ó bá wà","ìwé àti pẹ́ńsù","káàdì àwòrán apá ewéko","àpò kékeré tàbí ibùsùn ọgbà","agolo omi","aami","tabulẹti/fóònù lábẹ́ ìṣàkóso olùkọ́ fún fífi àwòrán wé bí ó bá yẹ"],
  safety:["Má jẹ ewéko tí a kò mọ̀.","Yà ewéko olóró, tó ń fa ìrora tàbí ẹ̀gún kúrò nínú iṣẹ́ ọmọ.","Fọ ọwọ́ lẹ́yìn mímu ilẹ̀ tàbí ewéko.","Lo irinṣẹ́ ọmọ tó ní ààbò nìkan pẹ̀lú amọ̀nà.","Fún akẹ́kọ̀ọ́ tó ní allergy tàbí ìṣòro gbigbe ni ipa tó ba wọn mu.","Má jẹ́ kí AI nìkan pinnu pé ewéko kan jẹun tàbí jẹ́ oogun."],
  lessons:[
    {id:"PF-04-L1",title:"Pade Ewéko Kan",objective:"Mọ ewéko gẹ́gẹ́ bí ohun alààyè tó ní apá àti aini tí a lè rí.",teaching:["Ewéko jẹ́ ohun alààyè tó ń dagba, tó sì ń yí padà.","Ewéko oríṣìíríṣìí lè yàtọ̀ gan-an ṣùgbọ́n wọ́n tún lè ní ànímọ́ tó wọ́pọ̀.","Ìṣàkíyèsí pẹ̀lú àkíyèsí ń ràn wa lọwọ láti ṣàpèjúwe ohun tá a rí kí a tó ṣàlàyé idi."],activity:"Kíyèsi ewéko agbègbè méjì tó ní ààbò, kí o kọ tàbí ya àwòrán ìfarajọ mẹ́ta àti ìyàtọ̀ mẹ́ta.",diy:"Ṣẹ̀dá káàdì ìṣàkíyèsí ewéko pẹ̀lú àwòrán, ibi, ìfojúsùn gígùn àti ànímọ́ méjì tí a rí.",aiLayer:"AI Ipele 1 — Ìdámọ̀: olùkọ́ fi hàn bí AI ṣe lè ṣàpèjúwe àwòrán, lẹ́yìn náà akẹ́kọ̀ọ́ fi àlàyé yẹn wé pẹ̀lú ìṣàkíyèsí tirẹ̀.",enterprise:"Ènìyàn ń ṣẹ̀dá ìyelori nípasẹ̀ gbíngbin, ìtọju, gbigbe àti lílo ewéko pẹ̀lú ojúṣe.",quiz:[{question:"Ewéko jẹ́…",options:["ohun alààyè","ẹ̀rọ","okuta","nọ́mbà"],answer:0},{question:"Olùkíyèsi tó dáa yẹ kí ó…",options:["wo dáadáa","gboju láìwo","ba ewéko jẹ́","foju kọ ìyàtọ̀"],answer:0},{question:"Ewéko méjì lè…",options:["ní ànímọ́ kan jọ, kí wọ́n sì yàtọ̀ ní omiiran","jẹ́ kanna nigbagbogbo","má nílò omi rárá","má ní apá kankan"],answer:0}]},
    {id:"PF-04-L2",title:"Gbongbo, Igi-Ara àti Ewé",objective:"Mọ gbongbo, igi-ara àti ewé kí o sì ṣàlàyé ipa wọn.",teaching:["Gbongbo ń mú ewéko dúró, ó sì ń gba omi àti eroja onjẹ.","Igi-ara ń gbe ewé dúró, ó sì ń rán omi àti ohun míì ká nínú ewéko.","Ewé ń gba ìmọ́lẹ̀, ó sì ń ràn ewéko lọwọ láti ṣe oúnjẹ."],activity:"Báramu àpẹẹrẹ gidi tàbí àwòrán mọ́ GBONGBO, IGI-ARA àti EWÉ, kí o sì tọpa ọ̀nà tí omi lè gbà láti ilẹ̀ lọ sókè.",diy:"Ṣe awoṣe ewéko rọrùn pẹ̀lú aami láti inú ìwé, igi tàbí ohun tí a tún lò.",aiLayer:"AI Ipele 2 — Fífiwé lábẹ́ amọ̀nà: lo irinṣẹ́ àwòrán lábẹ́ olùkọ́ láti fi gbongbo, igi-ara tàbí ewé aláìmọ̀ wé, kí o sì ṣàyẹ̀wò pẹ̀lú ohun ẹ̀kọ́ tó dájú.",enterprise:"Mímọ apá ewéko ń ràn agbẹ lọwọ láti mu irugbin dáadáa àti dín ibajẹ kù.",quiz:[{question:"Apá wo ni ó máa ń di ewéko mọ́lẹ̀?",options:["gbongbo","òdòdó","eso","aami"],answer:0},{question:"Ewé máa ń gba…",options:["ìmọ́lẹ̀","owó","plastiki","ariwo"],answer:0},{question:"Igi-ara ń ṣe iranlọwọ fún…",options:["ìtìlẹ́yìn àti gbigbe ohun","piparẹ gbongbo","dídẹ̀kun ìdagbasoke","rọ́pò ilẹ̀"],answer:0}]},
    {id:"PF-04-L3",title:"Òdòdó, Eso àti Irúgbìn",objective:"Ṣàlàyé ìbáṣepọ̀ láàárín òdòdó, eso àti irúgbìn pẹ̀lú àpẹẹrẹ rọrùn.",teaching:["Ọ̀pọ̀ ewéko aládòdó ń ṣe òdòdó gẹ́gẹ́ bí apá ìbímọ.","Eso sábà máa ń dáàbò bo tàbí gbe irúgbìn.","Irúgbìn lè dàgbà sí ewéko tuntun bí ipo bá dara."],activity:"Pín àpẹẹrẹ tàbí àwòrán ewéko tó ní ààbò sí ẹgbẹ́ òdòdó, eso àti irúgbìn, kí ẹ sì jíròrò bí wọ́n ṣe ní ìbáṣepọ̀.",diy:"Ṣẹ̀dá káàdì ìtẹ̀síwájú apá mẹ́ta: ÒDÒDÓ → ESO → IRÚGBÌN pẹ̀lú irugbin kan tí o mọ̀.",aiLayer:"AI Ipele 3 — Títẹ̀lé àti ìpín: fi àtẹ̀le ìgbésí-ayé tí akẹ́kọ̀ọ́ ṣe wé pẹ̀lú àtẹ̀le tí olùkọ́ gba láti AI, kí o sì rí àṣìṣe.",enterprise:"Irúgbìn, eso àti òdòdó lè jẹ́ ọjà pataki, ṣùgbọ́n didara da lórí iṣelọpọ àti mímu pẹ̀lú ààbò.",quiz:[{question:"Irúgbìn lè…",options:["dàgbà sí ewéko tuntun","di irin","rọ́pò omi","ṣe ina mọnamọna taara"],answer:0},{question:"Eso sábà ní…",options:["irúgbìn","irinṣẹ́","waya","okuta nìkan"],answer:0},{question:"Àtẹ̀le wo ni ó sábà tọ́?",options:["òdòdó → eso → irúgbìn","irúgbìn → irin → eso","ewé → batiri → gbongbo","ilẹ̀ → waya → òdòdó"],answer:0}]},
    {id:"PF-04-L4",title:"Ohun Tí Ewéko Nílò",objective:"Mọ ipo ìpilẹ̀ tí ewéko nílò láti dagba dáadáa.",teaching:["Ewéko nílò omi, ìmọ́lẹ̀, afẹ́fẹ́, eroja onjẹ àti aaye tó yẹ.","Kekere ju tàbí púpọ̀ ju ti orísun kan lè fa iṣoro.","Ewéko oríṣìíríṣìí lè nílò omi, ìmọ́lẹ̀ àti aaye ní iye tó yàtọ̀."],activity:"Fi ọmọ ewéko méjì tó jọra sí ipo ààbò tó yàtọ̀, kí o sọ ohun tí o ro pé yóò ṣẹlẹ̀.",diy:"Ṣe kẹ̀kẹ́ aini-ewéko tó fi omi, ìmọ́lẹ̀, afẹ́fẹ́, eroja onjẹ àti aaye hàn.",aiLayer:"AI Ipele 4 — Àsọtẹ́lẹ̀: olùkọ́ béèrè lọwọ AI fún àsọtẹ́lẹ̀ nípa ipo ìtọju ewéko kan; akẹ́kọ̀ọ́ fi wé pẹ̀lú ẹ̀rí ìṣàkíyèsí tirẹ̀.",enterprise:"Ìṣàkóso orísun tó dáa lè dín ìsòfò omi, ohun amúnibú ilẹ̀ àti ohun gbíngbin kù.",quiz:[{question:"Èwo ni aini ìpilẹ̀ ewéko?",options:["omi","ere plastiki","ọ̀rọ̀ aṣínà","kunrin"],answer:0},{question:"Ṣé omi tó pọ̀ ju lè ba ewéko kan jẹ́?",options:["Bẹ́ẹ̀ ni","Rárá, lailai","Ní alẹ́ nìkan","Lórí intanẹẹti nìkan"],answer:0},{question:"Ewéko oríṣìíríṣìí lè nílò…",options:["iye orísun tó yàtọ̀","ìtọju kanna nigbagbogbo","kò sí ìmọ́lẹ̀","kò sí aaye"],answer:0}]},
    {id:"PF-04-L5",title:"Àwọn Ewéko Tó Wúlò Ní Ayíká Wa",objective:"Pín ewéko tí a mọ̀ sí ẹ̀ka gẹ́gẹ́ bí ipa wọn nínú oúnjẹ, ojiji, ohun èlò, ẹwa tàbí ọ̀nà ìgbésí-ayé.",teaching:["Ewéko kan lè ní ìlò ju ọkan lọ.","Ènìyàn gbára lé ewéko fún oúnjẹ àti ọ̀pọ̀ ohun èlò.","Lílo ewéko pẹ̀lú ojúṣe túmọ̀ sí ìtọju ilẹ̀, omi àti ipese ọjọ́ iwájú."],activity:"Ṣẹ̀dá àtẹ àwùjọ lílo-ewéko pẹ̀lú ẹ̀ka bíi oúnjẹ, ojiji, okun/ohun èlò, ọṣọ àti owo/ìgbésí-ayé.",diy:"Fọ̀rọ̀ wá àgbàlagbà tí o gbẹ́kẹ̀lé nípa ewéko agbègbè kan tó wúlò, kí o kọ apá tí a ń lò àti bí a ṣe ń tọju rẹ̀.",aiLayer:"AI Ipele 5 — Ìjẹ́rìí: olùkọ́ fi hàn pé AI lè daba ìlò ewéko, ṣùgbọ́n ìdámọ̀ agbègbè àti ìsọfúnni ààbò gbọ́dọ̀ jẹ́rìí pẹ̀lú ènìyàn tàbí orísun tó dájú.",enterprise:"Ṣàwárí bí ìmọ̀ ewéko ṣe ń ṣe atilẹyin nursery, oko, sise oúnjẹ, landscaping àti iṣẹ́ aláwọ̀-ewe mìíràn, láìfìṣẹ́ iṣowo fún ọmọ.",quiz:[{question:"Ṣé ewéko kan lè ní ìlò púpọ̀?",options:["Bẹ́ẹ̀ ni","Rárá","Ewéko òkèèrè nìkan","Igi nìkan"],answer:0},{question:"Ìsọfúnni lílo ewéko gbọ́dọ̀…",options:["jẹ́rìí fún ìpeye","jẹ́ ohun tá a dá sílẹ̀","jẹ́ aláìní ààbò","dá lórí AI nìkan"],answer:0},{question:"Lílo ewéko pẹ̀lú ojúṣe ní…",options:["ìtọju orísun","ìsòfò","ibajẹ","ikórè aláìní ààbò"],answer:0}]},
    {id:"PF-04-L6",title:"Tọju Ewéko Alààyè",objective:"Lo ìṣàkíyèsí àti ìtọju ìpilẹ̀ fún ewéko lábẹ́ amọ̀nà, kí o sì kọ ẹ̀rí ayípadà sílẹ̀.",teaching:["Ìtọju ewéko jẹ́ ìyípo: kíyèsi → pinnu → ṣe → ṣàyẹ̀wò.","Àkọsílẹ̀ ń ràn wa lọwọ láti rí ayípadà kọjá akoko.","Ìtọju tó dáa ń dín ìsòfò kù, ó sì ń dahun sí ohun tí ewéko nílò gidi."],activity:"Ní tọkọtaya, ṣàyẹ̀wò ewéko tàbí ibùsùn kékeré, mọ aini ìtọju kan, kí o sì ṣe ìṣe lábẹ́ amọ̀nà bíi fifún omi, mulching tàbí yíyọ ìdọ̀tí tó ní ààbò.",diy:"Pa àkọsílẹ̀ ìtọju ewéko mẹ́ta pẹ̀lú ọjọ́, ìṣàkíyèsí, ìṣe àti abajade.",aiLayer:"Ìṣọ̀kan: fi ìpinnu ìtọju ẹgbẹ́ wé pẹ̀lú ìmọ̀ràn AI tí olùkọ́ pèsè, kí o sì dá ìpinnu ikẹhin lórí ẹ̀rí tí a rí àti ìmọ̀ràn agbègbè.",enterprise:"Ìtọju tó dájú, ìkọ̀wé àkọsílẹ̀ àti ìṣàkíyèsí didara jẹ́ ìwà iṣẹ́ pataki nínú oko àti iṣẹ́ aláwọ̀-ewe.",quiz:[{question:"Ìyípo ìtọju tó wúlò ni…",options:["kíyèsi → pinnu → ṣe → ṣàyẹ̀wò","ṣe → foju kọ → gbàgbé","gboju → ṣòfò → lọ","daakọ → fi pamọ́ → dúró"],answer:0},{question:"Kí ló dé tí a fi ń pa àkọsílẹ̀ ìtọju?",options:["láti tọpa ayípadà","láti fi ẹ̀rí pamọ́","láti yàgò fún ìṣàkíyèsí","láti rọ́pò ewéko"],answer:0},{question:"Ìpinnu ìtọju tó dáa yẹ kí ó lo…",options:["ìṣàkíyèsí àti ìmọ̀ràn tó dájú","gboju lasan","ọ̀rọ̀ aṣínà","ìtọ́nisọ́nà ewu"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Apá ewéko wo ni ó sábà ń gba omi láti ilẹ̀?",options:["Gbongbo","Òdòdó","Eso","Irúgbìn nìkan"],answer:0},{question:"Apá wo ni ó sábà ń gba ìmọ́lẹ̀?",options:["Ewé","Gbongbo","Eso nìkan","Aami"],answer:0},{question:"Kí ni irúgbìn lè di ní ipo tó dara?",options:["Ewéko tuntun","Irin","Plastiki","Batiri"],answer:0},{question:"Èwo ni aini ìpilẹ̀ ewéko?",options:["Omi","Ọ̀rọ̀ aṣínà","Kunrin","Epo nìkan"],answer:0},{question:"Kí ló dé tí a fi ń fi ewéko wé?",options:["Láti rí ìfarajọ àti ìyàtọ̀","Láti ba wọn jẹ́","Láti yàgò fún ẹ̀kọ́","Láti jẹ́ kí wọ́n jọ patapata"],answer:0},{question:"Ṣé AI nìkan lè jẹ́rìí pé ewéko tí a kò mọ̀ jẹun?",options:["Rárá","Bẹ́ẹ̀ ni nigbagbogbo","Tí fọ́tò bá mọ́ nìkan","Tí ọmọ bá béèrè nìkan"],answer:0},{question:"Èwo ni ẹ̀rí ìtọju ewéko tó dáa?",options:["Àkọsílẹ̀ ìṣàkíyèsí tó ní ọjọ́","Ahọ́n","Gboju láìkíyèsi","Iṣẹ́ ẹlòmíràn tí kò jọmọ́"],answer:0},{question:"Ìmọ̀ ewéko lè ṣe atilẹyin ìgbésí-ayé nípasẹ̀…",options:["gbíngbin, nursery, processing àti ìtọju","ìsòfò nìkan","mímu aláìní ààbò","fífipamọ́ ìsọfúnni"],answer:0}],theory:["Darúkọ apá pataki ewéko kan tí o mọ̀, kí o ṣàlàyé iṣẹ́ kan ti ọkọọkan.","Ṣàlàyé ohun márùn-ún tí ewéko lè nílò láti dagba dáadáa.","Ṣàpèjúwe ewéko agbègbè kan tó wúlò àti ọ̀nà méjì tí ènìyàn fi ń lò ó.","Ṣàlàyé idi tí àkọsílẹ̀ ìtọju ewéko fi lè ràn agbẹ lọwọ láti ṣe ìpinnu tó dáa.","Ṣàlàyé idi tí ìsọfúnni AI nípa ewéko tí a kò mọ̀ fi gbọ́dọ̀ jẹ́rìí kí ẹnikẹ́ni tó jẹ tàbí lo ewéko náà."],practical:"Kíyèsi ewéko alààyè tó ní ààbò, mọ apá tàbí ànímọ́ mẹ́rin o kere tan, ṣe ìdánilójú aini ìtọju kan, ṣe ìṣe ìtọju kan lábẹ́ amọ̀nà, kí o sì ṣàfihàn àkọsílẹ̀ ẹ̀rí kukuru ti ìṣàkíyèsí, ìṣe àti abajade tí a retí."},
  evidence:["Káàdì ìṣàkíyèsí ewéko","Awoṣe apá ewéko","Káàdì òdòdó-eso-irúgbìn","Kẹ̀kẹ́ aini ewéko","Àtẹ lílo ewéko àwùjọ tàbí àkọsílẹ̀ ifọrọwanilẹnuwo","Àkọsílẹ̀ ìtọju ewéko mẹ́ta","Àkọsílẹ̀ ìṣàkíyèsí iṣẹ́ olùkọ́"],
  passport:["K: mọ apá ewéko, aini àti ìlò tó wọ́pọ̀","P: ṣe ìṣàkíyèsí ewéko àti iṣẹ́ ìtọju lábẹ́ amọ̀nà","D: fi ìmọ̀ràn díjítà/AI wé pẹ̀lú ẹ̀rí taara àti orísun tó dájú","S: tẹ̀lé òfin ààbò ewéko, ilẹ̀ àti irinṣẹ́","E: so ìmọ̀ ewéko mọ́ ọjà, iṣẹ́ àti ìtọju orísun","L: ṣiṣẹ́ pọ̀, kọ ìṣàkíyèsí sílẹ̀ àti sọ ìpinnu ìtọju"],
  trainerNotes:["Lo ewéko tí akẹ́kọ̀ọ́ máa ń rí ní agbègbè bí ó bá ní ààbò.","Má ṣe fi ìlò oogun hàn gẹ́gẹ́ bí òtítọ́ tó dájú nínú ẹ̀ka ìpilẹ̀ yìí.","Fún ẹni tó ṣì ń kọ́ kíkà ní àṣàyàn ẹnu, àwòrán àti ohun tí a lè fọwọ́ kan.","Yí ipa ìṣàkíyèsí, fifún omi, ìwọn àti ìròyìn ká ní ìdájọ́.","Bí ọgbà kò bá sí, lo ewéko nínú àpò tàbí àwòrán didara pẹ̀lú ìṣàkíyèsí ewéko alààyè kan lábẹ́ amọ̀nà bí ó ṣeé ṣe."],
  remediation:"Dín iye apá ewéko tí a kọ́ lẹ́ẹ̀kan kù, lo ìbáramu léraléra pẹ̀lú ohun gidi tàbí awoṣe tí a lè fọwọ́ kan, kí o sì ṣe adaṣe àtẹ̀le kíyèsi–darúkọ–iṣẹ́.",
  extension:"Akẹ́kọ̀ọ́ ṣẹ̀dá profaili ojú-iwe kan fún irugbin agbègbè pataki tó fi apá ewéko, aini ìdagbasoke kan, ìlò kan àti ìṣe ìtọju kan hàn.",
  imagePrompts:["Àwọn ọmọ Africa ọdún 8–11 ń kíyèsi ewéko ọgbà tó ní ààbò pẹ̀lú olùkọ́ aláàánú, ń tọ́ka sí gbongbo, igi-ara àti ewé, ọgbà ilé-ẹ̀kọ́-àwùjọ tó kó gbogbo ènìyàn sí, ìmọ́lẹ̀ adayeba, kò sí ọrọ̀ tí a lè ka, àwọ̀ LIFEWS aláwọ̀-ewe àti goolu.","Àwòrán botaniki ọmọde tó fi ewéko oúnjẹ aládòdó gbogbogbo hàn pẹ̀lú gbongbo, igi-ara, ewé, òdòdó, eso àti irúgbìn tó hàn kedere, abẹ́lẹ̀ funfun, kò sí aami tàbí ọrọ̀.","Ẹgbẹ́ kékeré akẹ́kọ̀ọ́ Africa ń fun ewéko nínú àpò ní omi àti mulch lábẹ́ amọ̀nà nígbà tí wọ́n ń kọ ìṣàkíyèsí sílẹ̀, irinṣẹ́ ààbò, ìfowosowopo, kò sí ọrọ̀ tí a lè ka."]
};