import type { PF01Module } from "./pf-01";

type PF05Module = Omit<PF01Module,"code"> & { code:"PF-05" };

export const pf05Yo: PF05Module = {
  code:"PF-05",
  title:"Irúgbìn àti Bí Ó Ṣe Ń Bẹ̀rẹ̀ Sí Í Dagba",
  level:"Pathways Foundation",
  age:"Ní àárín ọdún 8 sí 11; ìpín ipele àti ipa iṣẹ́ ọwọ́ gbọ́dọ̀ tẹ̀lé ìmúrasílẹ̀ akẹ́kọ̀ọ́.",
  duration:"Ẹ̀kọ́ amọ̀nà mẹ́fà pẹ̀lú ìwádìí germination ọjọ́ 7–10 àti ìdánwò",
  fieldworkHours:3,
  bigQuestion:"Kí ló wà nínú irúgbìn, kí ló ń ràn án lọwọ láti bẹ̀rẹ̀ sí í dagba, àti báwo la ṣe lè dán ero wa wò pẹ̀lú ẹ̀rí?",
  whyItMatters:"Irúgbìn so oúnjẹ, iṣẹ́-ogbin, onírúurú ohun alààyè àti ọ̀nà ìgbésí-ayé ọjọ́ iwájú pọ̀. Nípasẹ̀ ìwádìí germination, akẹ́kọ̀ọ́ máa ń ṣe ìṣàkíyèsí, fair test, ìwọn, ìkọ̀wé àkọsílẹ̀, ìtọju orísun, lílo AI pẹ̀lú ojúṣe àti ìrònú iṣowo ìpilẹ̀, gbogbo rẹ̀ láti inú eto alààyè gidi.",
  outcomes:["Mọ irúgbìn gẹ́gẹ́ bí ẹya ewéko alààyè tó lè dàgbà sí ewéko tuntun ní ipo tó dara.","Mọ ànímọ́ irúgbìn wọ́pọ̀ kí o sì yà irúgbìn kúrò nínú ohun tí kì í ṣe irúgbìn.","Ṣàlàyé pé germination nílò ọrinrin tó yẹ, afẹ́fẹ́ àti ìwọ̀n otutu tó yẹ, nígbà tí ọmọ-ewéko lẹ́yìn ìfarahàn tún nílò ìmọ́lẹ̀ àti eroja onjẹ.","Ṣètò ìfiwéra germination rọrùn tí ó yí ipo kan ṣoṣo padà.","Kíyèsi, ka, wọn àti kọ ẹ̀rí germination sílẹ̀ kọjá akoko.","Lo ìmọ̀ràn díjítà tàbí AI pẹ̀lú ìrònú, kí o sì jẹ́rìí rẹ̀ pẹ̀lú ìdánwò àti ìtọ́sọ́nà tó dájú.","So didara irúgbìn, mímu pẹ̀lú àkíyèsí àti ìkọ̀wé àkọsílẹ̀ mọ́ iṣelọpọ oúnjẹ àti iṣẹ́ nursery pẹ̀lú ojúṣe."],
  vocabulary:["irúgbìn","germination","awọ irúgbìn","embryo","ọrinrin","afẹ́fẹ́","iwọn otutu","ọmọ-ewéko","gbongbo","ẹ̀ka tuntun","variable","kíyèsi","wọn","kọ sílẹ̀","fiwé","ẹ̀rí"],
  materials:["irúgbìn agbègbè tó ní ààbò bíi ẹ̀wà, agbado tàbí cowpea","ago tí a lè rí inú rẹ̀ tàbí àpò pẹlẹbẹ","cotton, paper towel tàbí medium tó yẹ","omi mímọ́","aami","pẹ́ńsù àti ìwé àkọsílẹ̀","ruula","grid kíkà tàbí tábìlì data rọrùn","ẹ̀rọ díjítà lábẹ́ ìṣàkóso olùkọ́ bí ó bá yẹ"],
  safety:["Lo irúgbìn tí a mọ̀, tí kì í ṣe olóró, tí olùkọ́ pèsè tàbí fọwọ́ sí nìkan.","Irúgbìn tí a lò fún ìdánwò kò yẹ kí a jẹ lẹ́yìn mímu tàbí germination.","Fọ ọwọ́ ṣáájú àti lẹ́yìn iṣẹ́ ọwọ́, kí ibi iṣẹ́ sì mọ́.","Nu omi tó dà sílẹ̀ lẹ́sẹ̀kẹsẹ̀ kí ẹni má bà a yọ.","Má jẹ́ kí akẹ́kọ̀ọ́ mu kemika seed-treatment tàbí pesticide.","Ìmọ̀ràn AI nípa kemika, seed treatment tàbí ààbò oúnjẹ kò lè rọ́pò ìtọ́sọ́nà olùkọ́ tàbí ìtọ́nisọ́nà ọja."],
  lessons:[
    {id:"PF-05-L1",title:"Irúgbìn Lè Di Ewéko",objective:"Mọ irúgbìn kí o sì ṣàlàyé ipa rẹ̀ nínú bí ewéko tuntun ṣe ń bẹ̀rẹ̀.",teaching:["Irúgbìn ní ọmọ-ewéko kékeré àti orísun onjẹ tí awọ irúgbìn ń dáàbò bo.","Irúgbìn yàtọ̀ ní gígùn, àwọ̀, ìrísí àti texture.","Kì í ṣe gbogbo ohun kékeré ni irúgbìn; ìdámọ̀ yẹ kí ó dá lórí ìṣàkíyèsí àti ìsọfúnni tó dájú."],activity:"Pín irúgbìn tó ní ààbò àti ohun tí kì í ṣe irúgbìn sí ẹgbẹ́, kí o sì ṣàpèjúwe irúgbìn kọọkan pẹ̀lú gígùn, àwọ̀, ìrísí àti oju rẹ̀.",diy:"Ṣẹ̀dá káàdì ìṣàkíyèsí irúgbìn mẹ́fà pẹ̀lú àwòrán tàbí àpẹẹrẹ, orúkọ bí a bá mọ̀ ọ́ àti ànímọ́ méjì tí a rí.",aiLayer:"AI Ipele 1 — Ìdámọ̀ àti ìbéèrè: fi àlàyé akẹ́kọ̀ọ́ wé pẹ̀lú àlàyé AI lábẹ́ olùkọ́, kí o sì mọ ohun tí a lè jẹ́rìí pẹ̀lú ìṣàkíyèsí taara.",enterprise:"Olùgbéjáde irúgbìn àti nursery ń ṣẹ̀dá ìyelori nípasẹ̀ fífi irúgbìn tí a dá mọ̀ dáadáa, tó lágbára àti ìsọfúnni tó péye fún ènìyàn.",quiz:[{question:"Kí ni irúgbìn tó yẹ lè mú jáde?",options:["Ewéko tuntun","Irinṣẹ́ irin","Batiri","Igo plastiki"],answer:0},{question:"Ànímọ́ wo ni o lè rí taara?",options:["Àwọ̀ irúgbìn","Owó tita ọjọ́ iwájú","Ọ̀rọ̀ aṣínà tí a kò rí","Ikore tó dájú"],answer:0},{question:"Kí ló dé tí a fi gbọ́dọ̀ dá irúgbìn mọ̀ dáadáa?",options:["Irúgbìn oríṣìíríṣìí ń dàgbà sí ewéko oríṣìíríṣìí","Gbogbo irúgbìn jọ","Aami kò ṣe pàtàkì","Gboju ń mú didara pọ̀"],answer:0}]},
    {id:"PF-05-L2",title:"Ohun Tó Wà Nínú Irúgbìn",objective:"Mọ awọ irúgbìn, orísun onjẹ àti embryo pẹ̀lú ìṣàkíyèsí irúgbìn tí a rọ sínú omi ní ààbò.",teaching:["Awọ irúgbìn ń dáàbò bo inú irúgbìn.","Ọ̀pọ̀ irúgbìn ní onjẹ tí a fipamọ́ fún ìdagbasoke ìbẹ̀rẹ̀.","Embryo ni ọmọ-ewéko kékeré tó bẹ̀rẹ̀ sí í dagba nígbà germination."],activity:"Olùkọ́ pèsè ẹ̀wà tàbí cowpea tí a rọ. Akẹ́kọ̀ọ́ ṣí ọkan díẹ̀díẹ̀, kí o fi inú rẹ̀ wé pẹ̀lú àwòrán, láìjẹ ẹ́.",diy:"Ṣe awoṣe irúgbìn ńlá láti ìwé tàbí ohun tí a tún lò, tó fi àbùdá òde, onjẹ tí a fipamọ́ àti ọmọ-ewéko hàn.",aiLayer:"AI Ipele 2 — Àlàyé àti fífiwé: béèrè fún àlàyé rọrùn nípa apá irúgbìn, kí o sì ṣàyẹ̀wò gbogbo ìsọ̀rọ̀ pẹ̀lú irúgbìn gidi àti àwòrán tó dájú.",enterprise:"Mímọ̀ apá irúgbìn ń ṣàlàyé idi tí mímu lile, ibi ìpamọ́ búburú àti kokoro fi lè dín didara irúgbìn kù.",quiz:[{question:"Kí ni ń dáàbò bo òde ọ̀pọ̀ irúgbìn?",options:["Awọ irúgbìn","Ewé òdòdó","Waya","Apoti batiri"],answer:0},{question:"Kí ni embryo?",options:["Ọmọ-ewéko tó ń dagba","Irinṣẹ́ ọgbà","Iru ilẹ̀","Aami apoti"],answer:0},{question:"Kí ló dé tí irúgbìn fi lè ní onjẹ tí a fipamọ́?",options:["Láti ṣe atilẹyin ìdagbasoke ìbẹ̀rẹ̀","Láti ṣe ina mọnamọna","Láti rọ́pò afẹ́fẹ́","Láti di plastiki"],answer:0}]},
    {id:"PF-05-L3",title:"Ohun Tí Germination Nílò",objective:"Ṣàlàyé ipo ìpilẹ̀ fún germination, kí o sì yà wọ́n kúrò nínú ohun tí ọmọ-ewéko nílò lẹ́yìn ìfarahàn.",teaching:["Ọ̀pọ̀ irúgbìn nílò ọrinrin, oxygen àti ìwọ̀n otutu tó yẹ láti germinate.","Omi díẹ̀ ju lè dènà germination; omi púpọ̀ ju lè dín afẹ́fẹ́ kù, kí ó sì fa iṣoro.","Aini ìmọ́lẹ̀ yàtọ̀ láàárín irúgbìn; lẹ́yìn ìfarahàn, ọmọ-ewéko nílò ìmọ́lẹ̀ àti eroja onjẹ tó yẹ."],activity:"Lo àwòrán ipo láti sọ àsọtẹ́lẹ̀ bóyá irúgbìn yóò germinate nígbà tí ó gbẹ, ní ọrinrin tó yẹ, nínú omi púpọ̀, ní ooru tó pọ̀ tàbí ipo mìíràn tí kò yẹ, kí o sì ṣàlàyé idi.",diy:"Ṣe kẹ̀kẹ́ aini germination tó yà IPO GERMINATION sí ọ̀tọ̀ kúrò nínú AINI ỌMỌ-EWÉKO LẸ́YÌN NÁÀ.",aiLayer:"AI Ipele 3 — Àsọtẹ́lẹ̀: fi àsọtẹ́lẹ̀ AI fún ipo irúgbìn méjì wé pẹ̀lú ti akẹ́kọ̀ọ́, kí o sì samisi ohun tí ìdánwò tó ń bọ̀ lè dán wò gidi.",enterprise:"Germination tó dáa ń dín ìsòfò irúgbìn, omi, aaye àti iṣẹ́ kù nínú oko àti nursery.",quiz:[{question:"Àkójọpọ̀ wo ni ó sábà ṣe pàtàkì fún germination?",options:["Ọrinrin, afẹ́fẹ́ àti ìwọ̀n otutu tó yẹ","Kunrin, plastiki àti ariwo","Owó, aami àti batiri","Ìmọ́lẹ̀ tó lágbára nìkan"],answer:0},{question:"Ṣé omi púpọ̀ ju lè fa iṣoro?",options:["Bẹ́ẹ̀ ni","Rárá","Fún irúgbìn plastiki nìkan","Lórí intanẹẹti nìkan"],answer:0},{question:"Kí ni a yẹ kí a fi àsọtẹ́lẹ̀ wé?",options:["Ẹ̀rí tí a rí","Ahọ́n","Gboju lasan","Ọ̀rọ̀ aṣínà"],answer:0}]},
    {id:"PF-05-L4",title:"Ṣètò Fair Germination Test",objective:"Ṣètò ìfiwéra rọrùn tí ipo kan yí padà nígbà tí ipo pataki mìíràn dúró bí ó ti lè ṣeé ṣe.",teaching:["Fair comparison ń yí ipo pataki kan padà, ó sì ń jẹ́ kí àwọn míì jọra bí ó ti lè ṣeé ṣe.","Gbogbo àpò nílò aami kedere kí ìṣàkíyèsí má bà a darapọ̀.","Àkọsílẹ̀ ìbẹ̀rẹ̀ yẹ kí ó ní ọjọ́, iru irúgbìn, iye irúgbìn àti treatment."],activity:"Gẹ́gẹ́ bí kilasi, ṣe treatment méjì tó ní ààbò bíi ọrinrin tó yẹ àti gbẹ. Jíròrò ohun tó yí padà, ohun tó dúró, àti ohun tí a máa ka.",diy:"Ṣètò àpò germination méjì pẹ̀lú aami, iye irúgbìn kanna, iru irúgbìn kanna àti ipo kan tí a yí padà.",aiLayer:"AI Ipele 4 — Ṣàyẹ̀wò ìlànà: olùkọ́ béèrè lọwọ AI láti ṣàyẹ̀wò ìdánwò; akẹ́kọ̀ọ́ kọ ìmọ̀ràn tí yóò yí variable púpọ̀ padà tàbí fi ohun ewu sílẹ̀.",enterprise:"Ìdánwò tó dájú ń ràn agbẹ lọwọ láti ṣe ìpinnu kí wọ́n tó lo irúgbìn, omi tàbí iṣẹ́ púpọ̀.",quiz:[{question:"Nínú fair comparison, melo ni ipo pataki yẹ kí ó yí padà?",options:["Ọ̀kan","Gbogbo rẹ̀","Kò sí kankan nígbà tí a ń pe e ní ìfiwéra","Bó ṣe pọ̀ tó"],answer:0},{question:"Kí ló dé tí a fi ń fi aami sí àpò?",options:["Kí treatment àti àkọsílẹ̀ yé","Kí irúgbìn germinate lẹ́sẹ̀kẹsẹ̀","Láti rọ́pò ìṣàkíyèsí","Láti fi abajade pamọ́"],answer:0},{question:"Àkọsílẹ̀ ìbẹ̀rẹ̀ wo ni wúlò?",options:["Ọjọ́ àti iye irúgbìn","Ọ̀rọ̀ aṣínà","Àwòrán tí kò jọmọ́","Kò sí ìsọfúnni"],answer:0}]},
    {id:"PF-05-L5",title:"Ka, Wọn àti Fiwé",objective:"Kó data germination jọ, kí o sì lo o fún ìfiwéra láìyí ohun tí a rí padà kí ó ba àsọtẹ́lẹ̀ mu.",teaching:["Ka irúgbìn tó germinate pẹ̀lú òfin kan naa ní gbogbo ọjọ́ ìṣàkíyèsí.","Wọn ànímọ́ rọrùn bí gígùn gbongbo tàbí shoot nìkan bí kò bá ba ìdánwò jẹ́.","Ẹ̀rí lè tako àsọtẹ́lẹ̀; olùwádìí tó dáa ń kọ ohun tó ṣẹlẹ̀ gidi sílẹ̀, kì í ṣe ohun tí wọ́n fẹ́ kí ó ṣẹlẹ̀."],activity:"Kíyèsi treatment méjèèjì, ka irúgbìn tó germinate, kọ ìwọn tàbí ìṣàkíyèsí kan sílẹ̀, kí o sì fi abajade wé.",diy:"Pa germination log tó ní ìwọlé mẹ́ta o kere tan pẹ̀lú ọjọ́, treatment, iye tó germinate, ìṣàkíyèsí àti ìwọn bí ó bá yẹ.",aiLayer:"AI Ipele 5 — Ìtumọ̀ data: tẹ tábìlì data àpẹẹrẹ sínú AI, fi ìtumọ̀ rẹ̀ wé pẹ̀lú ti akẹ́kọ̀ọ́, kí o sì ṣàyẹ̀wò ìṣirò àti ìsọ̀rọ̀.",enterprise:"Nursery àti iṣẹ́ ọmọ-ewéko gbára lé kíkà tó péye, quality check àti àkọsílẹ̀, kì í ṣe ìlérí tó ga ju.",quiz:[{question:"Kí ni o yẹ kí o kọ sílẹ̀ bí abajade bá yàtọ̀ sí àsọtẹ́lẹ̀?",options:["Ohun tó ṣẹlẹ̀ gidi","Abajade tí a yí padà","Kò sí nǹkan","Abajade ẹlòmíràn"],answer:0},{question:"Kí ló dé tí a fi ń ka irúgbìn pẹ̀lú òfin kan naa?",options:["Kí ìfiwéra lè dúró ṣinṣin","Láti ṣe àseyọrí dájú","Láti fi ìkùnà pamọ́","Láti yàgò fún ẹ̀rí"],answer:0},{question:"Àkọsílẹ̀ data tó wúlò ní…",options:["ọjọ́, treatment àti ìṣàkíyèsí","akọlé nìkan","ọ̀rọ̀ aṣínà","èrè tó dájú"],answer:0}]},
    {id:"PF-05-L6",title:"Láti Ẹ̀rí Sí Ìdagba Tó Dáa",objective:"Lo ẹ̀rí germination láti ṣàlàyé abajade, mọ ààlà ìdánwò àti daba ìgbésẹ̀ tó ní ojúṣe.",teaching:["Ìparí yẹ kí ó dáhùn ìbéèrè ìwádìí pẹ̀lú ẹ̀rí tí a kọ sílẹ̀.","Ìdánwò kékeré kan kò jẹ́rìí pé gbogbo irúgbìn tàbí ibi yóò huwa bákan naa.","Ìmúdára lè jẹ́ atunṣe ìdánwò, lílo irúgbìn púpọ̀ síi, aami tó dáa tàbí dídán ipo míì tó ní ààbò wò."],activity:"Ẹgbẹ́ kọọkan ṣàfihàn treatment, ẹ̀rí àti ìparí. Ẹlẹgbẹ́ béèrè ìbéèrè ẹ̀rí kan, kí wọ́n sì daba ìmúdára kan.",diy:"Parí Seed Germination Investigation Poster: ÌBÉÈRÈ → ÀSỌTẸ́LẸ̀ → Ọ̀NÀ → DATA → ÌPARÍ → ÌMÚDÁRA.",aiLayer:"Ìṣọ̀kan — ìjẹ́rìí àti ìrònú: fi ìparí ẹgbẹ́ wé pẹ̀lú ìparí AI, kí o sì pa ìsọ̀rọ̀ tí data gidi ń ṣe atilẹyin mọ́.",enterprise:"So ọgbọ́n germination mọ́ nursery pẹ̀lú ojúṣe, crop establishment àti seed-quality; ọmọ ń kọ́ erongba náà láìjẹ́ pé a ní kí wọ́n ta ọja.",quiz:[{question:"Ìparí tó lagbara yẹ kí ó lo…",options:["Ẹ̀rí tí a kọ sílẹ̀","Gboju nìkan","Ìlérí tita","Itan tí kò jọmọ́"],answer:0},{question:"Ṣé ìdánwò kékeré kan jẹ́rìí pé gbogbo irúgbìn ní gbogbo ibi yóò huwa kanna?",options:["Rárá","Bẹ́ẹ̀ ni nigbagbogbo","Tí AI bá sọ bẹ́ẹ̀ nìkan","Tí gbogbo irúgbìn bá germinate nìkan"],answer:0},{question:"Èwo ni ìmúdára tó bójú mu?",options:["Tun ìdánwò ṣe pẹ̀lú àkọsílẹ̀ tó péye","Pa data tí a kò retí rẹ́","Yí ipo púpọ̀ padà láìkọ sílẹ̀","Sọ abajade dájú"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Kí ni germination?",options:["Ìbẹ̀rẹ̀ ìdagbasoke láti inú irúgbìn","Ikórè irugbin tó dàgbà","Apoti oúnjẹ","Gbigba batiri agbara"],answer:0},{question:"Ipo wo ni ó sábà nílò fún germination?",options:["Ọrinrin tó yẹ","Kunrin","Plastiki","Rísítì tita"],answer:0},{question:"Kí ló dé tí irúgbìn tó ń germinate fi nílò afẹ́fẹ́?",options:["Sẹẹli alààyè nílò oxygen fún respiration","Afẹ́fẹ́ ń sọ irúgbìn di irin","Afẹ́fẹ́ ń rọ́pò embryo","Kò ṣe pàtàkì"],answer:0},{question:"Kí ni ń mú germination comparison jẹ́ fair síi?",options:["Yí ipo pataki kan padà","Yí gbogbo ohun padà","Lo iru irúgbìn àti ipo oríṣìíríṣìí papọ̀","Yọ aami kúrò"],answer:0},{question:"Kí ni ẹ̀rí tó dáa?",options:["Ìṣàkíyèsí àti kíkà tó ní ọjọ́ láti inú ìdánwò","Ahọ́n","Àsọtẹ́lẹ̀ tí a tún kọ gẹ́gẹ́ bí abajade","Fọ́tò tí kò jọmọ́"],answer:0},{question:"Tí AI bá fún ọ ní ìparí tó yàtọ̀ sí data rẹ, kí ni ká ṣe?",options:["Ṣàyẹ̀wò data àti ìrònú kí o tó gba AI","Pa data rẹ́","Gbẹ́kẹ̀lé AI nigbagbogbo","Dá nọ́mbà tuntun sílẹ̀"],answer:0},{question:"Kí ló dé tí germination tó dáa fi ṣe pàtàkì fún agbẹ?",options:["Ó lè dín ìsòfò irúgbìn àti orísun kù","Ó jẹ́rìí èrè","Ó yọ gbogbo ewu oko kúrò","Ó rọ́pò ìtọju irugbin"],answer:0},{question:"Ìsọ̀rọ̀ wo ni ó ní ojúṣe?",options:["Ìdánwò kékeré wa ṣe atilẹyin ìparí yìí lábẹ́ ipo tí a dán wò","Ìdánwò wa jẹ́rìí pé gbogbo irúgbìn ní gbogbo ibi yóò huwa kanna","AI jẹ́rìí abajade","Àkọsílẹ̀ kò ṣe pàtàkì"],answer:0}],theory:["Ṣàlàyé ipo mẹ́ta tí irúgbìn sábà nílò fún germination àti idi tí ipo tí kò yẹ fi lè dín àṣeyọrí kù.","Ṣàlàyé ipa awọ irúgbìn àti embryo ní ọ̀nà rọrùn.","Ṣàlàyé bí o ṣe lè ṣe germination comparison treatment méjì ní fair.","Ṣàlàyé bí kíkà àti ìṣàkíyèsí ṣe ń ràn ọ lọwọ láti mọ treatment tó dáa jù.","Fún àpẹẹrẹ kan bí AI ṣe lè ràn ìwádìí germination lọwọ, kí o sì ṣàlàyé bí o ṣe máa jẹ́rìí abajade rẹ̀."],practical:"Ṣètò tàbí ṣàfihàn ìwádìí germination treatment méjì pẹ̀lú iru irúgbìn kanna àti iye ìbẹ̀rẹ̀ kanna. Ṣàlàyé ipo tí a yí padà, fi aami tó péye àti mímu ní ààbò hàn, ṣàfihàn ìṣàkíyèsí mẹ́ta tó ní ọjọ́ o kere tan, fi ẹ̀rí wé, kí o sì sọ ìparí kan tó ní ìdí àti ìmúdára kan."},
  evidence:["Káàdì ìṣàkíyèsí irúgbìn mẹ́fà","Awoṣe apá irúgbìn","Kẹ̀kẹ́ aini germination","Ìwé gbero fair test","Treatment germination méjì pẹ̀lú aami","Germination log ìwọlé mẹ́ta","Seed Germination Investigation Poster","Àkọsílẹ̀ ìdánwò iṣẹ́ olùkọ́"],
  passport:["K: ṣàlàyé apá irúgbìn àti ipo ìpilẹ̀ germination","P: ṣètò àti tọ́jú germination comparison rọrùn pẹ̀lú ààbò","D: ka, wọn, kọ sílẹ̀ àti jẹ́rìí ìtumọ̀ AI pẹ̀lú ẹ̀rí","S: tẹ̀lé ìmọ́tótó, ìṣàkóso omi tó dà àti òfin mímu irúgbìn ní ààbò","E: so didara germination àti lílo orísun dáadáa mọ́ nursery àti crop production pẹ̀lú ojúṣe","L: ṣe àsọtẹ́lẹ̀, ṣiṣẹ́ pọ̀, ṣàfihàn ẹ̀rí àti daba ìmúdára"],
  trainerNotes:["Yan irúgbìn tó mọ̀mọ́, tí kò ní treatment kemika, tí ó sì máa ń germinate kíákíá bí ó bá ṣeé ṣe.","Bẹ̀rẹ̀ iṣẹ́ ọwọ́ kutukutu tó kí ìṣàkíyèsí ọjọ́ púpọ̀ lè wà; akoko germination yàtọ̀ gẹ́gẹ́ bí irúgbìn àti ipo.","Má pe àṣeyọrí ní gbogbo irúgbìn germinate; abajade tí a kò retí jẹ́ ẹ̀rí tó wúlò.","Lo ẹnu, àwòrán, ohun tí a lè fọwọ́ kan àti ìrànlọ́wọ́ ẹlẹgbẹ́ fún ẹni tó ṣì ń kọ́ kíkà.","Yà kemika seed treatment ewu kúrò nínú iṣẹ́ ọmọ.","Jẹ́ kí ìjíròrò enterprise dojukọ didara, ìyelori àti stewardship, kì í ṣe tita ọmọ tàbí ìlérí owo-wiwọle."],
  remediation:"Lo irúgbìn ńlá kan tí a mọ̀, àwòrán títẹ̀lé àti ìfiwéra moist-versus-dry kan. Tun àtẹ̀le irúgbìn → gbongbo jáde → shoot dagba ṣe, kí ẹ sì tún tábìlì data kọ pọ̀ pẹ̀lú aami tàbí tally.",
  extension:"Akẹ́kọ̀ọ́ tún ìdánwò ṣe pẹ̀lú iru irúgbìn kejì tó ní ààbò tàbí ipo míì tí a ṣàkóso, kí o ṣe germination percentage rọrùn pẹ̀lú olùkọ́, kí o sì fiwé bóyá ìparí àkọ́kọ́ ṣi dúró.",
  imagePrompts:["Àwọn ọmọ Africa ọdún 8–11 nínú ibi ẹ̀kọ́ GreenSkills lábẹ́ amọ̀nà ń ṣètò ago germination ẹ̀wà tàbí cowpea, ohun èlò mọ́, aami láìsí ọrọ̀ tí a lè ka, ìwé àkọsílẹ̀, kó gbogbo ènìyàn sí, ìmọ́lẹ̀ adayeba, àwọ̀ LIFEWS aláwọ̀-ewe igbo àti goolu.","Àwòrán sáyẹ́nsì ọmọde tó fi irúgbìn ẹ̀wà hàn láti irúgbìn pípé sí gbongbo tó jáde, shoot kékeré àti ewé àkọ́kọ́, abẹ́lẹ̀ funfun, àtẹ̀le tó péye, kò sí aami tàbí ọrọ̀.","Akẹ́kọ̀ọ́ Africa photorealistic ń fi treatment germination méjì wé, ń kọ iye pẹ̀lú ruula àti ìwé àkọsílẹ̀ nígbà tí olùkọ́ ń bojú tó, ibi ẹ̀kọ́ ọgbà tó dojukọ ẹ̀rí, kò sí ọrọ̀ tí a lè ka."]
};