import type { PF01Module } from "./pf-01";

export const pf01Ig: PF01Module = {
  code:"PF-01", title:"Nnọọ na Mmụta na Ohere", level:"Pathways Foundation", age:"Ihe dịka afọ 8–11; nhọpụta kwesịrị ịdabere na nyocha onye mmụta, ọ bụghị afọ naanị.", duration:"Nkuzi nduzi 6 tinyere oge omume na nyocha", fieldworkHours:2,
  bigQuestion:"Kedu ka mmụta ga-esi nyere m aka ịghọta onwe m, obodo m na ohere ndị gbara m gburugburu?",
  whyItMatters:"Ọtụtụ ndị na-amalite Pathways enwetala mmụta e kwụsịrị, pere mpe ma ọ bụ enweghị mmụta ụlọ akwụkwọ. Modul a na-ewulite mmetụta ịbụ akụkụ nke otu, obi ike, usoro mmụta dị nchebe na njikọ dị n’etiti mmụta, ndụ kwa ụbọchị na ohere ọdịnihu.",
  outcomes:["Kọwaa ihe LIFEWS Pathways bụ ma kwuo ihe kpatara gị ji chọọ ịmụ.","Mata ike gị, ihe na-amasị gị na ebe ị chọrọ ito.","Mata ndị mmadụ, ebe na omume dị nchebe n’ebe mmụta.","Debe otu ebumnuche mmụta dị mfe ma mata usoro iji ruo ya.","Ghọta na nka bara uru nwere ike ịmepụta uru nye ezinụlọ na obodo.","Jiri ọrụ dijitalụ ma ọ bụ AI n’okpuru nduzi okenye n’ụzọ kwesịrị ekwesị."],
  vocabulary:["mmụta","ohere","ebumnuche","ike","nka","obodo","nhọrọ","omume","akaebe","ọrụ"],
  materials:["akwụkwọ ma ọ bụ workbook","pensụl/crayon","kaadị foto","maapụ foto obodo","template kaadị ebumnuche","tablet/ekwentị a na-ekekọrịta n’okpuru nlekọta onye nkuzi"],
  safety:["Ekwela ka a manye onye mmụta ikwu ahụmahụ mwute.","Jiri okwu na-adịghị eleda onye mmụta anya banyere akụkọ ụlọ akwụkwọ gara aga.","Onye nkuzi na-elekọta ngwaọrụ dijitalụ; onye mmụta ekwesịghị ịkekọrịta ozi nzuzo na AI.","Ọrụ otu na abụọ ga-agụnye ụmụ agbọghọ, ndị nwere nkwarụ na ndị ka na-amụta ịgụ na ide."],
  lessons:[
    {id:"PF-01-L1",title:"Enwere M Ebe N’ebe A",objective:"Kọwaa Pathways dịka ebe dị nchebe iji mụta, mee omume ma kwadebe maka ohere n’ọdịnihu.",teaching:["Mmụta nwere ike ime na klas, ubi, ụlọ, workshop na obodo.","Onye mmụta nwere ike ịmalite n’ebe dị iche; ebe ị malitere anaghị ekpebi ihe ị ga-enwe ike ime n’ọdịnihu.","Pathways na-ejikọta mmụta na nka aka na ohere mmegharị."],activity:"Mepụta nkwekọrịta klas site n’iji foto ma ọ bụ okwu maka nkwanye ùgwù, ige ntị, isonye, nchekwa na nlekọta.",diy:"Mee kaadị ‘Abụ m onye mmụta’ nwere eserese ma ọ bụ akara nke ihe ị chọrọ ịmụ.",aiLayer:"AI Layer 1 — Ịmata: onye nkuzi gosipụta ngwaọrụ nwere ike ịza ajụjụ ma ọ bụ hazie ozi ma kọwaa na AI bụ ngwa, ọ bụghị mmadụ ma ọ bụ onye nwere ikike ikpeazụ.",enterprise:"Ịmepụta uru na-amalite site n’idozi nsogbu bara uru. Ndị mmụta kpọọ otu ọrụ enyemaka a na-eme n’obodo ha.",quiz:[{question:"Kedu omume na-enyere ebe mmụta aka ịdị nchebe?",options:["Ige ntị n’ụzọ nkwanye ùgwù","Ịchị ọchị maka mmejọ","Izobe ihe","Igbochi ndị ọzọ ikwu okwu"],answer:0},{question:"Ebee ka mmụta nwere ike ime?",options:["N’ụlọ akwụkwọ naanị","N’ịntanet naanị","N’ọtụtụ ebe","N’ọrụ naanị"],answer:2},{question:"Gịnị ka i kwesịrị ime ma ọ bụrụ na ị ghọtaghị?",options:["Mee ka ị ghọtara","Rịọ enyemaka","Pụọ","Depụta ihe n’enweghị echiche"],answer:1}]},
    {id:"PF-01-L2",title:"Ike na Mmasị M",objective:"Mata ma ọ dịkarịa ala ike ma ọ bụ mmasị abụọ ma kọwaa otú omume si eme ka ha too.",teaching:["Ike bụ ihe anyị nwere ike ime, ụzọ anyị si enyere ndị ọzọ na àgwà ọma anyị na-egosi.","Mmasị bụ ihe anyị na-enwe mmasị ịmụ ma ọ bụ ime.","Nka na-eto site n’omume dị nchebe, nzaghachi na ndidi."],activity:"Gbaa gburugburu ike: họrọ kaadị foto nke ọrụ ị na-enwe mmasị na ya ma ọ bụ ị na-eme nke ọma, kọwaa otu nhọrọ nye onye ibe gị.",diy:"Mepụta ọta akụkụ atọ: Enwere m ike…, Ihe na-amasị m…, Achọrọ m imezi….",aiLayer:"AI Layer 2 — Mmekọrịta nduzi: tụnyere ihe mmadụ hụrụ gbasara ike na ndepụta dị mfe AI mepụtara; kparịta ihe kpatara mmadụ ji kwesị ikpebi ihe ziri ezi.",enterprise:"Ike dị iche iche nwere ike ghọọ nka bara uru. Jikọọ ịtụ ihe, ịkụ ihe, ịrụzi, ịkọwa ma ọ bụ ịhazi na mkpa obodo.",quiz:[{question:"Ike bụ…",options:["ihe bara uru ị nwere ike ịzụlite","ntaramahụhụ","ụlọ akwụkwọ","ọnụahịa"],answer:0},{question:"Nka na-akawanye mma site na…",options:["omume","izobe","iche naanị","ịkwụsị"],answer:0},{question:"Kedu okwu na-egosi echiche uto?",options:["Enweghị m ike ịmụ","Enwere m ike imezi site n’omume","Ndị ọzọ naanị nwere nka","Mmejọ na-akwụsị mmụta"],answer:1}]},
    {id:"PF-01-L3",title:"Mmụta Gbara M Gọdụ",objective:"Mata ohere mmụta kwa ụbọchị n’ihe oriri, mmiri, ume, ụlọ na obodo.",teaching:["Ịgụ akara, ịgụta ihe, ịtụ mmiri na ile osisi anya bụ ụdị mmụta.","Usoro nri-ume-mmiri bụ akụkụ ndụ kwa ụbọchị.","Nleba anya na-enyere anyị aka ịjụ ajụjụ ka mma."],activity:"Gaa ije mmụta ma mata ihe ise gụnyere ịgụ, ịgụta, ịtụ, ile anya ma ọ bụ ime mkpebi.",diy:"See maapụ ‘mmụta gbara m gburugburu’ nwere ma ọ dịkarịa ala ebe anọ na nka a na-eji n’ebe ọ bụla.",aiLayer:"AI Layer 3 — Nhazi: kewaa kaadị foto n’otu nri, ume, mmiri ma ọ bụ karịa otu; onye nkuzi nwere ike igosi nhazi AI ka ndị mmụta nyochaa ya.",enterprise:"Mata otu mkpa obodo na otu nka nwere ike inye aka, n’enweghị ịmanye ụmụaka ire ihe.",quiz:[{question:"Ịtụ mmiri na-eji…",options:["ọnụọgụ","ụra","ndị jụụ","chi ọma"],answer:0},{question:"Nleba anya pụtara…",options:["ile ihe anya nke ọma","ichefu","izobe","ire ahịa"],answer:0},{question:"Kedu nke nwere ike ịbụ ọrụ mmụta?",options:["Ịgụ akara ahịa","Nnwale naanị","Homework naanị","Ọ dịghị"],answer:0}]},
    {id:"PF-01-L4",title:"Ebumnuche na Obere Usoro",objective:"Debe otu ebumnuche mmụta doro anya ma kewaa ya n’usoro enwere ike ime.",teaching:["Ebumnuche na-akọwa ihe anyị chọrọ iru.","A pụrụ kewaa ebumnuche ọma n’obere ọrụ.","Akaebe na-enyere anyị aka ịhụ ọganihu."],activity:"Gbanwee ọchịchọ dịka ‘Achọrọ m ịgụ nke ọma’ ka ọ bụrụ usoro omume atọ enwere ike ịhụ.",diy:"Mee ladder ebumnuche ụbọchị asaa nwere otu obere ọrụ, otu onye enyemaka na ụzọ igosi ọganihu.",aiLayer:"AI Layer 4 — Prompt nwere ókè: onye nkuzi gosipụta ịrịọ AI echiche omume atọ; ndị mmụta kpebie nke dị nchebe, ezi uche na uru.",enterprise:"Nhazi bara uru na mmụta na azụmahịa: ebumnuche → akụ → omume → nyochaa nsonaazụ.",quiz:[{question:"Ebumnuche bara uru kwesịrị inwe…",options:["usoro doro anya","enweghị omume","enweghị ụzọ nyochaa","ọchịchọ naanị"],answer:0},{question:"Akaebe ọganihu nwere ike ịbụ…",options:["peeji omume emechara","asịrị","ọ dịghị ihe","ọrụ onye ọzọ"],answer:0},{question:"Ọ bụrụ na usoro siri ike, i kwesịrị…",options:["kewaa ya n’obere usoro","kwụsị ozugbo","zobe ya","ta onye ọzọ ụta"],answer:0}]},
    {id:"PF-01-L5",title:"Nhọrọ Dị Nchebe na Nke Ziri Ezi",objective:"Mata nhọrọ dị nchebe na mmụta, dijitalụ na obodo ma mara mgbe ị ga-achọ enyemaka okenye a tụkwasịrị obi.",teaching:["Nchekwa gụnyere ahụ, mmetụta uche na dijitalụ.","E kwesịghị ịkekọrịta ozi nzuzo na ndị a na-amaghị ma ọ bụ ngwa AI.","Okenye a tụkwasịrị obi nwere ike inye aka mgbe ihe yiri ihe ize ndụ ma ọ bụ mgbagwoju anya."],activity:"Kewaa kaadị ọnọdụ n’otu DỊ NCHEBE, JỤỌ OKENYE, na Ọ DỊGHỊ NCHEBE, wee kparịta ihe kpatara ya.",diy:"Mepụta ‘aka enyemaka’: otu onye ma ọ bụ ọrụ nchekwa n’aka mkpịsị aka ọ bụla.",aiLayer:"AI Layer 5 — Idozi nsogbu n’ụzọ ziri ezi: nyochaa azịza AI e chepụtara ma mata ozi kwesịrị ka onye nkuzi ma ọ bụ okenye a tụkwasịrị obi nyochaa.",enterprise:"Ọrụ kwesịrị ekwesị pụtara eziokwu, nchekwa, ilekọta akụ na omume ziri ezi n’ebe ndị ọzọ nọ.",quiz:[{question:"Ị kwesịrị inye AI adreesị ụlọ gị?",options:["Mba","Mgbe niile","Maka egwuregwu naanị","Mgbe ọ bụla a jụrụ"],answer:0},{question:"Ọ bụrụ na ihe yiri ihe ize ndụ, usoro ọma bụ…",options:["gwa okenye a tụkwasịrị obi","zobe ya","soro onye ịmaghị","kekọrịta ozi nzuzo"],answer:0},{question:"Ọrụ kwesịrị ekwesị gụnyere…",options:["eziokwu na nchekwa","imebi ngwa","ịghọ aghụghọ","iwepụ ndị ọzọ"],answer:0}]},
    {id:"PF-01-L6",title:"Maapụ Mmụta na Ohere M",objective:"Jikọta ike, ebumnuche, ohere obodo na ndị nkwado n’ime maapụ mmụta nke gị.",teaching:["Pathway na-ejikọta ebe anyị nọ ugbu a na usoro ndị nwere ike iso.","Ndị mmadụ nwere ike inwe ụzọ dị iche ma gbanwee ebumnuche ka ha na-amụta.","Nkwado, omume na akaebe na-enyere onye mmụta aka ịga n’ihu."],activity:"Nyochaa modul ahụ ma họrọ otu ike, otu ebumnuche, otu nka aka, otu onye enyemaka na otu usoro ọzọ.",diy:"Mepụta ma gosipụta maapụ: MỤ → IKE → EBUMNUCHE → OMUME → ONYE ENYEMAKA → USORO ỌZỌ.",aiLayer:"Njikọta: onye nkuzi nwere ike iji AI tụpụta ihe atụ nke usoro ọzọ; onye mmụta na onye nkuzi họrọ naanị nke kwekọrọ na afọ, dị nchebe ma kwe omume n’obodo.",enterprise:"Jikọọ ike na imepụta uru: inyere aka, imepụta, ịkụ ihe, ilekọta, ịkọwa ma ọ bụ ịhazi—n’enweghị ime ụmụaka ndị ọrụ azụmahịa.",quiz:[{question:"Pathway bụ…",options:["ụzọ site ugbu a ruo usoro ọzọ","ntaramahụhụ","otu ọrụ mgbe niile","ihe nzuzo"],answer:0},{question:"Ònye kwesịrị ịhọrọ ebumnuche gị na gị?",options:["gị na nkwado kwesịrị ekwesị","onye ịmaghị","AI naanị","ọ dịghị onye"],answer:0},{question:"Gịnị kwesịrị ịdị na maapụ ohere?",options:["ike na usoro ọzọ","password nzuzo","ntuziaka ize ndụ","njirimara onye ọzọ"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Gịnị bụ otu ebumnuche Pathways?",options:["Kwado mmụta na mgbanwe","Kwụsị mmụta aka","Dochie mkpebi ezinụlọ niile","Mee ka onye ọ bụla soro otu ụzọ"],answer:0},{question:"Gịnị na-enyere nka aka ịka mma?",options:["Omume na nzaghachi","Ịkwụsị","Izobe mmejọ","Izere ajụjụ"],answer:0},{question:"Ebumnuche mmụta ọma kwesịrị ịbụ…",options:["doro anya ma nwee ike ime","enweghị ike nyochaa","nke onye ọzọ","ihe nzuzo"],answer:0},{question:"Kedu omume dijitalụ dị nchebe?",options:["Chekwaa ozi nzuzo","Kekọrịta password","Nye onye ịmaghị adreesị","Kwere azịza AI niile"],answer:0},{question:"Gịnị bụ akaebe?",options:["Ihe na-egosi ihe i mere ma ọ bụ mụtara","echiche","asịrị","ntaramahụhụ"],answer:0},{question:"Imepụta uru nwere ike pụta…",options:["idozi nsogbu bara uru","imerụ ndị ọzọ","imefusị akụ","izobe nka"],answer:0},{question:"Ọ bụrụ na azịza AI yiri ihe na-ezighị ezi, i kwesịrị…",options:["nyochaa ya na isi iyi a pụrụ ịtụkwasị obi ma ọ bụ onye nkuzi","nabata ya mgbe niile","kesaa ya ozugbo","tinye ozi nzuzo"],answer:0},{question:"Kedu ihe kacha kọwaa ụzọ mmụta?",options:["Usoro enwere ike ime iji ruo ebumnuche","Otu ụzọ onye ọ bụla ga-eso","Nnwale ụlọ akwụkwọ naanị","Password"],answer:0}],theory:["Kọwaa ihe abụọ ịchọrọ ịmụ na ihe kpatara ha ji dị mkpa.","Kpọọ ike abụọ i nwere na otu ụzọ ị ga-esi mee omume nke ọ bụla.","Kọwaa iwu atọ na-eme ka ebe mmụta dị nchebe ma nwee nkwanye ùgwù.","Kọwaa otu mkpa obodo na nka nwere ike inye aka.","Kọwaa ihe kpatara e ji kwesị ịlele ozi dị mkpa AI mepụtara na onye ma ọ bụ isi iyi a pụrụ ịtụkwasị obi."],practical:"Gosipụta Maapụ Mmụta na Ohere nwere otu ike nke gị, otu ebumnuche mmụta, ma ọ dịkarịa ala usoro atọ, otu nka aka, otu onye enyemaka a tụkwasịrị obi, otu akaebe na otu ohere ọzọ kwekọrọ na afọ."},
  evidence:["Ọta ike emechara","Ladder ebumnuche ụbọchị asaa","Aka enyemaka","Maapụ mmụta gbara m gburugburu","Maapụ Mmụta na Ohere ikpeazụ","Ndekọ nleba anya onye nkuzi"],
  passport:["K: kọwaa mmụta, ebumnuche na ohere","P: mepụta ma gosipụta maapụ mmụta bara uru","D: gosi ojiji AI n’okpuru nduzi na nchedo nzuzo","S: mata nhọrọ dị nchebe na enyemaka a tụkwasịrị obi","E: ghọta nka dịka ụzọ isi mepụta uru n’obodo","L: debe ebumnuche, kọwaa ike ma sonye n’ụzọ nkwanye ùgwù"],
  trainerNotes:["Jiri okwu ọnụ, foto na ngosipụta maka ndị ka na-amụta ịgụ na ide.","Ejila akụkọ ụlọ akwụkwọ gara aga tụnyere ndị mmụta.","Jiri ihe atụ na ọrụ obodo mana ebugharịla ụmụaka n’ọrụ ize ndụ ma ọ bụ nke afọ ha na-ekwesịghị.","Mee ka ụmụ agbọghọ na ụmụ nwoke gbanwee ọrụ ndu, ihe na ngosi.","Ọrụ AI bụ nhọrọ ebe ngwaọrụ ma ọ bụ njikọ adịghị; kụziere echiche ahụ n’enweghị ịntanet."],
  remediation:"Kụziere echiche ọzọ site n’usoro foto, role play na nhazi ebumnuche otu-na-otu. Belata ibu ide ma debe otu ebumnuche nka.",
  extension:"Onye mmụta jụọ okenye a tụkwasịrị obi banyere otu nka ọ mụtara mgbe ọ dị obere, wee tinye ụzọ ahụ na maapụ ohere obodo.",
  imagePrompts:[]
};