import type { PF01Module } from "./pf-01";

type PF07Module = Omit<PF01Module,"code"> & { code:"PF-07" };

export const pf07Ig: PF07Module = {
  code:"PF-07",
  title:"Nri Si Ebe Ọ Bịa",
  level:"Pathways Foundation",
  age:"Ihe dị ka afọ 8–11; jiri ihe atụ dabara na nri obodo n'enweghị ileda ezinụlọ ma ọ bụ omenala ọ bụla anya.",
  duration:"Nkuzi ndu 6 tinyere map nke mmalite nri, nlele bara uru na nyocha",
  fieldworkHours:3,
  bigQuestion:"Ebee ka nri anyị si abịa, gịnị na-eme tupu o rute anyị, ma olee otú anyị ga-esi mee mkpebi nri nwere ọrụ site n'iji ihe akaebe?",
  whyItMatters:"Nri bụ nsonaazụ usoro ndu, mmekọrịta mmadụ na teknụzụ jikọrọ ọnụ. Modul a na-enyere ụmụakwụkwọ ịchọpụta ebe nri si malite, ịmata usoro si n'ubi ruo n'efere, na ịghọta otú nhazi, njem na nchekwa si emetụta uru, ịdị mma na nchekwa nri.",
  outcomes:[
    "Jikọta nri a na-ahụkarị na mmalite sitere n'osisi, anụmanụ ma ọ bụ ngwakọta.",
    "Mata ebe a na-emepụta nri dịka ubi, ogige, ebe anụmanụ na ebe nhazi nri.",
    "Kọwaa usoro dị mfe site n'ubi ruo n'efere maka opekata mpe nri obodo atọ.",
    "Kewaa ihe oriri mbụ na ngwaahịa nri a haziri.",
    "Ghọta na njikwa, njem, nchekwa na nkwadebe na-emetụta ịdị mma na nchekwa.",
    "Mepụta ma kọwaa njem otu nri site n'iji nlele na ihe akaebe.",
    "Nyochaa ozi AI ma ọ bụ dijitalụ gbasara mmalite nri site n'iji akara, onye maara ihe, nlele ma ọ bụ isi iyi a pụrụ ịtụkwasị obi.",
    "Jikọta ihe ọmụma usoro nri na ọrụ ubi, nhazi, njem, ire ahịa na ọrụ n'ụzọ kwekọrọ n'afọ ụmụaka."
  ],
  vocabulary:["nri","ihe oriri","ihe ubi","anụmanụ","ubi","ogige","owuwe ihe ubi","raw","nhazi","njem","nchekwa","ahịa","nkwadebe","mmalite","njem nri","ihe akaebe"],
  materials:["foto ma ọ bụ ihe atụ nke nri obodo","kaadị mmalite nri","akwụkwọ na pensụl/marker","ngwugwu nri dị ọcha nke tọgbọrọ chakoo","kaadị usoro si n'ubi ruo n'efere","map obodo ma ọ bụ eserese","ngwa dijitalụ onye nkuzi na-achịkwa ma ọ bụrụ na ọ dị"],
  safety:[
    "A naghị achọ ka ụmụakwụkwọ detụ nri n'ọnụ n'oge modul a.",
    "Jiri foto ma ọ bụ ihe dị ọcha emechiri emechi maka ọrụ nhazi.",
    "Nyochaa ihe gbasara allergy tupu ụmụakwụkwọ metụ nri ezigbo aka.",
    "Ekwela ka ụmụaka banye ebe igwe na-arụ ọrụ, kichin nnukwu ọrụ ma ọ bụ ụzọ ahịa n'enweghị nlekọta okenye.",
    "A ga-enyocha ndụmọdụ nchekwa nri sitere na AI ma ọ bụ social media na isi iyi kwesịrị ntụkwasị obi.",
    "Elela ezinụlọ ma ọ bụ omenala anya site n'ụdị nri ha na-eri."
  ],
  lessons:[
    {id:"PF-07-L1",title:"Nri Nwere Mmalite",objective:"Jikọta nri a na-ahụkarị na mmalite osisi, anụmanụ ma ọ bụ ngwakọta.",teaching:["Ọtụtụ nri na-amalite site n'osisi, anụmanụ ma ọ bụ ha abụọ.","Nri nwere ike gbanwee ọdịdị mgbe a haziri ma ọ bụ kwadebe ya.","Ịma ebe nri si abịa na-enyere anyị ịghọta ugbo, nri na-edozi ahụ, nchekwa na ọrụ."],activity:"Kewaa kaadị nri n'ime OSISI, ANỤMANỤ na NGWAKỌTA, kọwaa otu ihe kpatara nhọrọ ọ bụla.",diy:"Mepụta Bọdụ Mmalite Nri nwere opekata mpe nri asatọ na akụ na-egosi ebe ha si.",aiLayer:"AI Layer 1 — Nchọpụta: onye nkuzi jiri AI hazie nri ụfọdụ, ụmụakwụkwọ wee nyochaa azịza ya site na akara ma ọ bụ ihe ọmụma obodo.",enterprise:"Ndị ọrụ ugbo, ndị na-azụ anụmanụ, ndị na-akụ azụ na ndị na-ahazi nri na-emepụta uru n'ọtụtụ ebe n'usoro nri.",quiz:[{question:"Ọka si n'…",options:["Osisi","Igwe","Batrị","Nkume"],answer:0},{question:"Mmiri ara ehi si n'…",options:["Anụmanụ","Nkume","Plastik","Ala naanị"],answer:0},{question:"Gịnị mere anyị ji amụta mmalite nri?",options:["Iji ghọta otú e si emepụta ma jikwaa nri","Iji mụta agba ngwugwu naanị","Iji kwụsị ịjụ ajụjụ","Iji gosi omenala otu ka mma"],answer:0}]},
    {id:"PF-07-L2",title:"Ebe A Na-emepụta Nri",objective:"Mata ebe a na-akụ, na-azụ, na-akụ azụ ma ọ bụ na-ahazi nri.",teaching:["Nri nwere ike isi n'ubi, ogige, orchard, ebe a na-azụ anụmanụ, azụ na ebe ndị ọzọ.","Nri dị iche iche chọrọ ihe onwunwe na nlekọta dị iche.","Ebe a na-emepụta nri jikọtara na mmiri, ala, ume, ọrụ na ọnọdụ ihu igwe."],activity:"Jikọta nri na ebe a ga-emepụta ya site na map foto obodo.",diy:"See map nke isi mmalite nri obodo nwere opekata mpe ebe ise na nri ha.",aiLayer:"AI Layer 2 — Ntụnyere: tụnyere ndepụta AI nke ebe a ga-emepụta otu nri na ihe ndị dị n'ezie n'obodo.",enterprise:"Mmepụta nri na-akwado ọrụ ugbo, irrigation, nlekọta anụmanụ, njem na teknụzụ.",quiz:[{question:"Kedu nke bụ ebe mmepụta nri?",options:["Ogige","Ihu ihuenyo password","Igbe akpụkpọ ụkwụ","Ọkụ okporo ụzọ"],answer:0},{question:"Nri niile na-eji otu usoro mmepụta?",options:["Mba","Ee mgbe niile","Naanị n'obodo ukwu","Naanị mgbe a kpakọrọ ya"],answer:0},{question:"Mmepụta nri na-adaberekarị na…",options:["Ihe dịka mmiri na ala","Ọ dịghị ihe","Mgbasa ozi naanị","Ngwugwu naanị"],answer:0}]},
    {id:"PF-07-L3",title:"Site n'Ihe Oriri Mbụ Ruo Ngwaahịa",objective:"Kewaa ihe oriri mbụ na nri a haziri.",teaching:["Ihe oriri mbụ bụ ihe tupu nhazi buru ibu.","Nhazi nwere ike ịgụnye ịsa, ịkpụ, ịkpọ nkụ, ịkụ nri, isi nri, fermenting, ịgwakọta ma ọ bụ ịkwakọba.","Nhazi nwere ike ime ka nri dị mfe iji ma chekwaa, mana nchekwa na ịdị ọcha dị mkpa."],activity:"Mepụta ụzọ abụọ dịka ọka → ntụ ọka, cassava → garri, tomato → sauce ma ọ bụ mmiri ara ehi → yoghurt.",diy:"Mepụta tebụl: IHE MBỤ → USORO → NGWAAHỊA maka nri ise.",aiLayer:"AI Layer 3 — Nhazi usoro: lelee usoro AI nyere, mata ihe ziri ezi, ihe efu ma ọ bụ ihe nwere ihe ize ndụ.",enterprise:"Nhazi na-agbakwunye uru ma ọ bụrụ na e nwere ịdị ọcha, njikwa ịdị mma na ozi ziri ezi.",quiz:[{question:"Kedu nke bụ usoro nhazi nri?",options:["Ịkụ nri/grinding","Ịkọ nkọ","Ịzo akara","Ịhapụ ịdị ọcha"],answer:0},{question:"Ihe oriri mbụ nwere ike ịghọ…",options:["Ngwaahịa a haziri","Password","Ume ọkụ naanị","Tebụl ụlọ akwụkwọ"],answer:0},{question:"Nhazi kwesịrị ịgụnye…",options:["Njikwa nchekwa na ịdị mma","Shortcut na-adịghị mma","Enweghị ndekọ","Ihe a na-amaghị ama"],answer:0}]},
    {id:"PF-07-L4",title:"Njem Nri",objective:"Hazie usoro nri si na mmepụta ruo mgbe e riri ya.",teaching:["Njem nri nwere ike ịgụnye mmepụta, owuwe ihe ubi, njikwa, nhazi, njem, nchekwa, ire ma ọ bụ nkesa, nkwadebe na iri.","Nri niile anaghị eso otu ụzọ.","Usoro ọ bụla nwere ike imetụta ịdị mma, nchekwa, mkpofu na ọnụ ahịa."],activity:"Hazie kaadị usoro n'usoro kwesịrị ekwesị maka otu nri, tụnyere azịza otu ọzọ.",diy:"Mepụta Farm-to-Food Journey strip nwere opekata mpe usoro isii.",aiLayer:"AI Layer 4 — Systems mapping: tụnyere map ụmụakwụkwọ na ụzọ AI nyere, chọpụta ihe furu efu ma ọ bụ echiche na-enweghị ihe akaebe.",enterprise:"Ọrụ dị n'ụzọ nri gụnyere mmepụta, nhazi, njem, nchekwa, retail, food service na quality assurance.",quiz:[{question:"Tupu nri erute onye na-eri ya, ọ na-agakarị…",options:["N'ọtụtụ usoro jikọrọ ọnụ","Enweghị ihe na-eme","Mgbasa ozi naanị","Ngwugwu naanị"],answer:0},{question:"Nri niile na-agbaso otu njem?",options:["Mba","Ee","Naanị nri si mba ọzọ dị iche","Naanị ihe ọṅụṅụ dị iche"],answer:0},{question:"Gịnị mere usoro ndị a ji dị mkpa?",options:["Ha na-emetụta ịdị mma, nchekwa, mkpofu na ọnụ ahịa","Ha enweghị mmetụta","Ha na-agbanwe agba naanị","Ha na-ewepụ mkpa ịdị ọcha"],answer:0}]},
    {id:"PF-07-L5",title:"Njikwa, Nchekwa na Mkpofu",objective:"Mata omume na-echekwa nri ma belata mkpofu a pụrụ izere.",teaching:["Nri nwere ike ifu site na njikwa ọjọọ, mmebi, spoilage ma ọ bụ nchekwa na-adịghị mma.","Njikwa dị ọcha, nchekwa kwesịrị ekwesị na njem ọma na-echekwa ịdị mma.","Ibelata mkpofu na-echekwa mmiri, ume, ọrụ na ala ejiri mepụta nri."],activity:"Lelee foto nke njikwa nri ọma na ọjọọ, chọpụta ihe nwere ike ịkpata mmebi ma ọ bụ contamination.",diy:"Mepụta Food Care Checklist nwere omume ise maka otu nri.",aiLayer:"AI Layer 5 — Decision support: tụnyere ndụmọdụ nchekwa AI na omume onye nkuzi kwadoro; jụ ihe na-enweghị nkwenye nchekwa.",enterprise:"Ibelata spoilage na mmebi na-eme ka arụmọrụ na iji ihe onwunwe dị mma.",quiz:[{question:"Kedu ihe nwere ike belata mkpofu nri?",options:["Njikwa na nchekwa kwesịrị ekwesị","Mmebi ngwaahịa","Ịhapụ nri n'ebe na-adịghị mma","Ịghara ile spoilage anya"],answer:0},{question:"Gịnị mere mkpofu nri ji metụta mmiri na ume?",options:["E jiri ha mee mmepụta na njikwa","Nri nwere ọkụ eletrik","Ngwugwu na-emepụta ihe niile","Ọ naghị emetụta ihe"],answer:0},{question:"AI naanị kwesịrị ikpebi ma nri ka dị mma iri?",options:["Mba","Ee mgbe niile","Naanị ma foto doro anya","Naanị ma nri dị oke ọnụ"],answer:0}]},
    {id:"PF-07-L6",title:"Soro Otu Nri Site na Isi Ya Ruo Tebụl",objective:"Nyochaa ma gosipụta njem zuru ezu nke otu nri site n'ihe akaebe.",teaching:["Ịsoro nri pụtara ijikọ ngwaahịa na mmalite ya na usoro ọ gafere.","Ihe akaebe nwere ike ịbụ akara ngwugwu, nlele, ajụjụ ọnụ onye okenye tụkwasịrị obi ma ọ bụ isi iyi ziri ezi.","Ngosipụta siri ike na-ekewa ihe a maara na ihe a chere."],activity:"Otu ụmụakwụkwọ họrọ otu nri obodo ma wuo akụkọ site na isi ruo tebụl site na opekata mpe isi iyi abụọ.",diy:"Mechaa Food Journey Portfolio: MMALITE → MMỤPỤTA → OWUWE IHE UBI → NHazi → NJEM/NCHEKWA → NKWadebe → IRI.",aiLayer:"Integration — verification: jiri AI chọpụta otu ajụjụ ma ọ bụ usoro nwere ike ifu, nyochaa ya tupu itinye ya.",enterprise:"Mata opekata mpe ọrụ atọ ma ọ bụ ọrụ enyemaka jikọrọ na njem nri ahụ.",quiz:[{question:"Gịnị na-eme ka njem nri bụrụ nke a pụrụ ịtụkwasị obi?",options:["Ihe akaebe enyochara","Ịkọ nkọ","Ịkopi n'enweghị nyocha","Slogan ahịa"],answer:0},{question:"Kedu ihe a ga-eme ma usoro ahụ ejighị n'aka?",options:["Kwuo na ejighị n'aka ma nyochaa ya","Kwuo na ọ bụ eziokwu","Zoo ya","Mepụta ihe akaebe"],answer:0},{question:"Njem nri zuru ezu nwere ike igosi…",options:["Otú mmadụ, ihe onwunwe na usoro si jikọọ","Agba ngwugwu naanị","Ọnụ ahịa ikpeazụ naanị","Ọrụ otu onye naanị"],answer:0}]}
  ],
  finalAssessment:{
    mcq:[
      {question:"Osikapa si n'…",options:["Ihe ubi","Batrị","Plastik","Nkume"],answer:0},
      {question:"Kedu nke bụ nhazi nri?",options:["Ịkpọ nkụ ma ọ bụ ịkụ nri","Ịhapụ ịdị ọcha","Ịhapụ produce mebie","Ihichapụ ndekọ"],answer:0},
      {question:"Gịnị nwere ike ime n'etiti ubi na tebụl?",options:["Owuwe ihe ubi, njikwa, njem, nchekwa na nkwadebe","Ọ dịghị ihe","Mgbasa ozi naanị","Ịkwụ ụgwọ naanị"],answer:0},
      {question:"Gịnị mere nchekwa ọma ji dị mkpa?",options:["Ọ na-echekwa ịdị mma ma belata spoilage","Ọ na-eme ka nri ghara imebi ruo mgbe ebighị ebi","Ọ na-ewepụ ihe ize ndụ niile","Ọ na-anọchi ịdị ọcha"],answer:0},
      {question:"Kedu isi iyi nwere ike inyere ịchọpụta mmalite nri?",options:["Akara enyochara ma ọ bụ nkọwa onye na-emepụta","Asịrị","Post a na-enyochaghị","Ịkọ nkọ"],answer:0},
      {question:"Gịnị mere mkpofu nri ji nwekwara ike ịbụ mkpofu mmiri na ume?",options:["N'ihi na ejiri ha mee mmepụta na njikwa","N'ihi na nri nwere electricity","N'ihi na ngwugwu na-emepụta ihe niile","Ọ naghị emetụta ihe"],answer:0},
      {question:"Kedu ka a ga-esi jiri ozi AI gbasara mmalite nri?",options:["Dị ka aro a ga-enyocha","Dị ka eziokwu na-adịghị agbanwe agbanwe","Dochie nlele","Dochie ntuziaka nchekwa nri"],answer:0},
      {question:"Kedu nkọwa kacha mma maka food system?",options:["Ndị mmadụ, ihe onwunwe na ọrụ jikọrọ nri site na isi ruo ojiji","Ubi naanị","Ụlọ ahịa naanị","Kichin naanị"],answer:0}
    ],
    theory:["Họrọ otu nri a maara ma kọwaa ma isi mmalite ya bụ osisi, anụmanụ ma ọ bụ ngwakọta.","Kọwaa opekata mpe usoro isii n'ụzọ nri si n'isi ruo iri.","Kọwaa ụzọ abụọ njikwa ma ọ bụ nchekwa ọjọọ ga-esi bulie mkpofu nri.","Kọwaa otu nhazi si agbakwunye uru ma na-achọ nchekwa.","Kọwaa otu ị ga-esi nyochaa ikwu AI gbasara ebe nri si ma ọ bụ otú e si emepụta ya."],
    practical:"Họrọ otu nri a maara ma wuo njem site n'ihe akaebe, gosi mmalite ya, opekata mpe usoro isii, otu ihe onwunwe ejiri, otu okwu gbasara ịdị mma ma ọ bụ nchekwa, otu omume belata mkpofu, na ọrụ atọ jikọrọ njem ahụ."
  },
  evidence:["Bọdụ Mmalite Nri","Map isi mmalite nri obodo","Tebụl ihe mbụ ruo ngwaahịa","Farm-to-Food Journey strip","Food Care Checklist","Food Journey Portfolio","Ndekọ nyocha onye nkuzi"],
  passport:["K: mata mmalite nri, ebe mmepụta na usoro food system","P: wuo ma kọwaa njem nri site n'isi ruo tebụl","D: jiri ihe akaebe ma nyochaa ikwu AI/dijitalụ","S: soro allergy, food-contact na site-safety boundaries","E: mata ụzọ a na-agbakwunye uru n'ugbo, nhazi, njem na ọrụ","L: rụkọọ ọrụ, kewaa ihe akaebe na echiche, gwa akụkọ food system nke ọma"],
  trainerNotes:["Jiri nri obodo ụmụakwụkwọ maara nke ọma.","Ekwula na nri a haziri niile dị mma ma ọ bụ njọ; kọwaa ọrụ nhazi na mkpa nchekwa.","Jiri foto ma ọ bụ ngwugwu dị ọcha ma allergy ma ọ bụ hygiene bụrụ nsogbu.","Kpọọ onye ọrụ food system naanị site na usoro safeguarding kwadoro.","Gosi ọrụ ụmụ nwanyị na ụmụ nwoke n'usoro nri.","Koyere enterprise n'ọkwa echiche; e kwesịghị ịmanye ụmụaka ire ngwaahịa."],
  remediation:"Jiri naanị nri atọ na kaadị foto. Mụta usoro ISI → NHazi/NKWadebe → NJEM/NCHEKWA → IRI tupu agbakwunye nkọwa ndị ọzọ. Kwe ka ụmụakwụkwọ zaa ọnụ kama ide ogologo ederede.",
  extension:"Tụnyere njem nri ọhụrụ na nri a haziri, chọpụta ebe a na-eji mmiri na ume, wee nye otu aro iji belata mkpofu.",
  imagePrompts:[]
};