import type { PF01Module } from "./pf-01";

type PF04Module = Omit<PF01Module,"code"> & { code:"PF-04" };

export const pf04Fr: PF04Module = {
  code:"PF-04",
  title:"Les plantes autour de nous",
  level:"Fondation Pathways",
  age:"Environ 8 à 11 ans ; les activités pratiques doivent être adaptées aux conditions locales et aux besoins des apprenants.",
  duration:"6 leçons guidées plus observation, pratique au jardin et évaluation",
  fieldworkHours:3,
  bigQuestion:"Que peuvent nous apprendre les plantes sur l’alimentation, l’eau, les soins, les produits utiles et les lieux où nous vivons ?",
  whyItMatters:"Les plantes constituent une porte d’entrée accessible vers les sciences, les systèmes alimentaires et l’observation pratique. Ce module aide les apprenants à reconnaître les principales parties d’une plante, à comparer des plantes utiles, à comprendre leurs besoins de base et à relier les plantes à l’alimentation, aux moyens de subsistance, à la protection de l’environnement et aux futurs apprentissages GreenSkills.",
  outcomes:["Identifier les principales parties d’une plante et décrire des fonctions simples.","Distinguer racines, tiges, feuilles, fleurs, fruits et graines à partir d’exemples locaux.","Expliquer les besoins de base des plantes, notamment l’eau, la lumière, l’air, les nutriments et l’espace.","Observer et enregistrer des différences simples entre des plantes.","Relier les plantes à l’alimentation, aux matériaux, à l’ombre, à l’esthétique et aux moyens de subsistance.","Réaliser une tâche sûre et supervisée d’observation et de soin d’une plante avec des preuves."],
  vocabulary:["plante","racine","tige","feuille","fleur","fruit","graine","sol","eau","lumière du soleil","nutriment","observer","comparer","soin","récolte"],
  materials:["échantillons sûrs de plantes locales ou plantes vivantes","loupe si disponible","papier et crayons","cartes illustrées des parties d’une plante","petits récipients ou planche de culture","arrosoir","étiquettes","tablette/téléphone facultatif sous contrôle du facilitateur pour comparaison d’images"],
  safety:["Ne pas goûter de plantes inconnues.","Éviter les espèces toxiques, irritantes ou épineuses dans les activités avec les enfants.","Se laver les mains après manipulation de terre ou de matière végétale.","Utiliser uniquement des outils adaptés aux enfants et sous supervision.","Adapter les rôles pour les apprenants ayant des allergies ou des limitations de mobilité.","Ne jamais décider qu’une plante est comestible ou médicinale sur la seule base d’une réponse d’IA."],
  lessons:[
    {id:"PF-04-L1",title:"Rencontrer une plante",objective:"Reconnaître une plante comme un organisme vivant ayant des parties et des besoins observables.",teaching:["Les plantes sont des êtres vivants qui grandissent et changent.","Des plantes très différentes peuvent néanmoins partager des caractéristiques communes.","Une observation attentive nous aide à décrire ce que nous voyons avant d’expliquer pourquoi."],activity:"Observer deux plantes locales sûres et noter ou dessiner trois ressemblances et trois différences.",diy:"Créer une fiche d’observation d’une plante avec dessin, lieu, estimation de taille et deux caractéristiques visibles.",aiLayer:"Couche IA 1 — Reconnaissance : le facilitateur montre comment une description d’image par IA peut identifier des caractéristiques visibles ; les apprenants la comparent ensuite avec leur propre observation.",enterprise:"Les personnes créent de la valeur en cultivant, soignant, transportant et utilisant les plantes de manière responsable.",quiz:[{question:"Les plantes sont…",options:["des êtres vivants","des machines","des roches","des nombres"],answer:0},{question:"Un bon observateur doit…",options:["regarder attentivement","deviner sans regarder","abîmer la plante","ignorer les différences"],answer:0},{question:"Deux plantes peuvent…",options:["avoir des ressemblances et des différences","toujours être identiques","ne jamais avoir besoin d’eau","n’avoir aucune partie"],answer:0}]},
    {id:"PF-04-L2",title:"Racines, tiges et feuilles",objective:"Identifier les racines, les tiges et les feuilles et décrire leurs rôles de base.",teaching:["Les racines aident à ancrer la plante et à absorber l’eau et les nutriments.","Les tiges soutiennent les feuilles et transportent l’eau et d’autres matières dans la plante.","Les feuilles captent la lumière et aident la plante à fabriquer sa nourriture."],activity:"Associer des échantillons ou des images aux catégories RACINE, TIGE et FEUILLE, puis suivre le trajet possible de l’eau depuis le sol vers le haut.",diy:"Construire un modèle simple de plante étiqueté avec du papier, des bâtons ou des matériaux recyclés.",aiLayer:"Couche IA 2 — Comparaison guidée : utiliser un outil d’image contrôlé par le facilitateur pour comparer des racines, tiges ou feuilles inhabituelles puis vérifier avec des ressources pédagogiques fiables.",enterprise:"Comprendre les parties d’une plante aide les producteurs à manipuler correctement les cultures et à réduire les dégâts.",quiz:[{question:"Quelle partie ancre généralement une plante ?",options:["La racine","La fleur","Le fruit","L’étiquette"],answer:0},{question:"Les feuilles captent principalement…",options:["la lumière","de l’argent","du plastique","du bruit"],answer:0},{question:"Les tiges aident à…",options:["soutenir et transporter","effacer les racines","arrêter la croissance","remplacer le sol"],answer:0}]},
    {id:"PF-04-L3",title:"Fleurs, fruits et graines",objective:"Expliquer la relation entre fleurs, fruits et graines avec des exemples simples.",teaching:["De nombreuses plantes à fleurs produisent des fleurs dans le cadre de leur reproduction.","Les fruits protègent ou transportent souvent les graines.","Les graines peuvent devenir de nouvelles plantes lorsque les conditions conviennent."],activity:"Classer des exemples ou images sûrs en groupes fleur, fruit et graine et discuter de leurs liens.",diy:"Créer une carte en trois étapes FLEUR → FRUIT → GRAINE avec une culture familière.",aiLayer:"Couche IA 3 — Séquençage et classification : comparer les séquences de cycle de vie créées par les apprenants avec une séquence générée sous contrôle du facilitateur et repérer les erreurs.",enterprise:"Les graines, fruits et fleurs peuvent être des produits importants, mais leur qualité dépend d’une production et d’une manipulation sûres.",quiz:[{question:"Les graines peuvent…",options:["devenir de nouvelles plantes","devenir du métal","remplacer l’eau","produire directement de l’électricité"],answer:0},{question:"Un fruit contient souvent…",options:["des graines","des outils","des fils électriques","seulement des pierres"],answer:0},{question:"Quelle séquence est souvent correcte ?",options:["fleur → fruit → graine","graine → métal → fruit","feuille → batterie → racine","sol → fil → fleur"],answer:0}]},
    {id:"PF-04-L4",title:"Ce dont les plantes ont besoin",objective:"Identifier les conditions de base nécessaires à une bonne croissance des plantes.",teaching:["Les plantes ont besoin d’eau, de lumière, d’air, de nutriments et d’un espace adapté.","Trop peu ou trop d’une ressource peut créer des problèmes.","Les différentes plantes peuvent avoir besoin de quantités différentes d’eau, de lumière et d’espace."],activity:"Comparer deux jeunes plants identiques placés dans des conditions sûres différentes et prévoir ce qui pourrait se produire.",diy:"Créer une roue des besoins de la plante montrant eau, lumière, air, nutriments et espace.",aiLayer:"Couche IA 4 — Prédiction : le facilitateur demande à un outil d’IA une prédiction sur un scénario de soin ; les apprenants la comparent avec les preuves de leur propre observation.",enterprise:"Une bonne gestion des ressources peut réduire le gaspillage d’eau, d’intrants du sol et de matériel de plantation.",quiz:[{question:"Quel est un besoin de base d’une plante ?",options:["L’eau","Les jouets en plastique","Les mots de passe","La peinture"],answer:0},{question:"Trop d’eau peut-il nuire à certaines plantes ?",options:["Oui","Non, jamais","Seulement la nuit","Seulement en ligne"],answer:0},{question:"Les différentes plantes peuvent avoir besoin…",options:["de quantités différentes de ressources","toujours exactement des mêmes soins","d’aucune lumière","d’aucun espace"],answer:0}]},
    {id:"PF-04-L5",title:"Les plantes utiles autour de nous",objective:"Classer des plantes familières selon un ou plusieurs rôles utiles dans l’alimentation, l’ombre, les matériaux, l’esthétique ou les moyens de subsistance.",teaching:["Une plante peut avoir plusieurs usages.","Les personnes dépendent des plantes pour l’alimentation et de nombreux matériaux.","Utiliser les plantes de façon responsable suppose de prendre soin du sol, de l’eau et de l’approvisionnement futur."],activity:"Créer un tableau communautaire des usages des plantes avec des catégories comme alimentation, ombre, fibre/matériau, décoration et revenu/moyen de subsistance.",diy:"Interviewer un adulte de confiance à propos d’une plante locale utile et noter la partie utilisée ainsi que la façon dont elle est entretenue.",aiLayer:"Couche IA 5 — Vérification : le facilitateur montre que l’IA peut suggérer des usages de plantes, mais que l’identification locale et les affirmations de sécurité doivent être vérifiées auprès de personnes ou sources fiables.",enterprise:"Explorer comment la connaissance des plantes soutient les pépinières, l’agriculture, la transformation alimentaire, l’aménagement paysager et d’autres moyens de subsistance, sans attribuer de travail commercial aux enfants.",quiz:[{question:"Une plante peut-elle avoir plusieurs usages ?",options:["Oui","Non","Seulement les plantes importées","Seulement les arbres"],answer:0},{question:"Les informations sur l’usage des plantes doivent être…",options:["vérifiées","inventées","gardées dangereuses","fondées uniquement sur l’IA"],answer:0},{question:"L’utilisation responsable des plantes comprend…",options:["le soin des ressources","le gaspillage","les dégâts","une récolte dangereuse"],answer:0}]},
    {id:"PF-04-L6",title:"Prendre soin d’une plante vivante",objective:"Appliquer l’observation et des soins de base à une plante supervisée et documenter les preuves de changement.",teaching:["Le soin d’une plante suit un cycle : observer → décider → agir → vérifier.","Les registres nous aident à voir les changements dans le temps.","Un bon soin évite le gaspillage et répond aux besoins réels de la plante."],activity:"En binômes, inspecter une plante ou une petite planche, identifier un besoin et réaliser une action supervisée comme arroser, pailler ou enlever des débris sûrs.",diy:"Tenir un journal de soin de trois entrées avec date, observation, action et résultat.",aiLayer:"Intégration : comparer la décision de soin du groupe avec une suggestion d’IA fournie par le facilitateur, puis justifier le choix final avec les preuves observées et les conseils locaux.",enterprise:"Le soin fiable, la tenue de registres et l’observation de qualité sont des habitudes de travail fondamentales en agriculture et dans les métiers verts.",quiz:[{question:"Quel est un cycle de soin utile ?",options:["observer → décider → agir → vérifier","agir → ignorer → oublier","deviner → gaspiller → partir","copier → cacher → arrêter"],answer:0},{question:"Pourquoi tenir un journal de soin ?",options:["Pour suivre le changement","Pour cacher des preuves","Pour éviter l’observation","Pour remplacer la plante"],answer:0},{question:"Une bonne décision de soin doit utiliser…",options:["l’observation et des conseils fiables","le hasard","des mots de passe privés","des consignes dangereuses"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Quelle partie de la plante absorbe généralement l’eau du sol ?",options:["Les racines","Les fleurs","Le fruit","Seulement les graines"],answer:0},{question:"Quelle partie capte généralement la lumière ?",options:["Les feuilles","Les racines","Seulement le fruit","Les étiquettes"],answer:0},{question:"Que peuvent devenir les graines dans de bonnes conditions ?",options:["De nouvelles plantes","Du métal","Du plastique","Des batteries"],answer:0},{question:"Quel est un besoin de base d’une plante ?",options:["L’eau","Un mot de passe","La peinture","Seulement du carburant"],answer:0},{question:"Pourquoi comparer les plantes ?",options:["Pour remarquer ressemblances et différences","Pour les abîmer","Pour éviter d’apprendre","Pour les rendre identiques"],answer:0},{question:"L’IA seule peut-elle confirmer en sécurité qu’une plante inconnue est comestible ?",options:["Non","Toujours oui","Seulement si la photo est claire","Seulement si un enfant le demande"],answer:0},{question:"Quel est un bon élément de preuve de soin d’une plante ?",options:["Un journal daté d’observation","Une rumeur","Une supposition sans observation","Le travail sans rapport de quelqu’un d’autre"],answer:0},{question:"La connaissance des plantes peut soutenir des moyens de subsistance par…",options:["la culture, la pépinière, la transformation et les soins","seulement le gaspillage","la manipulation dangereuse","le fait de cacher l’information"],answer:0}],theory:["Nommez les principales parties d’une plante familière et décrivez une fonction de chacune.","Expliquez cinq choses dont les plantes peuvent avoir besoin pour bien grandir.","Décrivez une plante locale utile et au moins deux façons dont les gens l’utilisent.","Expliquez pourquoi un journal de soin peut aider un producteur à prendre de meilleures décisions.","Expliquez pourquoi les informations générées par IA sur une plante inconnue doivent être vérifiées avant de la manger ou de l’utiliser."],practical:"Observer une plante vivante sûre, identifier au moins quatre parties ou caractéristiques visibles, évaluer un besoin de soin, réaliser une action supervisée et présenter une courte trace de preuve montrant observation, action et résultat attendu."},
  evidence:["Fiche d’observation d’une plante","Modèle des parties de la plante","Carte fleur-fruit-graine","Roue des besoins de la plante","Tableau des usages communautaires ou fiche d’entretien","Journal de soin de trois entrées","Fiche d’observation pratique du facilitateur"],
  passport:["K : identifie les parties, besoins et usages courants des plantes","P : réalise une observation et une tâche de soin supervisée","D : compare des suggestions numériques/IA avec les preuves directes et des sources fiables","S : respecte les règles de sécurité pour les plantes, le sol et les outils","E : relie la connaissance des plantes aux produits, services et à la gestion responsable des ressources","L : travaille en équipe, enregistre ses observations et communique ses décisions de soin"],
  trainerNotes:["Utiliser des plantes que les apprenants rencontrent réellement localement lorsque cela est sûr.","Ne pas présenter les usages médicinaux comme des faits établis dans ce module de base.","Proposer des options orales, visuelles et tactiles pour les lecteurs débutants.","Faire tourner équitablement les rôles d’observation, d’arrosage, de mesure et de présentation.","S’il n’y a pas de jardin, utiliser des plantes en pots ou des images de qualité avec au moins une observation supervisée d’une plante vivante si possible."],
  remediation:"Réduire le nombre de parties de plante introduites à la fois, utiliser des appariements répétés avec des objets réels ou des modèles tactiles et répéter la séquence observer–nommer–fonction.",
  extension:"L’apprenant crée une fiche d’une page sur une culture locale importante montrant les parties de la plante, un besoin de croissance, un usage et une action de soin.",
  imagePrompts:["Enfants africains de 8 à 11 ans observant des plantes de jardin sûres avec un facilitateur bienveillant, montrant racines, tiges et feuilles, jardin scolaire-communautaire inclusif, lumière naturelle, aucun texte lisible, accents LIFEWS verts et dorés.","Illustration botanique adaptée aux enfants montrant une plante alimentaire générique à fleurs avec racines, tige, feuilles, fleur, fruit et graines clairement visibles, fond blanc, sans étiquettes ni texte.","Petit groupe photoréaliste d’apprenants africains arrosant et paillant un jardin en conteneurs sous supervision tout en enregistrant des observations sur papier, outils sûrs, collaboration, sans texte lisible."]
};