import type { PF01Module } from "./pf-01";

type PF03Module = Omit<PF01Module,"code"> & { code:"PF-03" };

export const pf03Yo: PF03Module = {
  code:"PF-03",
  title:"Nọ́mbà Nínú Ìgbésí-ayé Ojoojúmọ́",
  level:"Pathways Foundation",
  age:"Ní àárín ọdún 8 sí 11; ìpín sí ipele ìṣirò gbọ́dọ̀ tẹ̀lé ìdánwò ìpilẹ̀.",
  duration:"Ẹ̀kọ́ amọ̀nà mẹ́fà pẹ̀lú iṣẹ́ ọwọ́ àti ìdánwò",
  fieldworkHours:2,
  bigQuestion:"Báwo ni nọ́mbà ṣe ń ràn wa lọwọ láti ka, fiwé, wọn, gbero àti ṣe ìpinnu tó dáa lójoojúmọ́?",
  whyItMatters:"Ìmọ̀-ìṣirò tó wúlò ń jẹ́ kí akẹ́kọ̀ọ́ lè kópa pẹ̀lú ìgboyà nínú ìgbésí-ayé ojoojúmọ́, ẹ̀kọ́ iṣẹ́ ọwọ́ àti ikẹ́kọ̀ọ́ ọjọ́ iwájú. Ẹ̀ka yìí ń kọ́ kíkà iye, fífiwé, ìfojúsùn, ìwọn, ìkọ̀wé data àti ìyanjú iṣoro rọrùn nípasẹ̀ àpẹẹrẹ oúnjẹ, omi, ọgbà, ilé àti àwùjọ.",
  outcomes:["Ka kí o sì ṣàfihàn iye pẹ̀lú ohun, àmì àti nọ́mbà.","Fi iye wé pẹ̀lú ọ̀rọ̀ bíi púpọ̀ síi, díẹ̀ síi, dọ́gba, tóbi àti kékeré.","Wọn gígùn, iwọn omi àti iwuwo pẹ̀lú irinṣẹ́ tó yẹ tàbí ẹ̀ka ìwọn àìdájọ́.","Lo ìfikún àti ìyọkúrò rọrùn nínú ipo iṣẹ́ gidi.","Kọ ìṣàkíyèsí sínú tábìlì tàbí tally rọrùn.","Lo ìtìlẹ́yìn díjítà tàbí AI lábẹ́ amọ̀nà láti ṣàyẹ̀wò àpẹẹrẹ tàbí ìṣirò, nígbà tó ń ṣàlàyé ìrònú tirẹ̀."],
  vocabulary:["nọ́mbà","ka","iye","púpọ̀ síi","díẹ̀ síi","dọ́gba","wọn","gígùn","iwọn omi","iwuwo","fojúsùn","fikún","yọkúrò","tábìlì","tally"],
  materials:["ohun kíkà bíi irúgbìn tàbí ideri igo","káàdì nọ́mbà","okùn/ruula/teepu ìwọn","ago tàbí ohun ìwọn omi","ìwọ̀n rọrùn bí ó bá wà","ìwé àti pẹ́ńsù","àpẹẹrẹ tally","kálíkúlétọ̀ tàbí tabulẹti lábẹ́ ìṣàkóso olùkọ́ bí ó bá yẹ"],
  safety:["Lo ohun kíkà tó mọ́, tí kò ní eti tó le.","Má lo eru tó wuwo tàbí àpò tó lewu fún iṣẹ́ ìwọn.","So akẹ́kọ̀ọ́ pọ̀ kí ẹni tó ṣì ń kọ́ ìṣirò lè kópa láìtìjú.","Má jẹ́ kí akẹ́kọ̀ọ́ gbára lé kálíkúlétọ̀ tàbí AI kí wọ́n tó fi ìrònú ìpilẹ̀ hàn.","Gbogbo iṣẹ́ ìwọn ọwọ́ gbọ́dọ̀ yẹ fún ọjọ́-ori, kí olùkọ́ sì bojú tó."],
  lessons:[
    {id:"PF-03-L1",title:"Kíkà Ohun Tí A Rí",objective:"Ka, pín sí ẹgbẹ́ kí o sì ṣàfihàn ohun tó mọ̀ ní pípé.",teaching:["Kíkà ń sọ iye ohun tó wà nínú ẹgbẹ́ fún wa.","Pípín ohun sí ẹgbẹ́ lè mú kíkà iye tó pọ̀ rọrùn.","A lè fi iye hàn pẹ̀lú ohun, tally, ọ̀rọ̀ tàbí nọ́mbà."],activity:"Ka kí o sì pín irúgbìn, ideri igo tàbí káàdì sí ẹgbẹ́ 2, 5 àti 10; fi ọ̀nà oríṣìíríṣìí tí a fi hàn iye kan wé.",diy:"Ṣẹ̀dá pátákó kíkà pẹ̀lú apá márùn-ún, kí o sì fi iye oríṣìíríṣìí sí ọkọọkan.",aiLayer:"AI Ipele 1 — Ìdámọ̀: fi kíkà akẹ́kọ̀ọ́ wé pẹ̀lú kíkà díjítà tí olùkọ́ tẹ̀ sílẹ̀, kí ẹ jíròrò bí irinṣẹ́ ṣe lè ṣàyẹ̀wò láìrọ́pò àkíyèsí ènìyàn.",enterprise:"Kíkà tó péye ṣe pàtàkì fún ṣíṣe ètò ohun èlò, ṣàyẹ̀wò stock àti pín orísun ní ìdájọ́.",quiz:[{question:"Kí ni kíkà ń sọ fún wa?",options:["Iye ohun tó wà","Àwọ̀ wọn","Ẹni tó ní wọn","Ọjọ́-ori wọn"],answer:0},{question:"Pípín sí ẹgbẹ́ lè ràn wa lọwọ láti…",options:["ka iye tó pọ̀","fi ohun pamọ́","yàgò fún nọ́mbà","yí apapọ̀ padà"],answer:0},{question:"Kí ni ó lè ṣàfihàn iye?",options:["Àmì tally","Ọ̀rọ̀ nìkan","Àwòrán nìkan","Kò sí nǹkan"],answer:0}]},
    {id:"PF-03-L2",title:"Púpọ̀ Síi, Díẹ̀ Síi àti Dọ́gba",objective:"Fi iye méjì tàbí ju bẹ́ẹ̀ lọ wé kí o sì lo ọ̀rọ̀ fífiwé tó yẹ.",teaching:["A fi iye wé láti mọ èwo ni púpọ̀ síi, díẹ̀ síi tàbí dọ́gba.","Dọ́gba túmọ̀ sí pé iye méjì ní iye kan naa.","Fífiwé ń ràn wa lọwọ láti ṣe ìpinnu tó tọ́ àti tó munadoko."],activity:"Fi àwo ohun, ipele omi nínú àpò tí a lè rí inú rẹ̀ àti gígùn okùn wé; ṣàlàyé fífiwé kọọkan ní ẹnu.",diy:"Ṣe káàdì fífiwé mẹ́fà pẹ̀lú àwòrán àti ọ̀rọ̀ PÚPỌ̀ SÍI, DÍẸ̀ SÍI tàbí DỌ́GBA.",aiLayer:"AI Ipele 2 — Ìbáṣepọ̀ lábẹ́ amọ̀nà: olùkọ́ béèrè lọ́wọ́ irinṣẹ́ díjítà/AI fún àpẹẹrẹ fífiwé rọrùn; akẹ́kọ̀ọ́ dáhùn kọ́kọ́, kí o tó ṣàyẹ̀wò idahun irinṣẹ́.",enterprise:"Fífi iye wé ń ràn ènìyàn lọwọ láti dín ìsòfò kù àti pinnu iye ohun èlò tó yẹ.",quiz:[{question:"Dọ́gba túmọ̀ sí…",options:["iye kan naa","púpọ̀ síi nigbagbogbo","díẹ̀ síi nigbagbogbo","a kò mọ̀"],answer:0},{question:"Tí àpò A bá ní eso 8, B sì ní 5, A ní…",options:["púpọ̀ síi","díẹ̀ síi","dọ́gba","odo"],answer:0},{question:"Fífiwé wúlò fún…",options:["ṣe ìpinnu","yàgò fún gbogbo ìwọn","fi àkọsílẹ̀ pamọ́","yí òtítọ́ padà"],answer:0}]},
    {id:"PF-03-L3",title:"Wíwọ̀n Gígùn àti Ijìnnà",objective:"Wọn kí o sì fi gígùn wé pẹ̀lú ẹ̀ka ìwọn àìdájọ́ àti boṣewa bí ó bá wà.",teaching:["Ìwọn ń fún ànímọ́ bíi gígùn ní nọ́mbà.","Ẹ̀ka ìwọn kan naa ni a gbọ́dọ̀ lo nígbà fífi ìwọn wé.","Ìfojúsùn jẹ́ gboju tó ní ìdí tí a ṣe kí a tó wọn."],activity:"Fojú sùn, lẹ́yìn náà wọn gígùn tábìlì, ibùsùn ọgbà, okùn tàbí ohun yàrá pẹ̀lú ìka ọwọ́, ìgbésẹ̀, lẹ́yìn náà ruula tàbí teepu ìwọn.",diy:"Ṣẹ̀dá àkọsílẹ̀ ìwọn ohun márùn-ún tí ó ní ìfojúsùn, ìwọn gidi àti ìyàtọ̀.",aiLayer:"AI Ipele 3 — Ìdámọ̀ àpẹẹrẹ: fi àṣìṣe ìfojúsùn wé, kí o mọ bóyá ìfojúsùn máa ń ga ju, kéré ju tàbí sunmọ́ gidi.",enterprise:"Ìwọn tó péye ṣe pàtàkì fún ikole, gbíngbin, gígé ohun èlò àti gbero aaye.",quiz:[{question:"Kí ló dé tí a fi gbọ́dọ̀ lo ẹ̀ka ìwọn kan naa fún fífiwé?",options:["Kí ìwọn lè ṣe afiwe","Láti yí abajade padà","Láti mú kíkà ṣòro","Kò ṣe pàtàkì"],answer:0},{question:"Ìfojúsùn jẹ́…",options:["gboju tó ní ìdí kí a tó wọn","ohun tó máa ń péye nigbagbogbo","nọ́mbà aṣírí","owó"],answer:0},{question:"Irinṣẹ́ wo ni a fi wọn gígùn?",options:["Ruula tàbí teepu ìwọn","Ago nìkan","Ṣíbí nìkan","Akọlé ìwé"],answer:0}]},
    {id:"PF-03-L4",title:"Wíwọ̀n Omi àti Iye Míì",objective:"Wọn iwọn omi àti iwuwo rọrùn ní ààbò pẹ̀lú irinṣẹ́ tàbí ẹ̀ka ìwọn tó yẹ.",teaching:["Iwọn omi ń sọ iye aaye tí omi gba.","Iwuwo ń sọ bí ohun ṣe wuwo ní fífiwé pẹ̀lú ẹ̀ka ìwọn.","Ìwọn pẹ̀lú àkíyèsí ń dín ìsòfò àti àṣìṣe kù."],activity:"Wọn omi tó dọ́gba sínú àpò, kí o sì fi iwuwo ohun yàrá tàbí ọgbà tó ní ààbò wé pẹ̀lú ìwọ̀n rọrùn.",diy:"Ṣe tábìlì ìwọn ohun mẹ́rin pẹ̀lú orúkọ ohun, iye, ẹ̀ka ìwọn àti abajade.",aiLayer:"AI Ipele 4 — Ìbéèrè tó ní ààlà: olùkọ́ béèrè àpẹẹrẹ ibi tí ìwọn tó péye ṣe pàtàkì; akẹ́kọ̀ọ́ pín sí oúnjẹ, omi, ikole, oko tàbí ilé.",enterprise:"Iye tó dúró ṣinṣin ṣe pàtàkì nínú sise oúnjẹ, apoti, irigeson àti lílo orísun pẹ̀lú ojúṣe.",quiz:[{question:"Iwọn omi ń sọ…",options:["aaye tí omi gba","bi ohun ṣe pariwo","ọjọ́-ori","àwọ̀ rẹ̀"],answer:0},{question:"Kí ló dé tí a fi yẹ kí a wọn dáadáa?",options:["Láti dín àṣìṣe àti ìsòfò kù","Láti jẹ́ kí àkọsílẹ̀ má wúlò","Láti fi ìyàtọ̀ pamọ́","Láti yàgò fún ojúṣe"],answer:0},{question:"Èwo ni ẹ̀ka ìwọn?",options:["lítà","ọgbà","olùkọ́","àwòrán"],answer:0}]},
    {id:"PF-03-L5",title:"Ìfikún àti Ìyọkúrò Nínú Ayé Gidi",objective:"Lo ìfikún àti ìyọkúrò rọrùn láti yanju iṣoro iṣẹ́ tó mọ̀.",teaching:["Ìfikún ń darapọ̀ iye.","Ìyọkúrò ń sọ ohun tó ku tàbí ìyàtọ̀ láàárín iye méjì.","Àwòrán, ohun àti number line lè ràn wa lọwọ láti yanju iṣoro."],activity:"Yanju itan iṣiro nípa irúgbìn tí a gbin, ago omi tí a lo, eso tí a pín tàbí irinṣẹ́ tí a ka, lo ohun kọ́kọ́ kí o tó lo nọ́mbà.",diy:"Ṣẹ̀dá iṣoro ìfikún méjì àti ìyọkúrò méjì láti ipo àwùjọ tàbí ọgbà, kí o sì yanju wọn.",aiLayer:"AI Ipele 5 — Ìdánilójú: olùkọ́ fi ojútùú díjítà kan tó tọ́ àti ọkan tó ṣìṣe hàn; akẹ́kọ̀ọ́ ṣàlàyé èwo ni tó tọ́ àti idi.",enterprise:"Ìṣirò rọrùn ń ṣe atilẹyin kíkà stock, gbero ohun èlò àti ṣàyẹ̀wò change, ṣùgbọ́n a kò ní kí ọmọ ṣe iṣowo.",quiz:[{question:"Ìfikún ni a fi…",options:["darapọ̀ iye","fi iye pamọ́","pa gbogbo nọ́mbà rẹ́","wọn ooru nìkan"],answer:0},{question:"Ìyọkúrò lè sọ…",options:["ohun tó ku","àwọ̀ nìkan","orúkọ nìkan","kò sí nǹkan tó wúlò"],answer:0},{question:"Ọ̀nà tó dáa láti ṣàyẹ̀wò ìṣirò ni…",options:["lo ohun tàbí ọ̀nà mìíràn","gba idahun eyikeyi","fo iṣoro","daakọ láìronu"],answer:0}]},
    {id:"PF-03-L6",title:"Kíkọ Nọ́mbà Sílẹ̀ àti Rírí Àpẹẹrẹ",objective:"Kọ data rọrùn sílẹ̀ kí o sì mọ àpẹẹrẹ tàbí ayípadà ìpilẹ̀.",teaching:["Tally ń kọ iye igba tí ohun kan ṣẹlẹ̀ sílẹ̀.","Tábìlì ń ṣètò ìsọfúnni sí ila àti kọ́lámù.","Àpẹẹrẹ ń ràn wa lọwọ láti rí ohun tó tún máa ń ṣẹlẹ̀, ayípadà àti ìbáṣepọ̀ tó ṣeéṣe."],activity:"Kó data kékeré jọ láti yàrá tàbí ọgbà, bíi iye ewéko, ago omi ojoojúmọ́ tàbí iṣẹ́ ẹ̀kọ́ tí a fẹ́ràn, kí o sì ṣe tally/tábìlì.",diy:"Ṣẹ̀dá àkọsílẹ̀ data ọ̀sẹ̀ kan pẹ̀lú ìṣàkíyèsí márùn-ún o kere tan, kí o sọ tàbí kọ ohun méjì tí o rí.",aiLayer:"Ìṣọ̀kan: olùkọ́ lè tẹ data kan naa sínú spreadsheet tàbí AI láti gba akopọ̀; akẹ́kọ̀ọ́ fi akopọ̀ yẹn wé pẹ̀lú ìṣàkíyèsí tirẹ̀.",enterprise:"Àkọsílẹ̀ ń ràn ènìyàn lọwọ láti mọ ohun tó ṣẹlẹ̀, dín gboju kù àti gbero dáadáa.",quiz:[{question:"Kí ni tally ń fi hàn?",options:["iye igba tí ohun kan ṣẹlẹ̀","orúkọ nìkan","àwòrán nìkan","owó nìkan"],answer:0},{question:"Tábìlì ń ṣètò ìsọfúnni pẹ̀lú…",options:["ila àti kọ́lámù","àwọ̀ nìkan","aṣírí","àmì aláìlétò"],answer:0},{question:"Kí ló dé tí a fi ń pa àkọsílẹ̀ mọ́?",options:["Láti ṣe ìpinnu tó dáa","Láti pa ìsọfúnni rẹ́","Láti yàgò fún ẹ̀kọ́","Láti rọ́pò ìṣàkíyèsí"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Kí ni ìdí kíkà?",options:["Láti mọ iye","Láti mọ àwọ̀ nìkan","Láti fi ohun pamọ́","Láti yí iye padà"],answer:0},{question:"Ọ̀rọ̀ wo ni ó túmọ̀ sí pé iye méjì jẹ́ kan naa?",options:["Dọ́gba","Púpọ̀","Díẹ̀","Ìfojúsùn"],answer:0},{question:"Kí ni ó yẹ kí a ṣe pẹ̀lú ìfojúsùn?",options:["Fojú sùn, wọn, kí o sì fiwé","Gboju, dúró","Wọn láìkọ sílẹ̀","Foju kọ abajade"],answer:0},{question:"Iṣe wo ni ń darapọ̀ iye?",options:["Ìfikún","Ìyọkúrò nìkan","Fífiwé","Ìfojúsùn"],answer:0},{question:"Lítà ni a sábà fi wọn…",options:["iwọn omi","ọjọ́-ori","àwọ̀","ijìnnà ìlú nìkan"],answer:0},{question:"Kí ló dé tí àkọsílẹ̀ fi wúlò?",options:["Ó ń ràn wa lọwọ láti mọ ohun tó ṣẹlẹ̀ àti gbero","Ó ń pa ẹ̀rí rẹ́","Ó ń mú nọ́mbà di asán","Ó ń dènà fífiwé"],answer:0},{question:"Tí AI bá fún ọ ní idahun ìṣirò tó yàtọ̀ sí tirẹ̀, kí ni ká ṣe?",options:["Ṣàyẹ̀wò ìrònú pẹ̀lú ohun tàbí ọ̀nà mìíràn","Ro pé AI máa ń tó nigbagbogbo","Pa iṣẹ́ rẹ rẹ́","Pín ìsọfúnni àdáni"],answer:0},{question:"Ọgbọ́n wo ni wúlò fún gbero ibùsùn ọgbà?",options:["Ìwọn","Fífòju kọ aaye","Gboju lasan","Yàgò fún nọ́mbà"],answer:0}],theory:["Ṣàlàyé ọ̀nà méjì tí nọ́mbà fi wúlò nínú ìgbésí-ayé ojoojúmọ́.","Ṣàlàyé ìyàtọ̀ láàárín púpọ̀ síi, díẹ̀ síi àti dọ́gba pẹ̀lú àpẹẹrẹ tirẹ̀.","Ṣàlàyé idi tí ìfojúsùn fi lè wúlò kí a tó wọn.","Ṣẹ̀dá iṣoro ìfikún tàbí ìyọkúrò pẹ̀lú àpẹẹrẹ oúnjẹ, omi tàbí ọgbà, kí o sì yanju rẹ̀.","Ṣàlàyé idi tí ènìyàn fi gbọ́dọ̀ lóye ìṣirò dipo gbígbára lé kálíkúlétọ̀ tàbí AI patapata."],practical:"Ṣe ìwádìí ìṣirò kékeré: fojú sùn kí o sì wọn ohun mẹ́ta tàbí iye tó ní ààbò, kọ abajade sínú tábìlì, yanju iṣoro ìfikún kan àti ìyọkúrò kan pẹ̀lú data náà, kí o sì ṣàlàyé àpẹẹrẹ tàbí fífiwé kan tí o rí."},
  evidence:["Pátákó kíkà tàbí àkọsílẹ̀ pípín sí ẹgbẹ́","Káàdì fífiwé","Àkọsílẹ̀ ìfojúsùn àti ìwọn ohun márùn-ún","Tábìlì ìwọn iye","Iṣoro ìṣirò tí akẹ́kọ̀ọ́ ṣẹ̀dá","Àkọsílẹ̀ data ọ̀sẹ̀ kan","Àtòjọ ìṣàkíyèsí ìṣirò olùkọ́"],
  passport:["K: lóye kíkà, fífiwé, ìwọn, ìfikún, ìyọkúrò àti àkọsílẹ̀ data rọrùn","P: wọn, kọ sílẹ̀ àti yanju iṣoro iye gidi","D: ṣàyẹ̀wò abajade díjítà/AI pẹ̀lú ìrònú tirẹ̀","S: lo irinṣẹ́ ìwọn àti àpò ní ààbò","E: ṣàlàyé bí kíkà, ìwọn àti àkọsílẹ̀ ṣe ń dín ìsòfò kù àti ṣe atilẹyin gbero","L: ṣàlàyé ìrònú, ṣiṣẹ́ pọ̀ àti tún àṣìṣe ṣe ní ọ̀nà tó dáa"],
  trainerNotes:["Lo ohun gidi kí o tó lo àmì ìṣirò fún ẹni tó nílò rẹ̀.","Gba àlàyé ẹnu àti àfihàn gẹ́gẹ́ bí ẹ̀rí pẹ̀lú iṣẹ́ kọ̀wé.","Lo àpẹẹrẹ tó mọ̀mọ́ ní àṣà àti irinṣẹ́ ìwọn tó wà ní agbègbè.","Bí ẹ̀ka boṣewa kò tíì ye, bẹ̀rẹ̀ pẹ̀lú ẹ̀ka àìdájọ́ tó dúró ṣinṣin kí o sì yí lọ sí boṣewa díẹ̀díẹ̀.","Má lo ìdíje iyara tó ń tijú; tẹnumọ́ ìrònú àti ìlọsíwájú."],
  remediation:"Padà sí ohun gidi, ìbáramu ọkan-si-ọkan, number line àti ìwọn léraléra pẹ̀lú ẹ̀ka kan ní akoko kan. Dín ibiti nọ́mbà kù, ṣùgbọ́n pa iṣẹ́ tó wúlò mọ́.",
  extension:"Akẹ́kọ̀ọ́ ṣe àpẹrẹ ìpenija lílo orísun, bíi kíkà ago omi tí a lo fún ewéko díẹ̀ lojoojúmọ́, kí o sì daba ìmúdára tó dá lórí ẹ̀rí.",
  imagePrompts:["Àwọn ọmọ Africa ọdún 8–11 ń ka irúgbìn, wọn omi nínú ago tí a lè rí inú rẹ̀ àti lo teepu ìwọn nínú ọgbà ẹ̀kọ́ lábẹ́ amọ̀nà, ọmọkùnrin àti ọmọbìnrin pọ̀, ìmọ́lẹ̀ adayeba, kò sí ọrọ̀ tí a lè ka, àwọ̀ LIFEWS aláwọ̀-ewe àti ofeefee goolu.","Àwòrán ẹ̀kọ́ ọmọde tó ní aami mẹ́fà: kíkà, fífiwé, ruula, iwọn omi, ìfikún rọrùn àti tally, abẹ́lẹ̀ funfun, kò sí ọ̀rọ̀.","Ẹgbẹ́ kékeré akẹ́kọ̀ọ́ Africa ń kọ iye ewéko sínú tábìlì rọrùn lórí ìwé lẹ́gbẹ̀ẹ́ ọgbà ilé-ẹ̀kọ́, olùkọ́ nítòsí, ìfowosowopo tó yẹ fún ọjọ́-ori, kò sí ọrọ̀ tí a lè ka."]
};