import type { PF01Module } from "./pf-01";

type PF03Module = Omit<PF01Module,"code"> & { code:"PF-03" };

export const pf03Ig: PF03Module = {
  code:"PF-03",
  title:"Ọnụọgụgụ n’Ndụ Kwa Ụbọchị",
  level:"Pathways Foundation",
  age:"Ihe dịka afọ 8–11; itinye nwa akwụkwọ n’ọkwa mgbakọ kwesịrị ịdabere na nyocha mmalite.",
  duration:"Ihe ọmụmụ nduzi isii tinyere ọrụ aka na nyocha",
  fieldworkHours:2,
  bigQuestion:"Kedu ka ọnụọgụgụ si enyere anyị aka ịgụ ọnụ, tụnyere, tụọ, hazie ma mee mkpebi ka mma kwa ụbọchị?",
  whyItMatters:"Mgbakọ bara uru na-enyere ụmụ akwụkwọ aka isonye n’ụbọchị kwa ụbọchị, n’ọrụ aka na n’ọzụzụ nkà n’ọdịnihu n’ụzọ nwere ntụkwasị obi. Modul a na-ewulite ịgụ ọnụ, ntụnyere, ịkọ atụ, nha, ide data na idozi nsogbu dị mfe site n’ihe atụ metụtara nri, mmiri, ubi, ụlọ na obodo.",
  outcomes:["Gụọ ma gosipụta ọnụọgụ site n’iji ihe, akara na nọmba.","Tụnyere ọnụọgụ site n’iji karịa, pere mpe, hà nhata, ukwuu na nta.","Tụọ ogologo, olu mmiri na ibu site n’iji ngwaọrụ kwesịrị ekwesị ma ọ bụ unit dị mfe.","Jiri mgbakwunye na mwepụ dị mfe n’ọnọdụ bara uru.","Deba ihe a hụrụ n’ime tebụl ma ọ bụ tally dị mfe.","Jiri nkwado dijitalụ ma ọ bụ AI n’okpuru nduzi nyochaa usoro ma ọ bụ mgbakọ ma kọwaa echiche nke gị."],
  vocabulary:["nọmba","gụ ọnụ","ọnụọgụ","karịa","pere mpe","hà nhata","tụọ","ogologo","olu","ibu","kọ atụ","gbakwunye","wepụ","tebụl","tally"],
  materials:["ihe a ga-agụ dịka mkpụrụ ma ọ bụ mkpuchi karama","kaadị nọmba","eriri/rula/tape nha","iko ma ọ bụ akpa nha","balance dị mfe ma ọ bụrụ na ọ dị","akwụkwọ na pensụl","ụdị tally","calculator ma ọ bụ tablet n’okpuru nlekọta ma ọ bụrụ na ọ dị mkpa"],
  safety:["Jiri ihe a na-agụ dị ọcha, nke na-adịghị nkọ.","Ejila ibu dị arọ ma ọ bụ akpa dị ize ndụ n’ọrụ nha.","Jikọta ụmụ akwụkwọ abụọ abụọ ka ndị na-amalite mgbakọ nwee ike isonye n’enweghị ihere.","Ekwela ka ụmụ akwụkwọ dabere na calculator ma ọ bụ AI tupu ha gosipụta nghọta mgbakọ bụ isi.","Mee ka ọrụ nha niile dabara n’afọ ma bụrụ nke a na-elekọta."],
  lessons:[
    {id:"PF-03-L1",title:"Ịgụ Ihe Anyị Na-ahụ",objective:"Gụọ, kewaa n’otu ma gosipụta ihe a maara n’ụzọ ziri ezi.",teaching:["Ịgụ ọnụ na-agwa anyị ole ihe dị n’otu.","Ikewa ihe n’otu nwere ike ime ka ịgụ ọtụtụ ihe dị mfe.","A pụrụ igosi ọnụọgụ site n’ihe, tally, okwu ma ọ bụ nọmba."],activity:"Gụọ ma kewaa mkpụrụ, mkpuchi karama ma ọ bụ kaadị n’otu 2, 5 na 10; tụnyere ụzọ dị iche iche e si egosi otu ngụkọta.",diy:"Mepụta tray ịgụ ọnụ nwere akụkụ ise ma tinye ọnụọgụ dị iche n’akụkụ ọ bụla.",aiLayer:"AI Ogo 1 — Ịmata: tụnyere ihe nwa akwụkwọ gụrụ na ngụkọ dijitalụ onye nduzi tinyere, wee kwurịta otú ngwaọrụ si enyere aka nyochaa ma ọ naghị dochie nlebara anya.",enterprise:"Ịgụ ziri ezi dị mkpa n’ịhazi ihe, nyochaa stock na ikesa ihe n’ụzọ ziri ezi.",quiz:[{question:"Gịnị ka ịgụ ọnụ na-agwa anyị?",options:["Ole ihe dị","Agba ha","Onye nwe ha","Afọ ha"],answer:0},{question:"Ikewa n’otu nwere ike inyere anyị…",options:["ịgụ ọtụtụ ihe","izo ihe","zere nọmba","gbanwee ngụkọta"],answer:0},{question:"Gịnị nwere ike igosi ọnụọgụ?",options:["Tally marks","Okwu naanị","Onyonyo naanị","Ọ dịghị ihe"],answer:0}]},
    {id:"PF-03-L2",title:"Karịa, Pere Mpe na Hà Nhata",objective:"Tụnyere ọnụọgụ abụọ ma ọ bụ karịa ma jiri okwu ntụnyere kwesịrị ekwesị.",teaching:["Anyị na-atụnyere ọnụọgụ iji hụ nke karịrị, nke pere mpe ma ọ bụ nke hà nhata.","Hà nhata pụtara na ọnụọgụ abụọ nwere otu uru.","Ntụnyere na-enyere anyị aka ime mkpebi ziri ezi ma baa uru."],activity:"Tụnyere efere ihe, ọkwa mmiri n’ime akpa a na-ahụ anya na ogologo eriri; kọwaa ntụnyere ọ bụla n’ọnụ.",diy:"Mepụta kaadị ntụnyere isii nwere eserese na okwu KARỊA, PERE MPE ma ọ bụ HÀ NHATA.",aiLayer:"AI Ogo 2 — Mmekọrịta nduzi: onye nduzi jụọ ngwa dijitalụ/AI ka o mepụta ihe atụ ntụnyere dị mfe; ụmụ akwụkwọ dozie ha mbụ wee nyochaa azịza ngwa ahụ.",enterprise:"Ịtụnyere ọnụọgụ na-enyere ndị mmadụ aka ibelata mmefu na ịmata ole ihe a chọrọ.",quiz:[{question:"Hà nhata pụtara…",options:["otu ọnụọgụ","karịa mgbe niile","pere mpe mgbe niile","amaghị"],answer:0},{question:"Ọ bụrụ na akpa A nwere mkpụrụ osisi 8, B nwere 5, A nwere…",options:["karịa","pere mpe","hà nhata","efu"],answer:0},{question:"Ntụnyere bara uru maka…",options:["ime mkpebi","izere nha niile","izo ndekọ","ịgbanwe eziokwu"],answer:0}]},
    {id:"PF-03-L3",title:"Ịtụ Ogologo na Anya",objective:"Tụọ ma tụnyere ogologo site n’iji unit dị mfe na unit ọkọlọtọ ma ọ bụrụ na ọ dị.",teaching:["Nha na-enye àgwà dịka ogologo nọmba.","E kwesịrị iji otu unit ahụ mgbe a na-atụnyere nha.","Ịkọ atụ bụ ntule nwere ezi uche tupu a tụọ."],activity:"Kọ atụ wee tụọ ogologo tebụl, akwa ubi, eriri ma ọ bụ ihe klas site na span aka, nzọụkwụ, wee jiri rula ma ọ bụ tape nha.",diy:"Mepụta ndekọ nha maka ihe ise nke nwere ihe e tụrụ anya, nha n’ezie na ọdịiche.",aiLayer:"AI Ogo 3 — Ịmata usoro: tụnyere njehie n’ịkọ atụ iji chọpụta ma ntule na-adịkarị elu, ala ma ọ bụ nso eziokwu.",enterprise:"Nha ziri ezi dị mkpa n’ọrụ owuwu, ịkụ ihe, ịkpụ ihe na ịhazi oghere.",quiz:[{question:"Gịnị mere e ji eji otu unit ahụ tụnyere nha?",options:["Ka nha nwee ike ịtụnyere","Ka nsonaazụ gbanwee","Ka mgbakọ sie ike","Ọ dịghị mkpa"],answer:0},{question:"Ịkọ atụ bụ…",options:["ntule nwere ezi uche tupu nha","ihe na-adị ziri ezi mgbe niile","nọmba nzuzo","ọnụ ahịa"],answer:0},{question:"Kedu ngwaọrụ a na-eji tụọ ogologo?",options:["Rula ma ọ bụ tape nha","Iko naanị","Ngaji naanị","Aha akwụkwọ"],answer:0}]},
    {id:"PF-03-L4",title:"Ịtụ Mmiri na Ọnụọgụ Ndị Ọzọ",objective:"Tụọ olu na ibu dị mfe n’ụzọ dị nchebe site na ngwaọrụ ma ọ bụ unit kwesịrị ekwesị.",teaching:["Olu na-egosi ohere mmiri na-ejide.","Ibu na-egosi otú ihe si dị arọ ma e jiri ya tụnyere unit.","Nha nlezianya na-ebelata mmejọ na imefusị ihe."],activity:"Tụọ otu olu mmiri n’ime akpa dị iche ma tụnyere ibu ihe klas ma ọ bụ ubi dị nchebe site na balance dị mfe.",diy:"Kwadebe tebụl nha ihe anọ nwere ihe, ọnụọgụ, unit na nsonaazụ.",aiLayer:"AI Ogo 4 — Ajụjụ nwere oke: onye nduzi jụọ maka ihe atụ ebe nha ziri ezi dị mkpa; ụmụ akwụkwọ kewaa ha dịka nri, mmiri, owuwu, ugbo ma ọ bụ ụlọ.",enterprise:"Ọnụọgụ na-agbanweghi agbanwe dị mkpa n’isi nri, nkwakọba, irrigation na iji ihe n’ọrụ.",quiz:[{question:"Olu na-agwa anyị…",options:["ohere mmiri na-ejide","otu ihe si ada ụda","afọ ihe","agba ya"],answer:0},{question:"Gịnị mere e ji tụọ nlezianya?",options:["Ibelata mmejọ na imefusị ihe","Ime ka ndekọ ghara ịba uru","Izo ọdịiche","Izere ọrụ"],answer:0},{question:"Kedu nke bụ unit nha?",options:["lita","ubi","onye nkuzi","onyonyo"],answer:0}]},
    {id:"PF-03-L5",title:"Mgbakwunye na Mwepụ n’Ndụ N’ezie",objective:"Jiri mgbakwunye na mwepụ dị mfe dozie nsogbu bara uru a maara.",teaching:["Mgbakwunye na-ejikọta ọnụọgụ.","Mwepụ na-egosi ihe fọdụrụ ma ọ bụ ọdịiche n’etiti ọnụọgụ abụọ.","Eserese, ihe na number line nwere ike inyere aka idozi nsogbu."],activity:"Dozie akụkọ mgbakọ gbasara mkpụrụ e kụrụ, iko mmiri e jiri, mkpụrụ osisi e kesara ma ọ bụ ngwaọrụ e gụrụ, jiri ihe mbụ tupu nọmba.",diy:"Mepụta nsogbu mgbakwunye abụọ na mwepụ abụọ dabere n’ọnọdụ obodo ma ọ bụ ubi wee dozie ha.",aiLayer:"AI Ogo 5 — Nyocha: onye nduzi gosi otu azịza dijitalụ ziri ezi na otu na-ezighi ezi; ụmụ akwụkwọ kọwaa nke ziri ezi na ihe kpatara ya.",enterprise:"Mgbakọ dị mfe na-akwado ịgụ stock, ịhazi ihe na nyochaa change, mana a naghị atụ ụmụaka ka ha mee azụmahịa.",quiz:[{question:"A na-eji mgbakwunye…",options:["jikọta ọnụọgụ","izo ọnụọgụ","ihichapụ nọmba niile","tụọ okpomọkụ naanị"],answer:0},{question:"Mwepụ nwere ike ịgwa anyị…",options:["ihe fọdụrụ","agba naanị","aha naanị","ọ dịghị ihe bara uru"],answer:0},{question:"Ụzọ ọma isi nyochaa mgbakọ bụ…",options:["iji ihe ma ọ bụ ụzọ ọzọ","ịnakwere azịza ọ bụla","ịwụfe nsogbu","detuo n’enweghị echiche"],answer:0}]},
    {id:"PF-03-L6",title:"Ide Nọmba na Ịchọpụta Usoro",objective:"Deba data dị mfe ma chọpụta usoro ma ọ bụ mgbanwe bụ isi.",teaching:["Tally na-egosi ugboro ole ihe mere.","Tebụl na-ahazi ozi n’ahịrị na kọlụm.","Usoro na-enyere anyị aka ịhụ mmegharị, mgbanwe na njikọ nwere ike ịdị."],activity:"Kpọkọta obere data klas ma ọ bụ ubi dịka ọnụ ọgụgụ osisi, iko mmiri kwa ụbọchị ma ọ bụ ọrụ mmụta kacha amasị, wee mepụta tally/tebụl.",diy:"Mepụta obere ndekọ otu izu nwere ihe ị hụrụ ma ọ dịkarịa ala ise ma dee ma ọ bụ kwuo ihe abụọ ị chọpụtara.",aiLayer:"Njikọta: onye nduzi nwere ike itinye otu data ahụ na spreadsheet ma ọ bụ AI ka ọ mee nchịkọta; ụmụ akwụkwọ tụnyere nchịkọta ahụ na ihe ha hụrụ.",enterprise:"Ndekọ na-enyere ndị mmadụ aka ịghọta ihe mere, belata ịtụ n’amaghị ama ma hazie nke ọma.",quiz:[{question:"Gịnị ka tally na-egosi?",options:["ugboro ole ihe mere","aha naanị","onyonyo naanị","ego naanị"],answer:0},{question:"Tebụl na-ahazi ozi site n’iji…",options:["ahịrị na kọlụm","agba naanị","nzuzo","akara enweghị usoro"],answer:0},{question:"Gịnị mere e ji edebe ndekọ?",options:["Iji mee mkpebi ka mma","Ka ozi pụọ","Iji zere mmụta","Iji dochie nlebara anya"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Gịnị bụ ebumnuche ịgụ ọnụ?",options:["Ịmata ole ihe dị","Ịmata agba naanị","Izo ihe","Ịgbanwe uru"],answer:0},{question:"Kedu okwu pụtara na ọnụọgụ abụọ bụ otu?",options:["Hà nhata","Karịa","Pere mpe","Ịkọ atụ"],answer:0},{question:"Gịnị ka a na-emekarị na ntule?",options:["Kọ atụ, tụọ, wee tụnyere","Tụọ n’amaghị ama ma kwụsị","Tụọ n’enweghị ide","Leghara nsonaazụ anya"],answer:0},{question:"Kedu ọrụ na-ejikọta ọnụọgụ?",options:["Mgbakwunye","Mwepụ naanị","Ntụnyere","Ịkọ atụ"],answer:0},{question:"A na-ejikarị lita tụọ…",options:["olu","afọ","agba","anya obodo naanị"],answer:0},{question:"Gịnị mere ndekọ ji baa uru?",options:["Ọ na-enyere anyị ịhụ ihe mere ma hazie ọdịnihu","Ọ na-ewepụ ihe akaebe","Ọ na-eme nọmba ka ha ghara ịba uru","Ọ na-egbochi ntụnyere"],answer:0},{question:"Ọ bụrụ na AI nyere azịza mgbakọ dị iche na nke gị, gịnị ka ị ga-eme?",options:["Nyochaa echiche site n’ihe ma ọ bụ ụzọ ọzọ","Chee na AI na-adị ziri ezi mgbe niile","Hichapụ ọrụ gị","Kekọrịta ozi nzuzo"],answer:0},{question:"Kedu nkà bara uru n’ịhazi akwa ubi?",options:["Nha","Ileghara oghere anya","Ịtụ n’amaghị ama naanị","Izere nọmba"],answer:0}],theory:["Kọwaa ụzọ abụọ e si eji nọmba kwa ụbọchị.","Kọwaa ọdịiche n’etiti karịa, pere mpe na hà nhata site n’ihe atụ gị.","Kọwaa ihe mere ntule ji baa uru tupu nha.","Mepụta otu nsogbu mgbakwunye ma ọ bụ mwepụ site n’ihe atụ nri, mmiri ma ọ bụ ubi ma dozie ya.","Kọwaa ihe mere mmadụ ji kwesị ịghọta mgbakọ kama ịdabere kpamkpam na calculator ma ọ bụ AI."],practical:"Mee obere nchọpụta mgbakọ: kọ atụ wee tụọ ihe ma ọ bụ ọnụọgụ atọ dị nchebe, deba nsonaazụ n’ime tebụl, dozie otu nsogbu mgbakwunye na otu mwepụ site na data ahụ, wee kọwaa otu usoro ma ọ bụ ntụnyere ị hụrụ."},
  evidence:["Tray ịgụ ọnụ ma ọ bụ ndekọ grouping","Kaadị ntụnyere","Ndekọ ntule na nha ihe ise","Tebụl nha ọnụọgụ","Nsogbu mgbakọ nwa akwụkwọ mepụtara","Ndekọ data otu izu","Checklist nlebara anya mgbakọ nke onye nduzi"],
  passport:["K: na-aghọta ịgụ ọnụ, ntụnyere, nha, mgbakwunye, mwepụ na ndekọ data dị mfe","P: na-atụ, na-edeba ma na-edozi nsogbu ọnụọgụ bara uru","D: na-enyocha nsonaazụ dijitalụ/AI site na echiche onwe ya","S: na-eji ngwaọrụ nha na akpa n’ụzọ dị nchebe","E: na-akọwa otú ịgụ ọnụ, nha na ndekọ si belata imefusị ihe ma kwado atụmatụ","L: na-ekwupụta echiche, na-arụkọ ọrụ na ndị ọzọ ma na-edozi mmejọ n’ụzọ bara uru"],
  trainerNotes:["Jiri ihe a na-emetụ aka tupu akara mgbakọ maka ụmụ akwụkwọ chọrọ ya.","Nabata nkọwa ọnụ na ngosi dịka ihe akaebe tinyere ọrụ e dere.","Jiri ihe atụ omenala na ngwaọrụ nha a na-ahụ n’obodo.","Ọ bụrụ na unit ọkọlọtọ ka siri ike, malite na unit informal kwụsiri ike wee banye na ọkọlọtọ nwayọọ nwayọọ.","Zere asọmpi ọsọ nke na-eme ụmụ akwụkwọ ihere; mesie echiche na ọganihu ike."],
  remediation:"Laghachi n’ihe a na-emetụ aka, matching otu-na-otu, number line na nha ugboro ugboro site n’iji otu unit n’otu oge. Belata range nọmba ma debe otu ebumnuche ọrụ ahụ.",
  extension:"Nwa akwụkwọ mepụta obere ihe ịma aka iji akụrụngwa, dịka ịgụ iko mmiri a na-eji kwa ụbọchị maka osisi ole na ole, wee tụọ aro mmezi dabere na data.",
  imagePrompts:["Ụmụaka Africa afọ 8–11 na-agụ mkpụrụ, na-atụ mmiri n’iko doro anya ma na-eji tape nha n’ubi mmụta a na-elekọta, ụmụ nwoke na ụmụ nwanyị ọnụ, ìhè eke, enweghị ederede a pụrụ ịgụ, agba ndụ ndụ na odo ọlaedo LIFEWS.","Ihe osise mmụta dị ọcha maka ụmụaka nwere akara isii: ịgụ ọnụ, ntụnyere, rula, olu mmiri, mgbakwunye dị mfe na tally, ndabere ọcha, enweghị okwu.","Obere ìgwè ụmụ akwụkwọ Africa na-edeba ọnụ ọgụgụ osisi n’ime tebụl dị mfe n’akwụkwọ n’akụkụ ubi ụlọ akwụkwọ, onye nduzi nọ nso, mmekọrịta dabara n’afọ, enweghị ederede a pụrụ ịgụ."]
};