import type { PF01Module } from "./pf-01";

type PF02Module = Omit<PF01Module,"code"> & { code:"PF-02" };

export const pf02Yo: PF02Module = {
  code:"PF-02",
  title:"Kíkà Ayé Tó Yí Mi Ká",
  level:"Pathways Foundation",
  age:"Ní àárín ọdún 8 sí 11; ìpín sí ipele ìmọ̀-kíkà gbọ́dọ̀ tẹ̀lé ìdánwò ìpilẹ̀, kì í ṣe ọjọ́-ori nìkan.",
  duration:"Ẹ̀kọ́ amọ̀nà mẹ́fà, àṣeyọrí kíkà, iṣẹ́ ọwọ́ àti ìdánwò",
  fieldworkHours:2,
  bigQuestion:"Báwo ni ọ̀rọ̀, àwòrán, àmì àti àpẹẹrẹ ṣe lè ràn mí lọ́wọ́ láti lóye ayé tó yí mi ká kí n sì huwa ní ààbò?",
  whyItMatters:"Ìmọ̀-kíkà ìpilẹ̀ túbọ̀ níyelori nígbà tí akẹ́kọ̀ọ́ bá lè so ohun tí a kọ sí ìgbésí-ayé ojoojúmọ́. Ẹ̀ka yìí ń kọ́ ìṣàkíyèsí, èdè ẹnu, ọ̀rọ̀-ìmọ̀, fífi apá ọ̀rọ̀ jọ àti kíkà tó wúlò nípasẹ̀ àpẹẹrẹ tó mọ̀mọ́ láti inú oúnjẹ, omi, agbára, ọgbà àti àwùjọ, láìfi àwọn tó bẹ̀rẹ̀ kíkà ní ipele oríṣìíríṣìí sílẹ̀.",
  outcomes:[
    "Mọ̀ pé ohun tí a kọ, àwòrán, àmì àti àpẹẹrẹ ń gbé ìtumọ̀ kalẹ̀.",
    "Ka kí o sì lo àwọn ọ̀rọ̀ tó wọ́pọ̀ nípa ayíká àti eto oúnjẹ.",
    "Báramu ọ̀rọ̀ tí a gbọ́, àwòrán àti ọ̀rọ̀ tí a kọ.",
    "Lo àyíká ọ̀rọ̀ àti ìṣàkíyèsí dáadáa láti mọ ìtumọ̀ kí o sì ṣàyẹ̀wò rẹ̀.",
    "Ṣẹ̀dá ohun ìmọ̀ tó wúlò tí ó ní àwòrán, ọ̀rọ̀ àti ìsọfúnni.",
    "Lo ìtìlẹ́yìn díjítà tàbí AI lábẹ́ amọ̀nà láti fiwé, pín sí ẹ̀ka tàbí ṣàyẹ̀wò ọ̀rọ̀ láìpín ìsọfúnni àdáni."
  ],
  vocabulary:["ọ̀rọ̀","lẹ́tà","ohùn","àwòrán","àmì","àpẹẹrẹ","aami-orúkọ","ìtumọ̀","kà","ṣàyẹ̀wò","oúnjẹ","omi","ewéko","agbára","ààbò"],
  materials:["káàdì àwòrán tó yẹ fún agbègbè","káàdì ọ̀rọ̀","káàdì alfabeti/ohùn tó bá èdè ẹ̀kọ́ mu","àpò oúnjẹ tó mọ́ tàbí ẹ̀dà aami-orúkọ","ohun èlò ilé tàbí ọgbà tó ní ààbò","ìwé àti pẹ́ńsù/àmì","ẹ̀rọ díjítà tó wà lábẹ́ ìṣàkóso olùkọ́ nígbà tó bá yẹ"],
  safety:[
    "Lo ohun èlò àti àpò tó mọ́, tó sì ní ààbò nìkan.",
    "Má ṣe fi àṣìṣe kíkà ṣe ẹlẹ́yà tàbí fi ṣe ìdíje láàárín àwọn akẹ́kọ̀ọ́.",
    "Mú ẹ̀kọ́ ohun-lẹ́tà bá èdè tí a yàn mu; má ṣe ro pé òfin Gẹ̀ẹ́sì yóò ṣiṣẹ́ bákan náà fún Hausa, Arabic, Yorùbá, Igbo tàbí French.",
    "Má ṣe jẹ́ kí akẹ́kọ̀ọ́ ya fọ́tò ènìyàn tí a lè dá mọ̀, àdírẹ́sì tàbí ìwé àdáni kí wọ́n sì rán án sí irinṣẹ́ AI."
  ],
  lessons:[
    {id:"PF-02-L1",title:"Àwòrán, Àmì àti Ìtumọ̀",objective:"Ṣàlàyé bí àwòrán, àmì, àpẹẹrẹ àti ọ̀rọ̀ ṣe ń fi ìsọfúnni hàn.",teaching:["A kì í ka ìwé nìkan; a tún ń ka àmì, àpẹẹrẹ, àwòrán, aami-orúkọ àti ipo.","Àpẹẹrẹ lè sọ ìsọfúnni kíákíá, ṣùgbọ́n ìtumọ̀ rẹ̀ dá lórí ìmọ̀ tó wọ́pọ̀.","Olùkà tó dáa máa kọ́kọ́ kíyèsi kí ó tó pinnu ìtumọ̀ ohun kan."],activity:"Ìṣàwárí ìtumọ̀: wo àwọn àmì tí a mọ̀ àti káàdì àwòrán, kí o ṣàlàyé ohun tí ọkọọkan ń gbìmọ̀ láti sọ.",diy:"Ṣe àpẹẹrẹ ààbò tàbí ìtọju kan fún ọgbà ẹ̀kọ́ tàbí yàrá, kí o sì ṣàlàyé rẹ̀ ní ẹnu.",aiLayer:"AI Ipele 1 — Ìdámọ̀: yà àmì tí ènìyàn ṣe, abajade ìwádìí díjítà àti ìmọ̀ràn AI sí ọ̀tọ̀; gbogbo wọn ṣi nílò ìtúmọ̀ ènìyàn.",enterprise:"Àmì àti aami-orúkọ tó ṣe kedere ń ràn ènìyàn lọ́wọ́ láti lóye ọjà, ibi àti iṣẹ́; ìbánisọ̀rọ̀ tó dáa ń ṣẹ̀dá ìyelori.",quiz:[{question:"Kí ni ó lè sọ ìtumọ̀?",options:["Ọ̀rọ̀, àwòrán àti àpẹẹrẹ","Ìwé gígùn nìkan","Nọ́mbà nìkan","Kò sí nǹkan kankan"],answer:0},{question:"Kí ni ká ṣe kí a tó pinnu ìtumọ̀ àmì kan?",options:["Kíyèsi dáadáa","Foju kọ ọ","Ba a jẹ́","Gboju láìwo"],answer:0},{question:"Aami-orúkọ ni a fi…",options:["dá ohun kan mọ̀ tàbí ṣàlàyé rẹ̀","pa gbogbo ìsọfúnni mọ́","jẹ́ kí kíkà ṣòro","rọ́pò ààbò"],answer:0}]},
    {id:"PF-02-L2",title:"Ọ̀rọ̀ Nínú Oúnjẹ, Omi àti Agbára",objective:"Mọ̀ kí o sì ka àwọn ọ̀rọ̀ tó wúlò nínú ipo ojoojúmọ́ nípa oúnjẹ, omi àti agbára.",teaching:["Ọ̀rọ̀ tó mọ̀mọ́ rọrùn láti kọ́ nígbà tí a bá so mọ́ ohun àti ìṣe gidi.","Ọ̀rọ̀ lè jẹ́ orúkọ ohun, ìṣe tàbí ànímọ́.","Kíkà léraléra ń mú ìmúlò àti ìgboyà pọ̀ síi."],activity:"Yí ká àwọn ibùdó ọ̀rọ̀ fún oúnjẹ, omi, ewéko, irinṣẹ́ àti agbára; báramu káàdì ọ̀rọ̀ kọọkan mọ́ àwòrán tàbí ohun tó ní ààbò.",diy:"Ṣẹ̀dá káàdì àwòrán-ọ̀rọ̀ mẹ́wàá fúnra rẹ, kí o sì máa ka wọn fún alábàáṣiṣẹ́.",aiLayer:"AI Ipele 2 — Ìbáṣepọ̀ lábẹ́ amọ̀nà: olùkọ́ béèrè lọwọ irinṣẹ́ AI fún gbolóhùn rọrùn pẹ̀lú àwọn ọ̀rọ̀ tí a yàn; akẹ́kọ̀ọ́ ṣàyẹ̀wò bóyá wọn lóye tí wọ́n sì bá agbègbè mu.",enterprise:"A nílò ọ̀rọ̀ tó péye láti pe, ṣàlàyé àti ṣètò ọjà àti iṣẹ́ tó wúlò.",quiz:[{question:"Kí ni ń ràn ọ lọwọ láti kọ́ ọ̀rọ̀ tuntun?",options:["So mọ́ àwòrán tàbí ohun","Má wo o mọ́","Pa a mọ́","Fo gbogbo ohun rẹ̀"],answer:0},{question:"Kíkà léraléra lè mú…",options:["ìgboyà àti ìmúlò pọ̀","didara omi pọ̀ laifọwọyi","oju-ọjọ yí padà","batiri tóbi"],answer:0},{question:"Èwo ni ọ̀rọ̀ eto-oúnjẹ?",options:["irúgbìn","ọ̀rọ̀ aṣínà","satẹlaiti nìkan","ìdákẹ́jẹ"],answer:0}]},
    {id:"PF-02-L3",title:"Lẹ́tà, Ohùn àti Apá Ọ̀rọ̀",objective:"Lo àjọṣe lẹ́tà-ohùn tàbí àpẹẹrẹ ìkọ̀wé tó yẹ fún èdè láti ka àwọn ọ̀rọ̀ tí a mọ̀.",teaching:["Àwọn èdè tí a kọ ń ṣàfihàn ohun èdè ní ọ̀nà tó yàtọ̀.","A lè wa lẹ́tà, ohùn, sílábù tàbí apá ọ̀rọ̀ tí a ti mọ̀.","Tí ọ̀rọ̀ bá ṣòro, a lè lọ díẹ̀díẹ̀, pín un sí apá, kí a sì lo àyíká rẹ̀."],activity:"Kọ àwọn ọ̀rọ̀ tí a mọ̀ pẹ̀lú lẹ́tà gbigbe, káàdì sílábù tàbí ohun ìkọ̀wé tó yẹ fún èdè ẹ̀kọ́.",diy:"Ṣẹ̀dá àtẹ̀gùn ọ̀rọ̀ márùn-ún tí wọ́n jọra, kí o sì samisi apá tí o mọ̀ nínú ọkọọkan.",aiLayer:"AI Ipele 3 — Ìdámọ̀ àpẹẹrẹ: pín ọ̀rọ̀ sí ẹgbẹ́ gẹ́gẹ́ bí àpẹẹrẹ tí a rí tàbí tí a gbọ́, kí o sì fiwé pẹ̀lú ìmọ̀ràn díjítà.",enterprise:"Ìdámọ̀ àpẹẹrẹ ń ṣe iranlọwọ fún kíkà iye, fifi aami, ìkọ̀wé àkọsílẹ̀ àti ìṣàkóso didara.",quiz:[{question:"Tí ọ̀rọ̀ bá ṣòro, ọ̀nà tó dáa ni…",options:["pín un sí apá rọrùn","fi sílẹ̀ lẹ́sẹ̀kẹsẹ̀","dá ọ̀rọ̀ mìíràn sílẹ̀","bo o"],answer:0},{question:"Ṣé gbogbo èdè mẹ́fà lo òfin lẹ́tà-ohùn kan naa?",options:["Rárá","Bẹ́ẹ̀ ni","Ọjọ́ Ajé nìkan","Nínú ọgbà nìkan"],answer:0},{question:"Rírí apá ọ̀rọ̀ tó tún máa ń farahàn jẹ́…",options:["ìdámọ̀ àpẹẹrẹ","ìsòfò","fífipamọ́","fifi owó"],answer:0}]},
    {id:"PF-02-L4",title:"Kíkà Aami-Orúkọ àti Ìtọ́nisọ́nà",objective:"Yọ ìsọfúnni rọrùn tó wúlò jáde láti aami-orúkọ, àmì tàbí ìtọ́nisọ́nà tó yẹ fún ọjọ́-ori.",teaching:["Kíkà tó wúlò ń ràn wa lọwọ láti ṣe yíyan tó ní ààbò.","Akọlé, àwòrán, nọ́mbà àti ọ̀rọ̀ pataki lè ràn wa lọwọ láti rí ìsọfúnni.","A gbọ́dọ̀ béèrè lọ́wọ́ àgbàlagbà tí a gbẹ́kẹ̀lé bí ìsọfúnni ààbò kò bá ye wa."],activity:"Ka aami-orúkọ tí olùkọ́ pèsè fún àpò irúgbìn, ìkòkò omi tàbí irinṣẹ́ ọgbà; mọ orúkọ, ìlò àti ìtọ́nisọ́nà kan.",diy:"Ṣẹ̀dá aami-orúkọ apá mẹ́ta fún ohun kan ní yàrá tàbí ọgbà: ORÚKỌ → ÌLÒ → ÌTỌJU/ÀÀBÒ.",aiLayer:"AI Ipele 4 — Ìbéèrè tó ní ààlà: olùkọ́ fi hàn bí a ṣe lè béèrè fún àlàyé rọrùn ti aami-orúkọ tí kì í ṣe ìsọfúnni àdáni; akẹ́kọ̀ọ́ fiwé pẹ̀lú atilẹba kí ó sì rí ohun tó ṣòfo.",enterprise:"Aami-orúkọ tó péye ń kọ́ ìgbẹ́kẹ̀lé, ààbò àti iṣowo oníṣe-dára; aami eke tàbí aláìmọ̀ lewu.",quiz:[{question:"Kí ló dé tí a fi ń ka ìtọ́nisọ́nà?",options:["Láti mọ bí a ṣe le ṣe ohun ní ààbò àti pípé","Láti pa wọn run","Láti má lóye","Fún ọṣọ nìkan"],answer:0},{question:"Tí ìsọfúnni ààbò kò bá ye, kí ni ká ṣe?",options:["béèrè lọ́wọ́ àgbàlagbà tí a gbẹ́kẹ̀lé","gboju pẹ̀lú irinṣẹ́ ewu","foju kọ ọ","yí aami padà"],answer:0},{question:"Aami-orúkọ tó dáa gbọ́dọ̀ jẹ́…",options:["kedere àti pípé","ẹ̀tan ní ìmọ̀ọ́mọ̀","aláìkà","aṣírí"],answer:0}]},
    {id:"PF-02-L5",title:"Ṣàyẹ̀wò Ìtumọ̀",objective:"Lo àyíká, àwòrán àti ìrànlọ́wọ́ tó dájú láti ṣàyẹ̀wò pé ìtumọ̀ kan bójú mu.",teaching:["Olùkà tó dáa máa ń ṣàyẹ̀wò ìtumọ̀ dipo gbigba gboju àkọ́kọ́.","Àwòrán àti ọ̀rọ̀ tó yí ọ̀rọ̀ kan ká ni ìtanràn àyíká.","Irinṣẹ́ díjítà àti AI lè ṣe àṣìṣe, nítorí náà ìsọfúnni pataki gbọ́dọ̀ jẹ́rìí."],activity:"Ka gbolóhùn kukuru pẹ̀lú àwòrán tí ọ̀rọ̀ kan kò bá mu; wa a kí o sì tún un ṣe.",diy:"Ṣe kaadi tàbí aami-ìwé ‘Kà–Ronu–Ṣàyẹ̀wò’ pẹ̀lú ìgbésẹ̀ àwòrán mẹ́ta.",aiLayer:"AI Ipele 5 — Ìdánilójú: olùkọ́ fi àlàyé AI kan tó péye àti ọkan tí kò péye hàn; akẹ́kọ̀ọ́ lo ẹ̀rí tí ó rí láti yan eyi tó dáa.",enterprise:"Ṣíṣe ìsọfúnni ní ìdánilójú dènà àṣìṣe nínú àkọsílẹ̀, aami-orúkọ, iye àti ìbánisọ̀rọ̀ oníbàárà.",quiz:[{question:"Ìtanràn àyíká ń ràn wa lọwọ láti…",options:["mọ ìtumọ̀","gbàgbé ọrọ̀","pín ọ̀rọ̀ aṣínà","má wo"],answer:0},{question:"Ṣé a gbọ́dọ̀ gba gbogbo ohun tí AI kọ laifọwọyi?",options:["Rárá","Bẹ́ẹ̀ ni","Tí ó bá gùn nìkan","Tí ó bá ní àwọ̀ nìkan"],answer:0},{question:"Àtẹ̀le wo ni ó wúlò?",options:["Kà–Ronu–Ṣàyẹ̀wò","Gboju–Pa mọ́–Lọ","Daakọ–Gbàgbé–Pín","Fo–Fo–Fo"],answer:0}]},
    {id:"PF-02-L6",title:"Ìtọ́sọ́nà Àwòrán-Ọ̀rọ̀ Mi",objective:"Ṣẹ̀dá kí o sì ṣàfihàn ìtọ́sọ́nà àwòrán-ọ̀rọ̀ tó wúlò pẹ̀lú ọ̀rọ̀ àti aami tó péye.",teaching:["Onkọ̀wé yan ìsọfúnni gẹ́gẹ́ bí ẹni tí yóò ka àti ìdí tí a fi kọ ọ.","Ìtọ́sọ́nà tó wúlò gbọ́dọ̀ ní ètò, rọrùn láti ka, tó sì péye.","Ṣíṣe ìsọfúnni tún jẹ́ ojúṣe; a máa ń ṣàyẹ̀wò kí a tó pín."],activity:"Gbero ìtọ́sọ́nà kékeré lórí ọ̀kan: ọgbà ilé-ẹ̀kọ́, omi mímọ́, eroja oúnjẹ, lílo agbára ní ààbò tàbí ẹ̀kọ́ àwùjọ.",diy:"Ṣe ìtọ́sọ́nà àwòrán-ọ̀rọ̀ mẹ́fà; ọkọọkan ní àwòrán, ọ̀rọ̀ pataki àti òtítọ́ tàbí ìtọ́nisọ́nà kukuru, kí o sì ka/tabi ṣàfihàn rẹ̀ fún ẹlòmíràn.",aiLayer:"Ìṣọ̀kan: AI lè daba ọ̀rọ̀ tàbí gbolóhùn labẹ iṣakoso olùkọ́; akẹ́kọ̀ọ́ gbọ́dọ̀ yan, túnṣe, kí o sì ṣàlàyé ohun tó parí.",enterprise:"Ohun ìsọfúnni tó ṣe kedere ń ṣẹ̀dá ìyelori nípasẹ̀ ìbánisọ̀rọ̀ àti àpẹrẹ; didara túmọ̀ sí ìwúlò, ìpeye àti ìtọju.",quiz:[{question:"Ta ni olùgbọ́/olùkà?",options:["Àwọn ènìyàn tí a ṣe ìsọfúnni fún","Onkọ̀wé nìkan","Iru irúgbìn kan","Ọ̀rọ̀ aṣínà"],answer:0},{question:"Kí ni ká ṣe kí a tó pín ìtọ́sọ́nà?",options:["Ṣàyẹ̀wò ìpeye rẹ̀","Fi ìsọfúnni àdáni kun","Yọ gbogbo aami","Daakọ láìka"],answer:0},{question:"Ohun ìsọfúnni tó dáa gbọ́dọ̀ jẹ́…",options:["wúlò, kedere àti pípé","ẹ̀tan","ewu","aláìkà"],answer:0}]}
  ],
  finalAssessment:{
    mcq:[{question:"Èwo ni àpẹẹrẹ kíkà tó wúlò?",options:["Kíkà àmì ààbò","Fífòju kọ aami","Fífipamọ́ ọ̀rọ̀","Bíbà ìtọ́nisọ́nà jẹ́"],answer:0},{question:"Kí ni ń ràn olùkà lọwọ láti mọ ọ̀rọ̀ tuntun?",options:["Àyíká àti apá ọ̀rọ̀","Títì ìwé","Gboju lasan","Fífò gbogbo ìtanràn"],answer:0},{question:"Kí ló dé tí àwòrán fi wúlò ní ìbẹ̀rẹ̀ ìmọ̀-kíkà?",options:["Ó lè ṣe atilẹyin ìtumọ̀","Ó mú kí ọ̀rọ̀ má ṣe pataki mọ́","Ó rọ́pò ààbò","Ó jẹ́ kí gbogbo ìtumọ̀ péye"],answer:0},{question:"Ìwà wo ni aami-orúkọ yẹ kí ó ní?",options:["Ìpeye","Ẹ̀tan","Ìdàrúdàpọ̀","Aṣírí"],answer:0},{question:"Kí ni ká ṣe kí a tó pín ìsọfúnni AI pataki?",options:["Ṣàyẹ̀wò rẹ̀","Kò sí nkankan","Fi ìsọfúnni àdáni kun","Foju kọ ọrọ atilẹba"],answer:0},{question:"Àtẹ̀le wo ló ṣe atilẹyin kíkà pẹ̀lú àkíyèsí?",options:["Kíyèsi–Kà–Ronu–Ṣàyẹ̀wò","Gboju–Pín–Gbàgbé","Pa mọ́–Daakọ–Lọ","Yára–Foju kọ–Fi ranṣẹ́"],answer:0},{question:"Kí ló dé tí ẹ̀kọ́ kíkà fi lè yàtọ̀ láàárín Gẹ̀ẹ́sì, Arabic àti Yorùbá?",options:["Eto ìkọ̀wé àti ohun wọn yàtọ̀","Gbogbo èdè jọ","Ọ̀kan nìkan ni ọ̀rọ̀","A kò lè kọ́ wọn"],answer:0},{question:"Ìtọ́sọ́nà àwòrán-ọ̀rọ̀ ṣẹ̀dá ìyelori bí ó bá jẹ́…",options:["wúlò, kedere àti pípé","eke","ewu","aláìkà"],answer:0}],
    theory:["Ṣàlàyé nǹkan mẹ́ta nínú àwùjọ rẹ tí a lè ‘ka’ yàtọ̀ sí ìwé.","Yan ọ̀rọ̀ marun tí o mọ̀, kí o ṣàlàyé ọ̀nà tí o fi mọ̀ tàbí ka ọkọọkan.","Ṣàlàyé bí àwòrán tàbí ìtanràn àyíká ṣe ràn ọ lọwọ láti lóye ọ̀rọ̀ tuntun.","Ṣàlàyé idi tí aami-orúkọ àti ìtọ́nisọ́nà fi gbọ́dọ̀ péye tí wọ́n sì rọrùn láti lóye.","Ṣàpèjúwe ọ̀nà kan láti ṣàyẹ̀wò àlàyé díjítà tàbí AI kí o tó lò ó."],
    practical:"Ṣẹ̀dá kí o sì ṣàfihàn ní ẹnu ìtọ́sọ́nà àwòrán-ọ̀rọ̀ mẹ́fà lórí koko tó mọ̀ nípa oúnjẹ, omi, agbára, ọgbà tàbí ẹ̀kọ́ àwùjọ. Gbogbo apá gbọ́dọ̀ ní àwòrán tó yẹ, ọ̀rọ̀ pataki tó péye àti òtítọ́ tàbí ìtọ́nisọ́nà kukuru tí akẹ́kọ̀ọ́ fúnra rẹ ṣẹ̀dá. Olùkọ́ yóò wo ìdámọ̀, ìtumọ̀, ètò, ìpeye àti ìbánisọ̀rọ̀, kì í ṣe ìkọ̀wé ọwọ́ nìkan."
  },
  evidence:["Káàdì àwòrán-ọ̀rọ̀ mẹ́wàá","Àtẹ̀gùn àpẹẹrẹ ọ̀rọ̀","Aami-orúkọ iṣẹ́ apá mẹ́ta","Kaadi Kà–Ronu–Ṣàyẹ̀wò","Ìtọ́sọ́nà àwòrán-ọ̀rọ̀ mẹ́fà","Àkọsílẹ̀ olùkọ́ lórí kíkà ẹnu àti ìtumọ̀"],
  passport:["K: mọ̀ pé ọ̀rọ̀, àmì, àpẹẹrẹ àti ọrọ̀ iṣẹ́ jẹ́ orísun ìtumọ̀","P: ṣẹ̀dá àti lo aami-orúkọ àti ìtọ́sọ́nà àwòrán-ọ̀rọ̀","D: lo ìtìlẹ́yìn díjítà/AI lábẹ́ amọ̀nà láti pín tàbí ṣàyẹ̀wò èdè láìfi ìpamọ́ sí ewu","S: ka ìsọfúnni ààbò ìpilẹ̀ tàbí béèrè ìrànlọ́wọ́","E: ṣàlàyé bí ìbánisọ̀rọ̀ àti aami-orúkọ tó péye ṣe ń ṣẹ̀dá ìgbẹ́kẹ̀lé àti ìyelori","L: ka/tabi ṣàfihàn fún ẹlẹgbẹ́, gba ìtóni, kí o sì ṣàyẹ̀wò iṣẹ́ kí o tó pín"],
  trainerNotes:["Kọ́ ìmọ̀-kíkà nínú èdè ẹ̀kọ́ tí a yàn; ṣe ìbámu fífi lẹ́tà sí ohun sí èdè yẹn dipo títumọ̀ phonics Gẹ̀ẹ́sì lọ́nà taara.","Gba ìdáhùn ẹnu, títẹ̀lé àmi, ìbáramu àti yíyan àwòrán gẹ́gẹ́ bí ẹ̀rí nígbà tí ìmọ̀-kíkà ń dàgbà.","Lo ohun àgbègbè àti àwòrán tó mọ̀mọ́ láìlo àfojúsùn ẹlẹ́yà.","Fún Arabic, lo ohun èlò RTL; fún Yorùbá àti Igbo, pa àmì ohun/diacritic mọ́ níbi tí ó yẹ; fún French, kọ́ àjọṣe ohun àti ìkọ̀wé tó yẹ.","Ṣe ìdánwò lórí ìtumọ̀ àti ìlọsíwájú, kì í ṣe accent."],
  remediation:"Dín iye ọ̀rọ̀ tí a ń ṣiṣẹ́ pọ̀, mú ìbáramu àwòrán-ohun pọ̀, lo kíkà ẹnu léraléra àti iṣẹ́ lẹ́tà/sílábù pẹ̀lú ọ̀pọ̀ ìmọ̀-ara, ṣùgbọ́n pa ìdí kíkà tó wúlò mọ́.",
  extension:"Akẹ́kọ̀ọ́ ṣe àyẹ̀wò àmì àti aami-orúkọ ní ibi ẹ̀kọ́ lábẹ́ amọ̀nà, kí o sì daba aami tuntun tàbí ìmúdára fún ìrọrùn wiwọle tàbí ààbò.",
  imagePrompts:["Ìran photorealistic ti ẹ̀kọ́ ìmọ̀-kíkà ìpilẹ̀ ní Africa, ọmọkùnrin àti ọmọbìnrin ọdún 8–11 ń báramu káàdì àwòrán pẹ̀lú ọ̀rọ̀ nípa ewéko, omi, oúnjẹ àti ohun agbára rọrùn, olùkọ́ aláàánú, ibi ẹ̀kọ́ àwùjọ tó mọ́, kò sí ọrọ̀ tí a lè ka, àwọ̀ aláwọ̀-ewe LIFEWS àti ofeefee gbígbóná.","Àwòrán ẹ̀kọ́ ọmọde tó fi àpò irúgbìn, ìkòkò omi, àpẹẹrẹ ewéko àti àmì ààbò hàn pẹ̀lú àpẹẹrẹ gilasi ìtóbi, abẹ́lẹ̀ funfun, aami nìkan, kò sí ọrọ̀.","Ìran photorealistic ti ẹgbẹ́ kékeré ọmọ Africa ń ṣe ìtọ́sọ́nà àwòrán-ọ̀rọ̀ pẹ̀lú àwòrán irugbin ọgbà àti ohun omi, pẹ́ńsù àti káàdì lórí tábìlì, ìfowosowopo tó kó gbogbo ènìyàn sí, ìmọ́lẹ̀ adayeba, kò sí ọrọ̀ tí a lè ka."]
};