import type { AppLanguage } from "@/lib/i18n6";
import type { PF01Module } from "./pf-01";

type PF11Module = Omit<PF01Module,"code"> & { code:"PF-11" };

const en: PF11Module = {
  code:"PF-11", title:"Digital Beginnings", level:"Pathways Foundation",
  age:"Approximately 8–11 years; all device use should be supervised and adapted to learner readiness.",
  duration:"6 guided lessons plus supervised digital practice and assessment time", fieldworkHours:2,
  bigQuestion:"How can we use digital devices safely, responsibly and usefully for learning and simple records?",
  whyItMatters:"Digital tools can support learning, communication, observation and recordkeeping, but they must be used with care. This module introduces common devices, basic input and navigation, simple data entry, privacy, online safety, responsible AI use and digital evidence without assuming prior device ownership or access.",
  outcomes:["Identify common digital devices and explain simple uses.","Use basic input controls such as keyboard, touchscreen or mouse with supervision.","Enter and save simple information in a structured digital record.","Recognize private information and explain why it should be protected.","Distinguish trusted guidance from suspicious or unverified digital content.","Use a simple checklist for safe and responsible device use.","Describe one appropriate use of AI and one reason AI outputs must be checked.","Create a basic digital learning record or evidence entry."],
  vocabulary:["digital","device","screen","keyboard","mouse","touchscreen","file","record","data","save","open","close","password","privacy","online","link","message","AI","verify","evidence"],
  materials:["supervised shared digital device where available","printed device picture cards","paper keyboard or interface mock-up","simple digital record template","privacy scenario cards","safe browsing scenario cards","learner notebook","optional offline training application"],
  safety:["Learners must not share passwords, access codes, home addresses, private phone numbers or other unnecessary personal data.","Use only facilitator-approved websites, apps, accounts and devices.","Do not ask learners to create public social-media accounts for this module.","Any online contact, message or link that feels unsafe, confusing or inappropriate should be shown to a trusted adult.","AI outputs are not automatically true and must not replace teacher, safeguarding or safety guidance.","Use shared devices in ways that respect accessibility, turn-taking and privacy."],
  lessons:[
    {id:"PF-11-L1",title:"Meet Digital Devices",objective:"Identify common devices and match them to appropriate uses.",teaching:["Digital devices include phones, tablets, computers and some sensors or smart equipment.","Different devices are designed for different tasks such as writing, measuring, communicating or storing information.","A device is a tool; safe and responsible use depends on the user."],activity:"Match device picture cards to tasks such as typing, taking a supervised photo, recording measurements, calculating and viewing learning content.",diy:"Create a My Digital Tools chart showing five devices and one safe use for each.",aiLayer:"AI Layer 1 — Recognition: compare an AI-generated device-use list with class knowledge and correct any unrealistic examples.",enterprise:"Digital tools are used in farming, retail, maintenance, logistics, education and many other services.",quiz:[{question:"Which is a digital device?",options:["Tablet","Spoon","Stone","Leaf"],answer:0},{question:"Can a digital device be used for records?",options:["Yes","No","Only for games","Only by adults"],answer:0},{question:"What determines safe device use?",options:["Responsible behaviour and guidance","The screen colour","The brand only","Guessing"],answer:0}]},
    {id:"PF-11-L2",title:"Input, Navigate and Save",objective:"Use basic controls to enter, correct and save simple information.",teaching:["Keyboards, touchscreens and mice help users give instructions to a device.","Digital work often involves opening, entering, checking and saving information.","Checking before saving reduces avoidable mistakes."],activity:"Use a paper interface first, then a supervised device to enter a short name or non-sensitive practice label, number and date into a simple template.",diy:"Complete a five-entry practice log using ENTER → CHECK → SAVE.",aiLayer:"AI Layer 2 — Error checking: compare two digital entries and ask which contains an obvious error before using an AI tool to confirm.",enterprise:"Accurate data entry matters in stock records, work logs, farm records and customer service.",quiz:[{question:"What should happen before saving a record?",options:["Check it","Delete it","Share the password","Guess"],answer:0},{question:"Which is an input tool?",options:["Keyboard","Cup","Rope","Leaf"],answer:0},{question:"Why save a file?",options:["So the information can be used later","To make it disappear","To remove all mistakes automatically","To publish it publicly"],answer:0}]},
    {id:"PF-11-L3",title:"Digital Records and Evidence",objective:"Create a simple structured digital observation record.",teaching:["A useful record has clear fields such as date, item, observation and quantity.","Digital evidence should be accurate and connected to the real activity.","Photos or files should only be collected when allowed and necessary."],activity:"Enter a fictional or real supervised garden observation such as date, plant type, height and note into a digital template.",diy:"Create a three-entry Digital Observation Log.",aiLayer:"AI Layer 3 — Data support: ask AI to summarize a sample table, then compare the summary with the original entries for accuracy.",enterprise:"Structured records support monitoring, quality checks and decision-making.",quiz:[{question:"Which field belongs in a useful observation record?",options:["Date","Secret password","Private bank details","Rumour"],answer:0},{question:"Should digital evidence match the real activity?",options:["Yes","No","Only sometimes","Only if shared publicly"],answer:0},{question:"Why use structured fields?",options:["To keep records clear and comparable","To hide information","To remove dates","To make errors harder to find"],answer:0}]},
    {id:"PF-11-L4",title:"Privacy and Safe Information",objective:"Recognize private information and practise protecting it.",teaching:["Some information should be kept private, including passwords and sensitive personal details.","Not every app, website or person needs access to personal information.","When unsure, learners should ask a trusted adult before sharing."],activity:"Sort scenario cards into SAFE TO SHARE IN CLASS / ASK FIRST / KEEP PRIVATE.",diy:"Create a Privacy Shield card listing five types of information that should not be shared casually.",aiLayer:"AI Layer 4 — Privacy check: review fictional prompts and identify which requests ask for unnecessary personal data.",enterprise:"Responsible organizations protect customer, worker and learner information.",quiz:[{question:"Which should be kept private?",options:["Password","Favourite school subject","A public weather fact","A plant height measurement"],answer:0},{question:"What should you do if a website asks for private information unexpectedly?",options:["Ask a trusted adult","Share it quickly","Use someone else's details","Ignore all safety rules"],answer:0},{question:"Why protect personal data?",options:["To reduce misuse and protect privacy","To make devices slower","To avoid learning","To hide public facts"],answer:0}]},
    {id:"PF-11-L5",title:"Think Before You Trust",objective:"Recognize that online and AI-generated information may be wrong, misleading or incomplete.",teaching:["Digital information can come from reliable and unreliable sources.","A confident-looking answer can still be incorrect.","Verification means checking important claims against trusted evidence or guidance."],activity:"Compare three fictional online claims about a garden topic and decide which would need verification before use.",diy:"Create a STOP → CHECK SOURCE → COMPARE → ASK → USE decision card.",aiLayer:"AI Layer 5 — Verification: ask AI one simple factual question, then verify the answer using a facilitator-approved source or direct observation.",enterprise:"Good digital decisions reduce errors, misinformation and poor service.",quiz:[{question:"Is every online claim true?",options:["No","Yes","Only if it has a picture","Only if it sounds confident"],answer:0},{question:"What does verify mean?",options:["Check against trusted evidence","Repeat a claim","Share quickly","Ignore the source"],answer:0},{question:"Should AI replace safety guidance?",options:["No","Yes","Always","Only for children"],answer:0}]},
    {id:"PF-11-L6",title:"My Safe Digital Learning Record",objective:"Combine basic device use, data entry, privacy and verification in one supervised task.",teaching:["Responsible digital use combines skill, accuracy, privacy and judgment.","A good digital record is useful without collecting unnecessary personal information.","Learners should be able to explain what they entered, why it is accurate and how they protected privacy."],activity:"Learners create a short supervised digital record from a classroom or garden activity and explain the fields, evidence and safety choices.",diy:"Complete a Digital Beginnings Portfolio containing one device-use chart, observation log, privacy card, verification example and reflection.",aiLayer:"Integration — responsible use: use AI for one optional suggestion, then document how the suggestion was checked before inclusion.",enterprise:"Digital literacy supports future learning and work across food, water, energy and service sectors.",quiz:[{question:"What makes digital use responsible?",options:["Accuracy, privacy, safety and verification","Sharing everything","Ignoring mistakes","Trusting every output"],answer:0},{question:"What should a digital record avoid?",options:["Unnecessary private information","Dates","Observations","Measurements"],answer:0},{question:"Why explain how information was checked?",options:["To show it is based on evidence","To make the file longer","To hide mistakes","To avoid responsibility"],answer:0}]}
  ],
  finalAssessment:{mcq:[{question:"Which is a digital device?",options:["Computer","Plate","Stone","Leaf"],answer:0},{question:"What should you do before saving a record?",options:["Check it","Share a password","Delete the date","Guess"],answer:0},{question:"Which information is private?",options:["Password","Plant height","Lesson title","Weather symbol"],answer:0},{question:"Should every online claim be trusted?",options:["No","Yes","Only if repeated","Only if colourful"],answer:0},{question:"What does verification mean?",options:["Checking against trusted evidence","Copying","Guessing","Posting"],answer:0},{question:"How should AI be used?",options:["As a tool whose output must be checked","As automatic truth","Instead of safeguarding guidance","To request private data"],answer:0},{question:"Why are structured digital records useful?",options:["They make information easier to understand and compare","They remove all errors automatically","They require private data","They replace observation"],answer:0},{question:"What should a learner do with a suspicious link or message?",options:["Show a trusted adult","Open it immediately","Forward it to everyone","Enter a password"],answer:0}],theory:["Name four digital devices and describe one appropriate use for each.","Explain why checking information before saving matters.","Give four examples of information that should be kept private.","Explain how you would verify an online or AI-generated claim.","Describe how a digital observation record could support a school garden or classroom project."],practical:"Using a supervised device or approved simulation, enter a simple observation record containing a date, non-sensitive item name, quantity or measurement and short note. Check the entry, save it, identify one privacy rule and explain how one factual claim would be verified."},
  evidence:["My Digital Tools chart","Five-entry practice log","Three-entry Digital Observation Log","Privacy Shield card","Verification decision card","Verified AI/digital example","Digital Beginnings Portfolio","Facilitator practical assessment record"],
  passport:["K: identifies basic devices, digital records, privacy and verification concepts","P: enters, checks and saves simple supervised digital information","D: creates structured records and verifies online/AI-supported information","S: protects passwords and personal information and reports unsafe digital contact","E: connects digital accuracy and records to responsible work and service","L: takes turns, asks for help when unsure and explains responsible digital choices"],
  trainerNotes:["Do not assume each learner owns a device; use shared devices and paper simulations where needed.","Use non-sensitive sample data for early practice.","Never ask learners to reveal real passwords during instruction.","Accessibility options such as larger text, audio, adaptive input or peer support should be used where appropriate.","Model verification rather than simply warning about misinformation.","Keep AI demonstrations facilitator-controlled and age appropriate."],
  remediation:"Use paper keyboard and interface simulations first. Practise only four actions—select, enter, check, save—then repeat with one non-sensitive digital record and a simple privacy sorting activity.",
  extension:"Learner creates a small digital table from five garden or classroom observations, calculates or compares one simple pattern with facilitator support, and writes a short note explaining how the data and any AI-supported interpretation were verified.",
  imagePrompts:["Photorealistic African children ages 8–11 using shared tablets and a laptop in a supervised GreenSkills classroom, entering simple garden observations, inclusive participation, privacy-safe screen content, no readable text, LIFEWS forest-green and golden accents.","Child-friendly educational illustration showing digital safety concepts: password protection, trusted adult, safe device use, checking information and private data shield, clean white background, no readable text.","Photorealistic African learner entering a plant measurement into a supervised digital observation log while another learner checks a paper record, facilitator nearby, no identifiable personal information on screen."]
};

export const pf11ByLanguage: Partial<Record<AppLanguage,PF11Module>> = { en };
export function getPF11(language:AppLanguage):PF11Module { return pf11ByLanguage[language] ?? en; }
